import type { DefenseDataset, DefenseSource } from "../defensePrime/model";

const sources: DefenseSource[] = [
  {
    id: "lmt-fy2025-results",
    title: "Lockheed Martin Reports Fourth Quarter and Full Year 2025 Financial Results",
    url: "https://investors.lockheedmartin.com/news-releases/news-release-details/lockheed-martin-reports-fourth-quarter-and-full-year-2025/",
    sourceStatus: "official_actual",
    publisher: "Lockheed Martin",
    publishedDate: "2026-01-27",
    accessedDate: "2026-05-12",
    notes: "Official FY2025 results, cash flow, segment results, backlog, aircraft deliveries, and 2026 outlook.",
  },
  {
    id: "lmt-q1-2026-results",
    title: "Lockheed Martin Reports First Quarter 2026 Financial Results",
    url: "https://investors.lockheedmartin.com/news-releases/news-release-details/lockheed-martin-reports-first-quarter-2026-financial-results",
    sourceStatus: "official_actual",
    publisher: "Lockheed Martin",
    publishedDate: "2026-04-21",
    accessedDate: "2026-05-12",
    notes: "Official Q1 2026 results, segment operating data, cash flow, backlog, and updated 2026 outlook.",
  },
  {
    id: "lmt-2026-guidance",
    title: "Lockheed Martin 2026 management guidance",
    url: "https://investors.lockheedmartin.com/news-releases/news-release-details/lockheed-martin-reports-first-quarter-2026-financial-results",
    sourceStatus: "management_guidance",
    publisher: "Lockheed Martin",
    publishedDate: "2026-04-21",
    accessedDate: "2026-05-12",
    notes: "Management outlook fields for 2026 sales, business segment operating profit, EPS, operating cash flow, capex, and free cash flow.",
  },
  {
    id: "lmt-ir-news-archive",
    title: "Lockheed Martin investor relations news archive",
    url: "https://investors.lockheedmartin.com/news-releases",
    sourceStatus: "official_actual",
    publisher: "Lockheed Martin Investor Relations",
    accessedDate: "2026-05-12",
    notes: "Official archive reference for older reporting events. Older event summaries are research-only until each transcript/release is cached.",
  },
  {
    id: "lmt-business-areas",
    title: "Lockheed Martin business areas",
    url: "https://www.lockheedmartin.com/en-us/who-we-are/business-areas.html",
    sourceStatus: "research_only",
    publisher: "Lockheed Martin",
    accessedDate: "2026-05-12",
    notes: "Qualitative source for program and business-area mapping. It is not used directly in valuation.",
  },
  {
    id: "lmt-market-snapshot",
    title: "External market-data snapshot for LMT",
    url: "https://www.marketwatch.com/investing/stock/lmt",
    sourceStatus: "market_data",
    publisher: "Market data provider",
    accessedDate: "2026-05-12",
    notes: "External market price, share-count, and market-cap snapshot. Not official company data.",
  },
  {
    id: "lmt-forecast-assumptions",
    title: "LMT local model forecast assumptions",
    url: "models_description/LMT_explained.txt",
    sourceStatus: "forecast_assumption",
    publisher: "Local model documentation",
    accessedDate: "2026-05-12",
    notes: "Scenario, WACC, terminal growth, target yield, multiple, and valuation-weight assumptions.",
  },
];

const sourceMap = Object.fromEntries(sources.map((source) => [source.id, source])) as Record<string, DefenseSource>;

export const lmtData: DefenseDataset = {
  ticker: "LMT",
  name: "Lockheed Martin Corporation",
  company: "Lockheed Martin Corporation",
  currency: "USD",
  sector: "Aerospace & Defense",
  description: "Defense prime with Aeronautics, Missiles and Fire Control, Rotary and Mission Systems, and Space.",
  latestReportingPeriod: "Q1 2026",
  investmentThesis:
    "Lockheed Martin is a concentrated, sovereign-defense compounder built around F-35, missile defense, rotary systems, naval systems, and space deterrence. Backlog above two years of sales supports revenue visibility, while cash conversion and program charges determine the quality of that visibility.",
  keyDebate:
    "The core debate is whether F-35 delivery cadence, MFC demand, Space missile-defense growth, and 2026 guidance can offset fixed-price program charges, Sikorsky/RMS pressure, and pension/cash-flow volatility.",
  marketMayMiss:
    "The stock is often framed as an F-35 proxy, but the valuation case increasingly depends on MFC backlog growth, NGI/FBM space demand, and whether program-charge risk becomes less frequent.",
  reportingTrendSummary:
    "Across the last eight reporting events, investor attention moved from program charges and F-35 delivery timing toward missile-defense backlog, Space growth, 2026 guidance credibility, and cash conversion. Q1 2026 reintroduced execution risk through lower FCF and backlog decline, so the key trend is not demand scarcity, but the market's demand for cleaner conversion from backlog to profit and cash.",
  dataGaps: [
    "Older quarterly call transcripts are not cached locally; the eight-event trend is research-only synthesis until transcripts are fetched and parsed.",
    "Market price and market capitalization are external market-data inputs, not official Lockheed Martin actuals.",
    "Order intake is derived from backlog movement plus sales because the official release discloses backlog but not a single consolidated order-intake field.",
    "Some program exposure scores are qualitative and are not used directly in valuation.",
  ],
  sources,
  sourceMap,
  periods: [
    {
      id: "FY2025",
      label: "FY2025A",
      fiscalYear: 2025,
      periodType: "FY",
      sourceStatus: "official_actual",
      sourceId: "lmt-fy2025-results",
      sales: 75048,
      operatingProfit: 6743,
      adjustedOperatingProfit: 6743,
      gaapEps: 21.49,
      freeCashFlow: 6908,
      operatingCashFlow: 8557,
      capex: 1649,
      backlog: 193622,
      orderIntake: 92630,
      orderIntakeSourceStatus: "derived",
      netIncome: 5017,
      dilutedShares: 233.4,
      dividendPerShare: 13.05,
      notes: "FY2025 release. Derived order-intake proxy equals sales plus ending backlog less FY2024 ending backlog.",
    },
    {
      id: "Q1-2026",
      label: "Q1 2026A",
      fiscalYear: 2026,
      periodType: "Q",
      sourceStatus: "official_actual",
      sourceId: "lmt-q1-2026-results",
      sales: 18021,
      operatingProfit: 1823,
      adjustedOperatingProfit: 1823,
      gaapEps: 6.44,
      freeCashFlow: -291,
      operatingCashFlow: 220,
      capex: 511,
      backlog: 186427,
      orderIntake: 10826,
      orderIntakeSourceStatus: "derived",
      netIncome: 1488,
      dilutedShares: 230.6,
      dividendPerShare: 3.3,
      notes: "Q1 2026 release. Derived order-intake proxy equals quarterly sales plus backlog change from FY2025 ending backlog.",
    },
  ],
  segments: [
    {
      id: "aeronautics",
      name: "Aeronautics",
      sourceStatus: "official_actual",
      sourceId: "lmt-fy2025-results",
      sales: 30257,
      operatingProfit: 2086,
      margin: 0.069,
      backlog: 59435,
      growth: 0.06,
      strategicRole: "F-35, F-16, C-130J, and advanced aircraft franchise with high strategic importance but delivery and profit-adjustment sensitivity.",
      keyPrograms: ["F-35", "F-16", "C-130J", "Skunk Works"],
      risks: ["F-35 delivery cadence", "Profit booking adjustments", "Customer acceptance timing"],
    },
    {
      id: "mfc",
      name: "Missiles and Fire Control",
      sourceStatus: "official_actual",
      sourceId: "lmt-fy2025-results",
      sales: 14450,
      operatingProfit: 1989,
      margin: 0.138,
      backlog: 46650,
      growth: 0.14,
      strategicRole: "High-demand missiles, fire control, precision strike, and missile-defense segment with the strongest FY2025 growth and margin profile.",
      keyPrograms: ["PAC-3", "THAAD", "GMLRS", "Javelin", "Hypersonics"],
      risks: ["Munitions capacity", "Fixed-price development", "Export approvals"],
    },
    {
      id: "rms",
      name: "Rotary and Mission Systems",
      sourceStatus: "official_actual",
      sourceId: "lmt-fy2025-results",
      sales: 17312,
      operatingProfit: 1323,
      margin: 0.076,
      backlog: 47715,
      growth: 0.0,
      strategicRole: "Sikorsky, integrated warfare systems, radar, Aegis, training, and mission systems with significant backlog but execution pressure.",
      keyPrograms: ["Black Hawk", "CH-53K", "Aegis", "Radar systems", "Training and logistics"],
      risks: ["Sikorsky execution", "Profit adjustments", "Program mix"],
    },
    {
      id: "space",
      name: "Space",
      sourceStatus: "official_actual",
      sourceId: "lmt-fy2025-results",
      sales: 13029,
      operatingProfit: 1345,
      margin: 0.103,
      backlog: 39822,
      growth: 0.04,
      strategicRole: "Strategic deterrence, missile defense, classified space, and national security space exposure.",
      keyPrograms: ["FBM", "Next Generation Interceptor", "Transport Layer", "National security space"],
      risks: ["Classified-program charges", "Development complexity", "ULA equity earnings"],
    },
  ],
  guidance: {
    year: 2026,
    sourceStatus: "management_guidance",
    sourceId: "lmt-2026-guidance",
    salesLow: 77500,
    salesHigh: 80000,
    epsLow: 29.35,
    epsHigh: 30.25,
    fcfLow: 6500,
    fcfHigh: 6800,
    operatingProfitLow: 8425,
    operatingProfitHigh: 8675,
    notes: "Q1 2026 release outlook for sales, business segment operating profit, EPS, and free cash flow.",
  },
  marketData: {
    sourceStatus: "market_data",
    sourceId: "lmt-market-snapshot",
    price: 512.25,
    priceDate: "2026-05-11",
    shares: 230.6,
    marketCap: 118126,
    enterpriseValue: 136929,
    dividendYield: 0.0258,
    notes: "External market snapshot around the May 2026 trading date; official actuals are not sourced from this feed.",
  },
  programs: [
    {
      name: "F-35 production and sustainment",
      segment: "Aeronautics",
      customer: "U.S. services and international partners",
      stage: "mature",
      geography: "U.S. / allied markets",
      maturityScore: 92,
      marginQualityScore: 66,
      growthScore: 62,
      riskScore: 64,
      sourceStatus: "research_only",
      sourceId: "lmt-business-areas",
      strategicRelevance: "F-35 is the central installed-base and sustainment franchise, but delivery cadence and profit adjustments can dominate quarterly sentiment.",
      valuationMapping: "risk_discount_only",
    },
    {
      name: "PAC-3, THAAD, GMLRS, and munitions",
      segment: "Missiles and Fire Control",
      customer: "U.S., NATO, and allied governments",
      stage: "ramping",
      geography: "U.S. / Europe / Middle East / Asia-Pacific",
      maturityScore: 84,
      marginQualityScore: 82,
      growthScore: 90,
      riskScore: 44,
      sourceStatus: "research_only",
      sourceId: "lmt-business-areas",
      strategicRelevance: "Missile-defense and precision-fires demand is the highest-quality growth lane in the current backlog.",
      valuationMapping: "scenario_context_only",
    },
    {
      name: "Aegis and integrated naval systems",
      segment: "Rotary and Mission Systems",
      customer: "U.S. Navy and allied navies",
      stage: "mature",
      geography: "U.S. / allied markets",
      maturityScore: 82,
      marginQualityScore: 70,
      growthScore: 58,
      riskScore: 48,
      sourceStatus: "research_only",
      sourceId: "lmt-business-areas",
      strategicRelevance: "Naval mission systems support long-cycle demand and allied fleet modernization, but segment mix and execution matter.",
      valuationMapping: "scenario_context_only",
    },
    {
      name: "Sikorsky Black Hawk and CH-53K",
      segment: "Rotary and Mission Systems",
      customer: "U.S. and international military helicopter customers",
      stage: "mature",
      geography: "U.S. / international",
      maturityScore: 78,
      marginQualityScore: 58,
      growthScore: 45,
      riskScore: 70,
      sourceStatus: "research_only",
      sourceId: "lmt-business-areas",
      strategicRelevance: "Rotary-wing exposure provides installed-base support but has been a recurring source of profit-adjustment and mix risk.",
      valuationMapping: "risk_discount_only",
    },
    {
      name: "FBM and Next Generation Interceptor",
      segment: "Space",
      customer: "U.S. Navy, Missile Defense Agency, and national security customers",
      stage: "ramping",
      geography: "U.S.",
      maturityScore: 70,
      marginQualityScore: 74,
      growthScore: 82,
      riskScore: 58,
      sourceStatus: "research_only",
      sourceId: "lmt-business-areas",
      strategicRelevance: "Strategic and missile-defense space programs provide long-duration demand, high mission criticality, and execution complexity.",
      valuationMapping: "scenario_context_only",
    },
  ],
  risks: [
    { id: "program-charges", name: "Program charges and profit-booking adjustments", probability: 0.48, impact: 0.72, affectedDriver: "Operating margin and valuation multiple", mitigation: "Track reach-forward losses, profit booking rate changes, and segment margin bridges.", sourceStatus: "research_only" },
    { id: "f35-cadence", name: "F-35 delivery and acceptance cadence", probability: 0.42, impact: 0.62, affectedDriver: "Revenue timing, Aeronautics margin, cash conversion", mitigation: "Monitor quarterly deliveries, customer acceptance, and sustainment commentary.", sourceStatus: "research_only" },
    { id: "cash-conversion", name: "Working-capital and FCF volatility", probability: 0.5, impact: 0.6, affectedDriver: "FCF yield and shareholder returns", mitigation: "Track contract assets, advances, capex, and quarterly FCF seasonality.", sourceStatus: "research_only" },
    { id: "budget", name: "U.S. defense-budget timing and continuing resolutions", probability: 0.35, impact: 0.5, affectedDriver: "Order intake and backlog conversion", mitigation: "Monitor defense appropriations, CR duration, and major award timing.", sourceStatus: "research_only" },
    { id: "rms", name: "RMS and Sikorsky execution pressure", probability: 0.38, impact: 0.52, affectedDriver: "RMS margin and blended operating profit", mitigation: "Track CH-53K, Seahawk, Black Hawk, and IWSS profit commentary.", sourceStatus: "research_only" },
  ],
  reportingEvents: [
    {
      quarter: "2024-Q2",
      eventDate: "2024-07",
      title: "Q2 2024 results event",
      sourceId: "lmt-ir-news-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Program charges and F-35 cadence", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "Program charges", intensity: 5, direction: "stable", evidence: "Investor focus centered on execution quality and margin risk." },
        { theme: "F-35 cadence", intensity: 4, direction: "stable", evidence: "Aircraft delivery and acceptance remained a key debate." },
        { theme: "MFC demand", intensity: 3, direction: "rising", evidence: "Missile and fire-control demand was supportive but not dominant." },
        { theme: "Cash conversion", intensity: 4, direction: "stable", evidence: "FCF reliability remained core to capital-return confidence." },
      ],
      debateQuestions: ["Are program charges temporary or structural?", "Can F-35 deliveries normalize?"],
      watchItems: ["Aeronautics margin", "Cash from operations", "F-35 deliveries"],
      aiSummary: { sourceStatus: "research_only", summary: "The market framed LMT as a quality defense compounder with a program-charge discount. Demand was not the issue; execution was." },
    },
    {
      quarter: "2024-Q3",
      eventDate: "2024-10",
      title: "Q3 2024 results event",
      sourceId: "lmt-ir-news-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Backlog quality and aircraft deliveries", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "Program charges", intensity: 4, direction: "stable", evidence: "Execution risk remained a valuation overhang." },
        { theme: "F-35 cadence", intensity: 5, direction: "rising", evidence: "Delivery timing was central to model updates." },
        { theme: "MFC demand", intensity: 3, direction: "rising", evidence: "Munitions demand gained attention." },
        { theme: "Space / NGI", intensity: 3, direction: "stable", evidence: "Space demand was visible but still secondary." },
      ],
      debateQuestions: ["Can Aeronautics cadence improve?", "Is MFC the emerging growth offset?"],
      watchItems: ["F-35 deliveries", "Backlog by segment", "MFC awards"],
      aiSummary: { sourceStatus: "research_only", summary: "Investor focus started broadening beyond F-35 toward MFC demand, but quarterly sentiment was still driven by aircraft delivery cadence." },
    },
    {
      quarter: "2024-Q4",
      eventDate: "2025-01",
      title: "FY2024 results and 2025 outlook event",
      sourceId: "lmt-ir-news-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "2025 reset after execution charges", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "Program charges", intensity: 5, direction: "stable", evidence: "The market needed proof that charges were peaking." },
        { theme: "2026 guidance", intensity: 1, direction: "new", evidence: "Longer-term guide was not yet central." },
        { theme: "MFC demand", intensity: 4, direction: "rising", evidence: "Missile defense started to influence the bull case." },
        { theme: "Cash conversion", intensity: 5, direction: "stable", evidence: "Capital-return confidence depended on clean FCF." },
      ],
      debateQuestions: ["Does 2025 guidance embed enough conservatism?", "Can MFC offset Aeronautics and RMS issues?"],
      watchItems: ["2025 sales guide", "Segment margin", "FCF guide"],
      aiSummary: { sourceStatus: "research_only", summary: "The FY2024 event was a reset: investors wanted a cleaner 2025 after charge-heavy periods and evidence that backlog could translate into cash." },
    },
    {
      quarter: "2025-Q1",
      eventDate: "2025-04",
      title: "Q1 2025 results event",
      sourceId: "lmt-ir-news-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Guidance confidence and F-35 normalization", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "F-35 cadence", intensity: 5, direction: "stable", evidence: "F-35 deliveries remained a top variable." },
        { theme: "MFC demand", intensity: 4, direction: "rising", evidence: "Missile demand was increasingly important." },
        { theme: "Cash conversion", intensity: 4, direction: "stable", evidence: "First-quarter cash seasonality remained a concern." },
        { theme: "Program charges", intensity: 4, direction: "falling", evidence: "The market looked for signs that charges were less frequent." },
      ],
      debateQuestions: ["Is the delivery cadence back on track?", "Is MFC becoming the highest-quality segment?"],
      watchItems: ["F-35 deliveries", "MFC backlog", "Working capital"],
      aiSummary: { sourceStatus: "research_only", summary: "The market started to reward backlog demand more, but only if F-35 and cash conversion showed stable execution." },
    },
    {
      quarter: "2025-Q2",
      eventDate: "2025-07",
      title: "Q2 2025 results event",
      sourceId: "lmt-ir-news-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Reach-forward losses and RMS pressure", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "Program charges", intensity: 5, direction: "rising", evidence: "Charges and profit adjustments returned to the center of the debate." },
        { theme: "RMS / Sikorsky", intensity: 5, direction: "rising", evidence: "Rotary and Mission Systems execution became a larger concern." },
        { theme: "MFC demand", intensity: 4, direction: "stable", evidence: "MFC demand remained the offset." },
        { theme: "Cash conversion", intensity: 5, direction: "rising", evidence: "FCF bridge credibility was heavily scrutinized." },
      ],
      debateQuestions: ["Are charges isolated or recurring?", "Can MFC growth offset lower-quality RMS earnings?"],
      watchItems: ["RMS margin", "Sikorsky commentary", "FCF guide"],
      aiSummary: { sourceStatus: "research_only", summary: "This was the most adverse event in the eight-quarter trend: investors focused on execution recurrence, not end-market demand." },
    },
    {
      quarter: "2025-Q3",
      eventDate: "2025-10",
      title: "Q3 2025 results event",
      sourceId: "lmt-ir-news-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "2026 setup and backlog mix", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "MFC demand", intensity: 5, direction: "rising", evidence: "Missile-defense backlog became a central positive." },
        { theme: "Space / NGI", intensity: 4, direction: "rising", evidence: "Strategic and missile-defense space growth gained attention." },
        { theme: "Program charges", intensity: 4, direction: "falling", evidence: "Investors looked for fewer new charges." },
        { theme: "2026 guidance", intensity: 3, direction: "rising", evidence: "The market increasingly framed 2026 as the recovery year." },
      ],
      debateQuestions: ["Can MFC and Space create enough mix improvement?", "What margin level is normalized?"],
      watchItems: ["Segment backlog", "MFC margin", "Space bookings"],
      aiSummary: { sourceStatus: "research_only", summary: "Investor focus shifted toward the 2026 recovery bridge, with MFC and Space viewed as the strongest ways to restore confidence." },
    },
    {
      quarter: "2025-Q4",
      eventDate: "2026-01-27",
      title: "FY2025 results and 2026 outlook",
      sourceId: "lmt-fy2025-results",
      sourceStatus: "official_actual",
      transcriptStatus: "official_release_only",
      keyMetrics: [
        { label: "Sales", value: "$75.0bn", sourceStatus: "official_actual" },
        { label: "FCF", value: "$6.9bn", sourceStatus: "official_actual" },
        { label: "Backlog", value: "$193.6bn", sourceStatus: "official_actual" },
      ],
      marketFocus: [
        { theme: "Backlog visibility", intensity: 5, direction: "rising", evidence: "FY2025 backlog increased to $193.6bn." },
        { theme: "2026 guidance", intensity: 5, direction: "rising", evidence: "Management gave 2026 guidance for sales, segment operating profit, EPS, and FCF." },
        { theme: "MFC demand", intensity: 5, direction: "stable", evidence: "MFC was the strongest FY2025 growth segment." },
        { theme: "Program charges", intensity: 4, direction: "stable", evidence: "Investors still tracked charge recurrence despite the strong backlog." },
      ],
      debateQuestions: ["Does FY2026 guidance finally normalize earnings power?", "How much of backlog is high-quality MFC and Space demand?"],
      watchItems: ["2026 segment operating profit", "FCF guide", "Backlog by segment"],
      aiSummary: { sourceStatus: "research_only", summary: "The FY2025 event gave the bull case a clearer backlog and guidance base, but the market still demanded evidence that charges and working-capital volatility would fade." },
    },
    {
      quarter: "2026-Q1",
      eventDate: "2026-04-21",
      title: "Q1 2026 results",
      sourceId: "lmt-q1-2026-results",
      sourceStatus: "official_actual",
      transcriptStatus: "official_release_only",
      keyMetrics: [
        { label: "Sales", value: "$18.0bn", sourceStatus: "official_actual" },
        { label: "EPS", value: "$6.44", sourceStatus: "official_actual" },
        { label: "FCF", value: "-$0.3bn", sourceStatus: "official_actual" },
        { label: "Backlog", value: "$186.4bn", sourceStatus: "official_actual" },
      ],
      marketFocus: [
        { theme: "Cash conversion", intensity: 5, direction: "rising", evidence: "Q1 FCF was negative due to working-capital timing and capex." },
        { theme: "Backlog visibility", intensity: 4, direction: "falling", evidence: "Backlog declined from FY2025 ending level but remained high." },
        { theme: "RMS / Sikorsky", intensity: 5, direction: "rising", evidence: "RMS operating profit declined and management cited helicopter program pressure." },
        { theme: "Space / NGI", intensity: 4, direction: "rising", evidence: "Space sales growth was supported by FBM and NGI volume." },
      ],
      debateQuestions: ["Is Q1 FCF just seasonality or a warning on conversion?", "Can MFC and Space offset RMS/Sikorsky pressure?"],
      watchItems: ["Contract assets", "RMS margin", "F-35 deliveries", "Backlog trend"],
      aiSummary: { sourceStatus: "research_only", summary: "Q1 2026 rebalanced the thesis: demand and guidance remained intact, but the market refocused on cash conversion, RMS/Sikorsky execution, and whether backlog quality can overcome quarterly volatility." },
    },
  ],
  scenarios: [
    {
      scenario: "Bear",
      revenueCagr: 0.018,
      operatingMargin: 0.098,
      wacc: 0.09,
      terminalGrowth: 0.017,
      targetFcfYield: 0.062,
      targetPe: 14.5,
      targetEvEbit: 12.5,
      probability: 0.25,
      narrative: "Program charges and working-capital volatility persist; backlog conversion is delayed by U.S. budget timing and F-35/RMS execution friction.",
    },
    {
      scenario: "Base",
      revenueCagr: 0.045,
      operatingMargin: 0.108,
      wacc: 0.08,
      terminalGrowth: 0.024,
      targetFcfYield: 0.052,
      targetPe: 18.5,
      targetEvEbit: 15.5,
      probability: 0.5,
      narrative: "2026 guidance holds, MFC and Space offset RMS pressure, and FCF normalizes after first-quarter seasonality.",
    },
    {
      scenario: "Bull",
      revenueCagr: 0.06,
      operatingMargin: 0.116,
      wacc: 0.074,
      terminalGrowth: 0.027,
      targetFcfYield: 0.046,
      targetPe: 21,
      targetEvEbit: 18,
      probability: 0.25,
      narrative: "MFC and Space demand persist, F-35 deliveries normalize, charges fade, and backlog quality earns a higher defense-prime multiple.",
    },
  ],
  assumptions: {
    currentPrice: 512.25,
    revenueCagr: 0.045,
    operatingMargin: 0.108,
    taxRate: 0.17,
    dAndAIntensity: 0.022,
    capexIntensity: 0.026,
    workingCapitalDragPctRevenueGrowth: 0.11,
    wacc: 0.08,
    terminalGrowth: 0.024,
    targetFcfYield: 0.052,
    targetPe: 18.5,
    targetEvEbit: 15.5,
    netDebt: 18803,
    dilutedShares: 230.6,
    dividendPerShare: 13.2,
    backlogDurabilityMaxAdjustment: 0.08,
    weightDcf: 0.35,
    weightFcfYield: 0.25,
    weightEvEbit: 0.15,
    weightPe: 0.1,
    weightBacklogDurability: 0.15,
  },
  capitalReturns: {
    dividendPerShare: 13.2,
    dividendsPaid: 3131,
    fcfPayout: 3131 / 6908,
    payoutRatio: 13.05 / 21.49,
    policy: "Progressive dividend plus opportunistic repurchases, constrained by FCF and balance-sheet capacity.",
    sourceStatus: "derived",
    sourceId: "lmt-fy2025-results",
    sustainabilityView:
      "The dividend appears supported in the base case by 2026 FCF guidance, but buybacks are more discretionary. The critical watch item is whether working-capital normalization and fewer program charges restore confidence in annual FCF conversion.",
  },
};
