import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const trvDataset = createLocalDeepResearchDataset({
  ticker: "TRV",
  companyName: "The Travelers Companies, Inc.",
  sector: "Property & Casualty Insurance / Commercial / Personal Lines",
  archetype: "P&C insurer / underwriting cycle and cat-normalized ROE",
  description:
    "TRV research cockpit focused on business insurance pricing, personal auto/property loss trends, catastrophe load, reserve development, investment income, capital return, and whether normalized ROE can hold as pricing moderates.",
  updatedAt: "2026-05-20",
  currentPrice: 305.02,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "pricing-loss-cost", label: "Pricing / Loss Cost" },
    { value: "personal-cat", label: "Personal / Cat" },
    { value: "float-capital", label: "Float / Capital" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "combined-ratio", label: "Underlying Combined Ratio", value: 0.9, format: "percent", description: "Normalized underwriting-quality proxy; official supplement import pending.", badge: "Placeholder" },
    { key: "pricing-spread", label: "Pricing Spread", value: 0.025, format: "percent", description: "Commercial rate less loss-cost trend framework.", badge: "Assumption" },
    { key: "cat-load", label: "Cat Load Risk", value: 0.11, format: "percent", description: "Normalized risk haircut for weather and secondary perils.", badge: "Assumption" },
    { key: "capital-return", label: "Capital Return Yield", value: 0.04, format: "percent", description: "Dividend plus buyback framework; official import pending.", badge: "Placeholder" },
    { key: "base-gap", label: "Base Upside / Downside", value: -0.02, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "business-insurance",
      question: "Is commercial pricing still above loss-cost trend?",
      currentView: "TRV needs rate adequacy in business insurance to offset cat volatility and personal lines pressure.",
      metric: "Renewal rate change, loss trend, underlying combined ratio",
      evidenceNeeded: "Segment pricing and accident-year loss ratio bridge",
      valuationTie: "Normalized FCF/earnings margin",
      bearCase: "Pricing slows while loss-cost inflation persists.",
    },
    {
      key: "personal-lines",
      question: "Are personal auto/property margins normalizing?",
      currentView: "Personal lines can recover, but weather and severity make the path volatile.",
      metric: "Personal lines combined ratio, auto severity, homeowners cat losses",
      evidenceNeeded: "Personal segment margin bridge",
      valuationTie: "Risk haircut",
      bearCase: "Weather and severity consume rate increases.",
    },
    {
      key: "reserve-cat",
      question: "How much of earnings is true underwriting versus cat luck?",
      currentView: "Normalize cat load before capitalizing earnings.",
      metric: "Cat losses, prior-year development, ex-cat combined ratio",
      evidenceNeeded: "Cat-normalized accident-year bridge",
      valuationTie: "Discount rate and exit multiple",
      bearCase: "Cat load structurally rises and reserve development worsens.",
    },
    {
      key: "investment-income",
      question: "Does investment income offset underwriting normalization?",
      currentView: "Fixed-income yield supports earnings but should be scenario-weighted as the rate cycle evolves.",
      metric: "New money yield, portfolio yield, duration",
      evidenceNeeded: "Portfolio roll-forward and reinvestment assumptions",
      valuationTie: "Revenue CAGR and terminal growth",
      bearCase: "Yield tailwind plateaus before underwriting fully improves.",
    },
  ],
  kpiSeries: [
    {
      key: "pricing-loss-cost",
      title: "Commercial Pricing Spread vs Combined Ratio",
      subtitle: "TRV's core underwriting debate is rate adequacy after several years of loss-cost inflation.",
      sourceStatus: "research_only",
      measures: [
        { key: "pricingSpread", label: "Pricing spread bps", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "combinedRatio", label: "Underlying combined ratio %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", pricingSpread: 250, combinedRatio: 0.914 },
        { period: "2024 Q2", pricingSpread: 230, combinedRatio: 0.908 },
        { period: "2024 Q3", pricingSpread: 210, combinedRatio: 0.912 },
        { period: "2024 Q4", pricingSpread: 205, combinedRatio: 0.907 },
        { period: "2025 Q1", pricingSpread: 200, combinedRatio: 0.904 },
        { period: "2025 Q2", pricingSpread: 190, combinedRatio: 0.902 },
        { period: "2025 Q3", pricingSpread: 180, combinedRatio: 0.905 },
        { period: "2025 Q4", pricingSpread: 170, combinedRatio: 0.901 },
        { period: "2026 Q1", pricingSpread: 165, combinedRatio: 0.9 },
      ],
    },
    {
      key: "personal-cat",
      title: "Personal Lines Recovery vs Cat Load",
      subtitle: "Personal lines recovery must be evaluated after weather and severity normalization.",
      sourceStatus: "research_only",
      measures: [
        { key: "personalRecovery", label: "Personal recovery index", format: "number", chartType: "bar", color: "#1e3a8a", axis: "left" },
        { key: "catLoad", label: "Cat load index", format: "number", chartType: "line", color: "#dc2626", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", personalRecovery: 76, catLoad: 94 },
        { period: "2024 Q2", personalRecovery: 81, catLoad: 105 },
        { period: "2024 Q3", personalRecovery: 86, catLoad: 118 },
        { period: "2024 Q4", personalRecovery: 89, catLoad: 98 },
        { period: "2025 Q1", personalRecovery: 92, catLoad: 96 },
        { period: "2025 Q2", personalRecovery: 95, catLoad: 110 },
        { period: "2025 Q3", personalRecovery: 98, catLoad: 121 },
        { period: "2025 Q4", personalRecovery: 100, catLoad: 102 },
        { period: "2026 Q1", personalRecovery: 102, catLoad: 99 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "commercial-pricing",
      tab: "pricing-loss-cost",
      title: "Business Insurance Pricing",
      thesis: "Commercial pricing must remain above loss-cost trend for TRV to sustain normalized ROE.",
      evidence: ["Renewal rate change", "Loss-cost trend", "Expense ratio"],
      watchItems: ["Casualty severity", "Workers' comp soft market", "Competitive rate pressure"],
      sourceStatus: "research_only",
    },
    {
      key: "personal-cat",
      tab: "personal-cat",
      title: "Personal Lines and Cat Volatility",
      thesis: "The personal lines recovery can be real but should be separated from weather volatility.",
      evidence: ["Auto severity", "Homeowners rate adequacy", "Cat load"],
      watchItems: ["Weather frequency", "Reinsurance cost", "Reserve additions"],
      sourceStatus: "research_only",
    },
    {
      key: "float-capital",
      tab: "float-capital",
      title: "Float, Yield and Buybacks",
      thesis: "Capital return adds per-share compounding only if cat volatility does not consume excess capital.",
      evidence: ["Book yield", "Capital ratio", "Buyback pace"],
      watchItems: ["Yield plateau", "Capital trapped after cat events", "BVPS volatility"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-17", headline: "Rate adequacy after cat volatility", keyQuestions: ["Is commercial rate above loss cost?", "Is personal recovery intact?", "How large was cat load?"], managementTone: "Disciplined.", modelReadThrough: "Keep valuation near fair value; require cat-normalized improvement.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-01-22", headline: "Investment income and buybacks", keyQuestions: ["Is portfolio yield still rising?", "What is buyback capacity?", "Any reserve development?"], managementTone: "Constructive.", modelReadThrough: "Capital return helps but does not remove cat haircut.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-16", headline: "Cat season check", keyQuestions: ["Cat loss relative to budget?", "Underlying margin?", "Personal lines trend?"], managementTone: "Balanced.", modelReadThrough: "Keep risk haircut until weather normalized.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-17", headline: "Personal lines recovery", keyQuestions: ["Auto severity?", "Homeowners pricing?", "Commercial rate?"], managementTone: "Recovery-oriented.", modelReadThrough: "Slight margin improvement but no multiple expansion yet.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-17", headline: "Loss-cost trend", keyQuestions: ["Is loss inflation slowing?", "Are reserves stable?", "What is cat load?"], managementTone: "Measured.", modelReadThrough: "Maintain normalized ROE assumption.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-01-22", headline: "ROE and capital return", keyQuestions: ["Buyback pace?", "Book yield?", "Underlying combined ratio?"], managementTone: "Confident.", modelReadThrough: "Support base valuation.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-17", headline: "Weather and reserves", keyQuestions: ["Cat load?", "Reserve development?", "Pricing adequacy?"], managementTone: "Cautious.", modelReadThrough: "Do not extrapolate headline EPS.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-19", headline: "Commercial pricing durability", keyQuestions: ["Business insurance rate?", "Personal segment loss ratio?", "Investment income?"], managementTone: "Constructive.", modelReadThrough: "Base case holds.", riskSignal: "Positive", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-19", fiscalPeriod: "FY2024 Q2", asOfPrice: 210, fairValue: 218, method: "Commercial pricing and capital return local fallback." },
    { eventDate: "2024-10-17", fiscalPeriod: "FY2024 Q3", asOfPrice: 240, fairValue: 235, method: "Weather and reserve normalized view." },
    { eventDate: "2025-01-22", fiscalPeriod: "FY2024 Q4", asOfPrice: 246, fairValue: 252, method: "ROE durability and buybacks." },
    { eventDate: "2025-04-17", fiscalPeriod: "FY2025 Q1", asOfPrice: 255, fairValue: 264, method: "Loss-cost trend normalization." },
    { eventDate: "2025-07-17", fiscalPeriod: "FY2025 Q2", asOfPrice: 273, fairValue: 278, method: "Personal lines recovery." },
    { eventDate: "2025-10-16", fiscalPeriod: "FY2025 Q3", asOfPrice: 286, fairValue: 286, method: "Cat season check and normalized ROE." },
    { eventDate: "2026-01-22", fiscalPeriod: "FY2025 Q4", asOfPrice: 299, fairValue: 296, method: "Investment income and buybacks." },
    { eventDate: "2026-04-17", fiscalPeriod: "FY2026 Q1", asOfPrice: 305, fairValue: 300, method: "Base underwriting / float local run." },
  ],
  valuationBase: {
    revenueBase: 48000,
    revenueCagr3Y: 0.045,
    terminalGrowth: 0.02,
    normalizedFcfMargin: 0.13,
    exitFcfMultiple: 13,
    evRevenueMultiple: 1.9,
    discountRate: 0.09,
    netCashDebt: 0,
    dilutedShares: 218,
    qualityAdjustment: 1.05,
    riskHaircut: 0.1,
    dividendYield: 0.014,
    buybackYield: 0.026,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.01, normalizedFcfMargin: 0.09, exitFcfMultiple: 10, evRevenueMultiple: 1.4, riskHaircut: 0.22, qualityAdjustment: 0.95, buybackYield: 0.01 },
    Base: {},
    Bull: { revenueCagr3Y: 0.065, normalizedFcfMargin: 0.16, exitFcfMultiple: 15, evRevenueMultiple: 2.2, riskHaircut: 0.06, qualityAdjustment: 1.11, buybackYield: 0.035 },
  },
  valuationDescription: "Maps P&C underwriting, float income and buybacks into the platform valuation framework until insurance-specific BVPS/ROE modeling is backend-backed.",
  risks: [
    { title: "Catastrophe volatility", detail: "Weather and secondary perils can overwhelm underlying margin improvements.", severity: "high", killSignal: "Cat load structurally rises above pricing assumptions." },
    { title: "Loss-cost inflation", detail: "Casualty and auto severity can outrun pricing.", severity: "high", killSignal: "Underlying combined ratio worsens despite positive renewal rates." },
    { title: "Reserve development", detail: "Adverse reserve development would impair trust in underwriting quality.", severity: "medium", killSignal: "Prior-year development turns adverse across multiple lines." },
  ],
  monitoring: ["Commercial renewal rate", "Personal auto severity", "Cat load", "Reserve development", "Book yield", "Buyback pace"],
  sourceGaps: ["Insurance-specific BVPS/ROE backend model is not implemented yet.", "Official segment combined-ratio and cat data should be imported from earnings supplements."],
});
