import type { MaDataset } from "./model";

export const maDataset: MaDataset = {
  latestReportingPeriod: "FY2026 Q1",
  marketData: {
    currentPrice: 489.94,
    priceDate: "2026-05-14",
    sharesForMarketCap: 908,
    marketCap: 444_865,
    source: "research_only offline fallback; backend daily price bars override this when API is online",
    sourceStatus: "research_only",
  },
  periods: [
    {
      id: "fy2025",
      label: "FY2025",
      fiscalYear: 2025,
      periodType: "annual",
      sourceStatus: "market_data_proxy",
      sourceId: "ma-static-fallback-fy2025",
      revenue: 31_400,
      operatingIncome: 18_300,
      operatingMargin: 0.583,
      netIncome: 14_100,
      dilutedEps: 15.35,
      dilutedShares: 918,
      operatingCashFlow: 16_300,
      capex: 1_100,
      freeCashFlow: 15_200,
      dividendsPaid: 2_650,
      buybacks: 11_200,
      dividendPerShare: 2.89,
      notes: "Static fallback; backend SQLite rows replace this when the API is online.",
    },
    {
      id: "fy2026-q1",
      label: "FY2026 Q1",
      fiscalYear: 2026,
      fiscalQuarter: "Q1",
      periodType: "quarter",
      sourceStatus: "market_data_proxy",
      sourceId: "ma-static-fallback-fy2026-q1",
      revenue: 8_200,
      operatingIncome: 4_750,
      operatingMargin: 0.579,
      netIncome: 3_650,
      dilutedEps: 4.02,
      dilutedShares: 908,
      operatingCashFlow: 3_900,
      capex: 280,
      freeCashFlow: 3_620,
      dividendsPaid: 660,
      buybacks: 3_000,
      dividendPerShare: 0.73,
      notes: "Static fallback; backend SQLite rows replace this when the API is online.",
    },
  ],
  operatingMetrics: [
    {
      periodId: "fy2026-q1",
      asOfDate: "2026-04-30",
      sourceStatus: "market_data_proxy",
      grossDollarVolume: 2_750_000,
      purchaseVolume: 2_100_000,
      crossBorderVolumeGrowth: 0.13,
      switchedTransactions: 46_000,
      switchedTransactionsGrowth: 0.11,
      processedTransactions: 46_000,
      cardsAccounts: 3_750,
      rebatesIncentives: 4_050,
      takeRate: 8_200 / 2_750_000,
      takeRateCommentary: "Net revenue yield is monitored against gross dollar volume and rebates/incentives.",
      crossBorderCommentary: "Cross-border remains the most travel-sensitive premium-growth driver.",
      valueAddedServicesCommentary: "Cybersecurity, fraud, identity, loyalty, data analytics, and consulting mix should support margins if growth stays above core network volume.",
      regulatoryCommentary: "Risk focus is network fees, routing, and interchange pressure rather than assuming every merchant fee headline is a direct MA revenue cut.",
      competitionCommentary: "Visa, Amex, domestic schemes, RTP, and account-to-account rails pressure different parts of the Mastercard model.",
      capitalReturnCommentary: "Buybacks are material to EPS growth and must be compared with FCF coverage.",
      normalizedFcfCommentary: "Capex-light economics support high FCF conversion, but incentives and regulation can change conversion quality.",
    },
  ],
  segmentFinancials: [
    { periodId: "fy2026-q1", segment: "Payment Network / Switched Transactions", taxonomy: "payments_network", revenue: 3_444, operatingIncome: 2_273, operatingMargin: 0.66, growth: 0.11, sourceStatus: "research_only" },
    { periodId: "fy2026-q1", segment: "Cross-Border Assessment and Travel", taxonomy: "cross_border", revenue: 2_050, operatingIncome: 1_476, operatingMargin: 0.72, growth: 0.13, sourceStatus: "research_only" },
    { periodId: "fy2026-q1", segment: "Value-Added Services and Cyber/Data", taxonomy: "value_added_services", revenue: 2_706, operatingIncome: 1_569, operatingMargin: 0.58, growth: 0.16, sourceStatus: "research_only" },
  ],
};
