import path from "node:path";

export const DEEP_RESEARCH_BACKEND_SLUGS = ["avav", "ktos", "jpm", "cb", "trv", "eqt", "qcom", "bac", "unh"];

const commonStartDate = "2018-01-01";
const commonLatestDate = "2026-05-20";

function dbPath(slug) {
  return path.resolve("data/local", slug, "backend", `${slug}_research.sqlite`);
}

function profile(input) {
  return {
    currency: "USD",
    unit: "USDm",
    historyStartDate: commonStartDate,
    latestDate: commonLatestDate,
    modelVersion: `${input.slug}_deep_research_v1_backend_pilot`,
    dbPath: dbPath(input.slug),
    ...input,
  };
}

export const deepResearchBackendProfiles = {
  avav: profile({
    slug: "avav",
    ticker: "AVAV",
    displayName: "AeroVironment",
    companyName: "AeroVironment, Inc.",
    archetype: "Defense autonomy / loitering munitions",
    irUrl: "https://investor.avinc.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings and transcript ingestion.",
    revenueStart: 75,
    revenueEnd: 230,
    operatingMarginStart: 0.06,
    operatingMarginEnd: 0.13,
    fcfMarginStart: 0.01,
    fcfMarginEnd: 0.12,
    sharesStart: 24,
    sharesEnd: 50,
    netDebtEnd: -190,
    priceStart: 41,
    priceEnd: 160,
    fairValueStart: 38,
    fairValueEnd: 150,
    baseAssumptions: {
      revenueCagr3Y: 0.19,
      terminalGrowth: 0.035,
      normalizedFcfMargin: 0.12,
      exitFcfMultiple: 32,
      evRevenueMultiple: 7.5,
      discountRate: 0.105,
      qualityAdjustment: 1.05,
      riskHaircut: 0.2,
      dividendYield: 0,
      buybackYield: 0,
    },
    segments: [
      { name: "Loitering Munitions / Tactical Systems", startMix: 0.42, endMix: 0.58, margin: 0.16 },
      { name: "Autonomy / Uncrewed Systems", startMix: 0.38, endMix: 0.30, margin: 0.11 },
      { name: "BlueHalo / Counter-UAS Optionality", startMix: 0.20, endMix: 0.12, margin: 0.08 },
    ],
    peers: ["LHX", "KTOS", "BA", "TXT"],
    debateQuestions: [
      "Is loitering munition demand a standing NATO procurement category or a wartime pull-forward?",
      "Can production throughput and supplier readiness convert backlog into cash?",
      "Does BlueHalo add software/autonomy content or dilute margin discipline?",
    ],
    riskTopics: ["program timing", "production bottlenecks", "defense budget lumpiness", "hardware commoditization"],
  }),
  ktos: profile({
    slug: "ktos",
    ticker: "KTOS",
    displayName: "Kratos Defense & Security Solutions",
    companyName: "Kratos Defense & Security Solutions, Inc.",
    archetype: "Affordable mass / tactical drone prime challenger",
    irUrl: "https://ir.kratosdefense.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings and transcript ingestion.",
    revenueStart: 190,
    revenueEnd: 380,
    operatingMarginStart: 0.05,
    operatingMarginEnd: 0.11,
    fcfMarginStart: -0.02,
    fcfMarginEnd: 0.08,
    sharesStart: 110,
    sharesEnd: 155,
    netDebtEnd: 120,
    priceStart: 11,
    priceEnd: 48,
    fairValueStart: 10,
    fairValueEnd: 42,
    baseAssumptions: {
      revenueCagr3Y: 0.16,
      terminalGrowth: 0.035,
      normalizedFcfMargin: 0.08,
      exitFcfMultiple: 28,
      evRevenueMultiple: 4.2,
      discountRate: 0.11,
      qualityAdjustment: 1.0,
      riskHaircut: 0.22,
      dividendYield: 0,
      buybackYield: 0,
    },
    segments: [
      { name: "Tactical Drones", startMix: 0.28, endMix: 0.43, margin: 0.12 },
      { name: "Space / Satellite / Microwave", startMix: 0.38, endMix: 0.32, margin: 0.10 },
      { name: "Defense Services", startMix: 0.34, endMix: 0.25, margin: 0.07 },
    ],
    peers: ["AVAV", "LHX", "NOC", "BA"],
    debateQuestions: [
      "Can affordable unmanned systems become a procurement category rather than demonstration revenue?",
      "Is Valkyrie / tactical drone demand production-ready?",
      "Does margin expand as programs scale or stay capped by contract mix?",
    ],
    riskTopics: ["prototype-to-production gap", "working capital", "competition from primes", "budget timing"],
  }),
  jpm: profile({
    slug: "jpm",
    ticker: "JPM",
    displayName: "JPMorgan Chase",
    companyName: "JPMorgan Chase & Co.",
    archetype: "Money-center bank / scale compounder",
    irUrl: "https://www.jpmorganchase.com/ir",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings, call reports and transcript ingestion.",
    revenueStart: 28500,
    revenueEnd: 45500,
    operatingMarginStart: 0.34,
    operatingMarginEnd: 0.41,
    fcfMarginStart: 0.28,
    fcfMarginEnd: 0.34,
    sharesStart: 3300,
    sharesEnd: 2850,
    netDebtEnd: 0,
    priceStart: 112,
    priceEnd: 285,
    fairValueStart: 118,
    fairValueEnd: 272,
    baseAssumptions: {
      revenueCagr3Y: 0.055,
      terminalGrowth: 0.025,
      normalizedFcfMargin: 0.31,
      exitFcfMultiple: 12,
      evRevenueMultiple: 2.5,
      discountRate: 0.095,
      qualityAdjustment: 1.12,
      riskHaircut: 0.12,
      dividendYield: 0.022,
      buybackYield: 0.025,
    },
    segments: [
      { name: "Consumer & Community Banking", startMix: 0.38, endMix: 0.35, margin: 0.39 },
      { name: "Commercial & Investment Bank", startMix: 0.43, endMix: 0.47, margin: 0.42 },
      { name: "Asset & Wealth Management", startMix: 0.19, endMix: 0.18, margin: 0.34 },
    ],
    peers: ["BAC", "C", "WFC", "GS"],
    debateQuestions: [
      "How much of normalized earnings power survives a lower-rate cycle?",
      "Is credit normalization benign or the first signal of consumer stress?",
      "Does scale and deposit franchise justify a structural premium multiple?",
    ],
    riskTopics: ["net interest income normalization", "credit costs", "capital rules", "deposit beta"],
  }),
  bac: profile({
    slug: "bac",
    ticker: "BAC",
    displayName: "Bank of America",
    companyName: "Bank of America Corporation",
    archetype: "Rate-sensitive bank / deposit franchise recovery",
    irUrl: "https://investor.bankofamerica.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings, call reports and transcript ingestion.",
    revenueStart: 22500,
    revenueEnd: 28500,
    operatingMarginStart: 0.30,
    operatingMarginEnd: 0.34,
    fcfMarginStart: 0.23,
    fcfMarginEnd: 0.28,
    sharesStart: 8200,
    sharesEnd: 7700,
    netDebtEnd: 0,
    priceStart: 30,
    priceEnd: 43,
    fairValueStart: 31,
    fairValueEnd: 47,
    baseAssumptions: {
      revenueCagr3Y: 0.045,
      terminalGrowth: 0.02,
      normalizedFcfMargin: 0.27,
      exitFcfMultiple: 10.5,
      evRevenueMultiple: 2.0,
      discountRate: 0.1,
      qualityAdjustment: 1.0,
      riskHaircut: 0.15,
      dividendYield: 0.026,
      buybackYield: 0.018,
    },
    segments: [
      { name: "Consumer Banking", startMix: 0.42, endMix: 0.40, margin: 0.36 },
      { name: "Global Banking / Markets", startMix: 0.36, endMix: 0.38, margin: 0.34 },
      { name: "Wealth Management", startMix: 0.22, endMix: 0.22, margin: 0.31 },
    ],
    peers: ["JPM", "C", "WFC", "USB"],
    debateQuestions: [
      "Does NII trough and reaccelerate as securities roll down?",
      "Is deposit franchise value masked by unrealized securities losses?",
      "Can buybacks resume meaningfully under capital rules?",
    ],
    riskTopics: ["NII pressure", "AOCI / capital sensitivity", "credit costs", "fee pressure"],
  }),
  cb: profile({
    slug: "cb",
    ticker: "CB",
    displayName: "Chubb",
    companyName: "Chubb Limited",
    archetype: "P&C underwriting compounder / global specialty insurer",
    irUrl: "https://investors.chubb.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with statutory filings, annual reports and transcript ingestion.",
    revenueStart: 8500,
    revenueEnd: 14500,
    operatingMarginStart: 0.20,
    operatingMarginEnd: 0.27,
    fcfMarginStart: 0.17,
    fcfMarginEnd: 0.24,
    sharesStart: 455,
    sharesEnd: 405,
    netDebtEnd: 7800,
    priceStart: 133,
    priceEnd: 285,
    fairValueStart: 142,
    fairValueEnd: 310,
    baseAssumptions: {
      revenueCagr3Y: 0.06,
      terminalGrowth: 0.025,
      normalizedFcfMargin: 0.23,
      exitFcfMultiple: 15,
      evRevenueMultiple: 2.8,
      discountRate: 0.09,
      qualityAdjustment: 1.13,
      riskHaircut: 0.1,
      dividendYield: 0.014,
      buybackYield: 0.02,
    },
    segments: [
      { name: "North America Commercial P&C", startMix: 0.46, endMix: 0.44, margin: 0.29 },
      { name: "Overseas General / Specialty", startMix: 0.31, endMix: 0.34, margin: 0.26 },
      { name: "Life / Personal Lines", startMix: 0.23, endMix: 0.22, margin: 0.18 },
    ],
    peers: ["TRV", "AIG", "ACGL", "WRB"],
    debateQuestions: [
      "Is pricing still ahead of loss cost inflation?",
      "Can underwriting discipline offset catastrophe volatility?",
      "Does investment income create durable ROE support?",
    ],
    riskTopics: ["catastrophe losses", "reserve development", "pricing cycle", "investment portfolio risk"],
  }),
  trv: profile({
    slug: "trv",
    ticker: "TRV",
    displayName: "Travelers",
    companyName: "The Travelers Companies, Inc.",
    archetype: "P&C pricing cycle / underwriting improvement",
    irUrl: "https://investor.travelers.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with statutory filings, annual reports and transcript ingestion.",
    revenueStart: 7400,
    revenueEnd: 12500,
    operatingMarginStart: 0.14,
    operatingMarginEnd: 0.21,
    fcfMarginStart: 0.12,
    fcfMarginEnd: 0.18,
    sharesStart: 265,
    sharesEnd: 230,
    netDebtEnd: 7000,
    priceStart: 134,
    priceEnd: 267,
    fairValueStart: 128,
    fairValueEnd: 250,
    baseAssumptions: {
      revenueCagr3Y: 0.045,
      terminalGrowth: 0.02,
      normalizedFcfMargin: 0.17,
      exitFcfMultiple: 12,
      evRevenueMultiple: 2.0,
      discountRate: 0.095,
      qualityAdjustment: 1.02,
      riskHaircut: 0.14,
      dividendYield: 0.016,
      buybackYield: 0.025,
    },
    segments: [
      { name: "Business Insurance", startMix: 0.54, endMix: 0.56, margin: 0.22 },
      { name: "Bond & Specialty", startMix: 0.11, endMix: 0.10, margin: 0.31 },
      { name: "Personal Insurance", startMix: 0.35, endMix: 0.34, margin: 0.14 },
    ],
    peers: ["CB", "AIG", "ALL", "PGR"],
    debateQuestions: [
      "Is personal lines margin recovery sustainable?",
      "Does commercial pricing still offset severity inflation?",
      "Are cat losses masking normalized underwriting profitability?",
    ],
    riskTopics: ["cat losses", "severity inflation", "reserve risk", "pricing competition"],
  }),
  eqt: profile({
    slug: "eqt",
    ticker: "EQT",
    displayName: "EQT",
    companyName: "EQT Corporation",
    archetype: "Natural gas / LNG-linked Appalachia producer",
    irUrl: "https://ir.eqt.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings, reserve reports and commodity deck ingestion.",
    revenueStart: 900,
    revenueEnd: 1900,
    operatingMarginStart: 0.22,
    operatingMarginEnd: 0.34,
    fcfMarginStart: 0.05,
    fcfMarginEnd: 0.22,
    sharesStart: 350,
    sharesEnd: 520,
    netDebtEnd: 5200,
    priceStart: 20,
    priceEnd: 55,
    fairValueStart: 24,
    fairValueEnd: 62,
    baseAssumptions: {
      revenueCagr3Y: 0.09,
      terminalGrowth: 0.015,
      normalizedFcfMargin: 0.22,
      exitFcfMultiple: 9,
      evRevenueMultiple: 3.0,
      discountRate: 0.11,
      qualityAdjustment: 1.0,
      riskHaircut: 0.18,
      dividendYield: 0.012,
      buybackYield: 0.02,
    },
    segments: [
      { name: "Appalachia Gas Production", startMix: 0.74, endMix: 0.70, margin: 0.33 },
      { name: "NGL / Liquids", startMix: 0.12, endMix: 0.13, margin: 0.25 },
      { name: "Midstream / Basis Optimization", startMix: 0.14, endMix: 0.17, margin: 0.20 },
    ],
    peers: ["AR", "RRC", "CNX", "EOG"],
    debateQuestions: [
      "How much LNG demand is already priced into Henry Hub and EQT equity?",
      "Can Appalachia basis and takeaway improve enough to unlock FCF?",
      "Does hedging protect downside or cap upside in a tightening gas cycle?",
    ],
    riskTopics: ["gas price", "basis differentials", "debt leverage", "regulatory / pipeline constraints"],
  }),
  qcom: profile({
    slug: "qcom",
    ticker: "QCOM",
    displayName: "Qualcomm",
    companyName: "QUALCOMM Incorporated",
    archetype: "Mobile SoC / licensing annuity / edge AI",
    irUrl: "https://investor.qualcomm.com/",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings and transcript ingestion.",
    revenueStart: 5600,
    revenueEnd: 11200,
    operatingMarginStart: 0.27,
    operatingMarginEnd: 0.32,
    fcfMarginStart: 0.22,
    fcfMarginEnd: 0.27,
    sharesStart: 1180,
    sharesEnd: 1110,
    netDebtEnd: -1600,
    priceStart: 64,
    priceEnd: 196,
    fairValueStart: 72,
    fairValueEnd: 205,
    baseAssumptions: {
      revenueCagr3Y: 0.085,
      terminalGrowth: 0.025,
      normalizedFcfMargin: 0.27,
      exitFcfMultiple: 19,
      evRevenueMultiple: 5.1,
      discountRate: 0.095,
      qualityAdjustment: 1.08,
      riskHaircut: 0.14,
      dividendYield: 0.018,
      buybackYield: 0.03,
    },
    segments: [
      { name: "QCT Handsets", startMix: 0.56, endMix: 0.48, margin: 0.28 },
      { name: "QTL Licensing", startMix: 0.23, endMix: 0.20, margin: 0.68 },
      { name: "Automotive / IoT / Edge AI", startMix: 0.21, endMix: 0.32, margin: 0.22 },
    ],
    peers: ["AVGO", "TXN", "NXPI", "MRVL"],
    debateQuestions: [
      "Is Android premium recovery durable after inventory normalization?",
      "How fast does Apple modem risk roll off, and what replaces it?",
      "Can auto and edge AI become large enough to change the multiple?",
    ],
    riskTopics: ["Apple modem transition", "China handset cycle", "licensing pressure", "auto backlog conversion"],
  }),
  unh: profile({
    slug: "unh",
    ticker: "UNH",
    displayName: "UnitedHealth Group",
    companyName: "UnitedHealth Group Incorporated",
    archetype: "Managed care / Optum services platform",
    irUrl: "https://www.unitedhealthgroup.com/investors.html",
    sourceNote: "Research proxy history built from local thesis model; replace with official filings, earnings supplements and transcript ingestion.",
    revenueStart: 56000,
    revenueEnd: 112000,
    operatingMarginStart: 0.075,
    operatingMarginEnd: 0.079,
    fcfMarginStart: 0.055,
    fcfMarginEnd: 0.065,
    sharesStart: 955,
    sharesEnd: 920,
    netDebtEnd: 72000,
    priceStart: 220,
    priceEnd: 389,
    fairValueStart: 225,
    fairValueEnd: 425,
    baseAssumptions: {
      revenueCagr3Y: 0.055,
      terminalGrowth: 0.025,
      normalizedFcfMargin: 0.065,
      exitFcfMultiple: 16,
      evRevenueMultiple: 1.05,
      discountRate: 0.095,
      qualityAdjustment: 1.05,
      riskHaircut: 0.18,
      dividendYield: 0.022,
      buybackYield: 0.018,
    },
    segments: [
      { name: "UnitedHealthcare Benefits", startMix: 0.58, endMix: 0.53, margin: 0.065 },
      { name: "Optum Health / Value-Based Care", startMix: 0.17, endMix: 0.22, margin: 0.075 },
      { name: "Optum Rx / Insight", startMix: 0.25, endMix: 0.25, margin: 0.085 },
    ],
    peers: ["ELV", "CI", "HUM", "CNC"],
    debateQuestions: [
      "Is medical cost trend a temporary pricing lag or a structural reset in managed-care margin?",
      "Can Medicare Advantage repricing restore profitability without adverse member selection?",
      "Does Optum still deserve a platform premium under PBM and vertical-integration scrutiny?",
    ],
    riskTopics: ["medical cost trend", "Medicare Advantage rates", "PBM regulation", "Optum execution", "cyber remediation"],
  }),
};

export function getDeepResearchBackendProfile(slugOrTicker) {
  const key = String(slugOrTicker ?? "").toLowerCase();
  return deepResearchBackendProfiles[key] ?? Object.values(deepResearchBackendProfiles).find((profile) => profile.ticker.toLowerCase() === key) ?? null;
}

export function listDeepResearchBackendProfiles() {
  return DEEP_RESEARCH_BACKEND_SLUGS.map((slug) => deepResearchBackendProfiles[slug]);
}
