import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const ktosDataset = createLocalDeepResearchDataset({
  ticker: "KTOS",
  companyName: "Kratos Defense & Security Solutions, Inc.",
  sector: "Defense Technology / Tactical Drones / Hypersonics / Space",
  archetype: "Defense growth platform / tactical drone and hypersonic exposure",
  description:
    "KTOS research cockpit focused on tactical drone programs, hypersonic test demand, satellite and space systems, funded backlog, adjusted EBITDA conversion, defense budget exposure, and whether high growth can become durable free cash flow.",
  updatedAt: "2026-05-20",
  currentPrice: 53.47,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "drones-hypersonics", label: "Drones / Hypersonics" },
    { value: "backlog-margins", label: "Backlog / Margins" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "program-momentum", label: "Program Momentum", value: 1.26, format: "number", description: "Research index for drones, hypersonics and space demand.", badge: "Assumption" },
    { key: "backlog-quality", label: "Backlog Quality", value: 0.68, format: "percent", description: "Share of demand assumed funded/convertible; official import pending.", badge: "Placeholder" },
    { key: "margin-path", label: "Adj. EBITDA Path", value: 0.13, format: "percent", description: "Base-case normalized margin bridge for scale economics.", badge: "Assumption" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: 0.08, format: "percent", description: "Cash conversion should lag revenue while programs ramp.", badge: "Assumption" },
    { key: "base-gap", label: "Base Upside / Downside", value: -0.16, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "drones-scale",
      question: "Do tactical drones become production programs or remain prototype/test demand?",
      currentView: "The re-rating requires funded production scale, not just program optionality.",
      metric: "Drone revenue, funded backlog, contract duration",
      evidenceNeeded: "Program awards, production quantities and customer concentration",
      valuationTie: "Revenue CAGR and EV/revenue cross-check",
      bearCase: "Programs remain lumpy and contract awards disappoint.",
    },
    {
      key: "hypersonics-space",
      question: "Can hypersonic and space work create a diversified growth base?",
      currentView: "Diversification is attractive but program timing and margin mix are uneven.",
      metric: "Space/hypersonic backlog, test cadence, margin by mix",
      evidenceNeeded: "Backlog bridge and program-level profitability",
      valuationTie: "Quality adjustment and discount rate",
      bearCase: "Revenue mix grows but margin and cash flow do not scale.",
    },
    {
      key: "cash-conversion",
      question: "When does adjusted EBITDA convert into real FCF?",
      currentView: "The market is paying for growth; cash proof is the main missing underwriting bridge.",
      metric: "FCF, working capital, capex, stock comp",
      evidenceNeeded: "Operating cash flow bridge and capex cadence",
      valuationTie: "Normalized FCF margin",
      bearCase: "Growth absorbs cash and equity dilution continues.",
    },
    {
      key: "budget-durability",
      question: "How sensitive is KTOS to U.S. defense budget timing?",
      currentView: "Growth is defense-priority aligned but still vulnerable to budget delays.",
      metric: "DoD awards, continuing resolutions, funded backlog",
      evidenceNeeded: "Budget line items and award timing",
      valuationTie: "Risk haircut",
      bearCase: "Funding delays push out revenue and compress multiple.",
    },
  ],
  kpiSeries: [
    {
      key: "drones-hypersonics",
      title: "Program Momentum vs Cash Conversion",
      subtitle: "KTOS needs funded drone and hypersonic demand to become visible EBITDA and FCF.",
      sourceStatus: "research_only",
      measures: [
        { key: "programIndex", label: "Program momentum", format: "number", chartType: "bar", color: "#111827", axis: "left" },
        { key: "fcfConversion", label: "FCF conversion %", format: "percent", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q1", programIndex: 80, fcfConversion: -0.03 },
        { period: "FY2024 Q2", programIndex: 86, fcfConversion: -0.01 },
        { period: "FY2024 Q3", programIndex: 92, fcfConversion: 0.01 },
        { period: "FY2024 Q4", programIndex: 101, fcfConversion: 0.02 },
        { period: "FY2025 Q1", programIndex: 112, fcfConversion: 0.03 },
        { period: "FY2025 Q2", programIndex: 124, fcfConversion: 0.04 },
        { period: "FY2025 Q3", programIndex: 132, fcfConversion: 0.05 },
        { period: "FY2025 Q4", programIndex: 143, fcfConversion: 0.06 },
        { period: "FY2026 Q1", programIndex: 152, fcfConversion: 0.07 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "program-scale",
      tab: "drones-hypersonics",
      title: "Tactical Drones and Hypersonic Test Demand",
      thesis: "KTOS is most interesting when tactical drones move from prototype budgets into repeat production awards.",
      evidence: ["Funded drone backlog", "Hypersonic test cadence", "Space system contract duration"],
      watchItems: ["Award pushouts", "Customer concentration", "Lower-margin cost-plus mix"],
      sourceStatus: "research_only",
    },
    {
      key: "backlog-margins",
      tab: "backlog-margins",
      title: "Backlog, EBITDA and Cash Conversion",
      thesis: "A defense-tech multiple needs a credible path from backlog to margin and FCF, not just sales growth.",
      evidence: ["Book-to-bill", "Adjusted EBITDA bridge", "Operating cash flow and capex"],
      watchItems: ["Working-capital drag", "SBC dilution", "Program loss charges"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-05-07", headline: "Can growth convert into FCF?", keyQuestions: ["Are drone programs funded?", "Is EBITDA margin scaling?", "Is working capital still a drag?"], managementTone: "Constructive on demand.", modelReadThrough: "Keep growth high but require cash conversion before raising fair value.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-02-24", headline: "Budget timing and backlog quality", keyQuestions: ["How much backlog is funded?", "What is production vs development mix?", "Any budget delay commentary?"], managementTone: "Positive but timing-aware.", modelReadThrough: "Risk haircut remains material.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-11-06", headline: "Drone program scale evidence", keyQuestions: ["Are tactical systems scaling?", "Is book-to-bill above 1?", "Are margins improving?"], managementTone: "Optimistic.", modelReadThrough: "Support revenue CAGR; do not lift terminal margin yet.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-08-07", headline: "Hypersonics and space cadence", keyQuestions: ["Is demand broad-based?", "Any program slippage?", "Can cash flow turn positive?"], managementTone: "Balanced.", modelReadThrough: "Maintain local valuation row.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-05-08", headline: "Defense-tech scarcity premium", keyQuestions: ["Is the stock pricing perfection?", "Are organic growth rates accelerating?", "What is FCF cadence?"], managementTone: "Growth confidence.", modelReadThrough: "Multiple needs funded backlog proof.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-02-26", headline: "Margin bridge after strong demand", keyQuestions: ["Can EBITDA expand?", "Is drone demand repeatable?", "Is capex rising?"], managementTone: "Constructive.", modelReadThrough: "Add growth confidence, keep cash conservatism.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-11-07", headline: "Backlog visibility", keyQuestions: ["What is funded backlog duration?", "Is space systems mix accretive?", "Are program costs controlled?"], managementTone: "Steady.", modelReadThrough: "No change to risk haircut.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-08-08", headline: "Early growth proof", keyQuestions: ["Is book-to-bill improving?", "Do drones carry attractive margin?", "Any CR/budget impact?"], managementTone: "Cautiously positive.", modelReadThrough: "Small fair value lift from demand visibility.", riskSignal: "Positive", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-08-08", fiscalPeriod: "FY2024 Q2", asOfPrice: 21, fairValue: 18, method: "Early program growth local fallback." },
    { eventDate: "2024-11-07", fiscalPeriod: "FY2024 Q3", asOfPrice: 25, fairValue: 21, method: "Backlog visibility with low cash conversion." },
    { eventDate: "2025-02-26", fiscalPeriod: "FY2024 Q4", asOfPrice: 31, fairValue: 26, method: "Demand acceleration and margin bridge." },
    { eventDate: "2025-05-08", fiscalPeriod: "FY2025 Q1", asOfPrice: 35, fairValue: 29, method: "Defense-tech scarcity premium audited." },
    { eventDate: "2025-08-07", fiscalPeriod: "FY2025 Q2", asOfPrice: 40, fairValue: 33, method: "Hypersonics and space cadence." },
    { eventDate: "2025-11-06", fiscalPeriod: "FY2025 Q3", asOfPrice: 46, fairValue: 38, method: "Drone program scale evidence." },
    { eventDate: "2026-02-24", fiscalPeriod: "FY2025 Q4", asOfPrice: 52, fairValue: 42, method: "Budget timing and funded backlog quality." },
    { eventDate: "2026-05-07", fiscalPeriod: "FY2026 Q1", asOfPrice: 54, fairValue: 45, method: "Base DCF / FCF multiple local run." },
  ],
  valuationBase: {
    revenueBase: 1150,
    revenueCagr3Y: 0.17,
    terminalGrowth: 0.035,
    normalizedFcfMargin: 0.08,
    exitFcfMultiple: 34,
    evRevenueMultiple: 5.5,
    discountRate: 0.105,
    netCashDebt: -150,
    dilutedShares: 179,
    qualityAdjustment: 1.0,
    riskHaircut: 0.2,
    dividendYield: 0,
    buybackYield: 0,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.07, normalizedFcfMargin: 0.03, exitFcfMultiple: 20, evRevenueMultiple: 3, riskHaircut: 0.35, qualityAdjustment: 0.85 },
    Base: {},
    Bull: { revenueCagr3Y: 0.25, normalizedFcfMargin: 0.12, exitFcfMultiple: 45, evRevenueMultiple: 7.5, riskHaircut: 0.11, qualityAdjustment: 1.12 },
  },
  valuationDescription: "Blends DCF, forward FCF multiple and EV/revenue cross-check for defense-tech growth with cash-conversion gating.",
  risks: [
    { title: "Program timing", detail: "Revenue growth can slip if defense awards or budget timing move right.", severity: "high", killSignal: "Book-to-bill drops below 1.0 while valuation remains high." },
    { title: "Cash conversion gap", detail: "Adjusted EBITDA can overstate economics if working capital and capex absorb cash.", severity: "high", killSignal: "FCF stays negative while revenue growth remains strong." },
    { title: "Dilution and SBC", detail: "Growth equity profiles can dilute if cash flow lags.", severity: "medium", killSignal: "Share count rises faster than revenue per share." },
  ],
  monitoring: ["Funded backlog", "Drone production awards", "Adjusted EBITDA margin", "Operating cash flow", "Budget/CR commentary"],
  sourceGaps: ["Official segment backlog and daily price bars need backend import.", "Program-level revenue mix is not yet parsed from filings/transcripts."],
});
