import type { EarningsCallDataset, EarningsFocusTopic } from "../earningsCall/types";

const focus = (topic: EarningsFocusTopic, intensity: number, summary: string) => ({ topic, intensity, summary });

export const gildEarningsDataset: EarningsCallDataset = {
  ticker: "GILD",
  name: "Gilead Sciences",
  sector: "Large-cap biopharma / HIV / oncology / liver disease",
  currency: "USD",
  currentPrice: 134.06,
  priceDate: "2026-05-07",
  primaryMetricName: "Biktarvy Sales",
  currentPeriodId: "q1-2026",
  moduleSummary:
    "GILD is framed around durable HIV cash flows, lenacapavir/Yeztugo prevention upside, oncology BD and whether cell therapy/Trodelvy can diversify growth.",
  valuationNote: "This module is earnings-call intelligence only; a full GILD valuation would require HIV LOE durability, oncology rNPV, BD charges and capital returns.",
  evidence: [
    { id: "gild-q2-2024", title: "GILD Q2 2024 results", sourceType: "official_press_release", date: "2024-08-08", url: "https://www.gilead.com/news/news-details/2024/gilead-sciences-announces-second-quarter-2024-financial-results", extractedMetric: "Q2 2024 HIV, oncology and Veklury dynamics", confidence: "medium" },
    { id: "gild-q3-2024", title: "GILD Q3 2024 results", sourceType: "official_press_release", date: "2024-11-06", url: "https://www.gilead.com/news/news-details/2024/gilead-sciences-announces-third-quarter-2024-financial-results", extractedMetric: "Q3 2024 revenue and HIV growth", confidence: "medium" },
    { id: "gild-q4-2024", title: "GILD Q4/FY 2024 results", sourceType: "official_press_release", date: "2025-02-11", url: "https://www.gilead.com/news/news-details/2025/gilead-sciences-announces-fourth-quarter-and-full-year-2024-financial-results", extractedMetric: "FY 2024 base business and guidance", confidence: "medium" },
    { id: "gild-q1-2025", title: "IBD GILD Q1 2025 read-through", sourceType: "market_data", date: "2025-04-24", url: "https://www.investors.com/news/technology/gilead-stock-gilead-sciences-earnings-q1-2025/", extractedMetric: "Q1 2025 revenue $6.67bn; Biktarvy $3.15bn; Trodelvy miss", confidence: "medium" },
    { id: "gild-q2-2025", title: "GILD Q2 2025 results", sourceType: "official_press_release", date: "2025-08-07", url: "https://investors.gilead.com/news/news-details/2025/Gilead-Sciences-Announces-Second-Quarter-2025-Financial-Results/default.aspx", extractedMetric: "Q2 2025 revenue $7.1bn; Biktarvy $3.5bn; Yeztugo approval", confidence: "high" },
    { id: "gild-q3-2025", title: "GILD Q3 2025 results", sourceType: "official_press_release", date: "2025-10-30", url: "https://investors.gilead.com/news/news-details/2025/Gilead-Sciences-Announces-Third-Quarter-2025-Financial-Results/default.aspx", extractedMetric: "Q3 2025 revenue $7.8bn; Biktarvy $3.7bn; cell therapy -11%", confidence: "high" },
    { id: "gild-q4-2025", title: "GILD Q4/FY 2025 results", sourceType: "official_press_release", date: "2026-02-11", url: "https://www.gilead.com/news/news-details/2026/gilead-sciences-announces-fourth-quarter-and-full-year-2025-financial-results", extractedMetric: "FY 2025 revenue $29.4bn; Biktarvy $14.3bn; Trodelvy $384m Q4", confidence: "high" },
    { id: "gild-q1-2026", title: "GILD Q1 2026 results", sourceType: "official_press_release", date: "2026-05-07", url: "https://investors.gilead.com/news/news-details/2026/Gilead-Sciences-Announces-First-Quarter-Financial-Results/default.aspx", extractedMetric: "Q1 2026 product sales $6.9bn; Biktarvy $3.4bn; cash $8.6bn", confidence: "high" },
    { id: "gild-market-2026-05-07", title: "GILD market data snapshot", sourceType: "market_data", date: "2026-05-07", url: "https://www.marketwatch.com/data-news/gilead-sciences-inc-stock-underperforms-thursday-when-compared-to-competitors-ddb7548a-4c3d9196104d", extractedMetric: "GILD closed at $134.06 on May 7, 2026", confidence: "medium" },
  ],
  quarters: [
    { id: "q2-2024", label: "Q2 2024", callDate: "2024-08-08", totalRevenue: 6_950, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_200, cashOrLiquidity: 9_500, managementTone: "execution", marketFocus: [focus("core_revenue", 8, "HIV durability drove the base case."), focus("pipeline", 7, "Lenacapavir prevention data increased strategic optionality."), focus("cell_therapy", 6, "Cell therapy growth was monitored but not thesis-leading."), focus("capital_allocation", 6, "Dividend and buybacks remained important.")], analystQuestions: ["How durable is Biktarvy?", "How large is lenacapavir prevention?", "Can oncology diversify growth?"], aiSummary: "The debate was still HIV durability first, with lenacapavir beginning to look like the next leg of the story.", sourceEvidenceIds: ["gild-q2-2024"] },
    { id: "q3-2024", label: "Q3 2024", callDate: "2024-11-06", totalRevenue: 7_545, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_470, cashOrLiquidity: 9_800, managementTone: "pipeline", marketFocus: [focus("core_revenue", 8, "Biktarvy and HIV carried the quarter."), focus("pipeline", 8, "Lenacapavir prevention data pulled pipeline debate forward."), focus("cell_therapy", 6, "Yescarta/Tecartus competition stayed relevant."), focus("margin", 5, "IPRD and investment spend affected EPS quality.")], analystQuestions: ["Can lenacapavir reshape prevention?", "Is HIV pricing durable?", "What is the oncology path? "], aiSummary: "Pipeline became more important after lenacapavir data, but HIV cash flow still anchored the stock.", sourceEvidenceIds: ["gild-q3-2024"] },
    { id: "q4-2024", label: "Q4 2024", callDate: "2025-02-11", totalRevenue: 7_600, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_600, cashOrLiquidity: 10_000, managementTone: "execution", marketFocus: [focus("core_revenue", 8, "Base business stability was the central proof point."), focus("pipeline", 8, "Lenacapavir and oncology pipeline shaped 2025 expectations."), focus("capital_allocation", 7, "Cash returns and BD capacity remained visible."), focus("cell_therapy", 6, "Cell therapy competition remained a drag.")], analystQuestions: ["How conservative is 2025 guidance?", "What is lenacapavir launch timing?", "Can Trodelvy regain momentum?"], aiSummary: "Q4 2024 set up 2025 as a year where GILD needed HIV stability plus pipeline conversion.", sourceEvidenceIds: ["gild-q4-2024"] },
    { id: "q1-2025", label: "Q1 2025", callDate: "2025-04-24", totalRevenue: 6_670, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_150, cashOrLiquidity: 9_700, managementTone: "defensive", marketFocus: [focus("core_revenue", 8, "Biktarvy was solid but missed the high-end bar."), focus("pipeline", 7, "Lenacapavir remained the key upside."), focus("cell_therapy", 6, "Cell therapy and Trodelvy softness weighed on diversification."), focus("margin", 5, "EPS beat helped offset revenue miss.")], analystQuestions: ["Was Biktarvy weakness temporary?", "Can Trodelvy reaccelerate?", "How fast can lenacapavir launch?"], aiSummary: "The market briefly returned to defensive questions: HIV was still durable, but oncology/cell therapy diversification looked less clean.", sourceEvidenceIds: ["gild-q1-2025"] },
    { id: "q2-2025", label: "Q2 2025", callDate: "2025-08-07", totalRevenue: 7_100, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_500, cashOrLiquidity: 9_600, managementTone: "inflection", marketFocus: [focus("core_revenue", 8, "HIV growth stayed healthy."), focus("pipeline", 9, "Yeztugo approval made prevention a launch story."), focus("launch_execution", 8, "Investors shifted to uptake, access and persistence."), focus("growth_portfolio", 7, "Trodelvy and Livdelzi diversity mattered more.")], analystQuestions: ["How quickly can Yeztugo ramp?", "What access barriers exist?", "Can Trodelvy support oncology growth?"], aiSummary: "Q2 2025 was the transition from lenacapavir data to Yeztugo launch execution.", sourceEvidenceIds: ["gild-q2-2025"] },
    { id: "q3-2025", label: "Q3 2025", callDate: "2025-10-30", totalRevenue: 7_800, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_686, cashOrLiquidity: 9_400, managementTone: "inflection", marketFocus: [focus("core_revenue", 8, "HIV sales rose 4% and Biktarvy remained the anchor."), focus("launch_execution", 9, "Strong start for Yeztugo became a top discussion point."), focus("pipeline", 8, "Multiple launches/readouts in 2026 drove optimism."), focus("cell_therapy", 7, "Cell therapy sales declined 11%, keeping competitive pressure in focus.")], analystQuestions: ["Is Yeztugo uptake sustainable?", "How should investors price 2026 launches?", "Can cell therapy stabilize?"], aiSummary: "The market focus shifted to launch execution and the breadth of 2026 pipeline catalysts.", sourceEvidenceIds: ["gild-q3-2025"] },
    { id: "q4-2025", label: "Q4 2025", callDate: "2026-02-11", totalRevenue: 7_750, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_650, cashOrLiquidity: 10_600, managementTone: "pipeline", marketFocus: [focus("core_revenue", 8, "FY HIV sales rose 6% and supported the dividend/cash-flow case."), focus("pipeline", 9, "Pipeline and BD became the long-term growth debate."), focus("launch_execution", 8, "Yeztugo launch trajectory remained central."), focus("capital_allocation", 7, "Cash deployment into BD and shareholder returns mattered.")], analystQuestions: ["How large can Yeztugo be?", "How much BD is needed?", "Can oncology improve?"], aiSummary: "Q4 2025 framed Gilead as an HIV compounder trying to buy and launch its next growth layer.", sourceEvidenceIds: ["gild-q4-2025"] },
    { id: "q1-2026", label: "Q1 2026", callDate: "2026-05-07", totalRevenue: 6_950, revenueUnit: "USDm", primaryMetricLabel: "Biktarvy", primaryMetric: 3_400, cashOrLiquidity: 8_600, managementTone: "pipeline", marketFocus: [focus("core_revenue", 8, "HIV sales increased 10%; Biktarvy remained durable."), focus("launch_execution", 9, "Yeztugo and Descovy prevention dynamics became the top debate."), focus("pipeline", 9, "Arcellx, Tubulis and Ouro deals reset the pipeline narrative."), focus("margin", 8, "Acquired IPRD charges made earnings quality the key issue."), focus("cell_therapy", 7, "Cell therapy sales remained under competitive pressure.")], analystQuestions: ["Is Yeztugo guidance credible?", "How should investors treat IPRD charges?", "Can acquisitions create oncology growth?"], aiSummary: "The current debate is whether Gilead's HIV/prevention franchise and BD-heavy pipeline can offset IPRD noise and weak cell therapy.", sourceEvidenceIds: ["gild-q1-2026"] },
  ],
};
