import type { ValuationAssumption } from "../types";
import type { PltrScenarioDefinition, PltrValuationAssumptions } from "./model";

export const defaultPltrValuationAssumptions: PltrValuationAssumptions = {
  currentPrice: 134.88499450683594,
  baseRevenue: 7656,
  revenueCagrYears1To5: 0.28,
  terminalRevenueGrowth: 0.04,
  adjustedOperatingMargin: 0.52,
  gaapOperatingMargin: 0.36,
  fcfMargin: 0.42,
  sbcAsPctRevenue: 0.12,
  normalizedSbcAsPctRevenue: 0.06,
  dilutionRate: 0.015,
  taxRate: 0.18,
  wacc: 0.095,
  terminalMultiple: 22,
  revenueMultiple: 18,
  fcfYield: 0.035,
  netCash: 8000,
  dilutedShares: 2562,
  ruleOf40MultipleSlope: 0.18,
};

const AS_OF_DATE = "2026-05-04";
const ASSUMPTION_PROVENANCE =
  "analyst_assumption: PLTR first-version underwriting defaults. Replace with user-approved model assumptions before investment use.";

export const pltrValuationAssumptionKeys = [
  "currentPrice",
  "baseRevenue",
  "revenueCagrYears1To5",
  "terminalRevenueGrowth",
  "adjustedOperatingMargin",
  "gaapOperatingMargin",
  "fcfMargin",
  "sbcAsPctRevenue",
  "normalizedSbcAsPctRevenue",
  "dilutionRate",
  "taxRate",
  "wacc",
  "terminalMultiple",
  "revenueMultiple",
  "fcfYield",
  "netCash",
  "dilutedShares",
  "ruleOf40MultipleSlope",
] as const;

export const pltrAssumptionDefinitions: ValuationAssumption[] = [
  {
    key: "currentPrice",
    label: "Current Price",
    value: defaultPltrValuationAssumptions.currentPrice,
    min: 25,
    max: 500,
    step: 0.5,
    format: "currency",
    source: "actual",
    description: "Editable market price used only for upside/downside, current EV, and reverse DCF. The default is an unofficial yfinance snapshot, not an official company source.",
    category: "Market",
    unit: "USD",
    periodicity: "annual",
    asOfDate: "2026-05-11",
    provenance: "yfinance_snapshot: data/local/pltr/yfinance/pltr_chart_snapshot.json.",
  },
  {
    key: "baseRevenue",
    label: "FY Revenue Base",
    value: defaultPltrValuationAssumptions.baseRevenue,
    min: 3500,
    max: 12000,
    step: 25,
    format: "number",
    source: "actual",
    description: "FY 2026 revenue guidance midpoint in USD millions, used as the forward base for scenario valuation.",
    category: "Revenue",
    unit: "USD",
    periodicity: "forward annual",
    asOfDate: AS_OF_DATE,
    provenance: "company_disclosure: Q1 2026 business update guidance midpoint.",
  },
  {
    key: "revenueCagrYears1To5",
    label: "Revenue CAGR",
    value: defaultPltrValuationAssumptions.revenueCagrYears1To5,
    min: 0.05,
    max: 0.55,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Five-year revenue CAGR. This is the core debate for PLTR because valuation already discounts exceptional growth.",
    category: "Revenue",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "terminalRevenueGrowth",
    label: "Terminal Growth",
    value: defaultPltrValuationAssumptions.terminalRevenueGrowth,
    min: 0.02,
    max: 0.06,
    step: 0.001,
    format: "percent",
    source: "assumption",
    description: "Long-term nominal revenue growth after the explicit forecast period.",
    category: "DCF",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "adjustedOperatingMargin",
    label: "Adjusted Operating Margin",
    value: defaultPltrValuationAssumptions.adjustedOperatingMargin,
    min: 0.25,
    max: 0.68,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Steady-state adjusted operating margin. Kept separate from GAAP margin because SBC is central to the PLTR debate.",
    category: "Margin",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "gaapOperatingMargin",
    label: "GAAP Operating Margin",
    value: defaultPltrValuationAssumptions.gaapOperatingMargin,
    min: 0.05,
    max: 0.55,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Steady-state GAAP operating margin after stock compensation and payroll tax effects.",
    category: "Margin",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "fcfMargin",
    label: "FCF Margin",
    value: defaultPltrValuationAssumptions.fcfMargin,
    min: 0.15,
    max: 0.65,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Company-level free cash flow margin. Per-share value is separately penalized through dilution.",
    category: "Cash Flow",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "sbcAsPctRevenue",
    label: "SBC / Revenue",
    value: defaultPltrValuationAssumptions.sbcAsPctRevenue,
    min: 0,
    max: 0.3,
    step: 0.0025,
    format: "percent",
    source: "actual",
    description: "Current SBC intensity used in the SBC tracker, not a hidden valuation booster.",
    category: "SBC",
    unit: "percent",
    periodicity: "annual",
    asOfDate: AS_OF_DATE,
    provenance: "company_disclosure: Q1 2026 filing and business update seed values.",
  },
  {
    key: "normalizedSbcAsPctRevenue",
    label: "Normalized SBC / Revenue",
    value: defaultPltrValuationAssumptions.normalizedSbcAsPctRevenue,
    min: 0,
    max: 0.2,
    step: 0.0025,
    format: "percent",
    source: "assumption",
    description: "Long-term SBC intensity. Used as an explicit forecast assumption, not inferred from transcript sentiment.",
    category: "SBC",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "dilutionRate",
    label: "Dilution Rate",
    value: defaultPltrValuationAssumptions.dilutionRate,
    min: -0.02,
    max: 0.06,
    step: 0.001,
    format: "percent",
    source: "assumption",
    description: "Annual diluted share-count change. Negative values imply buyback offset.",
    category: "SBC",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "taxRate",
    label: "Tax Rate",
    value: defaultPltrValuationAssumptions.taxRate,
    min: 0.1,
    max: 0.25,
    step: 0.0025,
    format: "percent",
    source: "assumption",
    description: "Cash tax rate used in DCF cross-checks.",
    category: "DCF",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "wacc",
    label: "WACC",
    value: defaultPltrValuationAssumptions.wacc,
    min: 0.07,
    max: 0.14,
    step: 0.0025,
    format: "percent",
    source: "assumption",
    description: "Discount rate for long-duration software cash flows.",
    category: "DCF",
    unit: "percent",
    periodicity: "annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "terminalMultiple",
    label: "Terminal FCF Multiple",
    value: defaultPltrValuationAssumptions.terminalMultiple,
    min: 8,
    max: 45,
    step: 0.5,
    format: "multiple",
    source: "assumption",
    description: "Exit FCF multiple used in the scenario-based long-term FCF per-share framework.",
    category: "Multiples",
    unit: "multiple",
    periodicity: "forward annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "revenueMultiple",
    label: "Revenue Multiple",
    value: defaultPltrValuationAssumptions.revenueMultiple,
    min: 4,
    max: 35,
    step: 0.5,
    format: "multiple",
    source: "assumption",
    description: "Forward EV/revenue multiple cross-check. Useful for PLTR because high near-term profitability can still leave valuation dominated by growth expectations.",
    category: "Multiples",
    unit: "multiple",
    periodicity: "forward annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "fcfYield",
    label: "Target FCF Yield",
    value: defaultPltrValuationAssumptions.fcfYield,
    min: 0.015,
    max: 0.08,
    step: 0.0005,
    format: "percent",
    source: "assumption",
    description: "Target company-level FCF yield cross-check.",
    category: "Multiples",
    unit: "percent",
    periodicity: "forward annual",
    provenance: ASSUMPTION_PROVENANCE,
  },
  {
    key: "netCash",
    label: "Net Cash",
    value: defaultPltrValuationAssumptions.netCash,
    min: 0,
    max: 15000,
    step: 50,
    format: "number",
    source: "actual",
    description: "Cash, cash equivalents, and Treasury securities less debt in USD millions.",
    category: "Balance Sheet",
    unit: "USD",
    periodicity: "quarterly",
    asOfDate: AS_OF_DATE,
    provenance: "company_disclosure: Q1 2026 business update states about $8.0B cash, equivalents, and US Treasury securities and no debt.",
  },
  {
    key: "dilutedShares",
    label: "Diluted Shares",
    value: defaultPltrValuationAssumptions.dilutedShares,
    min: 2000,
    max: 3200,
    step: 5,
    format: "number",
    source: "derived",
    description: "Diluted share-count proxy in millions, derived from Q1 2026 net income and diluted EPS until XBRL extraction is refreshed.",
    category: "Share Count",
    unit: "share",
    periodicity: "quarterly",
    asOfDate: AS_OF_DATE,
    provenance: "derived: Q1 2026 net income divided by diluted EPS. Validate against 10-Q diluted weighted-average shares.",
  },
  {
    key: "ruleOf40MultipleSlope",
    label: "Rule-of-40 Multiple Slope",
    value: defaultPltrValuationAssumptions.ruleOf40MultipleSlope,
    min: 0.05,
    max: 0.35,
    step: 0.005,
    format: "number",
    source: "assumption",
    description: "Revenue multiple sensitivity to Rule of 40 score in the implied multiple framework.",
    category: "Multiples",
    provenance: ASSUMPTION_PROVENANCE,
  },
];

export const pltrScenarioDefinitions: PltrScenarioDefinition[] = [
  {
    name: "Bear",
    summary: "AIP hype fades, commercial growth decelerates, government normalizes, SBC stays elevated, and the multiple compresses.",
    assumptions: {
      revenueCagrYears1To5: 0.16,
      commercialRevenueCagr: 0.18,
      governmentRevenueCagr: 0.1,
      adjustedOperatingMargin: 0.42,
      gaapOperatingMargin: 0.22,
      fcfMargin: 0.28,
      normalizedSbcAsPctRevenue: 0.11,
      dilutionRate: 0.035,
      terminalMultiple: 12,
      revenueMultiple: 7,
      fcfYield: 0.065,
    },
  },
  {
    name: "Base",
    summary: "AIP sustains strong US commercial growth, government remains durable, margins expand gradually, and the premium multiple normalizes.",
    assumptions: {
      revenueCagrYears1To5: 0.28,
      commercialRevenueCagr: 0.34,
      governmentRevenueCagr: 0.18,
      adjustedOperatingMargin: 0.52,
      gaapOperatingMargin: 0.36,
      fcfMargin: 0.42,
      normalizedSbcAsPctRevenue: 0.06,
      dilutionRate: 0.015,
      terminalMultiple: 22,
      revenueMultiple: 18,
      fcfYield: 0.035,
    },
  },
  {
    name: "Bull",
    summary: "PLTR becomes a durable enterprise AI operating layer, commercial revenue compounds strongly, margins expand, and dilution fades.",
    assumptions: {
      revenueCagrYears1To5: 0.38,
      commercialRevenueCagr: 0.46,
      governmentRevenueCagr: 0.24,
      adjustedOperatingMargin: 0.6,
      gaapOperatingMargin: 0.46,
      fcfMargin: 0.5,
      normalizedSbcAsPctRevenue: 0.04,
      dilutionRate: 0.005,
      terminalMultiple: 30,
      revenueMultiple: 25,
      fcfYield: 0.026,
    },
  },
  {
    name: "Hyper Bull",
    summary: "Speculative case: PLTR becomes a category-defining AI infrastructure software platform with unusually persistent growth and very high FCF margin.",
    assumptions: {
      revenueCagrYears1To5: 0.48,
      commercialRevenueCagr: 0.58,
      governmentRevenueCagr: 0.3,
      adjustedOperatingMargin: 0.66,
      gaapOperatingMargin: 0.52,
      fcfMargin: 0.56,
      normalizedSbcAsPctRevenue: 0.03,
      dilutionRate: 0,
      terminalMultiple: 38,
      revenueMultiple: 32,
      fcfYield: 0.02,
    },
  },
];

export const pltrScenarioPresets = Object.fromEntries(
  pltrScenarioDefinitions
    .filter((scenario) => scenario.name !== "Hyper Bull")
    .map((scenario) => [scenario.name, scenario.assumptions]),
) as Record<"Bear" | "Base" | "Bull", Partial<PltrValuationAssumptions>>;
