import type { ValidationWarning } from "../types";
import type { PltrActualQuarter, PltrDataset, PltrGuidancePoint, PltrMetric, PltrMetricUnit, PltrResearchSignal } from "./model";
import { pltrSources } from "./data/sources";
import { pltrQaPairs, pltrTopicTrends, pltrTranscriptEvents } from "./data/transcripts";

const Q1_2026_BUSINESS_UPDATE = "https://investors.palantir.com/files/Palantir%20-%20Q1%202026%20Business%20Update.pdf";
const SEC_COMPANYFACTS = "https://data.sec.gov/api/xbrl/companyfacts/CIK0001321655.json";
const SEC_SUBMISSIONS = "https://data.sec.gov/submissions/CIK0001321655.json";

const metricCatalog: Array<{ key: string; label: string; unit: PltrMetricUnit }> = [
  { key: "revenue", label: "Revenue", unit: "USDm" },
  { key: "yoyRevenueGrowth", label: "YoY Revenue Growth", unit: "percent" },
  { key: "qoqRevenueGrowth", label: "QoQ Revenue Growth", unit: "percent" },
  { key: "usCommercialRevenue", label: "US Commercial Revenue", unit: "USDm" },
  { key: "usCommercialGrowth", label: "US Commercial Growth", unit: "percent" },
  { key: "commercialRevenue", label: "Commercial Revenue", unit: "USDm" },
  { key: "governmentRevenue", label: "Government Revenue", unit: "USDm" },
  { key: "usGovernmentRevenue", label: "US Government Revenue", unit: "USDm" },
  { key: "internationalCommercialRevenue", label: "International Commercial Revenue", unit: "USDm" },
  { key: "internationalGovernmentRevenue", label: "International Government Revenue", unit: "USDm" },
  { key: "customerCount", label: "Customer Count", unit: "count" },
  { key: "commercialCustomerCount", label: "Commercial Customer Count", unit: "count" },
  { key: "usCommercialCustomerCount", label: "US Commercial Customer Count", unit: "count" },
  { key: "rpo", label: "Remaining Performance Obligations", unit: "USDm" },
  { key: "billings", label: "Billings", unit: "USDm" },
  { key: "adjustedOperatingIncome", label: "Adjusted Operating Income", unit: "USDm" },
  { key: "gaapOperatingIncome", label: "GAAP Operating Income", unit: "USDm" },
  { key: "adjustedOperatingMargin", label: "Adjusted Operating Margin", unit: "percent" },
  { key: "gaapOperatingMargin", label: "GAAP Operating Margin", unit: "percent" },
  { key: "freeCashFlow", label: "Free Cash Flow", unit: "USDm" },
  { key: "adjustedFreeCashFlow", label: "Adjusted Free Cash Flow", unit: "USDm" },
  { key: "fcfMargin", label: "FCF Margin", unit: "percent" },
  { key: "ruleOf40", label: "Rule of 40", unit: "percent" },
  { key: "sbcExpense", label: "Stock-Based Compensation Expense", unit: "USDm" },
  { key: "sbcAsPctRevenue", label: "SBC as % of Revenue", unit: "percent" },
  { key: "dilutedShareCount", label: "Diluted Share Count", unit: "shares_m" },
  { key: "netIncome", label: "Net Income", unit: "USDm" },
  { key: "eps", label: "EPS", unit: "USD" },
  { key: "cashAndEquivalents", label: "Cash, Equivalents, and Treasury Securities", unit: "USDm" },
  { key: "debt", label: "Debt", unit: "USDm" },
  { key: "netCash", label: "Net Cash", unit: "USDm" },
  { key: "guidanceRevenue", label: "Guidance Revenue", unit: "USDm" },
  { key: "guidanceOperatingIncome", label: "Guidance Adjusted Operating Income", unit: "USDm" },
  { key: "guidanceFcf", label: "Guidance Adjusted Free Cash Flow", unit: "USDm" },
  { key: "netDollarRetention", label: "Net Dollar Retention", unit: "percent" },
  { key: "largeDeals1m", label: "Deals >= $1M", unit: "count" },
  { key: "largeDeals5m", label: "Deals >= $5M", unit: "count" },
  { key: "largeDeals10m", label: "Deals >= $10M", unit: "count" },
];

type MetricSeed = {
  value: number | null;
  sourceUrl?: string | null;
  sourceType?: PltrMetric["sourceType"];
  sourceConfidence?: PltrMetric["sourceConfidence"];
  notes?: string;
};

function buildMetrics(period: string, seeds: Record<string, MetricSeed>): Record<string, PltrMetric> {
  return Object.fromEntries(
    metricCatalog.map((item) => {
      const seed = seeds[item.key];
      return [
        item.key,
        {
          key: item.key,
          label: item.label,
          value: seed?.value ?? null,
          unit: item.unit,
          period,
          sourceUrl: seed?.sourceUrl ?? null,
          sourceType: seed?.sourceType ?? "manual_todo",
          sourceConfidence: seed?.sourceConfidence ?? "todo",
          notes: seed?.notes ?? "Not disclosed in the starter dataset. Run the PLTR fetch and metric-builder scripts or manually add a sourced value.",
        } satisfies PltrMetric,
      ];
    }),
  );
}

function q(
  periodId: string,
  label: string,
  fiscalYear: number,
  fiscalQuarter: 1 | 2 | 3 | 4,
  periodEnd: string,
  seeds: Record<string, MetricSeed>,
): PltrActualQuarter {
  return {
    periodId,
    label,
    fiscalYear,
    fiscalQuarter,
    periodEnd,
    metrics: buildMetrics(periodId, seeds),
  };
}

const companyPresentationSeed = {
  sourceUrl: Q1_2026_BUSINESS_UPDATE,
  sourceType: "company_presentation" as const,
  sourceConfidence: "high" as const,
};

const secSeed = {
  sourceUrl: SEC_COMPANYFACTS,
  sourceType: "sec_filing" as const,
  sourceConfidence: "high" as const,
};

const secDerivedSeed = {
  sourceUrl: SEC_COMPANYFACTS,
  sourceType: "derived" as const,
  sourceConfidence: "medium" as const,
};

export const pltrActuals: PltrActualQuarter[] = [
  q("q1-2024", "Q1 2024", 2024, 1, "2024-03-31", {
    revenue: { value: 634.338, ...secSeed, notes: "Quarterly revenue from SEC companyfacts." },
    gaapOperatingIncome: { value: 80.881, ...secSeed, notes: "GAAP operating income from SEC companyfacts." },
    gaapOperatingMargin: { value: 80.881 / 634.338, ...secDerivedSeed, notes: "Derived from GAAP operating income and revenue." },
    freeCashFlow: { value: 129.579 - 2.664, ...secDerivedSeed, notes: "Derived from operating cash flow less capital expenditures in SEC companyfacts." },
    fcfMargin: { value: (129.579 - 2.664) / 634.338, ...secDerivedSeed, notes: "Derived from free cash flow and revenue." },
    sbcExpense: { value: 125.651, ...secSeed, notes: "Stock-based compensation expense from SEC companyfacts." },
    sbcAsPctRevenue: { value: 125.651 / 634.338, ...secDerivedSeed, notes: "Derived from SBC expense and revenue." },
    dilutedShareCount: { value: 2400.107, ...secSeed, notes: "Weighted average diluted shares from SEC companyfacts." },
    netIncome: { value: 105.53, ...secSeed, notes: "Net income from SEC companyfacts." },
  }),
  q("q2-2024", "Q2 2024", 2024, 2, "2024-06-30", {
    revenue: { value: 1312.472 - 634.338, ...secDerivedSeed, notes: "Derived as Q2 2024 YTD revenue less Q1 2024 revenue from SEC companyfacts." },
    yoyRevenueGrowth: { value: 0.27, sourceUrl: "https://investors.palantir.com/news-details/2024/Palantir-Reports-Revenue-Growth-of-27-Year-Over-Year-and-Raises-Full-Year-Revenue-Guidance-Record-GAAP-EPS-of-0.06-in-Q2-2024/", sourceType: "official_ir", sourceConfidence: "high", notes: "Headline year-over-year revenue growth in the official Q2 2024 release." },
    gaapOperatingIncome: { value: 186.22 - 80.881, ...secDerivedSeed, notes: "Derived as Q2 2024 YTD operating income less Q1 2024 operating income from SEC companyfacts." },
    gaapOperatingMargin: { value: (186.22 - 80.881) / (1312.472 - 634.338), ...secDerivedSeed, notes: "Derived from GAAP operating income and revenue." },
    freeCashFlow: { value: (273.766 - 129.579) - (5.543 - 2.664), ...secDerivedSeed, notes: "Derived as quarterly operating cash flow less quarterly capital expenditures from SEC companyfacts." },
    fcfMargin: { value: ((273.766 - 129.579) - (5.543 - 2.664)) / (1312.472 - 634.338), ...secDerivedSeed, notes: "Derived from free cash flow and revenue." },
    sbcExpense: { value: 267.415 - 125.651, ...secDerivedSeed, notes: "Derived as Q2 2024 YTD SBC less Q1 2024 SBC from SEC companyfacts." },
    sbcAsPctRevenue: { value: (267.415 - 125.651) / (1312.472 - 634.338), ...secDerivedSeed, notes: "Derived from SBC expense and revenue." },
    dilutedShareCount: { value: 2407.402, ...secSeed, notes: "YTD weighted average diluted shares from SEC companyfacts; use as the best available period proxy." },
    netIncome: { value: 239.656 - 105.53, ...secDerivedSeed, notes: "Derived as Q2 2024 YTD net income less Q1 2024 net income from SEC companyfacts." },
  }),
  q("q3-2024", "Q3 2024", 2024, 3, "2024-09-30", {
    revenue: { value: 2037.988 - 1312.472, ...secDerivedSeed, notes: "Derived as Q3 2024 YTD revenue less Q2 2024 YTD revenue from SEC companyfacts." },
    yoyRevenueGrowth: { value: 0.3, sourceUrl: "https://investors.palantir.com/news-details/2024/Palantir-Reports-Revenue-Growth-of-30-YY-U.S.-Revenue-Growth-of-44-YY-GAAP-EPS-of-0.06-Raises-Full-Year-Guidance-on-Revenue-U.S.-Comm-Revenue-Adj.-Free-Cash-Flow-Adj.-Op.-Income-Above-Consensus-Estimates-on-AI-Demand-that-Wont-Slow-Down/", sourceType: "official_ir", sourceConfidence: "high", notes: "Headline year-over-year revenue growth in the official Q3 2024 release." },
    gaapOperatingIncome: { value: 299.36 - 186.22, ...secDerivedSeed, notes: "Derived as Q3 2024 YTD operating income less Q2 2024 YTD operating income from SEC companyfacts." },
    gaapOperatingMargin: { value: (299.36 - 186.22) / (2037.988 - 1312.472), ...secDerivedSeed, notes: "Derived from GAAP operating income and revenue." },
    freeCashFlow: { value: (693.538 - 273.766) - (9.528 - 5.543), ...secDerivedSeed, notes: "Derived as quarterly operating cash flow less quarterly capital expenditures from SEC companyfacts." },
    fcfMargin: { value: ((693.538 - 273.766) - (9.528 - 5.543)) / (2037.988 - 1312.472), ...secDerivedSeed, notes: "Derived from free cash flow and revenue." },
    sbcExpense: { value: 409.84 - 267.415, ...secDerivedSeed, notes: "Derived as Q3 2024 YTD SBC less Q2 2024 YTD SBC from SEC companyfacts." },
    sbcAsPctRevenue: { value: (409.84 - 267.415) / (2037.988 - 1312.472), ...secDerivedSeed, notes: "Derived from SBC expense and revenue." },
    dilutedShareCount: { value: 2424.864, ...secSeed, notes: "YTD weighted average diluted shares from SEC companyfacts; use as the best available period proxy." },
    netIncome: { value: 383.181 - 239.656, ...secDerivedSeed, notes: "Derived as Q3 2024 YTD net income less Q2 2024 YTD net income from SEC companyfacts." },
  }),
  q("q4-2024", "Q4 2024", 2024, 4, "2024-12-31", {
    revenue: { value: 2865.507 - 2037.988, ...secDerivedSeed, notes: "Derived as FY 2024 revenue less Q3 2024 YTD revenue from SEC companyfacts." },
    yoyRevenueGrowth: { value: 0.36, sourceUrl: "https://investors.palantir.com/news-details/2025/Palantir-Reports-Q4-2024-Revenue-Growth-of-36-YY-U.S.-Revenue-Growth-of-52-YY-Issues-FY-2025-Revenue-Guidance-of-31-YY-Growth-Eviscerating-Consensus-Estimates/", sourceType: "official_ir", sourceConfidence: "high", notes: "Headline year-over-year revenue growth in the official Q4 2024 release." },
    gaapOperatingIncome: { value: 310.403 - 299.36, ...secDerivedSeed, notes: "Derived as FY 2024 operating income less Q3 2024 YTD operating income from SEC companyfacts." },
    gaapOperatingMargin: { value: (310.403 - 299.36) / (2865.507 - 2037.988), ...secDerivedSeed, notes: "Derived from GAAP operating income and revenue." },
    freeCashFlow: { value: (1153.865 - 693.538) - (12.634 - 9.528), ...secDerivedSeed, notes: "Derived as quarterly operating cash flow less quarterly capital expenditures from SEC companyfacts." },
    fcfMargin: { value: ((1153.865 - 693.538) - (12.634 - 9.528)) / (2865.507 - 2037.988), ...secDerivedSeed, notes: "Derived from free cash flow and revenue." },
    sbcExpense: { value: 691.638 - 409.84, ...secDerivedSeed, notes: "Derived as FY 2024 SBC less Q3 2024 YTD SBC from SEC companyfacts." },
    sbcAsPctRevenue: { value: (691.638 - 409.84) / (2865.507 - 2037.988), ...secDerivedSeed, notes: "Derived from SBC expense and revenue." },
    dilutedShareCount: { value: 2450.818, ...secSeed, notes: "FY 2024 weighted average diluted shares from SEC companyfacts." },
    netIncome: { value: 462.19 - 383.181, ...secDerivedSeed, notes: "Derived as FY 2024 net income less Q3 2024 YTD net income from SEC companyfacts." },
    cashAndEquivalents: { value: 2098.524, ...secSeed, notes: "Cash and cash equivalents at December 31, 2024 from SEC companyfacts." },
    netCash: { value: 2098.524, ...secDerivedSeed, notes: "Debt is not loaded for this period in the starter dataset; cash is used as a conservative net-cash proxy pending official backfill." },
  }),
  q("q1-2025", "Q1 2025", 2025, 1, "2025-03-31", {
    revenue: { value: 883.855, ...companyPresentationSeed, notes: "Total revenue from Q1 2026 business update comparison chart." },
    yoyRevenueGrowth: { value: 0.39, ...companyPresentationSeed, notes: "Rule of 40 reconciliation chart." },
    usCommercialRevenue: { value: 255, ...companyPresentationSeed, notes: "Q1 2026 business update comparison chart." },
    usCommercialGrowth: { value: null },
    commercialRevenue: { value: 397, ...companyPresentationSeed, notes: "Q1 2026 business update comparison chart." },
    governmentRevenue: { value: 487, ...companyPresentationSeed, notes: "Q1 2026 business update comparison chart." },
    usGovernmentRevenue: { value: 373, ...companyPresentationSeed, notes: "Q1 2026 business update comparison chart." },
    customerCount: { value: 769, ...companyPresentationSeed, notes: "TTM customer count ending March 31, 2025." },
    commercialCustomerCount: { value: 622, ...companyPresentationSeed, notes: "TTM commercial customer count ending March 31, 2025." },
    usCommercialCustomerCount: { value: 432, ...companyPresentationSeed, notes: "TTM US commercial customer count ending March 31, 2025." },
    adjustedOperatingIncome: { value: 391, ...companyPresentationSeed, notes: "Rounded adjusted operating income chart value." },
    gaapOperatingIncome: { value: 176.048, ...secSeed, notes: "SEC filing seed value; refresh through XBRL metric builder." },
    adjustedOperatingMargin: { value: 0.44, ...companyPresentationSeed, notes: "Adjusted operating margin from Rule of 40 reconciliation." },
    gaapOperatingMargin: { value: 176.048 / 883.855, sourceUrl: SEC_COMPANYFACTS, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from GAAP operating income and revenue." },
    adjustedFreeCashFlow: { value: 370, ...companyPresentationSeed, notes: "Rounded adjusted FCF chart value." },
    fcfMargin: { value: 0.42, ...companyPresentationSeed, notes: "Adjusted FCF margin chart value." },
    ruleOf40: { value: 0.83, ...companyPresentationSeed, notes: "Rule of 40 reconciliation." },
    sbcExpense: { value: 155.339, ...secSeed, notes: "SEC filing seed value; validate with XBRL metric builder." },
    sbcAsPctRevenue: { value: 155.339 / 883.855, sourceUrl: SEC_COMPANYFACTS, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from SBC expense and revenue." },
    dilutedShareCount: { value: 2552.818, ...secSeed, notes: "Weighted average diluted shares from SEC companyfacts." },
    freeCashFlow: { value: 310.263 - 6.184, ...secDerivedSeed, notes: "Derived from operating cash flow less capital expenditures in SEC companyfacts." },
  }),
  q("q2-2025", "Q2 2025", 2025, 2, "2025-06-30", {
    revenue: { value: 464.385 / 0.46, sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from rounded adjusted operating income and adjusted operating margin chart; replace with XBRL value." },
    yoyRevenueGrowth: { value: 0.48, ...companyPresentationSeed, notes: "Rule of 40 reconciliation chart." },
    customerCount: { value: 849, ...companyPresentationSeed, notes: "TTM customer count ending June 30, 2025." },
    commercialCustomerCount: { value: 692, ...companyPresentationSeed, notes: "TTM commercial customer count ending June 30, 2025." },
    usCommercialCustomerCount: { value: 485, ...companyPresentationSeed, notes: "TTM US commercial customer count ending June 30, 2025." },
    adjustedOperatingIncome: { value: 464.385, ...companyPresentationSeed, notes: "Adjusted operating income from Q1 2026 business update reconciliation." },
    gaapOperatingIncome: { value: 269.317, ...companyPresentationSeed, notes: "GAAP operating income from Q1 2026 business update reconciliation." },
    adjustedOperatingMargin: { value: 0.46, ...companyPresentationSeed, notes: "Adjusted operating margin from Rule of 40 reconciliation." },
    gaapOperatingMargin: { value: 269.317 / (464.385 / 0.46), sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from GAAP operating income and revenue proxy." },
    ruleOf40: { value: 0.94, ...companyPresentationSeed, notes: "Rule of 40 reconciliation." },
    dilutedShareCount: { value: 2557.911, ...secSeed, notes: "YTD weighted average diluted shares from SEC companyfacts; use as the best available period proxy." },
    freeCashFlow: { value: (849.514 - 310.263) - (13.818 - 6.184), ...secDerivedSeed, notes: "Derived as quarterly operating cash flow less quarterly capital expenditures from SEC companyfacts." },
    sbcExpense: { value: 315.31 - 155.339, ...secDerivedSeed, notes: "Derived as Q2 2025 YTD SBC less Q1 2025 SBC from SEC companyfacts." },
    sbcAsPctRevenue: { value: (315.31 - 155.339) / (464.385 / 0.46), ...secDerivedSeed, notes: "Derived from SBC expense and revenue proxy." },
  }),
  q("q3-2025", "Q3 2025", 2025, 3, "2025-09-30", {
    revenue: { value: 1181.092, sourceUrl: SEC_SUBMISSIONS, sourceType: "sec_filing", sourceConfidence: "medium", notes: "Seeded from Q3 2025 10-Q filing summary; refresh through official filing parser." },
    yoyRevenueGrowth: { value: 0.63, ...companyPresentationSeed, notes: "Rule of 40 reconciliation chart." },
    commercialRevenue: { value: 548.416, sourceUrl: SEC_SUBMISSIONS, sourceType: "sec_filing", sourceConfidence: "medium", notes: "Q3 2025 10-Q segment revenue seed; refresh through official filing parser." },
    governmentRevenue: { value: 632.676, sourceUrl: SEC_SUBMISSIONS, sourceType: "sec_filing", sourceConfidence: "medium", notes: "Q3 2025 10-Q segment revenue seed; refresh through official filing parser." },
    customerCount: { value: 911, ...companyPresentationSeed, notes: "TTM customer count ending September 30, 2025." },
    commercialCustomerCount: { value: 742, ...companyPresentationSeed, notes: "TTM commercial customer count ending September 30, 2025." },
    usCommercialCustomerCount: { value: 530, ...companyPresentationSeed, notes: "TTM US commercial customer count ending September 30, 2025." },
    rpo: { value: 2600, ...companyPresentationSeed, notes: "Total RPO chart value in USD millions." },
    billings: { value: 1460, ...companyPresentationSeed, notes: "Billings chart value in USD millions; verify label ordering from source PDF." },
    adjustedOperatingIncome: { value: 600.54, ...companyPresentationSeed, notes: "Adjusted operating income from Q1 2026 business update reconciliation." },
    gaapOperatingIncome: { value: 393.256, ...companyPresentationSeed, notes: "GAAP operating income from Q1 2026 business update reconciliation." },
    adjustedOperatingMargin: { value: 0.51, ...companyPresentationSeed, notes: "Adjusted operating margin from Rule of 40 reconciliation." },
    gaapOperatingMargin: { value: 393.256 / 1181.092, sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from GAAP operating income and seeded revenue." },
    ruleOf40: { value: 1.14, ...companyPresentationSeed, notes: "Rule of 40 reconciliation." },
    dilutedShareCount: { value: 2562.367, ...secSeed, notes: "YTD weighted average diluted shares from SEC companyfacts; use as the best available period proxy." },
    freeCashFlow: { value: (1357.178 - 849.514) - (20.61 - 13.818), ...secDerivedSeed, notes: "Derived as quarterly operating cash flow less quarterly capital expenditures from SEC companyfacts." },
    sbcExpense: { value: 487.628 - 315.31, ...secDerivedSeed, notes: "Derived as Q3 2025 YTD SBC less Q2 2025 YTD SBC from SEC companyfacts." },
    sbcAsPctRevenue: { value: (487.628 - 315.31) / 1181.092, ...secDerivedSeed, notes: "Derived from SBC expense and revenue." },
  }),
  q("q4-2025", "Q4 2025", 2025, 4, "2025-12-31", {
    revenue: { value: 798 / 0.57, sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from rounded adjusted operating income and adjusted operating margin chart; replace with 10-K value." },
    yoyRevenueGrowth: { value: 0.7, ...companyPresentationSeed, notes: "Rule of 40 reconciliation chart." },
    customerCount: { value: 954, ...companyPresentationSeed, notes: "TTM customer count ending December 31, 2025." },
    commercialCustomerCount: { value: 780, ...companyPresentationSeed, notes: "TTM commercial customer count ending December 31, 2025." },
    usCommercialCustomerCount: { value: 571, ...companyPresentationSeed, notes: "TTM US commercial customer count ending December 31, 2025." },
    rpo: { value: 4080, ...companyPresentationSeed, notes: "Total RPO chart value in USD millions." },
    billings: { value: 1490, ...companyPresentationSeed, notes: "Billings chart value in USD millions; verify label ordering from source PDF." },
    adjustedOperatingIncome: { value: 798, ...companyPresentationSeed, notes: "Rounded adjusted operating income chart value." },
    gaapOperatingIncome: { value: 575, ...companyPresentationSeed, notes: "Rounded GAAP operating income chart value." },
    adjustedOperatingMargin: { value: 0.57, ...companyPresentationSeed, notes: "Adjusted operating margin from Rule of 40 reconciliation." },
    gaapOperatingMargin: { value: 575 / (798 / 0.57), sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from GAAP operating income and revenue proxy." },
    ruleOf40: { value: 1.27, ...companyPresentationSeed, notes: "Rule of 40 reconciliation." },
    dilutedShareCount: { value: 2565.197, ...secSeed, notes: "FY 2025 weighted average diluted shares from SEC companyfacts." },
    freeCashFlow: { value: (2134.473 - 1357.178) - (33.882 - 20.61), ...secDerivedSeed, notes: "Derived as quarterly operating cash flow less quarterly capital expenditures from SEC companyfacts." },
    sbcExpense: { value: 684.033 - 487.628, ...secDerivedSeed, notes: "Derived as FY 2025 SBC less Q3 2025 YTD SBC from SEC companyfacts." },
    sbcAsPctRevenue: { value: (684.033 - 487.628) / (798 / 0.57), ...secDerivedSeed, notes: "Derived from SBC expense and revenue proxy." },
  }),
  q("q1-2026", "Q1 2026", 2026, 1, "2026-03-31", {
    revenue: { value: 1632.583, ...companyPresentationSeed, notes: "Total revenue from Q1 2026 business update." },
    yoyRevenueGrowth: { value: 0.85, ...companyPresentationSeed, notes: "Q1 2026 total revenue growth." },
    qoqRevenueGrowth: { value: 0.16, ...companyPresentationSeed, notes: "Q1 2026 total revenue sequential growth." },
    usCommercialRevenue: { value: 595, ...companyPresentationSeed, notes: "US commercial revenue comparison chart." },
    usCommercialGrowth: { value: 1.33, ...companyPresentationSeed, notes: "US commercial revenue growth comparison chart." },
    commercialRevenue: { value: 774, ...companyPresentationSeed, notes: "Commercial revenue comparison chart." },
    governmentRevenue: { value: 858, ...companyPresentationSeed, notes: "Government revenue comparison chart." },
    usGovernmentRevenue: { value: 687, ...companyPresentationSeed, notes: "US government revenue comparison chart." },
    internationalCommercialRevenue: { value: 179, sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived as commercial revenue less US commercial revenue." },
    internationalGovernmentRevenue: { value: 171, sourceUrl: Q1_2026_BUSINESS_UPDATE, sourceType: "derived", sourceConfidence: "medium", notes: "Derived as government revenue less US government revenue." },
    customerCount: { value: 1007, ...companyPresentationSeed, notes: "TTM customer count ending March 31, 2026." },
    commercialCustomerCount: { value: 832, ...companyPresentationSeed, notes: "TTM commercial customer count ending March 31, 2026." },
    usCommercialCustomerCount: { value: 615, ...companyPresentationSeed, notes: "TTM US commercial customer count ending March 31, 2026." },
    rpo: { value: 4450, ...companyPresentationSeed, notes: "Total RPO chart value in USD millions." },
    billings: { value: 1750, ...companyPresentationSeed, notes: "Billings chart value in USD millions; verify label ordering from source PDF." },
    adjustedOperatingIncome: { value: 984, ...companyPresentationSeed, notes: "Rounded adjusted operating income chart value." },
    gaapOperatingIncome: { value: 753.998, ...secSeed, notes: "SEC filing seed value from Q1 2026 10-Q." },
    adjustedOperatingMargin: { value: 0.6, ...companyPresentationSeed, notes: "Adjusted operating margin from Rule of 40 reconciliation." },
    gaapOperatingMargin: { value: 753.998 / 1632.583, sourceUrl: SEC_COMPANYFACTS, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from GAAP operating income and revenue." },
    adjustedFreeCashFlow: { value: 899.165, ...companyPresentationSeed, notes: "Adjusted free cash flow from Q1 2026 business update reconciliation." },
    fcfMargin: { value: 0.55, ...companyPresentationSeed, notes: "Adjusted free cash flow margin from business update chart." },
    ruleOf40: { value: 1.45, ...companyPresentationSeed, notes: "Rule of 40 reconciliation." },
    sbcExpense: { value: 201.592, ...secSeed, notes: "Total stock-based compensation expense from Q1 2026 10-Q seed." },
    sbcAsPctRevenue: { value: 201.592 / 1632.583, sourceUrl: SEC_COMPANYFACTS, sourceType: "derived", sourceConfidence: "medium", notes: "Derived from SBC expense and revenue." },
    dilutedShareCount: { value: 2570.924, ...secSeed, notes: "Weighted average diluted shares from SEC companyfacts." },
    freeCashFlow: { value: 899.165 - 7.401, ...secDerivedSeed, notes: "Derived from operating cash flow less capital expenditures in SEC companyfacts." },
    cashAndEquivalents: { value: 8000, ...companyPresentationSeed, notes: "Cash, cash equivalents, and US Treasury securities; rounded to nearest $0.1B in source." },
    debt: { value: 0, ...companyPresentationSeed, notes: "Business update states no debt." },
    netCash: { value: 8000, ...companyPresentationSeed, notes: "Derived from rounded cash and no debt disclosure." },
    guidanceRevenue: { value: 7656, ...companyPresentationSeed, notes: "Midpoint of FY 2026 revenue guidance range of $7.650B to $7.662B." },
    guidanceOperatingIncome: { value: 4446, ...companyPresentationSeed, notes: "Midpoint of FY 2026 adjusted operating income guidance range of $4.440B to $4.452B." },
    guidanceFcf: { value: 4300, ...companyPresentationSeed, notes: "Midpoint of FY 2026 adjusted FCF guidance range of $4.2B to $4.4B." },
    netDollarRetention: { value: 1.5, ...companyPresentationSeed, notes: "Net dollar retention disclosed for Q1 2026." },
    largeDeals1m: { value: 206, ...companyPresentationSeed, notes: "Q1 2026 deals of at least $1 million." },
    largeDeals5m: { value: 72, ...companyPresentationSeed, notes: "Q1 2026 deals of at least $5 million." },
    largeDeals10m: { value: 47, ...companyPresentationSeed, notes: "Q1 2026 deals of at least $10 million." },
  }),
];

export const pltrGuidance: PltrGuidancePoint[] = [
  {
    id: "fy2026-revenue-guidance",
    fiscalYear: 2026,
    period: "FY 2026",
    metric: "Revenue",
    low: 7650,
    high: 7662,
    midpoint: 7656,
    unit: "USDm",
    sourceUrl: Q1_2026_BUSINESS_UPDATE,
    sourceType: "company_presentation",
    sourceConfidence: "high",
    notes: "Q1 2026 business update FY guidance.",
  },
  {
    id: "fy2026-adjusted-operating-income-guidance",
    fiscalYear: 2026,
    period: "FY 2026",
    metric: "Adjusted operating income",
    low: 4440,
    high: 4452,
    midpoint: 4446,
    unit: "USDm",
    sourceUrl: Q1_2026_BUSINESS_UPDATE,
    sourceType: "company_presentation",
    sourceConfidence: "high",
    notes: "Q1 2026 business update FY guidance.",
  },
  {
    id: "fy2026-adjusted-fcf-guidance",
    fiscalYear: 2026,
    period: "FY 2026",
    metric: "Adjusted free cash flow",
    low: 4200,
    high: 4400,
    midpoint: 4300,
    unit: "USDm",
    sourceUrl: Q1_2026_BUSINESS_UPDATE,
    sourceType: "company_presentation",
    sourceConfidence: "high",
    notes: "Q1 2026 business update FY guidance.",
  },
  {
    id: "fy2026-us-commercial-revenue-guidance",
    fiscalYear: 2026,
    period: "FY 2026",
    metric: "US commercial revenue",
    low: 3224,
    high: null,
    midpoint: null,
    unit: "USDm",
    sourceUrl: Q1_2026_BUSINESS_UPDATE,
    sourceType: "company_presentation",
    sourceConfidence: "high",
    notes: "Guidance is disclosed as in excess of $3.224B and at least 120% growth.",
  },
];

export const pltrResearchSignals: PltrResearchSignal[] = [
  {
    id: "aip-us-commercial-acceleration",
    label: "AIP-linked US commercial acceleration",
    category: "AIP",
    score: 88,
    direction: "positive",
    evidence: "Q1 2026 US commercial revenue grew 133% year over year and US commercial customer count grew 42% year over year.",
    sourceUrl: Q1_2026_BUSINESS_UPDATE,
    sourceType: "company_presentation",
    valuationImpactAllowed: false,
    notes: "Research-only signal. It does not mechanically change revenue CAGR until mapped through forecast assumptions.",
  },
  {
    id: "ontology-operating-layer",
    label: "Ontology as operating layer",
    category: "Ontology",
    score: 82,
    direction: "positive",
    evidence: "Official platform documentation frames the Ontology as the layer connecting data, logic, actions, security, and operational workflows.",
    sourceUrl: "https://www.palantir.com/docs/foundry/ontology/overview",
    sourceType: "official_ir",
    valuationImpactAllowed: false,
    notes: "Research-only moat score. Must be mapped to retention, pricing, margin, or growth before valuation use.",
  },
  {
    id: "sbc-still-material",
    label: "SBC remains material",
    category: "SBC",
    score: 58,
    direction: "mixed",
    evidence: "Q1 2026 SBC expense remains a double-digit percentage of revenue despite strong GAAP profitability.",
    sourceUrl: SEC_COMPANYFACTS,
    sourceType: "sec_filing",
    valuationImpactAllowed: false,
    notes: "A valuation model should check per-share FCF and dilution, not only company-level FCF.",
  },
  {
    id: "valuation-debate",
    label: "Valuation is the largest debate",
    category: "Valuation",
    score: 40,
    direction: "negative",
    evidence: "The dashboard uses reverse DCF because the investment question is often what assumptions are already priced in.",
    sourceUrl: null,
    sourceType: "assumption",
    valuationImpactAllowed: false,
    notes: "Research framing, not a factual valuation call.",
  },
];

const dataWarnings: ValidationWarning[] = [
  {
    id: "pltr-starter-dataset-not-institutional-grade",
    title: "Starter dataset requires source refresh",
    detail: "Several quarterly values are seeded from official presentation charts or derived from rounded values. Run the PLTR scripts and review official filings before using the model as an institutional-grade source.",
    severity: "medium",
  },
  {
    id: "pltr-transcripts-not-yet-parsed",
    title: "Transcript text is not yet parsed",
    detail: "Transcript records are manifest-only until scripts/pltr_fetch_transcripts.mjs and scripts/pltr_build_qa_pairs.mjs populate local raw and extracted files.",
    severity: "medium",
  },
  {
    id: "pltr-market-price-unofficial",
    title: "Market price is an unofficial yfinance snapshot",
    detail: "Use the yfinance snapshot for market cross-check only and refresh before relying on upside/downside or reverse DCF output.",
    severity: "medium",
  },
];

export const pltrData: PltrDataset = {
  actuals: pltrActuals,
  guidance: pltrGuidance,
  researchSignals: pltrResearchSignals,
  transcriptEvents: pltrTranscriptEvents,
  qaPairs: pltrQaPairs,
  topicTrends: pltrTopicTrends,
  marketData: {
    ticker: "PLTR",
    currentPrice: 134.88499450683594,
    priceDate: "2026-05-11",
    marketCap: null,
    enterpriseValue: null,
    netCash: 8000,
    dilutedShares: 2562,
    sourceUrl: "https://query1.finance.yahoo.com/v8/finance/chart/PLTR?range=5d&interval=1d",
    sourceType: "yfinance",
    sourceConfidence: "medium",
    notes: "Unofficial Yahoo Finance chart endpoint snapshot saved in data/local/pltr/yfinance. Use for market cross-check only.",
  },
  sources: pltrSources,
  dataStatus: {
    lastUpdated: "2026-05-11",
    sourceNote: "Initial PLTR module seed. Official IR and SEC paths are configured, but not every metric has been extracted from filings yet.",
    warnings: dataWarnings,
  },
};
