import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const bacDataset = createLocalDeepResearchDataset({
  ticker: "BAC",
  companyName: "Bank of America Corporation",
  sector: "Large-Cap Bank / Consumer Banking / Wealth / Capital Markets",
  archetype: "Rate-sensitive bank / deposit franchise and securities-book recovery",
  description:
    "BAC research cockpit focused on NII sensitivity, deposit beta, securities-book/AOCI drag, consumer credit normalization, wealth-management durability, capital return, and whether earnings power recovers as rates and balance-sheet mix normalize.",
  updatedAt: "2026-05-20",
  currentPrice: 50.7,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "nii-deposits", label: "NII / Deposits" },
    { value: "aoci-capital", label: "AOCI / Capital" },
    { value: "credit-wealth", label: "Credit / Wealth" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "nii-recovery", label: "NII Recovery Score", value: 0.62, format: "percent", description: "Research score for NII trough/recovery and deposit cost stabilization.", badge: "Assumption" },
    { key: "aoci-release", label: "AOCI Recovery Optionality", value: 0.16, format: "percent", description: "Potential capital/earnings support from securities-book normalization.", badge: "Placeholder" },
    { key: "credit-risk", label: "Credit Risk Haircut", value: 0.2, format: "percent", description: "Consumer and CRE credit normalization risk.", badge: "Assumption" },
    { key: "capital-return", label: "Capital Return Capacity", value: 0.045, format: "percent", description: "Dividend plus buyback framework; CCAR import pending.", badge: "Placeholder" },
    { key: "base-gap", label: "Base Upside / Downside", value: 0.03, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "nii-recovery",
      question: "Is BAC near an NII trough, or does deposit repricing keep pressure on earnings?",
      currentView: "BAC is more rate-sensitive than JPM; the stock needs NII stabilization to re-rate.",
      metric: "NII, deposit costs, asset yield, loan growth",
      evidenceNeeded: "NII guide bridge and deposit beta by segment",
      valuationTie: "Revenue CAGR and risk haircut",
      bearCase: "Deposit competition offsets securities reinvestment and rate benefits.",
    },
    {
      key: "aoci-book",
      question: "How much value comes from AOCI recovery and securities-book normalization?",
      currentView: "AOCI recovery is real but timing-dependent and should not be double counted with NII recovery.",
      metric: "AOCI, tangible book, securities yield",
      evidenceNeeded: "Maturity schedule and OCI sensitivity",
      valuationTie: "Quality adjustment and capital-return capacity",
      bearCase: "Higher-for-longer rates delay book-value recovery.",
    },
    {
      key: "credit",
      question: "Is consumer credit normalization benign?",
      currentView: "Consumer losses matter more for BAC than many peers because the bull case needs capital return.",
      metric: "Card losses, delinquencies, reserve build",
      evidenceNeeded: "Portfolio-level charge-off and delinquency trends",
      valuationTie: "Risk haircut and normalized FCF/earnings power",
      bearCase: "Credit losses rise just as NII is still fading.",
    },
    {
      key: "wealth",
      question: "Can wealth and advisory stabilize lower spread income?",
      currentView: "Merrill and private bank economics help, but fee revenue cannot fully offset a bad NII path.",
      metric: "AUM flows, advisory fees, markets/IB fees",
      evidenceNeeded: "Fee growth and operating leverage",
      valuationTie: "Exit multiple and quality adjustment",
      bearCase: "Fee income slows with markets while expenses remain sticky.",
    },
  ],
  kpiSeries: [
    {
      key: "nii-deposits",
      title: "NII Recovery vs Deposit Beta",
      subtitle: "BAC needs deposit repricing to stop overwhelming asset-yield and securities reinvestment benefits.",
      sourceStatus: "research_only",
      measures: [
        { key: "niiIndex", label: "NII index", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "depositBeta", label: "Deposit beta %", format: "percent", chartType: "line", color: "#dc2626", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", niiIndex: 100, depositBeta: 0.43 },
        { period: "2024 Q2", niiIndex: 98, depositBeta: 0.45 },
        { period: "2024 Q3", niiIndex: 97, depositBeta: 0.46 },
        { period: "2024 Q4", niiIndex: 97, depositBeta: 0.46 },
        { period: "2025 Q1", niiIndex: 98, depositBeta: 0.45 },
        { period: "2025 Q2", niiIndex: 99, depositBeta: 0.44 },
        { period: "2025 Q3", niiIndex: 101, depositBeta: 0.43 },
        { period: "2025 Q4", niiIndex: 103, depositBeta: 0.42 },
        { period: "2026 Q1", niiIndex: 105, depositBeta: 0.41 },
      ],
    },
    {
      key: "aoci-capital",
      title: "AOCI Drag vs Capital Return",
      subtitle: "AOCI recovery can help book value and capital flexibility, but timing should be scenario-weighted.",
      sourceStatus: "research_only",
      measures: [
        { key: "aociDragIndex", label: "AOCI drag index", format: "number", chartType: "bar", color: "#7c2d12", axis: "left" },
        { key: "capitalReturn", label: "Capital return yield %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", aociDragIndex: 100, capitalReturn: 0.034 },
        { period: "2024 Q2", aociDragIndex: 96, capitalReturn: 0.036 },
        { period: "2024 Q3", aociDragIndex: 92, capitalReturn: 0.038 },
        { period: "2024 Q4", aociDragIndex: 88, capitalReturn: 0.04 },
        { period: "2025 Q1", aociDragIndex: 83, capitalReturn: 0.041 },
        { period: "2025 Q2", aociDragIndex: 78, capitalReturn: 0.043 },
        { period: "2025 Q3", aociDragIndex: 72, capitalReturn: 0.045 },
        { period: "2025 Q4", aociDragIndex: 66, capitalReturn: 0.046 },
        { period: "2026 Q1", aociDragIndex: 60, capitalReturn: 0.047 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "nii-deposits",
      tab: "nii-deposits",
      title: "NII Recovery Path",
      thesis: "BAC's re-rating requires evidence that deposit beta and balance-sheet drag are peaking.",
      evidence: ["NII guide", "Deposit cost stabilization", "Loan growth", "Securities reinvestment yield"],
      watchItems: ["Deposit outflows", "Lower-for-longer loan demand", "Expense growth"],
      sourceStatus: "research_only",
    },
    {
      key: "aoci-capital",
      tab: "aoci-capital",
      title: "AOCI / Tangible Book Recovery",
      thesis: "AOCI recovery can support tangible book and buybacks, but it is a timing variable, not a permanent earnings uplift.",
      evidence: ["HTM/AFS maturity schedule", "AOCI sensitivity", "CET1 and SCB"],
      watchItems: ["Rate volatility", "Regulatory capital rule changes", "Buyback pauses"],
      sourceStatus: "research_only",
    },
    {
      key: "credit-wealth",
      tab: "credit-wealth",
      title: "Credit and Wealth Fee Stability",
      thesis: "Wealth fees improve quality, but consumer credit determines whether BAC can return capital through the cycle.",
      evidence: ["AUM flows", "Advisory fees", "Card charge-offs", "Reserve build"],
      watchItems: ["Consumer stress", "Market-sensitive fee pressure", "CRE marks"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-15", headline: "NII trough and AOCI recovery", keyQuestions: ["Is NII guide improving?", "Is AOCI drag declining?", "Are consumer losses contained?"], managementTone: "Recovery-oriented.", modelReadThrough: "Allow modest upside if NII and capital both improve.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-01-16", headline: "Capital return after balance-sheet normalization", keyQuestions: ["What is excess CET1?", "Is buyback capacity rising?", "Any reserve pressure?"], managementTone: "Constructive.", modelReadThrough: "Lift buyback yield only after CCAR proof.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-15", headline: "Deposit beta improvement", keyQuestions: ["Are deposit costs stabilizing?", "How much NII recovery is visible?", "Does credit worsen?"], managementTone: "Cautiously optimistic.", modelReadThrough: "Reduce risk haircut slightly.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-16", headline: "Consumer credit check", keyQuestions: ["Card losses?", "Reserve build?", "Wealth fee trends?"], managementTone: "Balanced.", modelReadThrough: "Credit can offset NII optimism.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-15", headline: "NII still under pressure", keyQuestions: ["Is NII trough later?", "Are deposits migrating?", "How much AOCI release?"], managementTone: "Careful.", modelReadThrough: "Keep valuation discount to JPM.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-01-16", headline: "Rate sensitivity resets", keyQuestions: ["What is NII guide?", "Any securities-book repositioning?", "Capital target?"], managementTone: "Stabilizing.", modelReadThrough: "Begin recovery case, still source-gap heavy.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-15", headline: "AOCI and deposits", keyQuestions: ["Is AOCI drag easing?", "Deposit mix?", "NCO trend?"], managementTone: "Measured.", modelReadThrough: "No large fair value move.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-16", headline: "NII pressure versus valuation support", keyQuestions: ["Deposit beta?", "NII guide?", "Expense discipline?"], managementTone: "Cautious.", modelReadThrough: "Lower growth assumptions until guide improves.", riskSignal: "Needs Review", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-16", fiscalPeriod: "FY2024 Q2", asOfPrice: 44, fairValue: 42, method: "NII pressure and deposit beta local fallback." },
    { eventDate: "2024-10-15", fiscalPeriod: "FY2024 Q3", asOfPrice: 42, fairValue: 43, method: "AOCI and deposits valuation check." },
    { eventDate: "2025-01-16", fiscalPeriod: "FY2024 Q4", asOfPrice: 47, fairValue: 45, method: "Rate sensitivity reset." },
    { eventDate: "2025-04-15", fiscalPeriod: "FY2025 Q1", asOfPrice: 39, fairValue: 43, method: "NII pressure with recovery option." },
    { eventDate: "2025-07-16", fiscalPeriod: "FY2025 Q2", asOfPrice: 45, fairValue: 46, method: "Consumer credit and wealth fee check." },
    { eventDate: "2025-10-15", fiscalPeriod: "FY2025 Q3", asOfPrice: 48, fairValue: 49, method: "Deposit beta improvement." },
    { eventDate: "2026-01-16", fiscalPeriod: "FY2025 Q4", asOfPrice: 50, fairValue: 51, method: "Capital return and balance-sheet normalization." },
    { eventDate: "2026-04-15", fiscalPeriod: "FY2026 Q1", asOfPrice: 51, fairValue: 52, method: "Base earnings power / AOCI recovery local run." },
  ],
  valuationBase: {
    revenueBase: 102000,
    revenueCagr3Y: 0.035,
    terminalGrowth: 0.02,
    normalizedFcfMargin: 0.15,
    exitFcfMultiple: 9,
    evRevenueMultiple: 3.8,
    discountRate: 0.1,
    netCashDebt: 0,
    dilutedShares: 7417,
    qualityAdjustment: 1.03,
    riskHaircut: 0.14,
    dividendYield: 0.02,
    buybackYield: 0.025,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: -0.015, normalizedFcfMargin: 0.11, exitFcfMultiple: 7, evRevenueMultiple: 2.8, riskHaircut: 0.26, qualityAdjustment: 0.93, buybackYield: 0.01 },
    Base: {},
    Bull: { revenueCagr3Y: 0.055, normalizedFcfMargin: 0.18, exitFcfMultiple: 11, evRevenueMultiple: 4.5, riskHaircut: 0.08, qualityAdjustment: 1.1, buybackYield: 0.035 },
  },
  valuationDescription: "Maps BAC earnings recovery, NII stabilization and capital return into the platform DCF / capitalization framework until a bank-specific BVPS/ROE model is added.",
  risks: [
    { title: "NII recovery delayed", detail: "Deposit pricing and weak loan demand can delay the expected earnings recovery.", severity: "high", killSignal: "NII guide falls for two quarters while deposit beta rises." },
    { title: "AOCI timing", detail: "Higher-for-longer rates can keep book-value recovery out of the investable horizon.", severity: "medium", killSignal: "AOCI drag remains sticky and capital return stalls." },
    { title: "Consumer credit", detail: "Credit normalization can absorb operating leverage and capital return.", severity: "high", killSignal: "Charge-offs rise while reserve coverage falls." },
  ],
  monitoring: ["NII guide", "Deposit beta", "AOCI/tangible book", "CET1 and buybacks", "Card charge-offs", "Wealth AUM flows"],
  sourceGaps: ["Bank-specific BVPS/ROTCE backend model is not implemented yet.", "Official deposit, NII, AOCI and credit data should be imported from earnings supplements."],
});
