import type { ValuationAssumption } from "../types";
import type { AznScenarioDefinition, AznValuationAssumptions } from "./types";
import { aznMarketData } from "./data/marketData";

export const defaultAznValuationAssumptions: AznValuationAssumptions = {
  currentPriceGbp: aznMarketData.londonPriceGbp,
  gbpUsd: aznMarketData.gbpUsd,
  revenueCagr: 0.07,
  terminalGrowth: 0.025,
  operatingMargin: 0.34,
  taxRate: 0.2,
  reinvestmentRate: 0.16,
  wacc: 0.082,
  terminalRoic: 0.15,
  fcfConversion: 0.72,
  targetPipelineMargin: 0.36,
  pipelineDiscountRate: 0.1,
  oncologyRevenueMultiple: 6.3,
  cvrmRevenueMultiple: 4.6,
  respiratoryRevenueMultiple: 4.2,
  rareDiseaseRevenueMultiple: 6.0,
  infectiousDiseaseRevenueMultiple: 3.0,
  otherRevenueMultiple: 1.3,
  pipelineMultiple: 1.0,
  netDebtUsdM: aznMarketData.enterpriseValueUsdM - aznMarketData.marketCapUsdM,
  peerPeMultiple: 20,
  dividendPerShareUsd: aznMarketData.dividendPerShareUsd,
  weightDcf: 0.35,
  weightSotp: 0.3,
  weightPipeline: 0.2,
  weightMultiples: 0.15,
};

export const aznScenarioPresets: Record<"Bear" | "Base" | "Bull", AznValuationAssumptions> = {
  Bear: {
    ...defaultAznValuationAssumptions,
    revenueCagr: 0.04,
    operatingMargin: 0.31,
    terminalGrowth: 0.018,
    wacc: 0.092,
    fcfConversion: 0.62,
    targetPipelineMargin: 0.32,
    pipelineDiscountRate: 0.12,
    oncologyRevenueMultiple: 5.2,
    cvrmRevenueMultiple: 3.5,
    respiratoryRevenueMultiple: 3.4,
    rareDiseaseRevenueMultiple: 5.0,
    infectiousDiseaseRevenueMultiple: 2.0,
    otherRevenueMultiple: 0.8,
    peerPeMultiple: 16,
  },
  Base: defaultAznValuationAssumptions,
  Bull: {
    ...defaultAznValuationAssumptions,
    revenueCagr: 0.09,
    operatingMargin: 0.36,
    terminalGrowth: 0.03,
    wacc: 0.076,
    fcfConversion: 0.78,
    targetPipelineMargin: 0.38,
    pipelineDiscountRate: 0.09,
    oncologyRevenueMultiple: 7.1,
    cvrmRevenueMultiple: 5.2,
    respiratoryRevenueMultiple: 4.8,
    rareDiseaseRevenueMultiple: 6.8,
    infectiousDiseaseRevenueMultiple: 3.5,
    otherRevenueMultiple: 1.5,
    peerPeMultiple: 23,
  },
};

export const aznScenarioDefinitions: AznScenarioDefinition[] = (["Bear", "Base", "Bull"] as const).map((name) => ({
  name,
  assumptions: aznScenarioPresets[name],
}));

export const aznValuationAssumptionKeys = [
  "currentPriceGbp",
  "gbpUsd",
  "revenueCagr",
  "terminalGrowth",
  "operatingMargin",
  "taxRate",
  "reinvestmentRate",
  "wacc",
  "fcfConversion",
  "targetPipelineMargin",
  "pipelineDiscountRate",
  "oncologyRevenueMultiple",
  "cvrmRevenueMultiple",
  "respiratoryRevenueMultiple",
  "rareDiseaseRevenueMultiple",
  "peerPeMultiple",
  "weightDcf",
  "weightSotp",
  "weightPipeline",
  "weightMultiples",
] as const;

export const aznAssumptionDefinitions: ValuationAssumption[] = [
  { key: "currentPriceGbp", label: "London Price", value: defaultAznValuationAssumptions.currentPriceGbp, min: 80, max: 190, step: 0.1, format: "currency", source: "actual", description: "AZN London ordinary share price in GBP. The London quote is fetched in GBX and divided by 100.", category: "Market", unit: "GBP", periodicity: "annual", asOfDate: aznMarketData.priceDate, provenance: "market_data: Stooq AZN.UK close, normalized from GBX to GBP." },
  { key: "gbpUsd", label: "GBP / USD", value: defaultAznValuationAssumptions.gbpUsd, min: 1.15, max: 1.5, step: 0.001, format: "number", source: "actual", description: "FX rate used to convert USD model outputs to GBP share value.", category: "Market", unit: "number", periodicity: "annual", asOfDate: aznMarketData.priceDate, provenance: "market_data: Stooq GBPUSD close." },
  { key: "revenueCagr", label: "Revenue CAGR", value: defaultAznValuationAssumptions.revenueCagr, min: 0.02, max: 0.11, step: 0.0025, format: "percent", source: "assumption", description: "Five-year modeled revenue CAGR. Anchored to management's FY 2026 CER guidance and 2030 ambition, not treated as reported data.", category: "Growth", unit: "percent", periodicity: "annual", provenance: "research_only: scenario assumption." },
  { key: "terminalGrowth", label: "Terminal Growth", value: defaultAznValuationAssumptions.terminalGrowth, min: 0.01, max: 0.04, step: 0.001, format: "percent", source: "assumption", description: "Long-run nominal terminal growth for mature pharma cash flows.", category: "DCF", unit: "percent", periodicity: "annual", provenance: "research_only: scenario assumption." },
  { key: "operatingMargin", label: "Core Operating Margin", value: defaultAznValuationAssumptions.operatingMargin, min: 0.28, max: 0.39, step: 0.0025, format: "percent", source: "assumption", description: "Modeled steady-state core operating margin; current Q1 2026 core operating margin was 35%.", category: "Margin", unit: "percent", periodicity: "annual", provenance: "official + research_only: Q1 2026 core margin anchor with scenario adjustment." },
  { key: "taxRate", label: "Tax Rate", value: defaultAznValuationAssumptions.taxRate, min: 0.18, max: 0.24, step: 0.001, format: "percent", source: "assumption", description: "Core tax rate; management expects 18-22% for FY 2026.", category: "Cash Flow", unit: "percent", periodicity: "annual", provenance: "official: FY 2026 core tax guidance." },
  { key: "reinvestmentRate", label: "Reinvestment Rate", value: defaultAznValuationAssumptions.reinvestmentRate, min: 0.1, max: 0.24, step: 0.005, format: "percent", source: "assumption", description: "Incremental reinvestment drag for manufacturing, launch, working-capital and technology spend.", category: "Cash Flow", unit: "percent", periodicity: "annual", provenance: "research_only: scenario assumption." },
  { key: "wacc", label: "WACC", value: defaultAznValuationAssumptions.wacc, min: 0.065, max: 0.1, step: 0.001, format: "percent", source: "assumption", description: "Discount rate used in DCF and pipeline rNPV. This is an analyst scenario input.", category: "DCF", unit: "percent", periodicity: "annual", provenance: "research_only: scenario WACC." },
  { key: "fcfConversion", label: "FCF Conversion", value: defaultAznValuationAssumptions.fcfConversion, min: 0.55, max: 0.85, step: 0.005, format: "percent", source: "assumption", description: "Core operating profit to free-cash-flow conversion after tax, capex and working capital.", category: "Cash Flow", unit: "percent", periodicity: "annual", provenance: "official cash-flow anchor + research_only normalized conversion." },
  { key: "targetPipelineMargin", label: "Pipeline Margin", value: defaultAznValuationAssumptions.targetPipelineMargin, min: 0.25, max: 0.45, step: 0.005, format: "percent", source: "assumption", description: "After-tax contribution margin used to convert peak sales into pipeline rNPV.", category: "Pipeline", unit: "percent", periodicity: "annual", provenance: "research_only: pipeline rNPV scenario." },
  { key: "pipelineDiscountRate", label: "Pipeline Discount Rate", value: defaultAznValuationAssumptions.pipelineDiscountRate, min: 0.08, max: 0.14, step: 0.001, format: "percent", source: "assumption", description: "Discount rate used specifically for pipeline optionality.", category: "Pipeline", unit: "percent", periodicity: "annual", provenance: "research_only: pipeline rNPV scenario." },
  { key: "oncologyRevenueMultiple", label: "Oncology Revenue Multiple", value: defaultAznValuationAssumptions.oncologyRevenueMultiple, min: 4, max: 8, step: 0.1, format: "multiple", source: "assumption", description: "SOTP revenue multiple for Oncology, before risk haircuts.", category: "SOTP", unit: "multiple", periodicity: "annual", provenance: "research_only: pharma SOTP multiple." },
  { key: "cvrmRevenueMultiple", label: "CVRM Revenue Multiple", value: defaultAznValuationAssumptions.cvrmRevenueMultiple, min: 2.5, max: 6, step: 0.1, format: "multiple", source: "assumption", description: "SOTP revenue multiple for CVRM, haircut for Farxiga LOE.", category: "SOTP", unit: "multiple", periodicity: "annual", provenance: "research_only: pharma SOTP multiple." },
  { key: "respiratoryRevenueMultiple", label: "R&I Revenue Multiple", value: defaultAznValuationAssumptions.respiratoryRevenueMultiple, min: 2.5, max: 6, step: 0.1, format: "multiple", source: "assumption", description: "SOTP revenue multiple for Respiratory & Immunology.", category: "SOTP", unit: "multiple", periodicity: "annual", provenance: "research_only: pharma SOTP multiple." },
  { key: "rareDiseaseRevenueMultiple", label: "Rare Disease Multiple", value: defaultAznValuationAssumptions.rareDiseaseRevenueMultiple, min: 4, max: 8, step: 0.1, format: "multiple", source: "assumption", description: "SOTP revenue multiple for Rare Disease, reflecting orphan durability and pricing risk.", category: "SOTP", unit: "multiple", periodicity: "annual", provenance: "research_only: pharma SOTP multiple." },
  { key: "peerPeMultiple", label: "Peer P/E", value: defaultAznValuationAssumptions.peerPeMultiple, min: 12, max: 28, step: 0.25, format: "multiple", source: "assumption", description: "Quality-adjusted peer P/E cross-check. Peer set contains research-only ratio estimates, not a live market feed.", category: "Multiples", unit: "multiple", periodicity: "forward annual", provenance: "research_only: peer multiple cross-check." },
  { key: "weightDcf", label: "DCF Weight", value: defaultAznValuationAssumptions.weightDcf, min: 0.15, max: 0.5, step: 0.01, format: "percent", source: "assumption", description: "Blend weight for DCF.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightSotp", label: "SOTP Weight", value: defaultAznValuationAssumptions.weightSotp, min: 0.1, max: 0.45, step: 0.01, format: "percent", source: "assumption", description: "Blend weight for operating SOTP.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightPipeline", label: "Pipeline Weight", value: defaultAznValuationAssumptions.weightPipeline, min: 0.05, max: 0.35, step: 0.01, format: "percent", source: "assumption", description: "Blend weight for pipeline rNPV optionality.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightMultiples", label: "Multiples Weight", value: defaultAznValuationAssumptions.weightMultiples, min: 0.05, max: 0.3, step: 0.01, format: "percent", source: "assumption", description: "Blend weight for peer-multiple cross-check.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
];
