import type { ValuationAssumption } from "../types";
import type { DgeScenarioDefinition, DgeValuationAssumptions } from "./types";
import { dgeMarketData } from "./data/marketData";

export const defaultDgeValuationAssumptions: DgeValuationAssumptions = {
  currentPriceGbp: dgeMarketData.londonPriceGbp,
  gbpUsd: dgeMarketData.gbpUsd,
  sharesOutstandingM: dgeMarketData.sharesOutstandingM,
  netDebtUsdM: dgeMarketData.netDebtUsdM,
  normalizedFcf: 2_850,
  targetFcfYield: 0.08,
  normalizedEbit: 5_650,
  normalizedEbitda: 6_450,
  evEbitMultiple: 11.5,
  evEbitdaMultiple: 9.4,
  epsBeforeExceptional: 1.64,
  peMultiple: 14.5,
  dividendFloorUsd: 0.5,
  terminalOrganicGrowth: 0.025,
  operatingMargin: 0.285,
  usOrganicGrowth: -0.02,
  lacNormalizedGrowth: 0.045,
  regionQualityAdjustment: -0.05,
  weightFcfYield: 0.32,
  weightEvEbit: 0.2,
  weightEvEbitda: 0.18,
  weightPe: 0.12,
  weightDividend: 0.08,
  weightRegionQuality: 0.1,
};

export const dgeScenarioPresets: Record<"Bear" | "Base" | "Bull", DgeValuationAssumptions> = {
  Bear: {
    ...defaultDgeValuationAssumptions,
    normalizedFcf: 2_350,
    targetFcfYield: 0.095,
    normalizedEbit: 5_100,
    normalizedEbitda: 6_000,
    evEbitMultiple: 9.5,
    evEbitdaMultiple: 8.0,
    epsBeforeExceptional: 1.38,
    peMultiple: 11.5,
    terminalOrganicGrowth: 0.01,
    operatingMargin: 0.26,
    usOrganicGrowth: -0.08,
    lacNormalizedGrowth: 0.0,
    regionQualityAdjustment: -0.14,
  },
  Base: defaultDgeValuationAssumptions,
  Bull: {
    ...defaultDgeValuationAssumptions,
    normalizedFcf: 3_250,
    targetFcfYield: 0.068,
    normalizedEbit: 6_050,
    normalizedEbitda: 6_950,
    evEbitMultiple: 13.0,
    evEbitdaMultiple: 10.8,
    epsBeforeExceptional: 1.82,
    peMultiple: 17.5,
    terminalOrganicGrowth: 0.035,
    operatingMargin: 0.305,
    usOrganicGrowth: 0.025,
    lacNormalizedGrowth: 0.075,
    regionQualityAdjustment: 0.03,
  },
};

export const dgeScenarioDefinitions: DgeScenarioDefinition[] = (["Bear", "Base", "Bull"] as const).map((name) => ({
  name,
  assumptions: dgeScenarioPresets[name],
}));

export const dgeValuationAssumptionKeys = [
  "currentPriceGbp",
  "gbpUsd",
  "normalizedFcf",
  "targetFcfYield",
  "normalizedEbit",
  "normalizedEbitda",
  "evEbitMultiple",
  "evEbitdaMultiple",
  "epsBeforeExceptional",
  "peMultiple",
  "dividendFloorUsd",
  "terminalOrganicGrowth",
  "operatingMargin",
  "usOrganicGrowth",
  "lacNormalizedGrowth",
  "regionQualityAdjustment",
  "weightFcfYield",
  "weightEvEbit",
  "weightEvEbitda",
  "weightPe",
  "weightDividend",
  "weightRegionQuality",
] as const;

export const dgeAssumptionDefinitions: ValuationAssumption[] = [
  { key: "currentPriceGbp", label: "DGE.L Price", value: defaultDgeValuationAssumptions.currentPriceGbp, min: 8, max: 35, step: 0.05, format: "currency", source: "actual", description: "DGE.L London ordinary share price in GBP. Stooq quote is GBX and is divided by 100.", category: "Market", unit: "GBP", periodicity: "annual", asOfDate: dgeMarketData.priceDate, provenance: "market_data: Stooq DGE.UK close normalized from GBX to GBP." },
  { key: "gbpUsd", label: "GBP / USD", value: defaultDgeValuationAssumptions.gbpUsd, min: 1.15, max: 1.55, step: 0.001, format: "number", source: "actual", description: "FX rate used to convert USD operating data and valuation outputs to GBP per ordinary share.", category: "Market", unit: "number", periodicity: "annual", asOfDate: dgeMarketData.priceDate, provenance: "market_data: Stooq GBPUSD close." },
  { key: "normalizedFcf", label: "Normalized FCF", value: defaultDgeValuationAssumptions.normalizedFcf, min: 1_800, max: 3_800, step: 25, format: "currency", source: "assumption", description: "Normalized free cash flow after working-capital, inventory and exceptional-cost adjustments; not a reported metric.", category: "Cash Flow", unit: "USD", periodicity: "annual", provenance: "research_only: starts below FY2026 $3bn guidance pending cash bridge proof." },
  { key: "targetFcfYield", label: "Target FCF Yield", value: defaultDgeValuationAssumptions.targetFcfYield, min: 0.055, max: 0.11, step: 0.0025, format: "percent", source: "assumption", description: "Target normalized FCF yield adjusted dynamically for US demand, LAC inventory quality, leverage and dividend safety.", category: "Valuation", unit: "percent", periodicity: "annual", provenance: "research_only: beverage/staples risk-adjusted valuation input." },
  { key: "normalizedEbit", label: "Normalized EBIT", value: defaultDgeValuationAssumptions.normalizedEbit, min: 4_500, max: 6_600, step: 25, format: "currency", source: "assumption", description: "Normalized EBIT before exceptional distortions, anchored to FY2025 profit before exceptional items.", category: "Multiples", unit: "USD", periodicity: "annual", provenance: "official FY2025 OP before exceptional + research_only normalization." },
  { key: "normalizedEbitda", label: "Normalized EBITDA", value: defaultDgeValuationAssumptions.normalizedEbitda, min: 5_500, max: 7_500, step: 25, format: "currency", source: "assumption", description: "Normalized EBITDA used for leverage and EV/EBITDA cross-check.", category: "Multiples", unit: "USD", periodicity: "annual", provenance: "official leverage anchors + research_only normalization." },
  { key: "evEbitMultiple", label: "EV / EBIT", value: defaultDgeValuationAssumptions.evEbitMultiple, min: 7, max: 16, step: 0.25, format: "multiple", source: "assumption", description: "Normalized EV/EBIT multiple; lower in bear case when US/LAC growth quality is poor.", category: "Multiples", unit: "multiple", periodicity: "forward annual", provenance: "research_only: peer/multiple scenario input." },
  { key: "evEbitdaMultiple", label: "EV / EBITDA", value: defaultDgeValuationAssumptions.evEbitdaMultiple, min: 6.5, max: 13, step: 0.25, format: "multiple", source: "assumption", description: "Normalized EV/EBITDA cross-check for a levered global beverage company.", category: "Multiples", unit: "multiple", periodicity: "forward annual", provenance: "research_only: peer/multiple scenario input." },
  { key: "epsBeforeExceptional", label: "EPS Before Exceptional", value: defaultDgeValuationAssumptions.epsBeforeExceptional, min: 1, max: 2.4, step: 0.01, format: "currency", source: "assumption", description: "EPS before exceptional items, used only as a P/E cross-check.", category: "P/E", unit: "USD", periodicity: "forward annual", provenance: "official FY2025/H1 FY2026 EPS anchors + research_only normalization." },
  { key: "peMultiple", label: "P/E Multiple", value: defaultDgeValuationAssumptions.peMultiple, min: 9, max: 22, step: 0.25, format: "multiple", source: "assumption", description: "P/E cross-check multiple; not the primary valuation method.", category: "P/E", unit: "multiple", periodicity: "forward annual", provenance: "research_only: cross-check." },
  { key: "dividendFloorUsd", label: "Dividend Floor", value: defaultDgeValuationAssumptions.dividendFloorUsd, min: 0.4, max: 0.9, step: 0.01, format: "currency", source: "actual", description: "Rebased annual dividend floor per ordinary share. Old dividend history is not used as a safety anchor.", category: "Dividend", unit: "USD", periodicity: "annual", provenance: "official: FY2026 interim dividend rebasing." },
  { key: "terminalOrganicGrowth", label: "Terminal Organic Growth", value: defaultDgeValuationAssumptions.terminalOrganicGrowth, min: 0, max: 0.05, step: 0.001, format: "percent", source: "assumption", description: "Long-run organic growth implied in the market-expectations panel.", category: "Growth", unit: "percent", periodicity: "annual", provenance: "research_only: scenario input." },
  { key: "operatingMargin", label: "Operating Margin", value: defaultDgeValuationAssumptions.operatingMargin, min: 0.23, max: 0.33, step: 0.0025, format: "percent", source: "assumption", description: "Normalized operating margin after savings, tariff, A&P, mix and volume assumptions.", category: "Margin", unit: "percent", periodicity: "annual", provenance: "official margin anchor + research_only scenario input." },
  { key: "usOrganicGrowth", label: "US Organic Growth", value: defaultDgeValuationAssumptions.usOrganicGrowth, min: -0.1, max: 0.05, step: 0.0025, format: "percent", source: "assumption", description: "Scenario assumption for US organic sales after separating shipments, depletions and consumption.", category: "US Demand", unit: "percent", periodicity: "annual", provenance: "research_only: demand-cycle assumption." },
  { key: "lacNormalizedGrowth", label: "LAC Normalized Growth", value: defaultDgeValuationAssumptions.lacNormalizedGrowth, min: -0.03, max: 0.1, step: 0.0025, format: "percent", source: "assumption", description: "LAC growth after low-base, restocking and World Cup pull-forward adjustments.", category: "LAC Inventory", unit: "percent", periodicity: "annual", provenance: "research_only: inventory-quality adjustment." },
  { key: "regionQualityAdjustment", label: "Region Quality Adjustment", value: defaultDgeValuationAssumptions.regionQualityAdjustment, min: -0.2, max: 0.1, step: 0.005, format: "percent", source: "assumption", description: "Sum-of-region quality valuation adjustment, not a formal SOTP.", category: "Region Quality", unit: "percent", periodicity: "annual", provenance: "research_only: quality haircut/premium." },
  { key: "weightFcfYield", label: "FCF Yield Weight", value: defaultDgeValuationAssumptions.weightFcfYield, min: 0, max: 0.6, step: 0.01, format: "percent", source: "assumption", description: "Valuation blend weight for normalized FCF yield.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightEvEbit", label: "EV/EBIT Weight", value: defaultDgeValuationAssumptions.weightEvEbit, min: 0, max: 0.5, step: 0.01, format: "percent", source: "assumption", description: "Valuation blend weight for EV/EBIT.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightEvEbitda", label: "EV/EBITDA Weight", value: defaultDgeValuationAssumptions.weightEvEbitda, min: 0, max: 0.5, step: 0.01, format: "percent", source: "assumption", description: "Valuation blend weight for EV/EBITDA.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightPe", label: "P/E Weight", value: defaultDgeValuationAssumptions.weightPe, min: 0, max: 0.4, step: 0.01, format: "percent", source: "assumption", description: "Valuation blend weight for P/E cross-check.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightDividend", label: "Dividend Floor Weight", value: defaultDgeValuationAssumptions.weightDividend, min: 0, max: 0.35, step: 0.01, format: "percent", source: "assumption", description: "Valuation blend weight for dividend-yield floor.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
  { key: "weightRegionQuality", label: "Region Quality Weight", value: defaultDgeValuationAssumptions.weightRegionQuality, min: 0, max: 0.35, step: 0.01, format: "percent", source: "assumption", description: "Valuation blend weight for sum-of-region quality adjustment.", category: "Blend", unit: "percent", periodicity: "annual", provenance: "research_only: valuation blend." },
];
