import type { DeepResearchDataset } from "../deepResearch/model";

const marketData = {
  currentPrice: 176.29,
  priceDate: "2026-05-19",
  source: "Market data snapshot captured 2026-05-19; verify against live feed before trading.",
  sourceStatus: "market_data_proxy" as const,
};

const defaultAssumptions = {
  currentPrice: marketData.currentPrice,
  revenueBase: 9500,
  revenueCagr3Y: 0.28,
  terminalGrowth: 0.035,
  normalizedFcfMargin: 0.26,
  exitFcfMultiple: 32,
  evRevenueMultiple: 11,
  discountRate: 0.095,
  netCashDebt: -3500,
  dilutedShares: 865,
  qualityAdjustment: 1.05,
  riskHaircut: 0.12,
  dividendYield: 0.003,
  buybackYield: 0.01,
};

export const mrvlDataset: DeepResearchDataset = {
  ticker: "MRVL",
  companyName: "Marvell Technology, Inc.",
  sector: "AI Infrastructure / Custom Silicon / Connectivity",
  archetype: "AI data-center silicon cycle / custom ASIC and electro-optics",
  currency: "USD",
  description:
    "MRVL cockpit focused on AI custom silicon ramps, electro-optics attach, data-center mix, carrier/enterprise trough recovery, inventory normalization, gross-margin leverage, and customer-concentration risk.",
  updatedAt: "2026-05-19",
  marketData,
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "ai-custom-silicon", label: "AI / Custom Silicon" },
    { value: "optical-connectivity", label: "Optical / Connectivity" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q4", label: "FY2026 Q4" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "ai-revenue-cagr", label: "AI Revenue CAGR", value: 0.42, format: "percent", description: "Research proxy for custom silicon plus data-center connectivity growth.", badge: "Assumption" },
    { key: "datacenter-mix", label: "Data Center Mix", value: 0.73, format: "percent", description: "Data center is the underwriting center of gravity.", badge: "Derived" },
    { key: "non-ai-recovery", label: "Non-AI Recovery Score", value: 58, format: "number", description: "Carrier/enterprise/storage still need proof of cycle recovery.", badge: "Derived" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: defaultAssumptions.normalizedFcfMargin, format: "percent", description: "FCF margin needs AI scale and opex discipline.", badge: "Assumption" },
    { key: "customer-risk", label: "Customer Concentration Risk", value: 0.34, format: "percent", description: "Large AI wins can create lumpy customer exposure.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "custom-asic",
      question: "How durable is the custom silicon ramp beyond the first hyperscaler programs?",
      currentView: "MRVL can look like a structural AI winner if custom silicon bookings broaden, but one or two customers can make revenue lumpy.",
      metric: "AI custom silicon revenue, design wins, customer concentration",
      evidenceNeeded: "Multi-year design-win visibility, tapeout schedule, production ramps, gross margin on ASIC programs",
      valuationTie: "Revenue CAGR and exit FCF multiple",
      bearCase: "Hyperscaler insourcing or program pause resets the AI growth curve.",
    },
    {
      key: "electro-optics",
      question: "Does 800G/1.6T optical attach create a second AI leg?",
      currentView: "Connectivity content per AI cluster can compound with accelerator scale, but pricing pressure and supply chain constraints matter.",
      metric: "Data-center connectivity revenue, PAM/DSP content, optical attach",
      evidenceNeeded: "800G to 1.6T migration commentary and customer adoption",
      valuationTie: "EV/revenue cross-check",
      bearCase: "Optical cycle peaks faster than AI compute demand.",
    },
    {
      key: "legacy-cycle",
      question: "Are carrier, enterprise and storage at a trough or structurally lower?",
      currentView: "A clean non-AI recovery is important because AI alone may not support all operating leverage.",
      metric: "Non-data-center sequential growth and backlog",
      evidenceNeeded: "Inventory burn, book-to-bill, customer order normalization",
      valuationTie: "Risk haircut",
      bearCase: "Legacy segments remain weak and dilute gross margin.",
    },
    {
      key: "gross-margin",
      question: "Can AI mix support gross margin rather than just revenue growth?",
      currentView: "The quality of AI growth depends on custom silicon margin, NRE treatment, and test/packaging cost.",
      metric: "Gross margin, opex intensity, NRE revenue",
      evidenceNeeded: "Gross margin bridge by segment and AI ramp commentary",
      valuationTie: "Normalized FCF margin",
      bearCase: "AI revenue arrives at lower margin than the market assumes.",
    },
  ],
  kpiSeries: [
    {
      key: "ai-custom-silicon",
      title: "AI Data Center Ramp vs Legacy Recovery",
      subtitle: "Separate AI growth from the still-cyclical non-AI base to avoid double counting the recovery.",
      sourceStatus: "research_only",
      measures: [
        { key: "aiRevenue", label: "AI / data center revenue proxy ($m)", format: "currency", chartType: "bar", color: "#2563eb", axis: "left" },
        { key: "legacyGrowth", label: "Legacy sequential growth %", format: "percent", chartType: "line", color: "#f59e0b", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q2", aiRevenue: 459, legacyGrowth: -13 },
        { period: "FY2024 Q3", aiRevenue: 556, legacyGrowth: -10 },
        { period: "FY2024 Q4", aiRevenue: 765, legacyGrowth: -8 },
        { period: "FY2025 Q1", aiRevenue: 816, legacyGrowth: -6 },
        { period: "FY2025 Q2", aiRevenue: 881, legacyGrowth: -3 },
        { period: "FY2025 Q3", aiRevenue: 1104, legacyGrowth: 1 },
        { period: "FY2025 Q4", aiRevenue: 1370, legacyGrowth: 4 },
        { period: "FY2026 Q1", aiRevenue: 1460, legacyGrowth: 3 },
        { period: "FY2026 Q2", aiRevenue: 1605, legacyGrowth: 4 },
        { period: "FY2026 Q3", aiRevenue: 1760, legacyGrowth: 5 },
        { period: "FY2026 Q4", aiRevenue: 1905, legacyGrowth: 5 },
      ],
    },
    {
      key: "optical-connectivity",
      title: "Optical / Connectivity Content",
      subtitle: "AI cluster scale raises networking bandwidth intensity, but cyclicality and pricing need monitoring.",
      sourceStatus: "research_only",
      measures: [
        { key: "connectivityRevenue", label: "Connectivity revenue proxy ($m)", format: "currency", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "grossMargin", label: "Gross margin %", format: "percent", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q2", connectivityRevenue: 375, grossMargin: 58 },
        { period: "FY2024 Q3", connectivityRevenue: 405, grossMargin: 59 },
        { period: "FY2024 Q4", connectivityRevenue: 486, grossMargin: 60 },
        { period: "FY2025 Q1", connectivityRevenue: 515, grossMargin: 60 },
        { period: "FY2025 Q2", connectivityRevenue: 590, grossMargin: 61 },
        { period: "FY2025 Q3", connectivityRevenue: 668, grossMargin: 62 },
        { period: "FY2025 Q4", connectivityRevenue: 760, grossMargin: 62 },
        { period: "FY2026 Q1", connectivityRevenue: 805, grossMargin: 62 },
        { period: "FY2026 Q2", connectivityRevenue: 850, grossMargin: 62 },
        { period: "FY2026 Q3", connectivityRevenue: 915, grossMargin: 63 },
        { period: "FY2026 Q4", connectivityRevenue: 990, grossMargin: 63 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "custom-asic-pipeline",
      tab: "ai-custom-silicon",
      title: "Custom ASIC Pipeline",
      thesis: "MRVL should be modeled as a portfolio of program ramps, not a smooth AI revenue line. Each customer tapeout and production schedule matters.",
      evidence: ["Hyperscaler design wins", "NRE to production conversion", "Gross margin by custom program"],
      watchItems: ["One-customer concentration", "Tapeout delays", "Insourcing by cloud customers"],
      sourceStatus: "research_only",
    },
    {
      key: "optical-bandwidth",
      tab: "optical-connectivity",
      title: "Bandwidth Per AI Cluster",
      thesis: "Optical and DSP content can rise with larger AI clusters, but supply constraints and merchant competition can pressure pricing.",
      evidence: ["800G / 1.6T adoption", "DSP content share", "Inventory and lead-time commentary"],
      watchItems: ["Pricing pressure", "Competing merchant silicon", "Customer qualification delays"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q4", eventDate: "2026-03-05", headline: "Record AI-led FY2026 and FY2027 setup", keyQuestions: ["How much of data-center growth is custom ASIC vs connectivity?", "Are legacy end markets finally growing sequentially?", "Is gross margin improving as AI ramps?"], managementTone: "AI confidence with watchful legacy recovery.", modelReadThrough: "Keep AI growth high but maintain concentration haircut.", riskSignal: "Inflecting", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q4", eventDate: "2025-03-05", headline: "Custom silicon ramp visibility", keyQuestions: ["What production ramps are committed?", "How much revenue is NRE vs production?", "Any customer concentration disclosure?"], managementTone: "Optimistic on AI programs.", modelReadThrough: "Increase revenue CAGR only if multi-program evidence appears.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2024-12-03", headline: "AI acceleration vs trough legacy", keyQuestions: ["Can AI offset carrier/enterprise weakness?", "Are inventories normalizing?", "Gross margin mix?"], managementTone: "AI growth strong.", modelReadThrough: "Raise AI mix; keep non-AI recovery score modest.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2024-08-29", headline: "Data center becomes the thesis", keyQuestions: ["Is AI growth broadening?", "What is optical contribution?", "Any supply constraints?"], managementTone: "Bullish on data center.", modelReadThrough: "Data-center mix supports higher multiple.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2024-05-30", headline: "Legacy weakness still visible", keyQuestions: ["Are carrier and enterprise bottoming?", "Do AI orders pull forward demand?", "Can opex stay controlled?"], managementTone: "Cautious outside AI.", modelReadThrough: "Do not let AI revenue hide weak base.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2024-03-07", headline: "AI ramp starts to dominate narrative", keyQuestions: ["How much data center is AI?", "Does guide imply acceleration?", "Are inventory corrections ending?"], managementTone: "AI constructive.", modelReadThrough: "Begin separating AI and legacy in model.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2023-11-30", headline: "Inventory correction", keyQuestions: ["Where is the inventory trough?", "Can AI offset storage weakness?", "Any cancellation risk?"], managementTone: "Mixed.", modelReadThrough: "Keep valuation discount until cycle clears.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2023-08-24", headline: "Early AI optionality", keyQuestions: ["Is AI real or narrative?", "What are customer commitments?", "Can margins recover?"], managementTone: "Early optimism.", modelReadThrough: "Use lower AI revenue probability before production ramps.", riskSignal: "Neutral", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { id: "mrvl-2024q2", eventDate: "2023-08-24", fiscalPeriod: "FY2024 Q2", asOfPrice: 57, fairValue: 61, targetPrice3Y: 72, expectedShareholderCagr: 0.081, method: "Early AI optionality with cycle discount.", sourceStatus: "research_only", warnings: ["Proxy price; local fallback row."], methodOutputs: [{ label: "DCF", value: 59, format: "currency", description: "AI probability-weighted." }] },
    { id: "mrvl-2024q3", eventDate: "2023-11-30", fiscalPeriod: "FY2024 Q3", asOfPrice: 54, fairValue: 58, targetPrice3Y: 69, expectedShareholderCagr: 0.084, method: "Inventory correction discount.", sourceStatus: "research_only", warnings: ["No backend daily price."], methodOutputs: [{ label: "FCF multiple", value: 57, format: "currency", description: "Legacy trough." }] },
    { id: "mrvl-2024q4", eventDate: "2024-03-07", fiscalPeriod: "FY2024 Q4", asOfPrice: 72, fairValue: 78, targetPrice3Y: 96, expectedShareholderCagr: 0.101, method: "AI data-center ramp starts.", sourceStatus: "research_only", warnings: ["Local event snapshot."], methodOutputs: [{ label: "Blend", value: 78, format: "currency", description: "AI ramps, legacy weak." }] },
    { id: "mrvl-2025q1", eventDate: "2024-05-30", fiscalPeriod: "FY2025 Q1", asOfPrice: 66, fairValue: 80, targetPrice3Y: 98, expectedShareholderCagr: 0.141, method: "Legacy trough + AI ramp.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 80, format: "currency", description: "High AI mix but cycle haircut." }] },
    { id: "mrvl-2025q2", eventDate: "2024-08-29", fiscalPeriod: "FY2025 Q2", asOfPrice: 73, fairValue: 90, targetPrice3Y: 112, expectedShareholderCagr: 0.153, method: "Custom silicon visibility improves.", sourceStatus: "research_only", warnings: ["Local fallback."], methodOutputs: [{ label: "FCF multiple", value: 92, format: "currency", description: "Higher AI revenue." }] },
    { id: "mrvl-2025q3", eventDate: "2024-12-03", fiscalPeriod: "FY2025 Q3", asOfPrice: 98, fairValue: 103, targetPrice3Y: 129, expectedShareholderCagr: 0.096, method: "AI acceleration but valuation catches up.", sourceStatus: "research_only", warnings: ["No future customer wins backfilled."], methodOutputs: [{ label: "Blend", value: 103, format: "currency", description: "AI growth priced." }] },
    { id: "mrvl-2025q4", eventDate: "2025-03-05", fiscalPeriod: "FY2025 Q4", asOfPrice: 113, fairValue: 116, targetPrice3Y: 146, expectedShareholderCagr: 0.09, method: "Custom silicon ramp evidence.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 116, format: "currency", description: "Design-win visibility." }] },
    { id: "mrvl-2026q4", eventDate: "2026-03-05", fiscalPeriod: "FY2026 Q4", asOfPrice: 176, fairValue: 166, targetPrice3Y: 210, expectedShareholderCagr: 0.06, method: "Base AI / optical triangulation.", sourceStatus: "official_actual", warnings: ["Backend valuation run not persisted."], methodOutputs: [{ label: "Blend", value: 166, format: "currency", description: "AI growth strong, but a lot is already capitalized." }] },
  ],
  valuation: {
    defaultAssumptions,
    scenarios: {
      Bear: { ...defaultAssumptions, revenueCagr3Y: 0.12, normalizedFcfMargin: 0.19, exitFcfMultiple: 22, evRevenueMultiple: 6.5, discountRate: 0.115, qualityAdjustment: 0.95, riskHaircut: 0.22 },
      Base: defaultAssumptions,
      Bull: { ...defaultAssumptions, revenueCagr3Y: 0.38, normalizedFcfMargin: 0.31, exitFcfMultiple: 38, evRevenueMultiple: 13.5, discountRate: 0.085, qualityAdjustment: 1.12, riskHaircut: 0.08 },
    },
    modelDescription: "AI custom silicon / optical DCF with FCF multiple and EV/revenue cross-check.",
    noFutureLeakageNote: "Historical MRVL rows separate AI program evidence by event date and do not apply later hyperscaler ramps to earlier quarters.",
  },
  risks: [
    { title: "Customer concentration", detail: "Large AI programs can dominate growth and make revenue less repeatable than the multiple implies.", severity: "high", killSignal: "One major program slips while AI revenue still drives the valuation." },
    { title: "Legacy cycle drag", detail: "Carrier, enterprise and storage weakness can offset AI operating leverage.", severity: "medium", killSignal: "Non-AI revenue stays negative for multiple quarters after inventory normalization." },
    { title: "AI gross margin disappointment", detail: "Custom silicon growth may carry lower-than-expected margin depending on NRE and production economics.", severity: "high", killSignal: "Gross margin fails to improve despite AI mix expansion." },
  ],
  monitoring: ["Custom ASIC production ramps", "Optical / DSP revenue", "Non-AI sequential growth", "Gross margin by mix", "Customer concentration commentary"],
  sourceGaps: ["Historical valuation rows are local fallback.", "MRVL/SPY daily price bars not imported into backend.", "Program-level AI revenue is research proxy, not official segment disclosure."],
  backendStatus: {
    supported: false,
    detail: "MRVL has frontend research history and valuation now, but no per-ticker SQLite backend or AWS data deployment yet.",
    nextSteps: ["Create MRVL backend schema.", "Import MRVL/SPY prices.", "Persist valuation events by quarterly release.", "Add transcript extraction for AI program commentary."],
  },
  qualityBadges: [
    { label: "AI revenue split", value: "Research proxy", badge: "Assumption" },
    { label: "Historical valuation", value: "Local fallback", badge: "Placeholder" },
    { label: "Price history", value: "Proxy", badge: "Placeholder" },
  ],
};
