import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const cbDataset = createLocalDeepResearchDataset({
  ticker: "CB",
  companyName: "Chubb Limited",
  sector: "Property & Casualty Insurance / Specialty / Global Commercial",
  archetype: "Specialty P&C compounder / underwriting and float quality",
  description:
    "CB research cockpit focused on commercial P&C pricing, loss-cost inflation, reserve discipline, catastrophe exposure, reinvestment yield, specialty underwriting quality, capital return, and whether the premium insurer multiple remains justified.",
  updatedAt: "2026-05-20",
  currentPrice: 330.18,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "pricing-loss-cost", label: "Pricing / Loss Cost" },
    { value: "cat-reserves", label: "Cat / Reserves" },
    { value: "float-capital", label: "Float / Capital" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "combined-ratio", label: "Underlying Combined Ratio", value: 0.87, format: "percent", description: "Research proxy for normalized underwriting quality.", badge: "Placeholder" },
    { key: "pricing-spread", label: "Pricing > Loss Cost", value: 0.035, format: "percent", description: "Assumed positive spread between earned rate and loss-cost trend.", badge: "Assumption" },
    { key: "reinvestment-yield", label: "Reinvestment Yield Support", value: 0.047, format: "percent", description: "Investment income support from higher portfolio yields.", badge: "Assumption" },
    { key: "capital-return", label: "Capital Return Yield", value: 0.035, format: "percent", description: "Dividend plus repurchase framework; official data import pending.", badge: "Placeholder" },
    { key: "base-gap", label: "Base Upside / Downside", value: 0.04, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "pricing-loss-cost",
      question: "Is Chubb still earning rate above loss-cost inflation?",
      currentView: "The quality thesis depends on underwriting discipline and rate adequacy across commercial and specialty lines.",
      metric: "Rate change, loss-cost trend, underlying combined ratio",
      evidenceNeeded: "Line-by-line pricing and loss-cost commentary",
      valuationTie: "Normalized FCF/earnings margin and quality adjustment",
      bearCase: "Rate slows below loss-cost inflation and accident-year margin rolls over.",
    },
    {
      key: "reserve-discipline",
      question: "Are reserves still conservative?",
      currentView: "Reserve releases support confidence only if accident-year loss picks stay disciplined.",
      metric: "Prior-year development, accident-year loss ratio",
      evidenceNeeded: "Reserve triangle and catastrophe-normalized bridge",
      valuationTie: "Risk haircut",
      bearCase: "Favorable development fades or reserve additions appear.",
    },
    {
      key: "cat-climate",
      question: "How much catastrophe and climate volatility should investors underwrite?",
      currentView: "Chubb can price risk better than peers, but secondary perils and severity inflation still matter.",
      metric: "Cat loss ratio, reinsurance cost, geographic exposure",
      evidenceNeeded: "Cat load and reinsurance renewal commentary",
      valuationTie: "Discount rate and risk haircut",
      bearCase: "Higher cat load consumes pricing gains.",
    },
    {
      key: "investment-income",
      question: "Can reinvestment yield keep supporting ROE?",
      currentView: "Higher portfolio yields provide an earnings tailwind, but reinvestment support eventually plateaus.",
      metric: "Book yield, new money yield, duration",
      evidenceNeeded: "Fixed-income portfolio roll-forward",
      valuationTie: "Revenue/earnings growth and terminal growth",
      bearCase: "Yield tailwind fades while underwriting margin normalizes.",
    },
  ],
  kpiSeries: [
    {
      key: "pricing-loss-cost",
      title: "Pricing Spread vs Underwriting Margin",
      subtitle: "Chubb's premium valuation needs earned rate to exceed loss-cost inflation through the cycle.",
      sourceStatus: "research_only",
      measures: [
        { key: "pricingSpread", label: "Pricing spread bps", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "combinedRatio", label: "Underlying combined ratio %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", pricingSpread: 320, combinedRatio: 0.879 },
        { period: "2024 Q2", pricingSpread: 340, combinedRatio: 0.874 },
        { period: "2024 Q3", pricingSpread: 310, combinedRatio: 0.878 },
        { period: "2024 Q4", pricingSpread: 300, combinedRatio: 0.881 },
        { period: "2025 Q1", pricingSpread: 290, combinedRatio: 0.876 },
        { period: "2025 Q2", pricingSpread: 270, combinedRatio: 0.879 },
        { period: "2025 Q3", pricingSpread: 250, combinedRatio: 0.883 },
        { period: "2025 Q4", pricingSpread: 240, combinedRatio: 0.885 },
        { period: "2026 Q1", pricingSpread: 230, combinedRatio: 0.887 },
      ],
    },
    {
      key: "cat-reserves",
      title: "Cat Load vs Reserve Quality",
      subtitle: "Cat volatility should be separated from underlying reserve discipline.",
      sourceStatus: "research_only",
      measures: [
        { key: "catLoad", label: "Cat load index", format: "number", chartType: "bar", color: "#92400e", axis: "left" },
        { key: "reserveQuality", label: "Reserve quality score", format: "percent", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", catLoad: 88, reserveQuality: 0.78 },
        { period: "2024 Q2", catLoad: 93, reserveQuality: 0.8 },
        { period: "2024 Q3", catLoad: 112, reserveQuality: 0.79 },
        { period: "2024 Q4", catLoad: 97, reserveQuality: 0.8 },
        { period: "2025 Q1", catLoad: 91, reserveQuality: 0.81 },
        { period: "2025 Q2", catLoad: 99, reserveQuality: 0.81 },
        { period: "2025 Q3", catLoad: 118, reserveQuality: 0.8 },
        { period: "2025 Q4", catLoad: 102, reserveQuality: 0.8 },
        { period: "2026 Q1", catLoad: 96, reserveQuality: 0.8 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "pricing",
      tab: "pricing-loss-cost",
      title: "Commercial Pricing and Loss Cost",
      thesis: "Chubb compounds when disciplined pricing keeps accident-year margins ahead of social inflation and severity.",
      evidence: ["Rate change by line", "Loss-cost trend", "Underlying combined ratio"],
      watchItems: ["Casualty severity", "Workers' comp softening", "Property reinsurance cost"],
      sourceStatus: "research_only",
    },
    {
      key: "cat-reserves",
      tab: "cat-reserves",
      title: "Catastrophe Load and Reserve Conservatism",
      thesis: "The best underwriting franchises still need explicit cat and reserve audit work; headline combined ratio can mislead.",
      evidence: ["Cat load", "Prior-year development", "Accident-year loss picks"],
      watchItems: ["Reserve charge", "Secondary peril frequency", "Reinsurance renewal shock"],
      sourceStatus: "research_only",
    },
    {
      key: "float-capital",
      tab: "float-capital",
      title: "Float, Investment Income and Capital Return",
      thesis: "Higher reinvestment yields support ROE, but the market should not capitalize a yield tailwind as permanent growth.",
      evidence: ["New money yield", "Duration", "Buyback pace", "BVPS growth"],
      watchItems: ["Yield plateau", "Capital trapped by cat risk", "FX impact"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-22", headline: "Pricing spread and cat load", keyQuestions: ["Is rate still above loss cost?", "Any reserve development?", "How large is cat load?"], managementTone: "Disciplined.", modelReadThrough: "Keep quality premium with explicit cat haircut.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-01-28", headline: "Investment income and capital return", keyQuestions: ["Is book yield still rising?", "Are buybacks increasing?", "Any reserve noise?"], managementTone: "Constructive.", modelReadThrough: "Yield support helps near-term value but not terminal growth.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-21", headline: "Cat season audit", keyQuestions: ["Cat loss versus modeled?", "Does underlying combined ratio hold?", "What is reinsurance outlook?"], managementTone: "Measured.", modelReadThrough: "Hold risk haircut until cat normalization clearer.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-22", headline: "Casualty severity and reserve discipline", keyQuestions: ["Any casualty reserve strengthening?", "Rate adequacy?", "Premium growth quality?"], managementTone: "Underwriting-focused.", modelReadThrough: "Quality adjustment remains high.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-22", headline: "Pricing moderation", keyQuestions: ["Is pricing slowing?", "Are loss costs rising?", "Can investment income offset?"], managementTone: "Balanced.", modelReadThrough: "Do not overcapitalize yield tailwind.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-01-29", headline: "ROE durability", keyQuestions: ["Can ROE remain high?", "Capital return?", "Reserve releases?"], managementTone: "Confident.", modelReadThrough: "Premium multiple supported.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-22", headline: "Cat volatility", keyQuestions: ["Was cat load abnormal?", "Is reinsurance adequate?", "Any loss-cost surprise?"], managementTone: "Disciplined.", modelReadThrough: "Separate cat noise from underwriting quality.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-23", headline: "Rate adequacy", keyQuestions: ["Rate above loss cost?", "Is premium growth broad?", "Reserve development?"], managementTone: "Strong.", modelReadThrough: "Quality premium remains justified.", riskSignal: "Positive", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-23", fiscalPeriod: "FY2024 Q2", asOfPrice: 260, fairValue: 270, method: "Underwriting quality and book-value compounding local fallback." },
    { eventDate: "2024-10-22", fiscalPeriod: "FY2024 Q3", asOfPrice: 285, fairValue: 286, method: "Cat volatility separated from underlying margin." },
    { eventDate: "2025-01-29", fiscalPeriod: "FY2024 Q4", asOfPrice: 275, fairValue: 298, method: "ROE durability and investment income support." },
    { eventDate: "2025-04-22", fiscalPeriod: "FY2025 Q1", asOfPrice: 291, fairValue: 306, method: "Pricing moderation with quality premium." },
    { eventDate: "2025-07-22", fiscalPeriod: "FY2025 Q2", asOfPrice: 305, fairValue: 318, method: "Casualty severity and reserve discipline." },
    { eventDate: "2025-10-21", fiscalPeriod: "FY2025 Q3", asOfPrice: 319, fairValue: 325, method: "Cat season audit and reserve quality." },
    { eventDate: "2026-01-28", fiscalPeriod: "FY2025 Q4", asOfPrice: 326, fairValue: 336, method: "Investment income and capital return." },
    { eventDate: "2026-04-22", fiscalPeriod: "FY2026 Q1", asOfPrice: 330, fairValue: 343, method: "Base underwriting / float local run." },
  ],
  valuationBase: {
    revenueBase: 57000,
    revenueCagr3Y: 0.055,
    terminalGrowth: 0.025,
    normalizedFcfMargin: 0.16,
    exitFcfMultiple: 14,
    evRevenueMultiple: 2.4,
    discountRate: 0.085,
    netCashDebt: 0,
    dilutedShares: 388,
    qualityAdjustment: 1.12,
    riskHaircut: 0.08,
    dividendYield: 0.011,
    buybackYield: 0.024,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.02, normalizedFcfMargin: 0.11, exitFcfMultiple: 10, evRevenueMultiple: 1.8, riskHaircut: 0.2, qualityAdjustment: 1.0, buybackYield: 0.01 },
    Base: {},
    Bull: { revenueCagr3Y: 0.075, normalizedFcfMargin: 0.19, exitFcfMultiple: 16, evRevenueMultiple: 2.8, riskHaircut: 0.04, qualityAdjustment: 1.18, buybackYield: 0.03 },
  },
  valuationDescription: "Maps insurer underwriting quality, investment income and capital return into the platform DCF / earnings-capitalization framework until a BVPS/ROE insurance model is added.",
  risks: [
    { title: "Loss-cost inflation", detail: "Casualty severity and social inflation can outrun pricing.", severity: "high", killSignal: "Underlying combined ratio deteriorates despite positive rate." },
    { title: "Catastrophe volatility", detail: "Cat losses and reinsurance costs can reduce earnings quality.", severity: "medium", killSignal: "Cat load structurally exceeds modeled expectation." },
    { title: "Reserve risk", detail: "Reserve strengthening would challenge the underwriting-quality thesis.", severity: "high", killSignal: "Prior-year development turns materially adverse." },
  ],
  monitoring: ["Rate vs loss cost", "Underlying combined ratio", "Cat load", "Reserve development", "Book yield", "Buyback pace"],
  sourceGaps: ["Insurance-specific BVPS/ROE model is not implemented yet.", "Official line-level rate, loss-cost, cat and reserve data should be imported from supplements."],
});
