import type { StockValuationConfig } from "../types";
import type { MuScenarioPresetMap, MuValuationAssumptions } from "./model";

export const defaultMuValuationAssumptions: MuValuationAssumptions = {
  currentPrice: 678.83,
  dilutedShares: 1142,
  normalizedRevenue: 48_000,
  revenueGrowth: 0.11,
  grossMargin: 0.44,
  operatingMargin: 0.31,
  normalizedFcfMargin: 0.14,
  targetSalesMultiple: 4.0,
  targetEbitMultiple: 17,
  targetPe: 24,
  targetFcfYield: 0.04,
  discountRate: 0.095,
  terminalGrowth: 0.025,
  netCashUsd: -6_500,
  hbmMixUplift: 0.14,
  memoryCycleHaircut: 0.16,
  chinaRestrictionHaircut: 0.05,
  capexIntensityHaircut: 0.06,
  dividendYield: 0.001,
  buybackYield: 0.004,
};

export const muScenarioPresets: MuScenarioPresetMap = {
  Bear: {
    ...defaultMuValuationAssumptions,
    normalizedRevenue: 39_000,
    revenueGrowth: 0.02,
    grossMargin: 0.34,
    operatingMargin: 0.20,
    normalizedFcfMargin: 0.07,
    targetSalesMultiple: 2.3,
    targetEbitMultiple: 11,
    targetPe: 14,
    targetFcfYield: 0.065,
    discountRate: 0.11,
    hbmMixUplift: 0.04,
    memoryCycleHaircut: 0.28,
    chinaRestrictionHaircut: 0.10,
    capexIntensityHaircut: 0.10,
    buybackYield: 0,
  },
  Base: defaultMuValuationAssumptions,
  Bull: {
    ...defaultMuValuationAssumptions,
    normalizedRevenue: 58_000,
    revenueGrowth: 0.17,
    grossMargin: 0.50,
    operatingMargin: 0.38,
    normalizedFcfMargin: 0.21,
    targetSalesMultiple: 5.2,
    targetEbitMultiple: 22,
    targetPe: 30,
    targetFcfYield: 0.032,
    discountRate: 0.085,
    hbmMixUplift: 0.22,
    memoryCycleHaircut: 0.09,
    chinaRestrictionHaircut: 0.035,
    capexIntensityHaircut: 0.04,
    buybackYield: 0.008,
  },
};

export function buildMuValuationConfig(
  calculateValuation: StockValuationConfig["calculateValuation"],
): StockValuationConfig {
  return {
    ticker: "MU",
    modelType: "memory-cycle-hbm-normalized-dcf-fcf-ev-ebit-sales-triangulation",
    assumptions: [
      { key: "normalizedRevenue", label: "Normalized Revenue", value: defaultMuValuationAssumptions.normalizedRevenue, min: 25_000, max: 80_000, step: 500, format: "currency", source: "assumption", description: "Through-cycle revenue base after DRAM/NAND and HBM normalization.", category: "Scale", unit: "USD", periodicity: "forward annual" },
      { key: "revenueGrowth", label: "Revenue Growth", value: defaultMuValuationAssumptions.revenueGrowth, min: -0.08, max: 0.25, step: 0.005, format: "percent", source: "assumption", description: "Forward normalized growth from AI server memory, HBM and cyclical DRAM/NAND recovery.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "grossMargin", label: "Gross Margin", value: defaultMuValuationAssumptions.grossMargin, min: 0.18, max: 0.62, step: 0.005, format: "percent", source: "assumption", description: "Normalized gross margin, not latest-quarter peak margin.", category: "Margins", unit: "percent" },
      { key: "operatingMargin", label: "Operating Margin", value: defaultMuValuationAssumptions.operatingMargin, min: 0.08, max: 0.48, step: 0.005, format: "percent", source: "assumption", description: "Operating margin after mix, utilization and R&D intensity.", category: "Margins", unit: "percent" },
      { key: "normalizedFcfMargin", label: "FCF Margin", value: defaultMuValuationAssumptions.normalizedFcfMargin, min: 0.00, max: 0.30, step: 0.005, format: "percent", source: "assumption", description: "Free cash flow conversion after HBM and node-transition capex.", category: "Cash Flow", unit: "percent" },
      { key: "targetSalesMultiple", label: "EV/Sales", value: defaultMuValuationAssumptions.targetSalesMultiple, min: 1.0, max: 7.5, step: 0.1, format: "multiple", source: "assumption", description: "Revenue multiple for a cyclical but AI-levered memory supplier.", category: "Valuation", unit: "multiple" },
      { key: "targetEbitMultiple", label: "EV/EBIT", value: defaultMuValuationAssumptions.targetEbitMultiple, min: 6, max: 28, step: 0.5, format: "multiple", source: "assumption", description: "Normalized operating earnings multiple.", category: "Valuation", unit: "multiple" },
      { key: "targetPe", label: "P/E", value: defaultMuValuationAssumptions.targetPe, min: 8, max: 36, step: 0.5, format: "multiple", source: "assumption", description: "Normalized EPS multiple, used as a cross-check because spot EPS is cyclical.", category: "Valuation", unit: "multiple" },
      { key: "targetFcfYield", label: "Target FCF Yield", value: defaultMuValuationAssumptions.targetFcfYield, min: 0.025, max: 0.09, step: 0.001, format: "percent", source: "assumption", description: "FCF-yield guardrail after capital intensity.", category: "Valuation", unit: "percent" },
      { key: "discountRate", label: "Discount Rate", value: defaultMuValuationAssumptions.discountRate, min: 0.07, max: 0.13, step: 0.0025, format: "percent", source: "assumption", description: "Cost of equity reflecting memory cyclicality and AI concentration.", category: "Valuation", unit: "percent" },
      { key: "hbmMixUplift", label: "HBM Mix Uplift", value: defaultMuValuationAssumptions.hbmMixUplift, min: 0, max: 0.35, step: 0.005, format: "percent", source: "assumption", description: "Valuation uplift from durable HBM mix, qualification and pricing.", category: "Thesis", unit: "percent" },
      { key: "memoryCycleHaircut", label: "Memory Cycle Haircut", value: defaultMuValuationAssumptions.memoryCycleHaircut, min: 0, max: 0.40, step: 0.005, format: "percent", source: "assumption", description: "Explicit peak-cycle fade for DRAM/NAND and HBM supply additions.", category: "Risk", unit: "percent" },
      { key: "chinaRestrictionHaircut", label: "China / Export Haircut", value: defaultMuValuationAssumptions.chinaRestrictionHaircut, min: 0, max: 0.20, step: 0.005, format: "percent", source: "assumption", description: "China exposure and export-control risk haircut.", category: "Risk", unit: "percent" },
      { key: "capexIntensityHaircut", label: "Capex Intensity Haircut", value: defaultMuValuationAssumptions.capexIntensityHaircut, min: 0, max: 0.18, step: 0.005, format: "percent", source: "assumption", description: "Haircut for HBM and node-transition capital intensity.", category: "Risk", unit: "percent" },
    ],
    scenarios: [
      { name: "Bear", assumptions: muScenarioPresets.Bear },
      { name: "Base", assumptions: muScenarioPresets.Base },
      { name: "Bull", assumptions: muScenarioPresets.Bull },
    ],
    calculateValuation,
  };
}
