import type { MuDataset } from "./model";

export const muDataset: MuDataset = {
  ticker: "MU",
  companyName: "Micron Technology, Inc.",
  currency: "USD",
  latestReportingPeriod: "Q2 FY2026",
  marketData: {
    currentPrice: 678.83,
    priceDate: "2026-05-19",
    sharesForMarketCap: 1142,
    source: "SEC companyfacts for reported data; Nasdaq quote API primary price with Stooq close cross-check",
    sourceStatus: "market_data",
  },
  periods: [
    {
      id: "fy2023",
      label: "FY 2023",
      fiscalYear: 2023,
      periodType: "annual",
      asOfDate: "2023-09-27",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2023 / FY2023 10-K",
      revenue: 15540,
      grossProfit: -1416,
      grossMargin: -0.091,
      operatingIncome: -5745,
      operatingMargin: -0.37,
      netIncome: -5833,
      dilutedEps: -5.34,
      dilutedShares: 1093,
      operatingCashFlow: 1559,
      capex: 7676,
      freeCashFlow: -6117,
      notes: "Memory down-cycle trough; negative gross margin and FCF make peak/trough normalization more important than spot P/E.",
    },
    {
      id: "fy2024",
      label: "FY 2024",
      fiscalYear: 2024,
      periodType: "annual",
      asOfDate: "2024-09-26",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2024 / FY2024 10-K",
      revenue: 25111,
      grossProfit: 5613,
      grossMargin: 0.224,
      operatingIncome: 1304,
      operatingMargin: 0.052,
      netIncome: 778,
      dilutedEps: 0.7,
      dilutedShares: 1118,
      operatingCashFlow: 8507,
      capex: 8386,
      freeCashFlow: 121,
      notes: "Recovery year with margins turning positive while capex still absorbed most operating cash flow.",
    },
    {
      id: "fy2025",
      label: "FY 2025",
      fiscalYear: 2025,
      periodType: "annual",
      asOfDate: "2025-09-25",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2025 / FY2025 10-K",
      revenue: 37378,
      grossProfit: 14873,
      grossMargin: 0.398,
      operatingIncome: 9770,
      operatingMargin: 0.261,
      netIncome: 8539,
      dilutedEps: 7.59,
      dilutedShares: 1125,
      operatingCashFlow: 17525,
      capex: 15857,
      freeCashFlow: 1668,
      notes: "HBM and DRAM recovery lifted revenue and margins, but FCF remained capital-intensive.",
    },
    {
      id: "fy2026-q1",
      label: "Q1 FY2026",
      fiscalYear: 2026,
      fiscalQuarter: "Q1",
      periodType: "quarter",
      asOfDate: "2025-12-18",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2025Q4 / FY2026 Q1 10-Q",
      revenue: 13643,
      grossProfit: 7646,
      grossMargin: 0.56,
      operatingIncome: 6136,
      operatingMargin: 0.45,
      netIncome: 5240,
      dilutedEps: 4.6,
      dilutedShares: 1138,
      operatingCashFlow: 8411,
      capex: 5389,
      freeCashFlow: 3022,
      notes: "Quarterly margin and cash flow improved sharply as AI memory supply tightened.",
    },
    {
      id: "fy2026-q2",
      label: "Q2 FY2026",
      fiscalYear: 2026,
      fiscalQuarter: "Q2",
      periodType: "quarter",
      asOfDate: "2026-03-19",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2026Q1 / FY2026 Q2 10-Q",
      revenue: 23860,
      grossProfit: 17755,
      grossMargin: 0.744,
      operatingIncome: 16135,
      operatingMargin: 0.676,
      netIncome: 13785,
      dilutedEps: 12.07,
      dilutedShares: 1142,
      operatingCashFlow: 20314,
      capex: 11776,
      freeCashFlow: 8538,
      notes: "Latest reported period in SEC companyfacts; investors should check whether this reflects a super-cycle quarter before capitalizing it.",
    },
  ],
  operatingMetrics: [
    {
      periodId: "fy2023",
      asOfDate: "2023-09-27",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.15,
      dramCycleSignal: -0.7,
      nandCycleSignal: -0.6,
      capexIntensity: 0.494,
      aiServerExposureCommentary: "AI memory was not yet enough to offset the broader DRAM/NAND downturn.",
      pricingCommentary: "Pricing pressure and inventory corrections dominated the income statement.",
      supplyDisciplineCommentary: "Supply discipline was the key recovery condition.",
      chinaRiskCommentary: "China exposure and export restrictions remained a structural risk item.",
    },
    {
      periodId: "fy2024",
      asOfDate: "2024-09-26",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.45,
      dramCycleSignal: 0.25,
      nandCycleSignal: 0.1,
      capexIntensity: 0.334,
      aiServerExposureCommentary: "HBM demand began to matter more for mix and pricing.",
      pricingCommentary: "Pricing recovered, but FCF still lagged because wafer and HBM investment stayed high.",
      supplyDisciplineCommentary: "Industry supply discipline improved versus the trough.",
      chinaRiskCommentary: "China restrictions remained a risk to shipment mix and customer access.",
    },
    {
      periodId: "fy2025",
      asOfDate: "2025-09-25",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.75,
      dramCycleSignal: 0.65,
      nandCycleSignal: 0.35,
      capexIntensity: 0.424,
      aiServerExposureCommentary: "AI server memory became the central bull case, especially HBM capacity and qualification cadence.",
      pricingCommentary: "Pricing power improved materially; underwriting risk is whether investors extrapolate peak margins.",
      supplyDisciplineCommentary: "Supply discipline looks better, but memory remains cyclical.",
      chinaRiskCommentary: "Export-control sensitivity needs a separate haircut rather than being buried inside multiples.",
    },
    {
      periodId: "fy2026-q2",
      asOfDate: "2026-03-19",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.9,
      dramCycleSignal: 0.8,
      nandCycleSignal: 0.45,
      capexIntensity: 0.494,
      aiServerExposureCommentary: "Latest data supports a strong AI-memory upcycle; the question is durability of HBM mix and pricing.",
      pricingCommentary: "The valuation should stress a margin fade rather than capitalize one hot quarter.",
      supplyDisciplineCommentary: "Supply additions and customer qualification timing are the key watch items.",
      chinaRiskCommentary: "China and export controls can affect both demand and tool/supply-chain availability.",
    },
  ],
  historicalValuations: [
    {
      id: "mu-fy2018",
      label: "FY2018 close",
      eventDate: "2018-10-18",
      fiscalPeriod: "FY2018",
      asOfPrice: 42.87,
      fairValue: 51,
      targetPrice3Y: 64,
      expectedShareholderCagr: 0.143,
      method: "Through-cycle DRAM/NAND EV/EBIT and FCF yield",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "No HBM uplift is included before broad AI-memory demand became investable.",
        "Fair value reflects then-known DRAM/NAND cycle risk rather than current 2026 HBM margins.",
      ],
      methodOutputs: [
        { label: "Cycle EV/EBIT", value: 54, format: "currency", description: "Peak-to-mid-cycle EBIT multiple with supply discipline haircut." },
        { label: "FCF yield", value: 47, format: "currency", description: "FCF normalized for memory working-capital and capex swings." },
        { label: "Cycle haircut", value: -0.12, format: "percent", description: "Discount for memory peak earnings risk known at the event date." },
      ],
    },
    {
      id: "mu-fy2019",
      label: "FY2019 close",
      eventDate: "2019-10-18",
      fiscalPeriod: "FY2019",
      asOfPrice: 44.16,
      fairValue: 43,
      targetPrice3Y: 49,
      expectedShareholderCagr: 0.035,
      method: "Down-cycle normalized book-to-earnings bridge",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Valuation uses only down-cycle pricing and inventory data available around the FY2019 report.",
        "No current HBM or AI-server premium is backfilled into this period.",
      ],
      methodOutputs: [
        { label: "EV/Sales trough", value: 41, format: "currency", description: "Trough revenue multiple against depressed pricing." },
        { label: "Normalized EBIT", value: 45, format: "currency", description: "Recovered EBIT case with low supply-confidence." },
        { label: "Cycle risk", value: -0.18, format: "percent", description: "High uncertainty from inventory and pricing resets." },
      ],
    },
    {
      id: "mu-fy2020",
      label: "FY2020 close",
      eventDate: "2020-10-16",
      fiscalPeriod: "FY2020",
      asOfPrice: 52.57,
      fairValue: 57,
      targetPrice3Y: 72,
      expectedShareholderCagr: 0.111,
      method: "Recovery-cycle EV/EBIT and DCF",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Model gives credit for recovery-cycle utilization but does not assume a structural AI-memory premium.",
        "COVID-era demand mix is treated as cyclical rather than permanent.",
      ],
      methodOutputs: [
        { label: "Recovered EBIT", value: 60, format: "currency", description: "Normalized EBIT bridge after demand recovery." },
        { label: "DCF", value: 55, format: "currency", description: "Six-year recovery fade to mid-cycle margins." },
        { label: "Capex drag", value: -0.08, format: "percent", description: "Cash conversion haircut for node and wafer investment." },
      ],
    },
    {
      id: "mu-fy2021",
      label: "FY2021 close",
      eventDate: "2021-10-15",
      fiscalPeriod: "FY2021",
      asOfPrice: 69.96,
      fairValue: 82,
      targetPrice3Y: 104,
      expectedShareholderCagr: 0.142,
      method: "Mid-cycle DRAM recovery triangulation",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Fair value recognizes stronger DRAM demand, but NAND and supply response remain explicit risks.",
        "HBM is not treated as a mature separate profit pool in this older event.",
      ],
      methodOutputs: [
        { label: "EV/EBIT", value: 85, format: "currency", description: "Recovered operating margin cross-check." },
        { label: "P/E cross-check", value: 78, format: "currency", description: "Normalized EPS rather than spot peak EPS." },
        { label: "Supply discipline", value: 0.06, format: "percent", description: "Modest premium for better industry capital discipline." },
      ],
    },
    {
      id: "mu-fy2022",
      label: "FY2022 close",
      eventDate: "2022-10-14",
      fiscalPeriod: "FY2022",
      asOfPrice: 52.91,
      fairValue: 48,
      targetPrice3Y: 58,
      expectedShareholderCagr: 0.031,
      method: "Inventory correction stress case",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Valuation is compressed for inventory correction, customer digestion and capex absorption then visible.",
        "No future HBM uplift is introduced before evidence from later AI-server cycles.",
      ],
      methodOutputs: [
        { label: "Trough EV/Sales", value: 45, format: "currency", description: "Down-cycle revenue multiple with pricing pressure." },
        { label: "Normalized FCF", value: 52, format: "currency", description: "Cash conversion after capex normalization." },
        { label: "Inventory risk", value: -0.22, format: "percent", description: "Haircut for channel correction and weaker pricing." },
      ],
    },
    {
      id: "mu-fy2023",
      label: "FY2023 close",
      eventDate: "2023-10-06",
      fiscalPeriod: "FY2023",
      asOfPrice: 68.9,
      fairValue: 61,
      targetPrice3Y: 75,
      expectedShareholderCagr: 0.035,
      method: "Trough recovery with negative FCF guardrail",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Negative reported gross margin and FCF constrain the fair value despite early AI-memory enthusiasm.",
        "HBM is handled as a small emerging mix option, not a current full-cycle margin anchor.",
      ],
      methodOutputs: [
        { label: "Recovery EV/Sales", value: 66, format: "currency", description: "Revenue recovery with margin still below prior peaks." },
        { label: "FCF yield", value: 54, format: "currency", description: "Penalty for negative trough FCF and high reinvestment." },
        { label: "HBM option", value: 0.04, format: "percent", description: "Small option credit based on then-visible AI memory demand." },
      ],
    },
    {
      id: "mu-fy2024",
      label: "FY2024 close",
      eventDate: "2024-10-03",
      fiscalPeriod: "FY2024",
      asOfPrice: 103.71,
      fairValue: 118,
      targetPrice3Y: 152,
      expectedShareholderCagr: 0.136,
      method: "HBM mix uplift plus FCF guardrail",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "HBM premium is introduced only after AI-memory evidence was visible by this event.",
        "Capex intensity still caps valuation confidence.",
      ],
      methodOutputs: [
        { label: "EV/EBIT", value: 124, format: "currency", description: "Normalized operating income with HBM mix credit." },
        { label: "DCF", value: 112, format: "currency", description: "FCF fade with elevated capex." },
        { label: "HBM uplift", value: 0.14, format: "percent", description: "Explicit mix premium separated from base memory cycle." },
      ],
    },
    {
      id: "mu-fy2025",
      label: "FY2025 close",
      eventDate: "2025-10-02",
      fiscalPeriod: "FY2025",
      asOfPrice: 255.4,
      fairValue: 318,
      targetPrice3Y: 430,
      expectedShareholderCagr: 0.19,
      method: "AI-memory upcycle triangulation",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Fair value lifts with HBM and DRAM pricing, but does not capitalize the latest margin as permanent.",
        "Supply catch-up and customer qualification risk remain explicit in the method bridge.",
      ],
      methodOutputs: [
        { label: "EV/EBIT", value: 335, format: "currency", description: "AI-memory upcycle EBIT with fade." },
        { label: "FCF yield", value: 292, format: "currency", description: "FCF value after HBM capex burden." },
        { label: "Cycle haircut", value: -0.16, format: "percent", description: "Downside adjustment for memory supply response." },
      ],
    },
    {
      id: "mu-fy2026-q1",
      label: "Q1 FY2026",
      eventDate: "2025-12-18",
      fiscalPeriod: "Q1 FY2026",
      asOfPrice: 345.1,
      fairValue: 428,
      targetPrice3Y: 585,
      expectedShareholderCagr: 0.192,
      method: "HBM durability case with capex stress",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Uses Q1 FY2026 data only; Q2 FY2026 margin evidence is not included.",
        "Model explicitly tests whether HBM mix survives a capex-heavy supply response.",
      ],
      methodOutputs: [
        { label: "DCF", value: 442, format: "currency", description: "Forward FCF with HBM mix and capex fade." },
        { label: "P/E cross-check", value: 406, format: "currency", description: "Normalized EPS after cycle fade." },
        { label: "Capex haircut", value: -0.11, format: "percent", description: "Penalty for capital intensity and cash conversion risk." },
      ],
    },
    {
      id: "mu-fy2026-q2",
      label: "Q2 FY2026",
      eventDate: "2026-03-19",
      fiscalPeriod: "Q2 FY2026",
      asOfPrice: 452.8,
      fairValue: 520,
      targetPrice3Y: 720,
      expectedShareholderCagr: 0.168,
      method: "Latest HBM cycle model with normalized margin fade",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Latest quarter supports the bull case, but spot margins are faded before valuation.",
        "Backend price import and persisted valuation runs are still required for production-grade no-leakage audit.",
      ],
      methodOutputs: [
        { label: "EV/EBIT", value: 548, format: "currency", description: "Normalized EBIT with HBM mix but cycle fade." },
        { label: "FCF yield", value: 488, format: "currency", description: "FCF guardrail after capex and working capital." },
        { label: "HBM uplift", value: 0.2, format: "percent", description: "Current visible HBM mix premium." },
      ],
    },
  ],
  earningsCalls: [
    {
      id: "mu-call-fy2025-q3",
      quarter: "Q3 FY2025",
      callDate: "2025-06-25",
      sourceStatus: "research_only",
      managementTone: "constructive",
      reportedFacts: [
        "AI server memory demand remained the central upside driver.",
        "HBM capacity qualification and supply allocation were more important than generic bit growth.",
        "Capex intensity stayed elevated as the company invested into leading-edge DRAM and HBM.",
      ],
      analystFocus: ["HBM capacity sold out visibility", "DRAM pricing sustainability", "Capex and FCF conversion"],
      marketFocusSummary: "Investors were shifting from a generic memory recovery question to a durability-of-HBM question.",
      modelReadThrough: "Raise HBM mix uplift, but keep capex and cycle haircuts visible so the model does not over-capitalize one upcycle.",
      focusScores: { hbmDemand: 82, dramPricing: 68, nandPricing: 44, capexFcf: 72, chinaRisk: 46, supplyDiscipline: 63 },
    },
    {
      id: "mu-call-fy2025-q4",
      quarter: "Q4 FY2025",
      callDate: "2025-09-25",
      sourceStatus: "research_only",
      managementTone: "bullish",
      reportedFacts: [
        "FY2025 recovery showed HBM and DRAM mix moving margins materially higher.",
        "FCF improved but still lagged earnings power because capex absorbed cash.",
        "The company framed AI memory as a structural mix shift, not only a cyclical recovery.",
      ],
      analystFocus: ["HBM share gains", "Long-term gross margin", "Supply response risk"],
      marketFocusSummary: "The debate became whether MU deserved an AI-infrastructure multiple or a memory-cycle multiple.",
      modelReadThrough: "Increase normalized revenue and gross margin, but fade peak operating margin in outer years.",
      focusScores: { hbmDemand: 90, dramPricing: 78, nandPricing: 50, capexFcf: 75, chinaRisk: 50, supplyDiscipline: 70 },
    },
    {
      id: "mu-call-fy2026-q1",
      quarter: "Q1 FY2026",
      callDate: "2025-12-18",
      sourceStatus: "research_only",
      managementTone: "bullish",
      reportedFacts: [
        "Q1 FY2026 revenue and margin suggested strong AI-memory pricing and supply tightness.",
        "Cash conversion improved, but capex remained a key underwriting variable.",
        "Management commentary increased confidence in near-term HBM demand visibility.",
      ],
      analystFocus: ["HBM qualification cadence", "DRAM contract pricing", "2026 capex envelope"],
      marketFocusSummary: "The market started asking if the cycle could stay tighter for longer because AI absorbs leading-edge DRAM.",
      modelReadThrough: "Raise near-term fair value, but require a visible supply-risk index in the forecast model.",
      focusScores: { hbmDemand: 94, dramPricing: 84, nandPricing: 55, capexFcf: 80, chinaRisk: 54, supplyDiscipline: 72 },
    },
    {
      id: "mu-call-fy2026-q2",
      quarter: "Q2 FY2026",
      callDate: "2026-03-19",
      sourceStatus: "research_only",
      managementTone: "constructive",
      reportedFacts: [
        "Q2 FY2026 results strengthened the case that HBM can reshape through-cycle earnings.",
        "Reported margins were very high, creating a separate risk of peak-margin extrapolation.",
        "China/export restrictions and supply additions remained the main red-team variables.",
      ],
      analystFocus: ["HBM durability into 2027", "Supply additions", "China exposure", "Peak vs normalized FCF"],
      marketFocusSummary: "The debate is no longer whether MU benefits from AI, but how much of the benefit is already priced as permanent.",
      modelReadThrough: "Keep the fair value above price only if 2027-2030 HBM mix and FCF conversion survive a supply catch-up case.",
      focusScores: { hbmDemand: 96, dramPricing: 86, nandPricing: 58, capexFcf: 78, chinaRisk: 62, supplyDiscipline: 74 },
    },
  ],
  memoryCycleForecast: [
    {
      year: 2026,
      sourceStatus: "forecast_assumption",
      cyclePhase: "AI-memory upcycle",
      dramBitGrowth: 0.18,
      nandBitGrowth: 0.12,
      hbmRevenueMix: 0.18,
      revenue: 49000,
      grossMargin: 0.48,
      operatingMargin: 0.34,
      fcfMargin: 0.16,
      capexIntensity: 0.43,
      demandIndex: 86,
      supplyRiskIndex: 62,
      commentary: "Base case assumes HBM absorbs leading-edge DRAM capacity while NAND remains a lower-quality swing factor.",
    },
    {
      year: 2027,
      sourceStatus: "forecast_assumption",
      cyclePhase: "HBM capacity ramp",
      dramBitGrowth: 0.16,
      nandBitGrowth: 0.13,
      hbmRevenueMix: 0.23,
      revenue: 56000,
      grossMargin: 0.5,
      operatingMargin: 0.36,
      fcfMargin: 0.18,
      capexIntensity: 0.4,
      demandIndex: 88,
      supplyRiskIndex: 70,
      commentary: "Highest upside year if AI accelerator demand and customer qualifications support premium pricing.",
    },
    {
      year: 2028,
      sourceStatus: "forecast_assumption",
      cyclePhase: "Supply catch-up",
      dramBitGrowth: 0.13,
      nandBitGrowth: 0.14,
      hbmRevenueMix: 0.25,
      revenue: 59000,
      grossMargin: 0.46,
      operatingMargin: 0.31,
      fcfMargin: 0.15,
      capexIntensity: 0.37,
      demandIndex: 76,
      supplyRiskIndex: 78,
      commentary: "Model fades margin as supply response arrives; HBM mix rises but pricing power normalizes.",
    },
    {
      year: 2029,
      sourceStatus: "forecast_assumption",
      cyclePhase: "Cycle normalization",
      dramBitGrowth: 0.1,
      nandBitGrowth: 0.12,
      hbmRevenueMix: 0.27,
      revenue: 62000,
      grossMargin: 0.43,
      operatingMargin: 0.28,
      fcfMargin: 0.14,
      capexIntensity: 0.34,
      demandIndex: 70,
      supplyRiskIndex: 66,
      commentary: "Through-cycle case assumes AI mix persists, but commodity memory pricing stops expanding.",
    },
    {
      year: 2030,
      sourceStatus: "forecast_assumption",
      cyclePhase: "Through-cycle AI mix",
      dramBitGrowth: 0.11,
      nandBitGrowth: 0.11,
      hbmRevenueMix: 0.3,
      revenue: 68000,
      grossMargin: 0.45,
      operatingMargin: 0.3,
      fcfMargin: 0.16,
      capexIntensity: 0.31,
      demandIndex: 74,
      supplyRiskIndex: 55,
      commentary: "Longer-run model assumes HBM becomes a durable mix layer, not a permanent peak-margin state.",
    },
  ],
  researchQuestions: [
    {
      key: "hbm",
      question: "Is HBM a durable structural mix shift or a cyclical super-cycle?",
      currentView: "The model values MU on normalized revenue, FCF and EBIT rather than latest-quarter EPS alone.",
      evidenceNeeded: "HBM capacity, qualification status, contract duration, pricing resets, competitor capacity additions and AI server unit growth.",
    },
    {
      key: "memory-cycle",
      question: "Where are DRAM and NAND in the cycle?",
      currentView: "Cycle haircut is explicit so the base case can fade margins instead of assuming peak profitability persists.",
      evidenceNeeded: "Channel inventory, spot/contract pricing, utilization, bit growth and capex guidance.",
    },
    {
      key: "fcf",
      question: "Can FCF convert through the capex cycle?",
      currentView: "High gross margin does not automatically mean high FCF because HBM and node transitions consume capital.",
      evidenceNeeded: "Capex intensity, working capital, HBM equipment requirements and depreciation cadence.",
    },
    {
      key: "china",
      question: "How large is China/export-control risk?",
      currentView: "The framework uses a separate China haircut so geopolitical risk is visible.",
      evidenceNeeded: "China customer mix, export-control scope, license treatment and customer inventory reactions.",
    },
  ],
  sourceGaps: [
    "HBM mix, DRAM/NAND pricing and customer qualification data are research-only until official tables or transcript extractions are added.",
    "MU historical valuation rows are local research snapshots; no SQLite persistence or daily-price backtest is registered yet.",
    "The Stooq market price snapshot should be cross-checked before IC use because market-data vendors can differ on adjusted prices.",
  ],
};
