import type { MuDataset } from "./model";

export const muDataset: MuDataset = {
  ticker: "MU",
  companyName: "Micron Technology, Inc.",
  currency: "USD",
  latestReportingPeriod: "Q2 FY2026",
  marketData: {
    currentPrice: 678.83,
    priceDate: "2026-05-19",
    sharesForMarketCap: 1142,
    source: "SEC companyfacts for reported data; Nasdaq quote API primary price with Stooq close cross-check",
    sourceStatus: "market_data",
  },
  periods: [
    {
      id: "fy2023",
      label: "FY 2023",
      fiscalYear: 2023,
      periodType: "annual",
      asOfDate: "2023-09-27",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2023 / FY2023 10-K",
      revenue: 15540,
      grossProfit: -1416,
      grossMargin: -0.091,
      operatingIncome: -5745,
      operatingMargin: -0.37,
      netIncome: -5833,
      dilutedEps: -5.34,
      dilutedShares: 1093,
      operatingCashFlow: 1559,
      capex: 7676,
      freeCashFlow: -6117,
      notes: "Memory down-cycle trough; negative gross margin and FCF make peak/trough normalization more important than spot P/E.",
    },
    {
      id: "fy2024",
      label: "FY 2024",
      fiscalYear: 2024,
      periodType: "annual",
      asOfDate: "2024-09-26",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2024 / FY2024 10-K",
      revenue: 25111,
      grossProfit: 5613,
      grossMargin: 0.224,
      operatingIncome: 1304,
      operatingMargin: 0.052,
      netIncome: 778,
      dilutedEps: 0.7,
      dilutedShares: 1118,
      operatingCashFlow: 8507,
      capex: 8386,
      freeCashFlow: 121,
      notes: "Recovery year with margins turning positive while capex still absorbed most operating cash flow.",
    },
    {
      id: "fy2025",
      label: "FY 2025",
      fiscalYear: 2025,
      periodType: "annual",
      asOfDate: "2025-09-25",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2025 / FY2025 10-K",
      revenue: 37378,
      grossProfit: 14873,
      grossMargin: 0.398,
      operatingIncome: 9770,
      operatingMargin: 0.261,
      netIncome: 8539,
      dilutedEps: 7.59,
      dilutedShares: 1125,
      operatingCashFlow: 17525,
      capex: 15857,
      freeCashFlow: 1668,
      notes: "HBM and DRAM recovery lifted revenue and margins, but FCF remained capital-intensive.",
    },
    {
      id: "fy2026-q1",
      label: "Q1 FY2026",
      fiscalYear: 2026,
      fiscalQuarter: "Q1",
      periodType: "quarter",
      asOfDate: "2025-12-18",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2025Q4 / FY2026 Q1 10-Q",
      revenue: 13643,
      grossProfit: 7646,
      grossMargin: 0.56,
      operatingIncome: 6136,
      operatingMargin: 0.45,
      netIncome: 5240,
      dilutedEps: 4.6,
      dilutedShares: 1138,
      operatingCashFlow: 8411,
      capex: 5389,
      freeCashFlow: 3022,
      notes: "Quarterly margin and cash flow improved sharply as AI memory supply tightened.",
    },
    {
      id: "fy2026-q2",
      label: "Q2 FY2026",
      fiscalYear: 2026,
      fiscalQuarter: "Q2",
      periodType: "quarter",
      asOfDate: "2026-03-19",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2026Q1 / FY2026 Q2 10-Q",
      revenue: 23860,
      grossProfit: 17755,
      grossMargin: 0.744,
      operatingIncome: 16135,
      operatingMargin: 0.676,
      netIncome: 13785,
      dilutedEps: 12.07,
      dilutedShares: 1142,
      operatingCashFlow: 20314,
      capex: 11776,
      freeCashFlow: 8538,
      notes: "Latest reported period in SEC companyfacts; investors should check whether this reflects a super-cycle quarter before capitalizing it.",
    },
  ],
  operatingMetrics: [
    {
      periodId: "fy2023",
      asOfDate: "2023-09-27",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.15,
      dramCycleSignal: -0.7,
      nandCycleSignal: -0.6,
      capexIntensity: 0.494,
      aiServerExposureCommentary: "AI memory was not yet enough to offset the broader DRAM/NAND downturn.",
      pricingCommentary: "Pricing pressure and inventory corrections dominated the income statement.",
      supplyDisciplineCommentary: "Supply discipline was the key recovery condition.",
      chinaRiskCommentary: "China exposure and export restrictions remained a structural risk item.",
    },
    {
      periodId: "fy2024",
      asOfDate: "2024-09-26",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.45,
      dramCycleSignal: 0.25,
      nandCycleSignal: 0.1,
      capexIntensity: 0.334,
      aiServerExposureCommentary: "HBM demand began to matter more for mix and pricing.",
      pricingCommentary: "Pricing recovered, but FCF still lagged because wafer and HBM investment stayed high.",
      supplyDisciplineCommentary: "Industry supply discipline improved versus the trough.",
      chinaRiskCommentary: "China restrictions remained a risk to shipment mix and customer access.",
    },
    {
      periodId: "fy2025",
      asOfDate: "2025-09-25",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.75,
      dramCycleSignal: 0.65,
      nandCycleSignal: 0.35,
      capexIntensity: 0.424,
      aiServerExposureCommentary: "AI server memory became the central bull case, especially HBM capacity and qualification cadence.",
      pricingCommentary: "Pricing power improved materially; underwriting risk is whether investors extrapolate peak margins.",
      supplyDisciplineCommentary: "Supply discipline looks better, but memory remains cyclical.",
      chinaRiskCommentary: "Export-control sensitivity needs a separate haircut rather than being buried inside multiples.",
    },
    {
      periodId: "fy2026-q2",
      asOfDate: "2026-03-19",
      sourceStatus: "research_only",
      hbmDemandSignal: 0.9,
      dramCycleSignal: 0.8,
      nandCycleSignal: 0.45,
      capexIntensity: 0.494,
      aiServerExposureCommentary: "Latest data supports a strong AI-memory upcycle; the question is durability of HBM mix and pricing.",
      pricingCommentary: "The valuation should stress a margin fade rather than capitalize one hot quarter.",
      supplyDisciplineCommentary: "Supply additions and customer qualification timing are the key watch items.",
      chinaRiskCommentary: "China and export controls can affect both demand and tool/supply-chain availability.",
    },
  ],
  researchQuestions: [
    {
      key: "hbm",
      question: "Is HBM a durable structural mix shift or a cyclical super-cycle?",
      currentView: "The model values MU on normalized revenue, FCF and EBIT rather than latest-quarter EPS alone.",
      evidenceNeeded: "HBM capacity, qualification status, contract duration, pricing resets, competitor capacity additions and AI server unit growth.",
    },
    {
      key: "memory-cycle",
      question: "Where are DRAM and NAND in the cycle?",
      currentView: "Cycle haircut is explicit so the base case can fade margins instead of assuming peak profitability persists.",
      evidenceNeeded: "Channel inventory, spot/contract pricing, utilization, bit growth and capex guidance.",
    },
    {
      key: "fcf",
      question: "Can FCF convert through the capex cycle?",
      currentView: "High gross margin does not automatically mean high FCF because HBM and node transitions consume capital.",
      evidenceNeeded: "Capex intensity, working capital, HBM equipment requirements and depreciation cadence.",
    },
    {
      key: "china",
      question: "How large is China/export-control risk?",
      currentView: "The framework uses a separate China haircut so geopolitical risk is visible.",
      evidenceNeeded: "China customer mix, export-control scope, license treatment and customer inventory reactions.",
    },
  ],
  sourceGaps: [
    "HBM mix, DRAM/NAND pricing and customer qualification data are research-only until official tables or transcript extractions are added.",
    "No MU backend SQLite workflow is registered yet; historical event-based valuation and daily-price backtests are deferred.",
    "The Stooq market price snapshot should be cross-checked before IC use because market-data vendors can differ on adjusted prices.",
  ],
};
