import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const avavDataset = createLocalDeepResearchDataset({
  ticker: "AVAV",
  companyName: "AeroVironment, Inc.",
  sector: "Defense Technology / Autonomous Systems / Loitering Munitions",
  archetype: "Defense autonomy compounder / drone warfare platform",
  description:
    "AVAV research cockpit focused on Switchblade demand, Ukraine/NATO replenishment, Replicator-style autonomy funding, BlueHalo integration risk, production scaling, gross margin durability, and whether drone warfare growth is already capitalized.",
  updatedAt: "2026-05-20",
  currentPrice: 160.23,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "switchblade-demand", label: "Switchblade / Demand" },
    { value: "orders-backlog", label: "Orders / Funded Backlog" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q3", label: "FY2026 Q3" },
    { value: "fy2026-q2", label: "FY2026 Q2" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "bookings-ytd", label: "FY2026 YTD Bookings ($m)", value: 2_100, format: "currency", description: "Company-disclosed firm orders entered into for the first nine months of FY2026.", badge: "Actual" },
    { key: "backlog-cover", label: "Funded Backlog Cover", value: 0.7, format: "multiple", description: "Latest funded backlog divided by annualized FY2026 Q3 revenue; this is a derived coverage check, not management guidance.", badge: "Derived" },
    { key: "prod-scale", label: "Execution / Conversion Risk", value: 0.22, format: "percent", description: "Risk haircut for shipment timing, working capital, supplier constraints and BlueHalo integration execution.", badge: "Assumption" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: 0.12, format: "percent", description: "Defense tech target margin once acquired programs scale.", badge: "Assumption" },
    { key: "base-gap", label: "Base Upside / Downside", value: -0.06, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "switchblade-duration",
      question: "Is Switchblade demand a multi-year NATO replenishment cycle or a wartime pull-forward?",
      currentView: "The bull case needs repeat replenishment and doctrine adoption, not one-off urgency orders.",
      metric: "Bookings, backlog duration, international orders",
      evidenceNeeded: "Contract timing, unit volume, customer mix and funded backlog conversion",
      valuationTie: "Revenue CAGR and exit multiple",
      bearCase: "Demand normalizes after conflict-driven replenishment and procurement cycles slow.",
    },
    {
      key: "bluehalo-integration",
      question: "Does BlueHalo expand the autonomy stack or dilute margins with integration risk?",
      currentView: "The acquisition can broaden directed energy, counter-UAS and autonomy exposure, but execution risk is real.",
      metric: "Organic growth bridge, gross margin, integration cost",
      evidenceNeeded: "Segment margin bridge, funded backlog quality and bookings scope after close",
      valuationTie: "Risk haircut and normalized FCF margin",
      bearCase: "Revenue growth rises but cash conversion and credibility fall.",
    },
    {
      key: "production-bottleneck",
      question: "Can AVAV turn demand into shipped units without working-capital drag?",
      currentView: "Production throughput and supplier reliability are the gating variables.",
      metric: "Revenue conversion, funded backlog, inventory turns, delivery cadence",
      evidenceNeeded: "Plant capacity, supplier lead times, funded backlog conversion and working-capital build",
      valuationTie: "FCF margin and discount rate",
      bearCase: "Backlog grows but shipments and cash lag.",
    },
    {
      key: "platform-multiple",
      question: "Should AVAV trade like a defense prime supplier or a scarce autonomy platform?",
      currentView: "Premium multiple is justified only if software/autonomy content and repeat demand become visible.",
      metric: "Recurring support, software content, program diversity",
      evidenceNeeded: "Mix disclosure and customer concentration",
      valuationTie: "Quality adjustment and revenue multiple cross-check",
      bearCase: "Hardware-heavy mix compresses toward defense supplier multiples.",
    },
  ],
  kpiSeries: [
    {
      key: "orders-backlog",
      title: "Revenue, Bookings and Funded Backlog",
      subtitle: "Company-disclosed revenue and funded backlog. Bookings are shown only where AVAV disclosed a quarterly, fiscal-year or fiscal-YTD figure.",
      leftAxisLabel: "$m",
      rightAxisLabel: "Book-to-bill",
      sourceStatus: "official_actual",
      measures: [
        { key: "revenue", label: "Revenue ($m)", format: "currency", chartType: "bar", color: "#38bdf8", axis: "left" },
        { key: "fundedBacklog", label: "Funded backlog ($m)", format: "currency", chartType: "bar", color: "#a78bfa", axis: "left" },
        { key: "bookingsDisclosed", label: "Bookings disclosed ($m)", format: "currency", chartType: "bar", color: "#fbbf24", axis: "left" },
        { key: "bookToBill", label: "Book-to-bill", format: "multiple", chartType: "line", color: "#5eead4", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q3", revenue: 186.6, fundedBacklog: 462.8 },
        { period: "FY2024 Q4", revenue: 197.0, fundedBacklog: 400.2 },
        { period: "FY2025 Q1", revenue: 189.5, fundedBacklog: 372.9 },
        { period: "FY2025 Q2", revenue: 188.5, fundedBacklog: 467.1 },
        { period: "FY2025 Q3", revenue: 167.6, fundedBacklog: 763.5 },
        { period: "FY2025 Q4", revenue: 275.1, fundedBacklog: 726.6, bookingsDisclosed: 1_200, bookToBill: 1.46 },
        { period: "FY2026 Q1", revenue: 454.7, fundedBacklog: 1_100, bookingsDisclosed: 399.0, bookToBill: 0.88 },
        { period: "FY2026 Q2", revenue: 472.5, fundedBacklog: 1_100, bookingsDisclosed: 1_400, bookToBill: 2.9 },
        { period: "FY2026 Q3", revenue: 408.0, fundedBacklog: 1_100, bookingsDisclosed: 2_100, bookToBill: 1.6 },
      ],
    },
    {
      key: "switchblade-demand",
      title: "Switchblade Demand and Manufacturing Readiness Framework",
      subtitle: "Research-only view kept separate from official funded backlog so execution assumptions do not masquerade as reported backlog.",
      sourceStatus: "research_only",
      measures: [
        { key: "demandIndex", label: "Demand index", format: "number", chartType: "bar", color: "#64748b", axis: "left" },
        { key: "productionReadiness", label: "Production readiness %", format: "percent", chartType: "line", color: "#67e8f9", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q1", demandIndex: 84, productionReadiness: 0.58 },
        { period: "FY2024 Q2", demandIndex: 91, productionReadiness: 0.61 },
        { period: "FY2024 Q3", demandIndex: 108, productionReadiness: 0.64 },
        { period: "FY2024 Q4", demandIndex: 122, productionReadiness: 0.68 },
        { period: "FY2025 Q1", demandIndex: 128, productionReadiness: 0.71 },
        { period: "FY2025 Q2", demandIndex: 136, productionReadiness: 0.74 },
        { period: "FY2025 Q3", demandIndex: 149, productionReadiness: 0.77 },
        { period: "FY2025 Q4", demandIndex: 156, productionReadiness: 0.8 },
        { period: "FY2026 Q1", demandIndex: 164, productionReadiness: 0.82 },
        { period: "FY2026 Q2", demandIndex: 171, productionReadiness: 0.84 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "switchblade-demand",
      tab: "switchblade-demand",
      title: "Switchblade / Loitering Munition Cycle",
      thesis: "AVAV's durability depends on whether loitering munitions become a standing procurement category rather than a conflict-specific surge.",
      evidence: ["International replenishment orders", "DoD budget line-item durability", "Unit cost and production cadence"],
      watchItems: ["Order lumpiness", "Alternative drone suppliers", "Export-control delays"],
      sourceStatus: "research_only",
    },
    {
      key: "orders-backlog",
      tab: "orders-backlog",
      title: "Orders, Funded Backlog and Revenue Conversion",
      thesis: "The key debate is no longer whether demand exists; it is whether funded backlog and disclosed bookings convert into revenue, margin and cash without BlueHalo integration drag.",
      evidence: ["FY2026 YTD bookings", "Funded backlog", "Book-to-bill", "Revenue conversion", "Gross margin bridge"],
      watchItems: ["YTD bookings versus quarterly bookings", "Working-capital build", "Supplier bottlenecks", "Integration charges"],
      sourceStatus: "official_actual",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q3", eventDate: "2026-03-10", headline: "YTD orders strong, but Space impairment and revenue timing add execution risk", keyQuestions: ["How much of $2.1bn YTD bookings converts in FY2027?", "What portion of $1.1bn funded backlog is AxS versus SCDE?", "Can margins recover after goodwill/intangible pressure?"], managementTone: "Demand confident; execution caveats around Space timing.", modelReadThrough: "Keep growth optionality, but increase attention to conversion quality and BlueHalo integration risk.", riskSignal: "Inflecting", sourceStatus: "official_actual" },
    { quarter: "FY2026 Q2", eventDate: "2025-12-09", headline: "Bookings spike and funded backlog reset after BlueHalo", keyQuestions: ["Is $1.4bn bookings mostly long-cycle or near-term revenue?", "Does 2.9x book-to-bill translate into FY2027 growth?", "Are production lead times improving?"], managementTone: "Growth-oriented and confident.", modelReadThrough: "Revenue growth visibility improves; cash conversion still needs proof.", riskSignal: "Positive", sourceStatus: "official_actual" },
    { quarter: "FY2026 Q1", eventDate: "2025-09-09", headline: "Funded backlog reaches $1.1bn after acquisition close", keyQuestions: ["How durable is the initial BlueHalo backlog uplift?", "Are orders international or mostly U.S.?", "Is gross margin recovering?"], managementTone: "Demand confident.", modelReadThrough: "Revenue multiple can stay elevated only with shipment proof.", riskSignal: "Neutral", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q4", eventDate: "2025-06-24", headline: "Record revenue, FY bookings and acquisition debate", keyQuestions: ["Does BlueHalo broaden software content?", "What are integration costs?", "Is funded backlog quality improving?"], managementTone: "Strategic expansion.", modelReadThrough: "Raise TAM narrative; do not raise FCF margin yet.", riskSignal: "Needs Review", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q3", eventDate: "2025-03-04", headline: "Record funded backlog but shipment disruption", keyQuestions: ["Is demand recurring?", "Are NATO customers scaling?", "Can production absorb demand after weather disruption?"], managementTone: "Constructive with operational caveat.", modelReadThrough: "Supports high revenue CAGR but not terminal margin.", riskSignal: "Positive", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q2", eventDate: "2024-12-04", headline: "Backlog rebuild and working capital", keyQuestions: ["Does inventory build precede shipments?", "Any contract timing slippage?", "Are margins mix-pressured?"], managementTone: "Balanced.", modelReadThrough: "Maintain conservative cash conversion.", riskSignal: "Neutral", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q1", eventDate: "2024-09-04", headline: "Initial funding versus full program ceiling", keyQuestions: ["How much funded backlog excludes future IDIQ funding?", "Can gross margin hold?", "Any export delays?"], managementTone: "Positive on demand.", modelReadThrough: "Demand improves, execution still gating.", riskSignal: "Positive", sourceStatus: "official_actual" },
    { quarter: "FY2024 Q4", eventDate: "2024-06-26", headline: "Growth scarcity versus funded backlog visibility", keyQuestions: ["Is the multiple outrunning backlog?", "Are international orders broadening?", "What is cash conversion?"], managementTone: "Optimistic.", modelReadThrough: "Increase quality adjustment only with cash proof.", riskSignal: "Neutral", sourceStatus: "official_actual" },
    { quarter: "FY2024 Q3", eventDate: "2024-03-04", headline: "Category adoption early evidence", keyQuestions: ["Are Switchblade orders repeat?", "Any production constraints?", "Is mix improving?"], managementTone: "Encouraging.", modelReadThrough: "Early positive signal; keep local valuation conservative.", riskSignal: "Positive", sourceStatus: "official_actual" },
  ],
  historicalValuations: [
    { eventDate: "2024-03-04", fiscalPeriod: "FY2024 Q3", asOfPrice: 128, fairValue: 110, method: "Backlog and production-capacity local fallback." },
    { eventDate: "2024-06-26", fiscalPeriod: "FY2024 Q4", asOfPrice: 182, fairValue: 124, method: "Defense autonomy premium audited against cash conversion." },
    { eventDate: "2024-09-04", fiscalPeriod: "FY2025 Q1", asOfPrice: 188, fairValue: 130, method: "Demand visibility improved, production risk retained." },
    { eventDate: "2024-12-03", fiscalPeriod: "FY2025 Q2", asOfPrice: 194, fairValue: 136, method: "Backlog conversion and working-capital bridge." },
    { eventDate: "2025-03-04", fiscalPeriod: "FY2025 Q3", asOfPrice: 171, fairValue: 143, method: "Loitering munition category adoption case." },
    { eventDate: "2025-06-24", fiscalPeriod: "FY2025 Q4", asOfPrice: 198, fairValue: 148, method: "Acquisition TAM uplift with integration haircut." },
    { eventDate: "2025-09-03", fiscalPeriod: "FY2026 Q1", asOfPrice: 182, fairValue: 152, method: "Bookings durability plus shipment proof." },
    { eventDate: "2026-03-04", fiscalPeriod: "FY2026 Q2", asOfPrice: 165, fairValue: 150, method: "Base DCF / FCF multiple local run." },
  ],
  valuationBase: {
    revenueBase: 820,
    revenueCagr3Y: 0.19,
    terminalGrowth: 0.035,
    normalizedFcfMargin: 0.12,
    exitFcfMultiple: 32,
    evRevenueMultiple: 7.5,
    discountRate: 0.105,
    netCashDebt: -200,
    dilutedShares: 50,
    qualityAdjustment: 1.05,
    riskHaircut: 0.2,
    dividendYield: 0,
    buybackYield: 0,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.08, normalizedFcfMargin: 0.07, exitFcfMultiple: 20, evRevenueMultiple: 4.2, riskHaircut: 0.34, qualityAdjustment: 0.9 },
    Base: {},
    Bull: { revenueCagr3Y: 0.28, normalizedFcfMargin: 0.16, exitFcfMultiple: 42, evRevenueMultiple: 10.5, riskHaircut: 0.12, qualityAdjustment: 1.14 },
  },
  valuationDescription: "Blends DCF, forward FCF multiple and EV/revenue cross-check for a high-growth defense autonomy supplier.",
  risks: [
    { title: "War-demand pull-forward", detail: "Drone demand may be a temporary replenishment cycle rather than a durable procurement category.", severity: "high", killSignal: "Bookings slow while backlog conversion remains weak." },
    { title: "Integration and production risk", detail: "Acquisition integration, supplier bottlenecks and manufacturing scale can delay cash conversion.", severity: "high", killSignal: "Gross margin and FCF both miss despite revenue growth." },
    { title: "Competition and commoditization", detail: "Lower-cost drones and alternative suppliers can compress hardware economics.", severity: "medium", killSignal: "Average selling price or margin falls while units rise." },
  ],
  monitoring: ["Bookings scope and book-to-bill", "Funded backlog conversion", "Gross margin bridge", "Inventory and working capital", "International customer mix"],
  sourceGaps: ["AVAV discloses funded backlog and bookings, not unit-level production backlog or program-by-program shipment cadence.", "BlueHalo pro-forma financials and segment-level backlog mix need manual filing review.", "Daily price bars and persisted valuation runs still need backend refresh before production handoff."],
  backendDetail: "AVAV is wired to the unified backend; the frontend now uses official local revenue, bookings and funded-backlog rows while persisted backend valuation runs remain the next refresh step.",
  backendNextSteps: [
    "Import AVAV daily prices and SPY benchmark bars.",
    "Persist event-specific valuation runs for FY2024 Q3 through FY2026 Q3.",
    "Add filing/transcript evidence fields for funded backlog, bookings scope and segment conversion.",
  ],
});
