import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const avavDataset = createLocalDeepResearchDataset({
  ticker: "AVAV",
  companyName: "AeroVironment, Inc.",
  sector: "Defense Technology / Autonomous Systems / Loitering Munitions",
  archetype: "Defense autonomy compounder / drone warfare platform",
  description:
    "AVAV research cockpit focused on Switchblade demand, Ukraine/NATO replenishment, Replicator-style autonomy funding, BlueHalo integration risk, production scaling, gross margin durability, and whether drone warfare growth is already capitalized.",
  updatedAt: "2026-05-20",
  currentPrice: 160.23,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "switchblade-demand", label: "Switchblade / Demand" },
    { value: "production-backlog", label: "Production / Backlog" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q3", label: "FY2026 Q3" },
    { value: "fy2026-q2", label: "FY2026 Q2" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "orders-index", label: "Bookings Momentum", value: 1.32, format: "number", description: "Research index for loitering munition and autonomous systems demand.", badge: "Assumption" },
    { key: "backlog-cover", label: "Backlog Cover", value: 1.4, format: "multiple", description: "Approximate revenue coverage framework; needs official backlog import.", badge: "Placeholder" },
    { key: "prod-scale", label: "Production Scale Risk", value: 0.22, format: "percent", description: "Risk haircut for ramp, supply chain and integration execution.", badge: "Assumption" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: 0.12, format: "percent", description: "Defense tech target margin once acquired programs scale.", badge: "Assumption" },
    { key: "base-gap", label: "Base Upside / Downside", value: -0.06, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "switchblade-duration",
      question: "Is Switchblade demand a multi-year NATO replenishment cycle or a wartime pull-forward?",
      currentView: "The bull case needs repeat replenishment and doctrine adoption, not one-off urgency orders.",
      metric: "Bookings, backlog duration, international orders",
      evidenceNeeded: "Contract timing, unit volume, customer mix and funded backlog conversion",
      valuationTie: "Revenue CAGR and exit multiple",
      bearCase: "Demand normalizes after conflict-driven replenishment and procurement cycles slow.",
    },
    {
      key: "bluehalo-integration",
      question: "Does BlueHalo expand the autonomy stack or dilute margins with integration risk?",
      currentView: "The acquisition can broaden directed energy, counter-UAS and autonomy exposure, but execution risk is real.",
      metric: "Organic growth bridge, gross margin, integration cost",
      evidenceNeeded: "Segment margin bridge and backlog quality after close",
      valuationTie: "Risk haircut and normalized FCF margin",
      bearCase: "Revenue growth rises but cash conversion and credibility fall.",
    },
    {
      key: "production-bottleneck",
      question: "Can AVAV turn demand into shipped units without working-capital drag?",
      currentView: "Production throughput and supplier reliability are the gating variables.",
      metric: "Inventory turns, delivery cadence, gross margin",
      evidenceNeeded: "Plant capacity, supplier lead times, working-capital build",
      valuationTie: "FCF margin and discount rate",
      bearCase: "Backlog grows but shipments and cash lag.",
    },
    {
      key: "platform-multiple",
      question: "Should AVAV trade like a defense prime supplier or a scarce autonomy platform?",
      currentView: "Premium multiple is justified only if software/autonomy content and repeat demand become visible.",
      metric: "Recurring support, software content, program diversity",
      evidenceNeeded: "Mix disclosure and customer concentration",
      valuationTie: "Quality adjustment and revenue multiple cross-check",
      bearCase: "Hardware-heavy mix compresses toward defense supplier multiples.",
    },
  ],
  kpiSeries: [
    {
      key: "switchblade-demand",
      title: "Loitering Munition Demand vs Production Scale",
      subtitle: "AVAV needs order visibility to translate into shipped volume and cash conversion.",
      sourceStatus: "research_only",
      measures: [
        { key: "demandIndex", label: "Demand index", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "productionReadiness", label: "Production readiness %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q1", demandIndex: 84, productionReadiness: 0.58 },
        { period: "FY2024 Q2", demandIndex: 91, productionReadiness: 0.61 },
        { period: "FY2024 Q3", demandIndex: 108, productionReadiness: 0.64 },
        { period: "FY2024 Q4", demandIndex: 122, productionReadiness: 0.68 },
        { period: "FY2025 Q1", demandIndex: 128, productionReadiness: 0.71 },
        { period: "FY2025 Q2", demandIndex: 136, productionReadiness: 0.74 },
        { period: "FY2025 Q3", demandIndex: 149, productionReadiness: 0.77 },
        { period: "FY2025 Q4", demandIndex: 156, productionReadiness: 0.8 },
        { period: "FY2026 Q1", demandIndex: 164, productionReadiness: 0.82 },
        { period: "FY2026 Q2", demandIndex: 171, productionReadiness: 0.84 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "switchblade-demand",
      tab: "switchblade-demand",
      title: "Switchblade / Loitering Munition Cycle",
      thesis: "AVAV's durability depends on whether loitering munitions become a standing procurement category rather than a conflict-specific surge.",
      evidence: ["International replenishment orders", "DoD budget line-item durability", "Unit cost and production cadence"],
      watchItems: ["Order lumpiness", "Alternative drone suppliers", "Export-control delays"],
      sourceStatus: "research_only",
    },
    {
      key: "production-backlog",
      tab: "production-backlog",
      title: "Backlog Conversion and Production Discipline",
      thesis: "The market will forgive a premium multiple only if backlog converts into shipments, margin and cash.",
      evidence: ["Book-to-bill", "Inventory days", "Gross margin bridge", "BlueHalo synergy delivery"],
      watchItems: ["Working-capital build", "Supplier bottlenecks", "Integration charges"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q2", eventDate: "2026-03-04", headline: "Drone demand visibility after acquisition integration", keyQuestions: ["How much backlog is funded?", "Is BlueHalo accretive to margin?", "Are production lead times improving?"], managementTone: "Growth-oriented but integration-sensitive.", modelReadThrough: "Keep revenue growth high but hold risk haircut until cash conversion improves.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2026 Q1", eventDate: "2025-09-03", headline: "Bookings durability versus production throughput", keyQuestions: ["Are orders international or mostly U.S.?", "What is delivery cadence?", "Is gross margin recovering?"], managementTone: "Demand confident.", modelReadThrough: "Revenue multiple can stay elevated only with shipment proof.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2025-06-24", headline: "Acquisition and autonomy stack debate", keyQuestions: ["Does acquisition broaden software content?", "What are integration costs?", "Is backlog quality improving?"], managementTone: "Strategic expansion.", modelReadThrough: "Raise TAM narrative; do not raise FCF margin yet.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-03-04", headline: "Loitering munitions as category", keyQuestions: ["Is demand recurring?", "Are NATO customers scaling?", "Can production absorb demand?"], managementTone: "Constructive.", modelReadThrough: "Supports high revenue CAGR but not terminal margin.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2024-12-03", headline: "Backlog and working capital", keyQuestions: ["Does inventory build precede shipments?", "Any contract timing slippage?", "Are margins mix-pressured?"], managementTone: "Balanced.", modelReadThrough: "Maintain conservative cash conversion.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2024-09-04", headline: "Defense demand signal check", keyQuestions: ["How much is funded backlog?", "Can gross margin hold?", "Any export delays?"], managementTone: "Positive on demand.", modelReadThrough: "Demand improves, execution still gating.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2024-06-26", headline: "Growth scarcity versus valuation", keyQuestions: ["Is the multiple outrunning backlog?", "Are international orders broadening?", "What is cash conversion?"], managementTone: "Optimistic.", modelReadThrough: "Increase quality adjustment only with cash proof.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-03-04", headline: "Category adoption early evidence", keyQuestions: ["Are Switchblade orders repeat?", "Any production constraints?", "Is mix improving?"], managementTone: "Encouraging.", modelReadThrough: "Early positive signal; keep local valuation conservative.", riskSignal: "Positive", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-03-04", fiscalPeriod: "FY2024 Q3", asOfPrice: 128, fairValue: 110, method: "Backlog and production-capacity local fallback." },
    { eventDate: "2024-06-26", fiscalPeriod: "FY2024 Q4", asOfPrice: 182, fairValue: 124, method: "Defense autonomy premium audited against cash conversion." },
    { eventDate: "2024-09-04", fiscalPeriod: "FY2025 Q1", asOfPrice: 188, fairValue: 130, method: "Demand visibility improved, production risk retained." },
    { eventDate: "2024-12-03", fiscalPeriod: "FY2025 Q2", asOfPrice: 194, fairValue: 136, method: "Backlog conversion and working-capital bridge." },
    { eventDate: "2025-03-04", fiscalPeriod: "FY2025 Q3", asOfPrice: 171, fairValue: 143, method: "Loitering munition category adoption case." },
    { eventDate: "2025-06-24", fiscalPeriod: "FY2025 Q4", asOfPrice: 198, fairValue: 148, method: "Acquisition TAM uplift with integration haircut." },
    { eventDate: "2025-09-03", fiscalPeriod: "FY2026 Q1", asOfPrice: 182, fairValue: 152, method: "Bookings durability plus shipment proof." },
    { eventDate: "2026-03-04", fiscalPeriod: "FY2026 Q2", asOfPrice: 165, fairValue: 150, method: "Base DCF / FCF multiple local run." },
  ],
  valuationBase: {
    revenueBase: 820,
    revenueCagr3Y: 0.19,
    terminalGrowth: 0.035,
    normalizedFcfMargin: 0.12,
    exitFcfMultiple: 32,
    evRevenueMultiple: 7.5,
    discountRate: 0.105,
    netCashDebt: -200,
    dilutedShares: 50,
    qualityAdjustment: 1.05,
    riskHaircut: 0.2,
    dividendYield: 0,
    buybackYield: 0,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.08, normalizedFcfMargin: 0.07, exitFcfMultiple: 20, evRevenueMultiple: 4.2, riskHaircut: 0.34, qualityAdjustment: 0.9 },
    Base: {},
    Bull: { revenueCagr3Y: 0.28, normalizedFcfMargin: 0.16, exitFcfMultiple: 42, evRevenueMultiple: 10.5, riskHaircut: 0.12, qualityAdjustment: 1.14 },
  },
  valuationDescription: "Blends DCF, forward FCF multiple and EV/revenue cross-check for a high-growth defense autonomy supplier.",
  risks: [
    { title: "War-demand pull-forward", detail: "Drone demand may be a temporary replenishment cycle rather than a durable procurement category.", severity: "high", killSignal: "Bookings slow while backlog conversion remains weak." },
    { title: "Integration and production risk", detail: "Acquisition integration, supplier bottlenecks and manufacturing scale can delay cash conversion.", severity: "high", killSignal: "Gross margin and FCF both miss despite revenue growth." },
    { title: "Competition and commoditization", detail: "Lower-cost drones and alternative suppliers can compress hardware economics.", severity: "medium", killSignal: "Average selling price or margin falls while units rise." },
  ],
  monitoring: ["Bookings / book-to-bill", "Funded backlog duration", "Gross margin bridge", "Inventory and working capital", "International customer mix"],
  sourceGaps: ["Official backlog, segment margin and daily price bars need backend import.", "BlueHalo pro-forma financials need manual filing review."],
});
