import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const unhDataset = createLocalDeepResearchDataset({
  ticker: "UNH",
  companyName: "UnitedHealth Group Incorporated",
  sector: "Managed Care / Healthcare Services / Optum",
  archetype: "Managed-care platform / Optum services compounder / regulatory risk discount",
  description:
    "UNH research cockpit focused on medical cost trend, Medicare Advantage repricing and membership quality, Optum Health risk-based care, OptumRx/PBM regulation, Change Healthcare execution, cash conversion, capital return, and whether the managed-care premium multiple should normalize or recover.",
  updatedAt: "2026-05-21",
  currentPrice: 389,
  priceDate: "2026-05-20",
  marketDataSource: "Manual market snapshot proxy; backend daily price bars are imported separately for historical valuation and backtest.",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "medical-cost", label: "Medical Cost Trend" },
    { value: "medicare-advantage", label: "Medicare Advantage" },
    { value: "optum", label: "Optum Unit Economics" },
    { value: "pbm-regulation", label: "PBM / Policy" },
    { value: "capital-return", label: "Cash / Capital" },
    { value: "earnings-questions", label: "Call Attention" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "q1-2026-mcr", label: "Q1 2026 MCR", value: 0.839, format: "percent", description: "Official Q1 2026 medical care ratio, down from Q1 2025, but still needs confirmation outside one quarter.", badge: "Actual" },
    { key: "uhc-margin", label: "UHC Op Margin", value: 0.066, format: "percent", description: "UnitedHealthcare Q1 2026 operating margin after repricing across lines of business.", badge: "Actual" },
    { key: "ma-attrition", label: "Senior Lives Change", value: -965, format: "number", description: "Q1 2026 Medicare Advantage / complex-population senior lives change in thousands; tests adverse-selection risk.", badge: "Actual" },
    { key: "optum-margin", label: "Optum Margin", value: 0.052, format: "percent", description: "Q1 2026 Optum operating margin; the platform thesis depends on recovery in Health, Insight and Rx quality.", badge: "Actual" },
    { key: "debt-capital", label: "Debt / Capital", value: 0.429, format: "percent", description: "Q1 2026 debt-to-capital ratio, with management targeting roughly 40% later in 2026.", badge: "Actual" },
  ],
  researchQuestions: [
    {
      key: "medical-cost-cycle",
      question: "Is the 2026 MCR improvement a real pricing catch-up or a reserve/timing quarter?",
      currentView: "The buy-side question is not whether Q1 improved; it is whether repricing can hold while elevated utilization and unit cost trend persist through the 2027 bid cycle.",
      metric: "MCR, days claims payable, reserve development, outpatient/senior utilization, commercial renewal yield",
      evidenceNeeded: "Quarterly MCR bridge, DCP movement, reserve commentary, commercial renewal pricing and utilization by service category",
      valuationTie: "Normalized FCF margin, WACC and near-term risk haircut",
      bearCase: "MCR normalizes for one quarter but re-accelerates as reserve benefits fade and utilization remains structurally higher.",
    },
    {
      key: "ma-durability",
      question: "Is Medicare Advantage attrition a healthy margin reset or adverse selection?",
      currentView: "A smaller MA book can be good if UNH exits underpriced lives, but it is dangerous if healthier seniors churn while high-acuity members remain.",
      metric: "Senior lives, MA bid pricing, benefit richness, STAR/risk-adjustment friction, risk-adjusted margin per member",
      evidenceNeeded: "MA membership cohort disclosure, bid-cycle benefit changes, competitor exits, RAF/STAR updates and senior utilization trend",
      valuationTie: "Revenue CAGR, quality adjustment and exit multiple",
      bearCase: "UNH reprices into a shrinking, higher-acuity MA base and loses the historical managed-care premium.",
    },
    {
      key: "optum-platform",
      question: "Which Optum profit pool is durable: Health risk-bearing care, Rx scale, or Insight workflow/data?",
      currentView: "Optum still differentiates UNH, but the analysis must separate care-delivery medical cost drag, Rx volume attrition and Insight investment/cyber normalization.",
      metric: "Optum Health margin, value-based lives, OptumRx adjusted scripts, specialty growth, Optum Insight backlog/margin",
      evidenceNeeded: "Segment revenue/margin bridge, value-based care membership, Rx adjusted scripts, Insight backlog and Change Healthcare recovery milestones",
      valuationTie: "SOTP quality adjustment, EV/revenue cross-check and FCF conversion",
      bearCase: "Optum growth becomes low-quality because Health absorbs medical cost pressure, Rx faces policy pressure and Insight margins stay below history.",
    },
    {
      key: "pbm-regulation",
      question: "Does PBM scrutiny hit disclosure, rebate mechanics, spread economics, or vertical integration itself?",
      currentView: "PBM risk is the multiple governor. A mild disclosure outcome is manageable; a structural rebate/spread or affiliated-pharmacy remedy changes OptumRx economics.",
      metric: "OptumRx adjusted scripts, specialty mix, margin, FTC/DOJ/state activity, employer retention",
      evidenceNeeded: "PBM contract economics, rebate/pass-through exposure, FTC/DOJ milestones, client renewal language and specialty-pharmacy channel mix",
      valuationTie: "Risk haircut, exit multiple and Optum SOTP value",
      bearCase: "Policy changes compress OptumRx economics while self-preferencing headlines keep the market from paying for Optum integration.",
    },
    {
      key: "cash-capital",
      question: "Can UNH fund remediation, debt reduction, dividends and buybacks without weakening regulated-capital flexibility?",
      currentView: "The capital-return debate has shifted from automatic buyback compounding to balance-sheet repair plus proof that cash conversion survives medical-cost and cyber/settlement friction.",
      metric: "CFO/net income, debt-to-capital, dividends, buybacks, regulated subsidiary dividends",
      evidenceNeeded: "Cash conversion, debt-to-capital path, share repurchase pace, litigation/cyber cash costs and subsidiary capital requirements",
      valuationTie: "FCF yield, buyback yield and downside liquidity haircut",
      bearCase: "Capital return remains constrained because cash goes to debt repair, remediation, legal costs and higher statutory capital buffers.",
    },
  ],
  kpiSeries: [
    {
      key: "medical-cost",
      title: "MCR, Claims Timing and Pricing Catch-Up",
      subtitle: "This tab tests whether the MCR improvement is durable or just reserve/timing noise before utilization re-accelerates.",
      sourceStatus: "derived",
      measures: [
        { key: "mcr", label: "Medical care ratio", format: "percent", chartType: "bar", color: "#b91c1c", axis: "left" },
        { key: "pricingAdequacy", label: "Pricing adequacy score", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
        { key: "claimsTimingRisk", label: "Claims timing risk", format: "percent", chartType: "line", color: "#f97316", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", mcr: 0.843, pricingAdequacy: 0.57, claimsTimingRisk: 0.48 },
        { period: "2024 Q2", mcr: 0.851, pricingAdequacy: 0.55, claimsTimingRisk: 0.56 },
        { period: "2024 Q3", mcr: 0.852, pricingAdequacy: 0.54, claimsTimingRisk: 0.58 },
        { period: "2024 FY", mcr: 0.855, pricingAdequacy: 0.52, claimsTimingRisk: 0.61 },
        { period: "2025 Q1", mcr: 0.848, pricingAdequacy: 0.49, claimsTimingRisk: 0.70 },
        { period: "2025 Q4", mcr: 0.895, pricingAdequacy: 0.50, claimsTimingRisk: 0.78 },
        { period: "2026 Q1", mcr: 0.839, pricingAdequacy: 0.68, claimsTimingRisk: 0.52 },
        { period: "2026 H2e", mcr: 0.846, pricingAdequacy: 0.72, claimsTimingRisk: 0.49 },
      ],
    },
    {
      key: "medicare-advantage",
      title: "Medicare Advantage Attrition vs Margin Quality",
      subtitle: "The high-quality outcome is deliberate shrinkage with better margin quality; the low-quality outcome is adverse selection.",
      sourceStatus: "derived",
      measures: [
        { key: "seniorLivesChange", label: "Senior lives change (k)", format: "number", chartType: "bar", color: "#1f2937", axis: "left" },
        { key: "marginQuality", label: "Margin quality score", format: "percent", chartType: "line", color: "#ea580c", axis: "right" },
        { key: "benefitReset", label: "Benefit reset intensity", format: "percent", chartType: "line", color: "#7c3aed", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", seniorLivesChange: 180, marginQuality: 0.70, benefitReset: 0.25 },
        { period: "2024 Q2", seniorLivesChange: 130, marginQuality: 0.66, benefitReset: 0.34 },
        { period: "2024 Q3", seniorLivesChange: 70, marginQuality: 0.62, benefitReset: 0.43 },
        { period: "2024 Q4", seniorLivesChange: 20, marginQuality: 0.58, benefitReset: 0.52 },
        { period: "2025 Q1", seniorLivesChange: -120, marginQuality: 0.54, benefitReset: 0.65 },
        { period: "2025 Q4", seniorLivesChange: -580, marginQuality: 0.56, benefitReset: 0.82 },
        { period: "2026 Q1", seniorLivesChange: -965, marginQuality: 0.66, benefitReset: 0.88 },
        { period: "2026 H2e", seniorLivesChange: -250, marginQuality: 0.70, benefitReset: 0.75 },
      ],
    },
    {
      key: "optum",
      title: "Optum Profit Pool Quality Map",
      subtitle: "Optum must be analyzed as three different assets: care delivery, pharmacy scale and workflow/data.",
      sourceStatus: "derived",
      measures: [
        { key: "optumRevenue", label: "Optum revenue ($B)", format: "number", chartType: "bar", color: "#0f766e", axis: "left" },
        { key: "adjustedScripts", label: "Adjusted scripts (M)", format: "number", chartType: "bar", color: "#2563eb", axis: "left" },
        { key: "optumMargin", label: "Optum margin", format: "percent", chartType: "line", color: "#7c3aed", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", optumRevenue: 61.1, adjustedScripts: 405, optumMargin: 0.061 },
        { period: "2024 Q2", optumRevenue: 62.9, adjustedScripts: 409, optumMargin: 0.059 },
        { period: "2024 Q3", optumRevenue: 63.9, adjustedScripts: 412, optumMargin: 0.057 },
        { period: "2024 Q4", optumRevenue: 65.1, adjustedScripts: 415, optumMargin: 0.056 },
        { period: "2025 Q1", optumRevenue: 63.9, adjustedScripts: 408, optumMargin: 0.061 },
        { period: "2025 Q4", optumRevenue: 70.3, adjustedScripts: 394, optumMargin: 0.002 },
        { period: "2026 Q1", optumRevenue: 63.7, adjustedScripts: 383, optumMargin: 0.052 },
        { period: "2026 H2e", optumRevenue: 66.5, adjustedScripts: 388, optumMargin: 0.058 },
      ],
    },
    {
      key: "pbm-regulation",
      title: "OptumRx Scale vs PBM Policy Heat",
      subtitle: "A high script base is valuable only if specialty, rebate, spread and affiliated-pharmacy economics remain investable.",
      sourceStatus: "derived",
      measures: [
        { key: "adjustedScripts", label: "Adjusted scripts (M)", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "policyHeat", label: "PBM policy heat score", format: "percent", chartType: "line", color: "#dc2626", axis: "right" },
        { key: "specialtyMix", label: "Specialty mix proxy", format: "percent", chartType: "line", color: "#0d9488", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", adjustedScripts: 405, policyHeat: 0.46, specialtyMix: 0.35 },
        { period: "2024 Q2", adjustedScripts: 409, policyHeat: 0.52, specialtyMix: 0.36 },
        { period: "2024 Q3", adjustedScripts: 412, policyHeat: 0.70, specialtyMix: 0.37 },
        { period: "2024 Q4", adjustedScripts: 415, policyHeat: 0.76, specialtyMix: 0.38 },
        { period: "2025 Q1", adjustedScripts: 408, policyHeat: 0.80, specialtyMix: 0.39 },
        { period: "2025 Q4", adjustedScripts: 394, policyHeat: 0.84, specialtyMix: 0.41 },
        { period: "2026 Q1", adjustedScripts: 383, policyHeat: 0.82, specialtyMix: 0.42 },
        { period: "2026 H2e", adjustedScripts: 388, policyHeat: 0.78, specialtyMix: 0.43 },
      ],
    },
    {
      key: "capital-return",
      title: "Cash Conversion, Debt Repair and Buyback Capacity",
      subtitle: "The post-reset case needs cash conversion plus debt-to-capital progress before buybacks can again compound EPS.",
      sourceStatus: "derived",
      measures: [
        { key: "cfo", label: "CFO ($B)", format: "number", chartType: "bar", color: "#0f766e", axis: "left" },
        { key: "buybackCapacity", label: "Buyback capacity score", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
        { key: "debtCapital", label: "Debt-to-capital", format: "percent", chartType: "line", color: "#b91c1c", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", cfo: 6.7, buybackCapacity: 0.76, debtCapital: 0.425 },
        { period: "2024 Q2", cfo: 6.4, buybackCapacity: 0.70, debtCapital: 0.430 },
        { period: "2024 Q3", cfo: 5.9, buybackCapacity: 0.63, debtCapital: 0.438 },
        { period: "2024 Q4", cfo: 7.1, buybackCapacity: 0.58, debtCapital: 0.442 },
        { period: "2025 Q1", cfo: 6.5, buybackCapacity: 0.49, debtCapital: 0.446 },
        { period: "2025 Q4", cfo: 4.1, buybackCapacity: 0.30, debtCapital: 0.439 },
        { period: "2026 Q1", cfo: 8.9, buybackCapacity: 0.55, debtCapital: 0.429 },
        { period: "2026 H2e", cfo: 8.2, buybackCapacity: 0.64, debtCapital: 0.405 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "medical-cost",
      tab: "medical-cost",
      title: "MCR Bridge: Utilization, Unit Cost and Reserve Development",
      thesis: "The medical-cost tab now asks whether Q1 2026's lower MCR is durable. A clean answer requires separate proof from repricing, favorable reserve development, claims payment timing and actual service utilization.",
      evidence: ["Q1 2026 MCR of 83.9% versus 84.8% in Q1 2025", "Days claims payable and reserve development", "Commercial renewal pricing and MA benefit reset"],
      watchItems: ["Outpatient surgeries", "Senior acuity", "Pharmacy trend", "DCP moving with MCR", "Negative reserve development"],
      sourceStatus: "derived",
    },
    {
      key: "medical-cost-breakpoints",
      tab: "medical-cost",
      title: "Valuation Breakpoints for Claims Trend",
      thesis: "If normalized MCR is 84% to 85%, UNH can regain part of its premium multiple; if the sustainable band is closer to 86% to 87%, FCF margin and terminal multiple both need to reset lower.",
      evidence: ["MCR sensitivity in normalized FCF margin", "Price-to-earnings recovery needs lower claims volatility", "Management language on elevated utilization and unit cost"],
      watchItems: ["Two-quarter MCR trend", "Claims payable days", "Employer renewal pricing", "MA bid-cycle commentary"],
      sourceStatus: "research_only",
    },
    {
      key: "medicare-advantage",
      tab: "medicare-advantage",
      title: "MA Repricing vs Adverse Selection",
      thesis: "The MA page now focuses on membership quality, not headline lives. Q1 2026 senior attrition can be bullish if it reflects disciplined exits, or bearish if healthy members leave faster than high-cost cohorts.",
      evidence: ["Q1 2026 Medicare Advantage / complex-population senior lives down 965k", "Trend-driven repricing actions", "Benefit redesign and competitor exits"],
      watchItems: ["AEP retention", "2027 bids", "STAR quality", "risk adjustment audits", "high-acuity cohort retention"],
      sourceStatus: "derived",
    },
    {
      key: "ma-profit-pool",
      tab: "medicare-advantage",
      title: "MA Profit Pool After CMS Rate Pressure",
      thesis: "The investable MA question is how much profit survives CMS rate pressure, RADV/risk-adjustment friction and benefit richness cuts after competitors also reprice.",
      evidence: ["Senior lives by product", "Benefit reset intensity", "Risk-adjusted margin per member", "CMS rate and STAR impact"],
      watchItems: ["Competitor bid discipline", "CMS final rate notice", "RADV updates", "benefit richness by county"],
      sourceStatus: "research_only",
    },
    {
      key: "optum",
      tab: "optum",
      title: "Optum Unit Economics, Not Just Mix",
      thesis: "The Optum tab now splits Optum into Health, Rx and Insight. The segment can support a premium only if care delivery stops absorbing medical-cost pressure, Rx volume stabilizes and Insight margins recover after investment/cyber disruption.",
      evidence: ["Q1 2026 Optum revenue of $63.7B and operating margin of 5.2%", "OptumRx adjusted scripts of 383M", "Optum Health adjusted margin bridge"],
      watchItems: ["value-based-care membership", "Optum Health medical cost", "specialty pharmacy growth", "Insight technology investment", "Change Healthcare normalization"],
      sourceStatus: "derived",
    },
    {
      key: "optum-sotp",
      tab: "optum",
      title: "Optum SOTP Debate",
      thesis: "A single Optum multiple is too blunt. Health deserves a lower risk-bearing care multiple until margin recovery is proven; Rx deserves a policy discount; Insight deserves workflow/data optionality only after backlog and margin normalize.",
      evidence: ["Optum Health operating margin", "OptumRx script and specialty mix", "Optum Insight backlog and earnings bridge"],
      watchItems: ["segment margin disclosure", "standalone peer multiples", "provider group impairment risk", "regulatory remedy scope"],
      sourceStatus: "research_only",
    },
    {
      key: "pbm-regulation",
      tab: "pbm-regulation",
      title: "PBM Remedies: Disclosure vs Economics",
      thesis: "The PBM page now separates low-impact transparency remedies from high-impact changes to spread pricing, rebates, affiliated pharmacy steering and GPO fee economics.",
      evidence: ["FTC PBM inquiry and insulin complaint", "OptumRx adjusted script trend", "specialty mix and client retention"],
      watchItems: ["FTC/DOJ deadlines", "state PBM bills", "employer pass-through contracts", "affiliated pharmacy scrutiny"],
      sourceStatus: "derived",
    },
    {
      key: "pbm-policy-map",
      tab: "pbm-regulation",
      title: "Policy Heat Map for OptumRx",
      thesis: "The downside is not just headline noise. If policy changes target rebate/GPO fees or affiliated specialty economics, the impact moves from disclosure cost to SOTP impairment.",
      evidence: ["PBM concentration claims", "OptumRx listed in FTC actions", "script volume and specialty mix"],
      watchItems: ["rebate safe-harbor proposals", "GPO fee disclosures", "specialty pharmacy reimbursement", "client renewal language"],
      sourceStatus: "research_only",
    },
    {
      key: "capital-return",
      tab: "capital-return",
      title: "Cash Conversion and Balance-Sheet Repair",
      thesis: "The capital tab asks whether UNH can restore its compounding profile while debt-to-capital moves toward target and buybacks restart without starving remediation and regulated capital needs.",
      evidence: ["Q1 2026 cash flow from operations of $8.9B", "Q1 2026 debt-to-capital of 42.9%", "management expectation to repurchase at least $2B by Q2 2026"],
      watchItems: ["CFO/net income", "debt-to-capital", "buyback cadence", "litigation and cyber cash costs", "subsidiary dividends"],
      sourceStatus: "derived",
    },
    {
      key: "capital-downside",
      tab: "capital-return",
      title: "Capital Return Downside Case",
      thesis: "If MCR remains volatile and policy/legal cash costs rise, the historical EPS compounding playbook weakens because buybacks become discretionary rather than automatic.",
      evidence: ["debt-to-capital target", "share repurchase timing", "regulated-capital flexibility"],
      watchItems: ["credit rating language", "dividend growth", "repurchase authorization use", "settlement/cyber costs"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-15", headline: "MCR improved, but MA attrition and Optum margin quality remain the test", keyQuestions: ["Is the 83.9% MCR a durable repricing result or reserve/timing benefit?", "Does 965k senior lives attrition improve MA margin quality or signal adverse selection?", "Can Optum Health and OptumRx recover with fewer value-based lives and lower scripts?", "Does $8.9B CFO support debt repair plus at least $2B of repurchases?"], managementTone: "Recovery-focused; claims management and pricing language improved, but Optum margin and MA attrition still require proof.", modelReadThrough: "Raise pricing-catch-up score, keep PBM/Optum risk haircut, and watch whether debt-to-capital moves toward 40%.", riskSignal: "Inflecting", sourceStatus: "derived" },
    { quarter: "FY2025 Q4", eventDate: "2026-01-15", headline: "Reset quarter: claims, portfolio actions and capital discipline", keyQuestions: ["How much of weak Optum margin is restructuring versus true care-delivery economics?", "Are benefit resets enough to reprice MA without losing attractive members?", "Is PBM scrutiny changing client contract terms?", "Will buybacks stay muted until leverage and remediation costs settle?"], managementTone: "Resetting expectations and prioritizing balance-sheet credibility over near-term EPS optics.", modelReadThrough: "Lower near-term Optum margin, keep MA shrinkage as potentially constructive only if MCR improves.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-15", headline: "Utilization in line but policy heat stays high", keyQuestions: ["Are medical-cost trends stable enough for 2026 pricing?", "Is OptumRx volume weakness from UHC attrition or competitive loss?", "Are FTC/PBM headlines affecting employer retention?", "Is cash flow covering remediation and dividends comfortably?"], managementTone: "Cautious stabilization, with policy and Optum quality still limiting multiple recovery.", modelReadThrough: "Do not restore historical premium multiple until Optum Health and Rx quality data improve.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-15", headline: "Claims trend versus guide and 2026 bid credibility", keyQuestions: ["Are claims reserves adequate after utilization surprise?", "Do MA bids imply margin repair or enrollment sacrifice?", "Can Optum Health recover without more restructuring?", "How much capital return is delayed by debt and cyber/legal costs?"], managementTone: "Defensive; management needs to earn back confidence in claims forecasting.", modelReadThrough: "Cut normalized FCF margin, increase WACC/risk haircut, and use a lower exit multiple.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-15", headline: "MA pressure becomes the dominant stock debate", keyQuestions: ["Is MA medical cost above planned 2025 trend?", "Does pricing action create adverse-selection risk?", "Is Optum Health margin exposed to the same utilization trend?", "Are PBM and Change Healthcare risks compounding the discount?"], managementTone: "Defensive and credibility-repair oriented.", modelReadThrough: "Move from quality-compounder valuation to recovery valuation until MCR and Optum data prove otherwise.", riskSignal: "Negative", sourceStatus: "derived" },
    { quarter: "FY2024 Q4", eventDate: "2025-01-15", headline: "Full-year MCR reset and 2025 outlook framing", keyQuestions: ["Does 2024 MCR of 85.5% define a new normal?", "Can 2025 revenue outlook absorb MA/Medicaid mix headwinds?", "Is Optum revenue growth high quality?", "Does $32B-$33B CFO outlook leave room for buybacks?"], managementTone: "Constructive but with higher utilization and CMS pressure embedded.", modelReadThrough: "Lower premium multiple and make claims trend a primary valuation driver.", riskSignal: "Inflecting", sourceStatus: "official_actual" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-15", headline: "MCR pressure and policy risk enter the foreground", keyQuestions: ["Is the 85.2% Q3 MCR one-time or broad-based?", "Are MA margins below plan?", "Is FTC/PBM attention moving from headline risk to economics?", "Can Optum Insight normalize after disruption?"], managementTone: "Measured, but the market should start adding a managed-care risk discount.", modelReadThrough: "Begin haircutting normalized margin and OptumRx SOTP multiple.", riskSignal: "Inflecting", sourceStatus: "derived" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-15", headline: "Change Healthcare recovery and early MCR warning signs", keyQuestions: ["Is Change Healthcare disruption contained?", "Does Q2 MCR pressure reflect CMS rate cuts and reserves?", "Is Optum Insight backlog intact?", "Is capital return still resilient?"], managementTone: "Execution-focused, with cyber recovery and claims trend both under watch.", modelReadThrough: "Keep platform premium but add execution and claims timing haircut.", riskSignal: "Neutral", sourceStatus: "derived" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-15", fiscalPeriod: "FY2024 Q2", asOfPrice: 515, fairValue: 545, method: "Optum platform premium with early cyber execution haircut." },
    { eventDate: "2024-10-15", fiscalPeriod: "FY2024 Q3", asOfPrice: 570, fairValue: 560, method: "Utilization pressure begins to offset quality premium." },
    { eventDate: "2025-01-15", fiscalPeriod: "FY2024 Q4", asOfPrice: 510, fairValue: 525, method: "Pricing recovery case, lower premium multiple." },
    { eventDate: "2025-04-15", fiscalPeriod: "FY2025 Q1", asOfPrice: 440, fairValue: 455, method: "Medical-cost reset and Optum Health haircut." },
    { eventDate: "2025-07-15", fiscalPeriod: "FY2025 Q2", asOfPrice: 310, fairValue: 375, method: "Claims-cycle stress valuation with higher risk haircut." },
    { eventDate: "2025-10-15", fiscalPeriod: "FY2025 Q3", asOfPrice: 335, fairValue: 390, method: "Stabilization watch, still discounted for MCR uncertainty." },
    { eventDate: "2026-01-15", fiscalPeriod: "FY2025 Q4", asOfPrice: 370, fairValue: 410, method: "MA repricing and capital return recovery bridge." },
    { eventDate: "2026-04-15", fiscalPeriod: "FY2026 Q1", asOfPrice: 389, fairValue: 425, method: "Base recovery case: MCR normalizes gradually, Optum platform retains partial premium." },
  ],
  valuationBase: {
    revenueBase: 420000,
    revenueCagr3Y: 0.055,
    terminalGrowth: 0.025,
    normalizedFcfMargin: 0.065,
    exitFcfMultiple: 16,
    evRevenueMultiple: 1.05,
    discountRate: 0.095,
    netCashDebt: -72000,
    dilutedShares: 920,
    qualityAdjustment: 1.05,
    riskHaircut: 0.18,
    dividendYield: 0.022,
    buybackYield: 0.018,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.025, normalizedFcfMargin: 0.046, exitFcfMultiple: 12, evRevenueMultiple: 0.75, discountRate: 0.105, riskHaircut: 0.32, qualityAdjustment: 0.92, buybackYield: 0.005 },
    Base: {},
    Bull: { revenueCagr3Y: 0.07, normalizedFcfMargin: 0.078, exitFcfMultiple: 18, evRevenueMultiple: 1.25, discountRate: 0.0875, riskHaircut: 0.11, qualityAdjustment: 1.12, buybackYield: 0.025 },
  },
  valuationDescription: "Triangulates UNH through DCF, normalized FCF yield and revenue cross-check while explicitly penalizing medical-cost-cycle and PBM/regulatory uncertainty.",
  risks: [
    { title: "Medical cost trend stays structurally high", detail: "If claims trend remains above pricing, normalized margin and the managed-care multiple both compress.", severity: "high", killSignal: "MCR misses pricing assumptions for two more quarters." },
    { title: "Medicare Advantage adverse selection", detail: "Benefit resets can shrink profitable lives and retain high-cost cohorts.", severity: "high", killSignal: "MA lives fall while MCR fails to improve." },
    { title: "PBM / vertical integration regulation", detail: "Policy pressure can cap OptumRx economics and keep the multiple depressed.", severity: "high", killSignal: "Material PBM spread or rebate economics are restricted." },
    { title: "Optum execution and cyber remediation", detail: "Change Healthcare recovery and Optum Health margins must normalize for the platform thesis to work.", severity: "medium", killSignal: "Optum margin fails to recover despite revenue growth." },
  ],
  monitoring: ["Medical care ratio", "MA membership and benefit design", "Optum Health margin", "OptumRx retention", "PBM/FTC/DOJ updates", "FCF conversion", "Buybacks and debt leverage"],
  sourceGaps: [
    "Official UNH filings, earnings supplements and transcript ingestion are not yet imported into the backend.",
    "MCR, MA membership, Optum segment margin and PBM exposure rows are research proxies until source-backed ingestion is added.",
    "Healthcare-specific actuarial reserve triangulation is not yet modeled as a dedicated backend table.",
  ],
});
