import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const unhDataset = createLocalDeepResearchDataset({
  ticker: "UNH",
  companyName: "UnitedHealth Group Incorporated",
  sector: "Managed Care / Healthcare Services / Optum",
  archetype: "Managed-care platform / Optum services compounder / regulatory risk discount",
  description:
    "UNH research cockpit focused on medical cost trend, Medicare Advantage repricing and membership quality, Optum Health risk-based care, OptumRx/PBM regulation, Change Healthcare execution, cash conversion, capital return, and whether the managed-care premium multiple should normalize or recover.",
  updatedAt: "2026-05-20",
  currentPrice: 389,
  priceDate: "2026-05-20",
  marketDataSource: "Manual market snapshot proxy; backend daily price bars are imported separately for historical valuation and backtest.",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "medical-cost", label: "Medical Cost Trend" },
    { value: "medicare-advantage", label: "Medicare Advantage" },
    { value: "optum", label: "Optum Platform" },
    { value: "pbm-regulation", label: "PBM / Regulation" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "mcr-pressure", label: "MCR Pressure", value: 0.865, format: "percent", description: "Research proxy for medical care ratio pressure versus normalized pricing.", badge: "Assumption" },
    { key: "ma-repricing", label: "MA Repricing Need", value: 0.11, format: "percent", description: "Qualitative haircut for Medicare Advantage benefits, bids and risk adjustment uncertainty.", badge: "Assumption" },
    { key: "optum-mix", label: "Optum Mix Support", value: 0.42, format: "percent", description: "Share of thesis value tied to Optum Health, Rx and Insight mix rather than insurance underwriting alone.", badge: "Assumption" },
    { key: "cash-conversion", label: "FCF Conversion Proxy", value: 0.72, format: "percent", description: "FCF to adjusted earnings bridge after working-capital and cyber remediation pressure.", badge: "Derived" },
    { key: "base-gap", label: "Base Upside / Downside", value: 0.05, format: "percent", description: "Local fallback valuation gap versus market proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "medical-cost-cycle",
      question: "Is elevated medical utilization a cyclical pricing lag or a structural reset in underwriting margin?",
      currentView: "UNH becomes investable only if pricing actions, benefit redesign and utilization management can pull MCR back toward a normalized band without accelerating member losses.",
      metric: "Medical care ratio, pricing yield, utilization trend, acuity mix",
      evidenceNeeded: "Quarterly MCR bridge, MA bid assumptions, outpatient/senior utilization commentary and claims reserve development",
      valuationTie: "Normalized FCF margin, discount rate and risk haircut",
      bearCase: "Medical cost trend stays above pricing for multiple bid cycles and the market de-rates the whole managed-care group.",
    },
    {
      key: "ma-durability",
      question: "How much Medicare Advantage profit pool survives rate pressure, STAR/risk-adjustment changes and benefit resets?",
      currentView: "MA can remain attractive, but membership quality matters more than headline lives when rates and coding intensity are under scrutiny.",
      metric: "MA lives, benefit richness, STAR quality, risk-adjusted margin per member",
      evidenceNeeded: "MA membership by cohort, bid-cycle pricing, benefit design changes and CMS rate commentary",
      valuationTie: "Revenue CAGR, quality adjustment and terminal multiple",
      bearCase: "UNH shrinks or reprices too aggressively and loses healthy members while retaining high-cost cohorts.",
    },
    {
      key: "optum-platform",
      question: "Can Optum still justify a platform premium after care-delivery cost pressure and cyber disruption?",
      currentView: "Optum is the strategic reason to own UNH, but it needs clean margin recovery and credible separation between services value and vertical-integration controversy.",
      metric: "Optum Health margin, value-based lives, OptumRx volume, Optum Insight backlog",
      evidenceNeeded: "Segment revenue/margin bridge, care delivery unit economics, Change Healthcare recovery milestones",
      valuationTie: "EV/revenue cross-check and quality adjustment",
      bearCase: "Optum margin recovery stalls and regulators treat vertical integration as a political target.",
    },
    {
      key: "pbm-regulation",
      question: "Does PBM/regulatory risk attack merchant economics, rebate mechanics or the vertically integrated model itself?",
      currentView: "The market discount should stay elevated until investors can underwrite PBM spread, rebate transparency and antitrust outcomes with fewer binary risks.",
      metric: "OptumRx margin, rebate/pass-through disclosure, regulatory actions",
      evidenceNeeded: "PBM contract mix, FTC/DOJ developments, spread-pricing exposure and client retention",
      valuationTie: "Risk haircut and exit multiple",
      bearCase: "Rule changes compress OptumRx economics while political attention limits multiple recovery.",
    },
  ],
  kpiSeries: [
    {
      key: "mcr-vs-pricing",
      title: "Medical Cost Ratio vs Pricing Recovery",
      subtitle: "The core debate is whether claims trend is peaking before pricing catches up.",
      sourceStatus: "research_only",
      measures: [
        { key: "mcr", label: "Medical care ratio", format: "percent", chartType: "bar", color: "#b91c1c", axis: "left" },
        { key: "pricingAdequacy", label: "Pricing adequacy score", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", mcr: 0.844, pricingAdequacy: 0.63 },
        { period: "2024 Q2", mcr: 0.852, pricingAdequacy: 0.61 },
        { period: "2024 Q3", mcr: 0.858, pricingAdequacy: 0.59 },
        { period: "2024 Q4", mcr: 0.862, pricingAdequacy: 0.58 },
        { period: "2025 Q1", mcr: 0.868, pricingAdequacy: 0.55 },
        { period: "2025 Q2", mcr: 0.872, pricingAdequacy: 0.56 },
        { period: "2025 Q3", mcr: 0.869, pricingAdequacy: 0.59 },
        { period: "2025 Q4", mcr: 0.865, pricingAdequacy: 0.62 },
        { period: "2026 Q1", mcr: 0.861, pricingAdequacy: 0.66 },
      ],
    },
    {
      key: "optum-platform",
      title: "Optum Mix vs Segment Margin",
      subtitle: "Optum supports the premium multiple only if services mix growth converts into durable margin recovery.",
      sourceStatus: "research_only",
      measures: [
        { key: "optumMix", label: "Optum revenue mix", format: "percent", chartType: "bar", color: "#0f766e", axis: "left" },
        { key: "optumMargin", label: "Optum margin", format: "percent", chartType: "line", color: "#7c3aed", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", optumMix: 0.385, optumMargin: 0.083 },
        { period: "2024 Q2", optumMix: 0.392, optumMargin: 0.081 },
        { period: "2024 Q3", optumMix: 0.398, optumMargin: 0.078 },
        { period: "2024 Q4", optumMix: 0.404, optumMargin: 0.077 },
        { period: "2025 Q1", optumMix: 0.410, optumMargin: 0.074 },
        { period: "2025 Q2", optumMix: 0.416, optumMargin: 0.075 },
        { period: "2025 Q3", optumMix: 0.421, optumMargin: 0.077 },
        { period: "2025 Q4", optumMix: 0.426, optumMargin: 0.079 },
        { period: "2026 Q1", optumMix: 0.431, optumMargin: 0.081 },
      ],
    },
    {
      key: "ma-membership-quality",
      title: "Medicare Advantage Lives vs Margin Quality",
      subtitle: "Headline membership growth can be bad if repricing forces adverse selection.",
      sourceStatus: "research_only",
      measures: [
        { key: "maLivesIndex", label: "MA lives index", format: "number", chartType: "bar", color: "#1f2937", axis: "left" },
        { key: "marginQuality", label: "Margin quality score", format: "percent", chartType: "line", color: "#ea580c", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", maLivesIndex: 100, marginQuality: 0.70 },
        { period: "2024 Q2", maLivesIndex: 101, marginQuality: 0.68 },
        { period: "2024 Q3", maLivesIndex: 102, marginQuality: 0.65 },
        { period: "2024 Q4", maLivesIndex: 102, marginQuality: 0.62 },
        { period: "2025 Q1", maLivesIndex: 101, marginQuality: 0.58 },
        { period: "2025 Q2", maLivesIndex: 100, marginQuality: 0.59 },
        { period: "2025 Q3", maLivesIndex: 99, marginQuality: 0.61 },
        { period: "2025 Q4", maLivesIndex: 98, marginQuality: 0.64 },
        { period: "2026 Q1", maLivesIndex: 98, marginQuality: 0.67 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "medical-cost",
      tab: "medical-cost",
      title: "Medical Cost Trend and Pricing Lag",
      thesis: "UNH's equity case is currently a claims-cycle normalization call: investors need evidence that outpatient, senior and pharmacy utilization can be priced without losing the best members.",
      evidence: ["Medical care ratio bridge", "Claims reserve development", "Pricing versus utilization by book"],
      watchItems: ["Outpatient utilization", "MA acuity mix", "Commercial employer renewal pricing", "Claims payable days"],
      sourceStatus: "research_only",
    },
    {
      key: "medicare-advantage",
      tab: "medicare-advantage",
      title: "Medicare Advantage Repricing",
      thesis: "The right question is not only whether MA lives grow; it is whether UNH can rebuild margin while retaining profitable cohorts under tighter CMS economics.",
      evidence: ["MA membership by cohort", "Benefit redesign", "STAR/risk-adjustment headwinds"],
      watchItems: ["2027 bid-cycle language", "Benefit richness", "Competitor exits", "Risk adjustment audit updates"],
      sourceStatus: "research_only",
    },
    {
      key: "optum",
      tab: "optum",
      title: "Optum as the Platform Asset",
      thesis: "Optum can defend the multiple if value-based care, pharmacy services and data/workflow assets recover margin and avoid being framed as a regulatory liability.",
      evidence: ["Optum Health margin", "OptumRx retention", "Change Healthcare recovery", "Value-based lives"],
      watchItems: ["Care delivery capacity", "Cyber remediation spend", "PBM transparency proposals", "Provider group impairment risk"],
      sourceStatus: "research_only",
    },
    {
      key: "pbm-regulation",
      tab: "pbm-regulation",
      title: "PBM / Vertical Integration Risk",
      thesis: "Regulatory risk is the multiple governor: the stock needs clarity on whether policy pressure affects only disclosure and rebate mechanics or structural economics.",
      evidence: ["FTC/DOJ process", "State PBM rules", "Client contract renewals", "Spread-pricing exposure"],
      watchItems: ["PBM bills", "Antitrust headlines", "Employer retention", "Drug-price reform proposals"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-15", headline: "MCR stabilization versus MA repricing", keyQuestions: ["Did MCR improve sequentially?", "Are 2027 MA bids priced conservatively?", "Is Optum Health margin recovering?"], managementTone: "Recovery-focused but credibility still rebuilding.", modelReadThrough: "Maintain risk haircut until MCR and Optum margins confirm.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-01-15", headline: "Benefit reset and member-quality tradeoff", keyQuestions: ["How much MA membership attrition is deliberate?", "Is pricing ahead of utilization?", "Any PBM regulatory update?"], managementTone: "Disciplined on pricing.", modelReadThrough: "Lower revenue growth, better margin-quality assumptions.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-15", headline: "Claims trend and Optum execution", keyQuestions: ["Is outpatient utilization still elevated?", "Is Optum Health improving?", "Any Change Healthcare residual cost?"], managementTone: "Cautious.", modelReadThrough: "Keep discount rate elevated.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-15", headline: "Medical cost trend versus guide", keyQuestions: ["Are claims reserves adequate?", "Is MA repricing enough?", "Are employers pushing back on pricing?"], managementTone: "Resetting expectations.", modelReadThrough: "Cut normalized margin; preserve long-term Optum option.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-15", headline: "MA and care-delivery pressure", keyQuestions: ["Is MCR pressure broad or MA-specific?", "Can Optum Health recover?", "Any cyber remediation drag?"], managementTone: "Defensive.", modelReadThrough: "Increase risk haircut materially.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-01-15", headline: "Initial recovery frame", keyQuestions: ["Can 2025 pricing offset utilization?", "Is OptumRx stable?", "How much buyback flexibility remains?"], managementTone: "Constructive but guarded.", modelReadThrough: "Use lower multiple than historical premium.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-15", headline: "Utilization pressure emerges", keyQuestions: ["Is MCR deteriorating?", "Are MA margins below plan?", "Any policy risk acceleration?"], managementTone: "Measured.", modelReadThrough: "Start adding managed-care risk discount.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-15", headline: "Optum and cyber recovery", keyQuestions: ["Is Change Healthcare disruption contained?", "Can Optum Insight backlog normalize?", "Is cash flow still resilient?"], managementTone: "Execution-focused.", modelReadThrough: "Keep platform premium but add execution haircut.", riskSignal: "Neutral", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-15", fiscalPeriod: "FY2024 Q2", asOfPrice: 515, fairValue: 545, method: "Optum platform premium with early cyber execution haircut." },
    { eventDate: "2024-10-15", fiscalPeriod: "FY2024 Q3", asOfPrice: 570, fairValue: 560, method: "Utilization pressure begins to offset quality premium." },
    { eventDate: "2025-01-15", fiscalPeriod: "FY2024 Q4", asOfPrice: 510, fairValue: 525, method: "Pricing recovery case, lower premium multiple." },
    { eventDate: "2025-04-15", fiscalPeriod: "FY2025 Q1", asOfPrice: 440, fairValue: 455, method: "Medical-cost reset and Optum Health haircut." },
    { eventDate: "2025-07-15", fiscalPeriod: "FY2025 Q2", asOfPrice: 310, fairValue: 375, method: "Claims-cycle stress valuation with higher risk haircut." },
    { eventDate: "2025-10-15", fiscalPeriod: "FY2025 Q3", asOfPrice: 335, fairValue: 390, method: "Stabilization watch, still discounted for MCR uncertainty." },
    { eventDate: "2026-01-15", fiscalPeriod: "FY2025 Q4", asOfPrice: 370, fairValue: 410, method: "MA repricing and capital return recovery bridge." },
    { eventDate: "2026-04-15", fiscalPeriod: "FY2026 Q1", asOfPrice: 389, fairValue: 425, method: "Base recovery case: MCR normalizes gradually, Optum platform retains partial premium." },
  ],
  valuationBase: {
    revenueBase: 420000,
    revenueCagr3Y: 0.055,
    terminalGrowth: 0.025,
    normalizedFcfMargin: 0.065,
    exitFcfMultiple: 16,
    evRevenueMultiple: 1.05,
    discountRate: 0.095,
    netCashDebt: -72000,
    dilutedShares: 920,
    qualityAdjustment: 1.05,
    riskHaircut: 0.18,
    dividendYield: 0.022,
    buybackYield: 0.018,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.025, normalizedFcfMargin: 0.046, exitFcfMultiple: 12, evRevenueMultiple: 0.75, discountRate: 0.105, riskHaircut: 0.32, qualityAdjustment: 0.92, buybackYield: 0.005 },
    Base: {},
    Bull: { revenueCagr3Y: 0.07, normalizedFcfMargin: 0.078, exitFcfMultiple: 18, evRevenueMultiple: 1.25, discountRate: 0.0875, riskHaircut: 0.11, qualityAdjustment: 1.12, buybackYield: 0.025 },
  },
  valuationDescription: "Triangulates UNH through DCF, normalized FCF yield and revenue cross-check while explicitly penalizing medical-cost-cycle and PBM/regulatory uncertainty.",
  risks: [
    { title: "Medical cost trend stays structurally high", detail: "If claims trend remains above pricing, normalized margin and the managed-care multiple both compress.", severity: "high", killSignal: "MCR misses pricing assumptions for two more quarters." },
    { title: "Medicare Advantage adverse selection", detail: "Benefit resets can shrink profitable lives and retain high-cost cohorts.", severity: "high", killSignal: "MA lives fall while MCR fails to improve." },
    { title: "PBM / vertical integration regulation", detail: "Policy pressure can cap OptumRx economics and keep the multiple depressed.", severity: "high", killSignal: "Material PBM spread or rebate economics are restricted." },
    { title: "Optum execution and cyber remediation", detail: "Change Healthcare recovery and Optum Health margins must normalize for the platform thesis to work.", severity: "medium", killSignal: "Optum margin fails to recover despite revenue growth." },
  ],
  monitoring: ["Medical care ratio", "MA membership and benefit design", "Optum Health margin", "OptumRx retention", "PBM/FTC/DOJ updates", "FCF conversion", "Buybacks and debt leverage"],
  sourceGaps: [
    "Official UNH filings, earnings supplements and transcript ingestion are not yet imported into the backend.",
    "MCR, MA membership, Optum segment margin and PBM exposure rows are research proxies until source-backed ingestion is added.",
    "Healthcare-specific actuarial reserve triangulation is not yet modeled as a dedicated backend table.",
  ],
});
