import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const qcomDataset = createLocalDeepResearchDataset({
  ticker: "QCOM",
  companyName: "QUALCOMM Incorporated",
  sector: "Semiconductors / Mobile SoC / Edge AI / Automotive Connectivity",
  archetype: "Semiconductor platform / handset cycle plus edge-AI and auto optionality",
  description:
    "QCOM research cockpit focused on Android handset recovery, Snapdragon premium share, Apple modem risk, licensing durability, automotive design-win backlog, IoT/edge-AI attach, margin leverage, buybacks, and whether diversification can offset handset cyclicality.",
  updatedAt: "2026-05-20",
  currentPrice: 195.61,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "handsets-license", label: "Handsets / License" },
    { value: "auto-edge-ai", label: "Auto / Edge AI" },
    { value: "margins-capital", label: "Margins / Capital" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q2", label: "FY2026 Q2" },
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "handset-cycle", label: "Handset Cycle Score", value: 0.64, format: "percent", description: "Research score for Android premium recovery and Snapdragon share.", badge: "Assumption" },
    { key: "auto-backlog", label: "Auto Backlog Durability", value: 0.72, format: "percent", description: "Automotive design-win backlog quality framework.", badge: "Placeholder" },
    { key: "licensing-risk", label: "Licensing Durability", value: 0.8, format: "percent", description: "QTL royalty durability and legal/regulatory risk framework.", badge: "Assumption" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: 0.27, format: "percent", description: "High-margin licensing plus chip-cycle margin framework.", badge: "Assumption" },
    { key: "base-gap", label: "Base Upside / Downside", value: 0.05, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "handsets",
      question: "Is Android premium handset recovery durable or just a cycle rebound?",
      currentView: "QCOM needs premium Android share and content gains to offset mature smartphone units.",
      metric: "Handset revenue, premium mix, Snapdragon share",
      evidenceNeeded: "OEM commentary, channel inventory and Android premium sell-through",
      valuationTie: "Revenue CAGR and exit multiple",
      bearCase: "Units normalize lower and China OEM competition pressures ASP/margin.",
    },
    {
      key: "apple-risk",
      question: "How much Apple modem risk is still embedded?",
      currentView: "Apple risk should be modeled as a scenario variable rather than ignored or fully priced in.",
      metric: "Apple modem revenue exposure, transition timing, replacement content",
      evidenceNeeded: "Contract duration and management exposure commentary",
      valuationTie: "Bear-case revenue and risk haircut",
      bearCase: "Apple transition is faster than expected and replacement growth lags.",
    },
    {
      key: "auto-edge-ai",
      question: "Can auto and edge AI become large enough to change the multiple?",
      currentView: "Automotive backlog and edge AI are credible, but still need revenue conversion and margin proof.",
      metric: "Auto revenue, design-win backlog, IoT/edge AI attach",
      evidenceNeeded: "Backlog conversion schedule and segment margin",
      valuationTie: "EV/revenue cross-check and quality adjustment",
      bearCase: "Auto backlog converts slowly and AI PCs/edge devices do not move the needle.",
    },
    {
      key: "qtl",
      question: "Is licensing still the hidden annuity?",
      currentView: "QTL remains central to cash conversion; regulatory and customer concentration risk should stay visible.",
      metric: "QTL revenue, EBT margin, royalty base",
      evidenceNeeded: "Licensee renewal and legal/regulatory updates",
      valuationTie: "Normalized FCF margin",
      bearCase: "Royalty pressure or litigation reduces the high-margin annuity.",
    },
  ],
  kpiSeries: [
    {
      key: "handsets-license",
      title: "Handset Recovery vs Licensing Durability",
      subtitle: "QCOM valuation hinges on handset cyclicality plus the durability of the QTL cash annuity.",
      sourceStatus: "research_only",
      measures: [
        { key: "handsetIndex", label: "Handset revenue index", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "licensingMargin", label: "Licensing margin %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q1", handsetIndex: 88, licensingMargin: 0.68 },
        { period: "FY2024 Q2", handsetIndex: 92, licensingMargin: 0.69 },
        { period: "FY2024 Q3", handsetIndex: 96, licensingMargin: 0.69 },
        { period: "FY2024 Q4", handsetIndex: 101, licensingMargin: 0.7 },
        { period: "FY2025 Q1", handsetIndex: 106, licensingMargin: 0.7 },
        { period: "FY2025 Q2", handsetIndex: 110, licensingMargin: 0.7 },
        { period: "FY2025 Q3", handsetIndex: 114, licensingMargin: 0.69 },
        { period: "FY2025 Q4", handsetIndex: 118, licensingMargin: 0.69 },
        { period: "FY2026 Q1", handsetIndex: 121, licensingMargin: 0.69 },
        { period: "FY2026 Q2", handsetIndex: 123, licensingMargin: 0.68 },
      ],
    },
    {
      key: "auto-edge-ai",
      title: "Automotive Backlog Conversion vs Edge-AI Optionality",
      subtitle: "Diversification matters only when auto and edge AI convert into material revenue and margin.",
      sourceStatus: "research_only",
      measures: [
        { key: "autoRevenueIndex", label: "Auto revenue index", format: "number", chartType: "bar", color: "#1e3a8a", axis: "left" },
        { key: "edgeAiIndex", label: "Edge-AI optionality index", format: "number", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q1", autoRevenueIndex: 70, edgeAiIndex: 60 },
        { period: "FY2024 Q2", autoRevenueIndex: 75, edgeAiIndex: 64 },
        { period: "FY2024 Q3", autoRevenueIndex: 81, edgeAiIndex: 69 },
        { period: "FY2024 Q4", autoRevenueIndex: 88, edgeAiIndex: 74 },
        { period: "FY2025 Q1", autoRevenueIndex: 96, edgeAiIndex: 80 },
        { period: "FY2025 Q2", autoRevenueIndex: 104, edgeAiIndex: 86 },
        { period: "FY2025 Q3", autoRevenueIndex: 112, edgeAiIndex: 91 },
        { period: "FY2025 Q4", autoRevenueIndex: 121, edgeAiIndex: 96 },
        { period: "FY2026 Q1", autoRevenueIndex: 130, edgeAiIndex: 102 },
        { period: "FY2026 Q2", autoRevenueIndex: 138, edgeAiIndex: 108 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "handsets-license",
      tab: "handsets-license",
      title: "Handset Cycle and QTL Annuity",
      thesis: "QCOM's cash quality depends on the QTL royalty engine while QCT handset revenue carries cycle and OEM-share risk.",
      evidence: ["Android premium units", "Snapdragon attach", "QTL margin", "Apple exposure"],
      watchItems: ["China OEM competition", "Apple modem transition", "Royalty disputes"],
      sourceStatus: "research_only",
    },
    {
      key: "auto-edge",
      tab: "auto-edge-ai",
      title: "Auto Backlog and Edge AI",
      thesis: "Auto and edge-AI growth can improve the multiple only when backlog conversion becomes visible and margin-accretive.",
      evidence: ["Auto design-win backlog", "Auto revenue growth", "AI PC / edge attach", "Segment margin"],
      watchItems: ["Auto production cycle", "Backlog timing", "AI feature monetization"],
      sourceStatus: "research_only",
    },
    {
      key: "margins-capital",
      tab: "margins-capital",
      title: "Margin Leverage and Buybacks",
      thesis: "FCF conversion and buybacks are the bridge between semiconductor cyclicality and per-share compounding.",
      evidence: ["Gross margin", "Opex discipline", "FCF conversion", "Share count"],
      watchItems: ["Inventory correction", "R&D intensity", "Buyback timing"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q2", eventDate: "2026-04-29", headline: "Handset recovery and AI edge attach", keyQuestions: ["Is premium Android demand durable?", "Any Apple exposure update?", "Is auto converting?"], managementTone: "Constructive.", modelReadThrough: "Raise quality only if auto revenue and QTL stay stable.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2026 Q1", eventDate: "2026-01-28", headline: "Licensing stability versus cycle", keyQuestions: ["QTL margin?", "Channel inventory?", "Auto backlog conversion?"], managementTone: "Balanced.", modelReadThrough: "Handset recovery supports base case.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2025-11-05", headline: "Apple and auto debate", keyQuestions: ["Apple modem timing?", "Auto revenue cadence?", "Buyback pace?"], managementTone: "Confident on diversification.", modelReadThrough: "Keep Apple risk haircut.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-07-30", headline: "Android premium cycle", keyQuestions: ["Premium units?", "China OEM share?", "QCT margin?"], managementTone: "Positive.", modelReadThrough: "Revenue CAGR improves but cycle risk remains.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-04-30", headline: "QTL annuity watch", keyQuestions: ["Licensing revenue stable?", "Any legal risk?", "FCF conversion?"], managementTone: "Stable.", modelReadThrough: "FCF margin remains core value driver.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-02-05", headline: "Handset inventory normalization", keyQuestions: ["Channel inventory?", "Android demand?", "Auto backlog?"], managementTone: "Improving.", modelReadThrough: "Begin recovery case.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2024-11-06", headline: "Diversification proof", keyQuestions: ["Auto growth?", "IoT stabilization?", "QTL durability?"], managementTone: "Constructive.", modelReadThrough: "No full multiple re-rate yet.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-07-31", headline: "Cycle trough versus structural risk", keyQuestions: ["Is handset trough past?", "Apple risk?", "Margins?"], managementTone: "Cautious.", modelReadThrough: "Keep valuation conservative.", riskSignal: "Needs Review", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-31", fiscalPeriod: "FY2024 Q3", asOfPrice: 171, fairValue: 168, method: "Handset trough and Apple-risk local fallback." },
    { eventDate: "2024-11-06", fiscalPeriod: "FY2024 Q4", asOfPrice: 173, fairValue: 176, method: "Diversification proof but no re-rate." },
    { eventDate: "2025-02-05", fiscalPeriod: "FY2025 Q1", asOfPrice: 168, fairValue: 182, method: "Handset inventory normalization." },
    { eventDate: "2025-04-30", fiscalPeriod: "FY2025 Q2", asOfPrice: 150, fairValue: 178, method: "QTL annuity supports downside." },
    { eventDate: "2025-07-30", fiscalPeriod: "FY2025 Q3", asOfPrice: 165, fairValue: 188, method: "Android premium recovery." },
    { eventDate: "2025-11-05", fiscalPeriod: "FY2025 Q4", asOfPrice: 183, fairValue: 198, method: "Apple risk and auto conversion." },
    { eventDate: "2026-01-28", fiscalPeriod: "FY2026 Q1", asOfPrice: 190, fairValue: 203, method: "Licensing stability versus cycle." },
    { eventDate: "2026-04-29", fiscalPeriod: "FY2026 Q2", asOfPrice: 196, fairValue: 206, method: "Base handset / auto / QTL local run." },
  ],
  valuationBase: {
    revenueBase: 41000,
    revenueCagr3Y: 0.075,
    terminalGrowth: 0.025,
    normalizedFcfMargin: 0.27,
    exitFcfMultiple: 18,
    evRevenueMultiple: 5.2,
    discountRate: 0.095,
    netCashDebt: -8000,
    dilutedShares: 1072,
    qualityAdjustment: 1.08,
    riskHaircut: 0.11,
    dividendYield: 0.017,
    buybackYield: 0.025,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: 0.0, normalizedFcfMargin: 0.22, exitFcfMultiple: 13, evRevenueMultiple: 3.5, riskHaircut: 0.23, qualityAdjustment: 0.98, buybackYield: 0.01 },
    Base: {},
    Bull: { revenueCagr3Y: 0.12, normalizedFcfMargin: 0.31, exitFcfMultiple: 22, evRevenueMultiple: 6.4, riskHaircut: 0.06, qualityAdjustment: 1.16, buybackYield: 0.035 },
  },
  valuationDescription: "Blends DCF, forward FCF multiple and EV/revenue cross-check across handset recovery, QTL durability and auto/edge-AI optionality.",
  risks: [
    { title: "Apple modem transition", detail: "Faster Apple insourcing can remove high-value modem revenue before diversification offsets it.", severity: "high", killSignal: "Management reduces Apple exposure assumptions materially." },
    { title: "Handset cyclicality", detail: "Android premium recovery can reverse if OEM demand or China competition weakens.", severity: "high", killSignal: "QCT handset revenue declines while inventory rises." },
    { title: "Licensing pressure", detail: "QTL royalty economics can face legal, regulatory or customer pushback.", severity: "medium", killSignal: "QTL margin/revenue deteriorates for multiple quarters." },
  ],
  monitoring: ["QCT handset revenue", "QTL revenue and margin", "Apple exposure", "Auto revenue/backlog", "IoT/edge-AI attach", "FCF and buybacks"],
  sourceGaps: ["Official segment revenue, QTL margin and auto backlog should be imported from earnings materials.", "Backend daily price bars and persisted historical valuation runs are deferred."],
});
