import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const beDataset = createLocalDeepResearchDataset({
  ticker: "BE",
  companyName: "Bloom Energy Corporation",
  sector: "Power / Fuel Cells / AI Data-Center Energy Infrastructure",
  archetype: "Solid-oxide fuel-cell platform / AI power scarcity / hydrogen optionality",
  description:
    "Bloom Energy research cockpit focused on data-center power scarcity, solid-oxide fuel-cell server deployments, bookings and backlog conversion, project-level gross margin, cash burn, hydrogen optionality, customer concentration, financing structure, and whether AI power demand can justify the premium valuation.",
  updatedAt: "2026-05-20",
  currentPrice: 286.65,
  priceDate: "2026-05-20",
  marketDataSource: "Market quote snapshot captured 2026-05-20; backend daily price bars are not yet persisted for BE.",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "ai-power", label: "AI Power Demand" },
    { value: "backlog-bookings", label: "Backlog / Bookings" },
    { value: "unit-economics", label: "Unit Economics" },
    { value: "hydrogen", label: "Hydrogen Optionality" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    {
      key: "current-price",
      label: "Current Price",
      value: 286.65,
      format: "currency",
      description: "Market quote snapshot used only as the comparison anchor, not as a valuation input plug.",
      badge: "Actual",
    },
    {
      key: "fy2026-revenue-guide",
      label: "FY2026 Revenue Guide",
      value: 3600,
      format: "currency",
      description: "Management FY2026 revenue guide midpoint in USD millions from Q1 2026 results.",
      badge: "Assumption",
    },
    {
      key: "product-backlog",
      label: "Product Backlog",
      value: 6000,
      format: "currency",
      description: "FY2025 disclosed product backlog in USD millions; conversion timing and margin remain the key diligence issue.",
      badge: "Actual",
    },
    {
      key: "total-backlog",
      label: "Total Backlog",
      value: 20000,
      format: "currency",
      description: "FY2025 disclosed total current backlog in USD millions, including service and contracted components.",
      badge: "Actual",
    },
    {
      key: "base-gap",
      label: "Base Upside / Downside",
      value: -0.56,
      format: "percent",
      description: "Local model fair value gap versus market quote; intentionally not price-anchored.",
      badge: "Derived",
    },
  ],
  researchQuestions: [
    {
      key: "ai-power-scarcity",
      question: "Is BE now a durable AI power infrastructure winner or a data-center scarcity trade?",
      currentView:
        "The bull case requires Bloom servers to solve real interconnection delays for hyperscale and colocation customers, not merely benefit from AI power headlines.",
      metric: "Data-center deployments, MW contracted, time-to-power, customer mix",
      evidenceNeeded: "Signed capacity, deployment cadence, power price, uptime, customer concentration and interconnection alternatives",
      valuationTie: "Revenue CAGR, EV/revenue cross-check and quality adjustment",
      bearCase: "Grid upgrades, gas turbines, batteries or utility PPAs narrow the urgency window before Bloom converts backlog.",
    },
    {
      key: "backlog-quality",
      question: "How bankable is the backlog and how quickly can it convert to revenue?",
      currentView:
        "A very large backlog can be valuable only if order terms, permitting, financing and customer readiness translate into shipped systems at acceptable gross margin.",
      metric: "Product backlog, bookings, revenue conversion, cancellation risk",
      evidenceNeeded: "Backlog roll-forward, customer terms, capacity reservations, delivery dates and cancellation/deferral history",
      valuationTie: "Revenue base, growth fade and risk haircut",
      bearCase: "Backlog expands through memoranda or long-dated orders while near-term conversion and cash collection lag.",
    },
    {
      key: "unit-economics",
      question: "Can Bloom scale hardware gross margin and service economics without absorbing too much working capital?",
      currentView:
        "Gross margin improvement is not enough; the investable case needs clean cash conversion after inventory, project financing and service obligations.",
      metric: "Gross margin, non-GAAP operating margin, free cash flow, working capital",
      evidenceNeeded: "System cost-down, service margin, warranty accruals, inventory turns, project-finance receivables and cash burn bridge",
      valuationTie: "Normalized FCF margin and exit FCF multiple",
      bearCase: "Revenue scales but project mix, warranty, inventory and financing needs keep FCF structurally weak.",
    },
    {
      key: "hydrogen-double-count",
      question: "Is hydrogen optionality real value or a narrative that should stay outside base valuation?",
      currentView:
        "Electrolyzers and hydrogen-ready systems can matter, but the base case should underwrite core power servers first and treat hydrogen as out-of-the-money optionality.",
      metric: "Electrolyzer orders, hydrogen-ready deployments, subsidy eligibility, margin",
      evidenceNeeded: "Commercial orders, customer economics without subsidies, 45V/IRA qualification and manufacturing scale",
      valuationTie: "Bull case only; not embedded in base revenue multiple",
      bearCase: "Hydrogen timelines slip and incentives do not support attractive customer economics.",
    },
    {
      key: "financing-dilution",
      question: "Does the growth plan require external capital, dilution or balance-sheet leverage?",
      currentView:
        "At a high equity valuation the hidden risk is not just technology execution; it is whether high growth consumes cash before operating leverage arrives.",
      metric: "Net debt, cash burn, capex, working capital, share count",
      evidenceNeeded: "Debt maturity schedule, project-financing terms, SBC, equity issuance and free-cash-flow bridge",
      valuationTie: "Net cash/debt, diluted shares, risk haircut",
      bearCase: "Cash needs rise with deployments and shareholder dilution absorbs the operating upside.",
    },
  ],
  kpiSeries: [
    {
      key: "ai-power",
      title: "AI Data-Center Power Scarcity vs Bloom Deployment Readiness",
      subtitle:
        "This framework separates the market's AI power urgency from BE-specific execution proof: contract quality, deployment cadence and serviceability.",
      sourceStatus: "research_only",
      measures: [
        { key: "aiPowerUrgency", label: "AI power urgency score", format: "number", chartType: "bar", color: "#3adbea", axis: "left" },
        { key: "deploymentReadiness", label: "BE deployment readiness", format: "number", chartType: "line", color: "#d6f75a", axis: "right" },
      ],
      points: [
        { period: "2024 Q2", aiPowerUrgency: 48, deploymentReadiness: 44 },
        { period: "2024 Q3", aiPowerUrgency: 55, deploymentReadiness: 47 },
        { period: "2024 Q4", aiPowerUrgency: 63, deploymentReadiness: 52 },
        { period: "2025 Q1", aiPowerUrgency: 70, deploymentReadiness: 56 },
        { period: "2025 Q2", aiPowerUrgency: 78, deploymentReadiness: 62 },
        { period: "2025 Q3", aiPowerUrgency: 86, deploymentReadiness: 70 },
        { period: "2025 Q4", aiPowerUrgency: 93, deploymentReadiness: 77 },
        { period: "2026 Q1", aiPowerUrgency: 98, deploymentReadiness: 82 },
        { period: "2026 Q2E", aiPowerUrgency: 100, deploymentReadiness: 86 },
      ],
    },
    {
      key: "backlog-bookings",
      title: "Backlog Scale vs Revenue Conversion",
      subtitle:
        "The value of a $20bn backlog depends on how much is near-term, contracted, financeable and convertible at attractive project margin.",
      sourceStatus: "derived",
      measures: [
        { key: "productBacklog", label: "Product backlog ($m)", format: "currency", chartType: "bar", color: "#2b8cff", axis: "left" },
        { key: "conversionScore", label: "Conversion quality score", format: "number", chartType: "line", color: "#ffa329", axis: "right" },
      ],
      points: [
        { period: "2024 Q2", productBacklog: 1800, conversionScore: 42 },
        { period: "2024 Q3", productBacklog: 2200, conversionScore: 45 },
        { period: "2024 Q4", productBacklog: 3100, conversionScore: 51 },
        { period: "2025 Q1", productBacklog: 3400, conversionScore: 54 },
        { period: "2025 Q2", productBacklog: 4200, conversionScore: 59 },
        { period: "2025 Q3", productBacklog: 5200, conversionScore: 66 },
        { period: "2025 Q4", productBacklog: 6000, conversionScore: 71 },
        { period: "2026 Q1", productBacklog: 6900, conversionScore: 74 },
      ],
    },
    {
      key: "unit-economics",
      title: "Revenue Scale vs Gross Margin and Cash Conversion",
      subtitle:
        "Bloom's valuation only works if revenue growth comes with durable gross margin and visible FCF inflection, not just backlog growth.",
      sourceStatus: "derived",
      measures: [
        { key: "revenue", label: "Quarterly revenue ($m)", format: "currency", chartType: "bar", color: "#59ea8a", axis: "left" },
        { key: "grossMargin", label: "Gross margin", format: "percent", chartType: "line", color: "#c09cff", axis: "right" },
      ],
      points: [
        { period: "2024 Q4", revenue: 572, grossMargin: 0.307 },
        { period: "2025 Q1", revenue: 326, grossMargin: 0.261 },
        { period: "2025 Q2", revenue: 401, grossMargin: 0.286 },
        { period: "2025 Q3", revenue: 519, grossMargin: 0.298 },
        { period: "2025 Q4", revenue: 778, grossMargin: 0.308 },
        { period: "2026 Q1", revenue: 751, grossMargin: 0.300 },
        { period: "2026 Q2E", revenue: 850, grossMargin: 0.315 },
        { period: "2026 Q3E", revenue: 950, grossMargin: 0.325 },
      ],
    },
    {
      key: "hydrogen",
      title: "Core Power Servers vs Hydrogen Optionality",
      subtitle:
        "Base underwriting stays on power-server deployments; electrolyzer and hydrogen-ready economics are tracked as separate optionality.",
      sourceStatus: "research_only",
      measures: [
        { key: "corePowerValue", label: "Core power-server thesis score", format: "number", chartType: "bar", color: "#3adbea", axis: "left" },
        { key: "hydrogenOption", label: "Hydrogen option score", format: "number", chartType: "line", color: "#ff554a", axis: "right" },
      ],
      points: [
        { period: "2024 Q2", corePowerValue: 46, hydrogenOption: 35 },
        { period: "2024 Q3", corePowerValue: 50, hydrogenOption: 34 },
        { period: "2024 Q4", corePowerValue: 57, hydrogenOption: 36 },
        { period: "2025 Q1", corePowerValue: 63, hydrogenOption: 37 },
        { period: "2025 Q2", corePowerValue: 71, hydrogenOption: 39 },
        { period: "2025 Q3", corePowerValue: 80, hydrogenOption: 41 },
        { period: "2025 Q4", corePowerValue: 87, hydrogenOption: 43 },
        { period: "2026 Q1", corePowerValue: 91, hydrogenOption: 45 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "ai-power",
      tab: "ai-power",
      title: "AI Power Scarcity and Time-to-Power",
      thesis:
        "Bloom becomes strategically valuable if it can deliver reliable behind-the-meter power faster than grid interconnects, gas turbines and utility PPAs for AI campuses.",
      evidence: ["Signed data-center deployments", "MW shipped and commissioned", "Time-to-power versus utility alternatives", "Uptime and service reliability"],
      watchItems: ["Customer concentration", "Permitting delays", "Gas supply and emissions rules", "Hyperscaler power strategy shifts"],
      sourceStatus: "research_only",
    },
    {
      key: "backlog-bookings",
      tab: "backlog-bookings",
      title: "Backlog Quality, Conversion and Cancellation Risk",
      thesis:
        "The backlog headline is not enough; investors need a roll-forward from orders to funded deployment, revenue, cash collection and service margin.",
      evidence: ["Product backlog roll-forward", "Bookings by customer type", "Delivery schedule", "Contracted service economics"],
      watchItems: ["Long-dated reservations", "Customer deferrals", "Financing partner constraints", "Cancellation language"],
      sourceStatus: "derived",
    },
    {
      key: "unit-economics",
      tab: "unit-economics",
      title: "Hardware Gross Margin and FCF Inflection",
      thesis:
        "The key model risk is whether Bloom can convert hardware scale into a positive FCF business after warranty, service, inventory and project-financing needs.",
      evidence: ["Gross margin bridge", "Service margin", "Working-capital days", "Warranty accruals", "Cash from operations"],
      watchItems: ["Inventory build", "Receivable financing", "Warranty spikes", "Manufacturing yield"],
      sourceStatus: "derived",
    },
    {
      key: "hydrogen",
      tab: "hydrogen",
      title: "Hydrogen Optionality Without Double Counting",
      thesis:
        "Hydrogen can be upside, but the base case should not capitalize electrolyzer economics before commercial orders, subsidy clarity and margin proof.",
      evidence: ["Electrolyzer orders", "Hydrogen-ready deployments", "45V/IRA eligibility", "Customer economics without subsidy"],
      watchItems: ["Policy changes", "Project delays", "Green hydrogen power costs", "Equipment competition"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    {
      quarter: "FY2026 Q1",
      eventDate: "2026-04-29",
      headline: "Record Q1 revenue, higher guide and AI power scarcity",
      keyQuestions: [
        "How much of the raised guide is contracted data-center demand versus pull-forward?",
        "What portion of backlog converts inside twelve months?",
        "Is gross margin stable as large AI projects scale?",
      ],
      managementTone: "Strong demand tone, increasingly data-center and AI infrastructure centered.",
      modelReadThrough: "Raise growth assumption but keep risk haircut because valuation now prices rapid backlog conversion.",
      riskSignal: "Positive",
      sourceStatus: "official_actual",
    },
    {
      quarter: "FY2025 Q4",
      eventDate: "2026-02-26",
      headline: "Record revenue, $6bn product backlog and $20bn total backlog",
      keyQuestions: [
        "What is the quality of the backlog and how much is firm?",
        "Can cash flow turn positive without external funding?",
        "Are data-center orders concentrated in one or two counterparties?",
      ],
      managementTone: "Confident on AI infrastructure demand and backlog visibility.",
      modelReadThrough: "Re-rate revenue base and backlog conversion score, but do not capitalize total backlog at face value.",
      riskSignal: "Inflecting",
      sourceStatus: "official_actual",
    },
    {
      quarter: "FY2025 Q3",
      eventDate: "2025-10-30",
      headline: "AI customer momentum becomes the primary debate",
      keyQuestions: [
        "Are orders supported by deployment permits and gas supply?",
        "Is manufacturing capacity keeping pace with bookings?",
        "Does service obligation scale with acceptable margin?",
      ],
      managementTone: "Demand-led but execution-heavy.",
      modelReadThrough: "Increase EV/revenue cross-check weight in bull case only.",
      riskSignal: "Inflecting",
      sourceStatus: "research_only",
    },
    {
      quarter: "FY2025 Q2",
      eventDate: "2025-07-31",
      headline: "Backlog conversion and power-server unit economics",
      keyQuestions: [
        "Is revenue conversion improving sequentially?",
        "What are the working-capital requirements for larger deployments?",
        "Can gross margin hold above 30%?",
      ],
      managementTone: "Constructive on scale, still cash-conversion focused.",
      modelReadThrough: "Keep normalized FCF margin below high-growth hardware peers until cash proof improves.",
      riskSignal: "Needs Review",
      sourceStatus: "research_only",
    },
    {
      quarter: "FY2025 Q1",
      eventDate: "2025-05-08",
      headline: "Early AI power optionality versus first-quarter revenue seasonality",
      keyQuestions: [
        "Was Q1 revenue softness seasonal, timing-related or demand-related?",
        "Are data-center customer discussions turning into binding orders?",
        "What is the margin mix of near-term shipments?",
      ],
      managementTone: "Bullish on opportunity but proof still early.",
      modelReadThrough: "Do not extrapolate backlog without conversion cadence.",
      riskSignal: "Neutral",
      sourceStatus: "official_actual",
    },
    {
      quarter: "FY2024 Q4",
      eventDate: "2025-02-27",
      headline: "Data-center use case emerges as the central upside path",
      keyQuestions: [
        "Is data-center demand incremental or replacing legacy commercial customers?",
        "How much revenue is tied to few large orders?",
        "Can service margins improve with installed base scale?",
      ],
      managementTone: "Strategically optimistic, still proving cash conversion.",
      modelReadThrough: "Lift long-term growth, keep balance-sheet haircut.",
      riskSignal: "Inflecting",
      sourceStatus: "official_actual",
    },
    {
      quarter: "FY2024 Q3",
      eventDate: "2024-11-07",
      headline: "Before the major AI power re-rating, focus was margin and orders",
      keyQuestions: [
        "Are commercial orders accelerating?",
        "Is gross margin improvement repeatable?",
        "How much cash is consumed by inventory and project financing?",
      ],
      managementTone: "Improving, but not yet a pure AI infrastructure story.",
      modelReadThrough: "Base case remains hardware-margin recovery, not scarcity premium.",
      riskSignal: "Neutral",
      sourceStatus: "research_only",
    },
    {
      quarter: "FY2024 Q2",
      eventDate: "2024-08-08",
      headline: "Gross margin and financing quality before AI power scarcity",
      keyQuestions: [
        "Can system cost-down offset deployment complexity?",
        "Are project-finance receivables expanding?",
        "Is hydrogen optionality consuming focus without orders?",
      ],
      managementTone: "Operational improvement but demand proof still mixed.",
      modelReadThrough: "Keep valuation mostly EV/sales and early FCF cross-check.",
      riskSignal: "Needs Review",
      sourceStatus: "research_only",
    },
  ],
  historicalValuations: [
    {
      eventDate: "2023-08-03",
      fiscalPeriod: "FY2023 Q2",
      asOfPrice: 17,
      fairValue: 14,
      method: "Pre-AI-scarcity local fallback using systems gross-margin recovery and cash-burn haircut.",
    },
    {
      eventDate: "2023-11-08",
      fiscalPeriod: "FY2023 Q3",
      asOfPrice: 12,
      fairValue: 12,
      method: "Demand timing and project-financing risk kept the valuation mostly sales-multiple based.",
    },
    {
      eventDate: "2024-02-15",
      fiscalPeriod: "FY2023 Q4",
      asOfPrice: 10,
      fairValue: 11,
      method: "Improving margin path but no data-center scarcity premium yet.",
    },
    {
      eventDate: "2024-05-09",
      fiscalPeriod: "FY2024 Q1",
      asOfPrice: 12,
      fairValue: 12,
      method: "Early 2024 local run focused on cash burn, revenue timing and hardware gross margin.",
    },
    {
      eventDate: "2024-08-08",
      fiscalPeriod: "FY2024 Q2",
      asOfPrice: 11,
      fairValue: 13,
      method: "Gross-margin improvement local fallback before hyperscale AI power became the dominant frame.",
    },
    {
      eventDate: "2024-11-07",
      fiscalPeriod: "FY2024 Q3",
      asOfPrice: 13,
      fairValue: 15,
      method: "Orders and margin recovery; no later AEP/Oracle scarcity premium allowed in this historical row.",
    },
    {
      eventDate: "2025-02-27",
      fiscalPeriod: "FY2024 Q4",
      asOfPrice: 24,
      fairValue: 24,
      method: "Data-center use case enters the thesis; still haircuts cash conversion and customer concentration.",
    },
    {
      eventDate: "2025-05-08",
      fiscalPeriod: "FY2025 Q1",
      asOfPrice: 19,
      fairValue: 28,
      method: "Q1 seasonality with stronger AI power pipeline; valuation adds backlog-conversion option.",
    },
    {
      eventDate: "2025-07-31",
      fiscalPeriod: "FY2025 Q2",
      asOfPrice: 30,
      fairValue: 37,
      method: "Improving conversion evidence and margin scale, but still working-capital constrained.",
    },
    {
      eventDate: "2025-10-30",
      fiscalPeriod: "FY2025 Q3",
      asOfPrice: 78,
      fairValue: 62,
      method: "AI power narrative accelerates; local fair value rises but remains below the re-rating price.",
    },
    {
      eventDate: "2026-02-26",
      fiscalPeriod: "FY2025 Q4",
      asOfPrice: 135,
      fairValue: 100,
      method: "Backlog step-change and FY2026 guide support higher value; total backlog not capitalized at face value.",
    },
    {
      eventDate: "2026-04-29",
      fiscalPeriod: "FY2026 Q1",
      asOfPrice: 226,
      fairValue: 140,
      method: "Record Q1 and raised guide; base case discounts execution, financing and customer-concentration risk.",
    },
  ],
  valuationBase: {
    revenueBase: 3600,
    revenueCagr3Y: 0.35,
    terminalGrowth: 0.03,
    normalizedFcfMargin: 0.2,
    exitFcfMultiple: 55,
    evRevenueMultiple: 10,
    discountRate: 0.115,
    netCashDebt: -900,
    dilutedShares: 320,
    qualityAdjustment: 1.1,
    riskHaircut: 0.18,
    dividendYield: 0,
    buybackYield: -0.01,
  },
  scenarioOverrides: {
    Bear: {
      revenueCagr3Y: 0.06,
      normalizedFcfMargin: 0.04,
      exitFcfMultiple: 16,
      evRevenueMultiple: 2.5,
      discountRate: 0.145,
      riskHaircut: 0.42,
      qualityAdjustment: 0.82,
      buybackYield: -0.03,
    },
    Base: {},
    Bull: {
      revenueCagr3Y: 0.5,
      normalizedFcfMargin: 0.27,
      exitFcfMultiple: 70,
      evRevenueMultiple: 15,
      discountRate: 0.105,
      riskHaircut: 0.1,
      qualityAdjustment: 1.22,
      buybackYield: 0,
    },
  },
  valuationDescription:
    "Blends DCF, forward FCF multiple and EV/revenue cross-check for a high-growth hardware platform. Current market price and trading multiple are not used to derive fair value; backlog conversion, normalized FCF margin and execution risk drive the model.",
  risks: [
    {
      title: "AI power demand priced ahead of conversion",
      detail:
        "The stock can de-rate if data-center urgency does not convert into commissioned systems, revenue and cash collection fast enough.",
      severity: "high",
      killSignal: "Product backlog grows but revenue conversion, commissioned MW and cash from operations lag for multiple quarters.",
    },
    {
      title: "Project economics and cash burn",
      detail:
        "Hardware scale may require inventory, warranty reserves, receivable financing and service support that delay FCF inflection.",
      severity: "high",
      killSignal: "Gross margin improves while operating cash flow stays negative because working capital and warranty absorb cash.",
    },
    {
      title: "Customer concentration and contract quality",
      detail:
        "Large AI infrastructure orders can create lumpiness, renegotiation risk and dependence on a small number of hyperscale or utility counterparties.",
      severity: "medium",
      killSignal: "One customer or financing partner accounts for most backlog growth without transparent delivery milestones.",
    },
    {
      title: "Alternative power solutions",
      detail:
        "Gas turbines, batteries, utility-scale PPAs, grid upgrades, nuclear deals or colocated generation can compete away the time-to-power premium.",
      severity: "medium",
      killSignal: "Hyperscalers shift incremental campuses toward utility/generation alternatives with better economics.",
    },
    {
      title: "Hydrogen optionality overcapitalized",
      detail:
        "Electrolyzer or hydrogen-ready narratives can inflate the multiple before commercial economics are proven.",
      severity: "medium",
      killSignal: "Hydrogen projects remain subsidy-dependent and do not produce material profitable orders.",
    },
  ],
  monitoring: [
    "Product backlog roll-forward",
    "Data-center customer deployments and MW commissioned",
    "FY2026 revenue guide revisions",
    "Gross margin and warranty accruals",
    "Operating cash flow and working capital",
    "Customer concentration",
    "Hydrogen/electrolyzer commercial orders",
    "Alternative power announcements from hyperscalers",
  ],
  sourceGaps: [
    "BE backend SQLite, daily price bars, SPY backtest and persisted valuation_runs are not implemented yet.",
    "Historical valuation rows use manual market-data proxies and should be replaced with nearest-prior trading day adjusted close from backend daily_price_bars.",
    "Backlog roll-forward, customer concentration, project-financing terms and service-margin details require official transcript/filing ingestion.",
    "Quarter-level revenue and gross-margin history includes local derived/proxy rows where official parsed data has not yet been normalized into the backend.",
  ],
});
