import type { StockValuationConfig, ValuationAssumption, ValuationScenario } from "../types";
import type { AaplScenarioPresetMap, AaplValuationAssumptions } from "./model";

export const defaultAaplValuationAssumptions: AaplValuationAssumptions = {
  currentPrice: 212,
  dilutedShares: 14_850,
  netCashDebt: 34_000,
  iPhoneGrowth: 0.01,
  servicesGrowth: 0.09,
  otherProductsGrowth: 0.02,
  productsGrossMargin: 0.37,
  servicesGrossMargin: 0.74,
  operatingMargin: 0.32,
  normalizedFcfMargin: 0.265,
  targetFcfYield: 0.038,
  targetPe: 27,
  targetEvEbit: 24,
  productsSalesMultiple: 5.0,
  servicesSalesMultiple: 8.5,
  aiOptionalityPerShare: 8,
  servicesRegulatoryHaircut: 0.05,
  chinaRiskHaircut: 0.06,
  buybackYield: 0.035,
  dividendYield: 0.005,
};

export const aaplScenarioPresets: AaplScenarioPresetMap = {
  Bear: {
    ...defaultAaplValuationAssumptions,
    iPhoneGrowth: -0.03,
    servicesGrowth: 0.045,
    otherProductsGrowth: -0.02,
    productsGrossMargin: 0.345,
    servicesGrossMargin: 0.68,
    operatingMargin: 0.285,
    normalizedFcfMargin: 0.225,
    targetFcfYield: 0.052,
    targetPe: 20,
    targetEvEbit: 17,
    productsSalesMultiple: 3.4,
    servicesSalesMultiple: 5.8,
    aiOptionalityPerShare: 0,
    servicesRegulatoryHaircut: 0.11,
    chinaRiskHaircut: 0.12,
    buybackYield: 0.02,
  },
  Base: defaultAaplValuationAssumptions,
  Bull: {
    ...defaultAaplValuationAssumptions,
    iPhoneGrowth: 0.055,
    servicesGrowth: 0.13,
    otherProductsGrowth: 0.045,
    productsGrossMargin: 0.39,
    servicesGrossMargin: 0.765,
    operatingMargin: 0.35,
    normalizedFcfMargin: 0.295,
    targetFcfYield: 0.032,
    targetPe: 32,
    targetEvEbit: 29,
    productsSalesMultiple: 6.0,
    servicesSalesMultiple: 10.5,
    aiOptionalityPerShare: 20,
    servicesRegulatoryHaircut: 0.025,
    chinaRiskHaircut: 0.035,
    buybackYield: 0.045,
  },
};

export const aaplValuationAssumptionDefinitions: ValuationAssumption[] = [
  {
    key: "currentPrice",
    label: "Current Price",
    value: defaultAaplValuationAssumptions.currentPrice,
    min: 50,
    max: 350,
    step: 1,
    format: "currency",
    source: "actual",
    description: "AAPL share price used for upside/downside.",
    category: "Market",
  },
  {
    key: "iPhoneGrowth",
    label: "iPhone Growth",
    value: defaultAaplValuationAssumptions.iPhoneGrowth,
    min: -0.08,
    max: 0.10,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Normalized iPhone revenue growth from replacement cycles, units, and ASP.",
    category: "iPhone Cycle",
  },
  {
    key: "servicesGrowth",
    label: "Services Growth",
    value: defaultAaplValuationAssumptions.servicesGrowth,
    min: 0,
    max: 0.18,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Services revenue growth from installed-base monetization and paid subscriptions.",
    category: "Services",
  },
  {
    key: "servicesGrossMargin",
    label: "Services Gross Margin",
    value: defaultAaplValuationAssumptions.servicesGrossMargin,
    min: 0.55,
    max: 0.82,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Services gross margin before explicit regulatory haircuts.",
    category: "Services",
  },
  {
    key: "productsGrossMargin",
    label: "Products Gross Margin",
    value: defaultAaplValuationAssumptions.productsGrossMargin,
    min: 0.30,
    max: 0.44,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Products gross margin, reflecting mix, component costs, and pricing.",
    category: "Products",
  },
  {
    key: "operatingMargin",
    label: "Operating Margin",
    value: defaultAaplValuationAssumptions.operatingMargin,
    min: 0.24,
    max: 0.40,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Normalized operating margin after mix and opex leverage.",
    category: "Margins",
  },
  {
    key: "normalizedFcfMargin",
    label: "FCF Margin",
    value: defaultAaplValuationAssumptions.normalizedFcfMargin,
    min: 0.18,
    max: 0.34,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Normalized free-cash-flow margin after capex and working capital.",
    category: "Cash Flow",
  },
  {
    key: "targetFcfYield",
    label: "Target FCF Yield",
    value: defaultAaplValuationAssumptions.targetFcfYield,
    min: 0.025,
    max: 0.07,
    step: 0.001,
    format: "percent",
    source: "assumption",
    description: "Equity FCF yield for mature quality-growth valuation.",
    category: "Valuation",
  },
  {
    key: "targetPe",
    label: "Target P/E",
    value: defaultAaplValuationAssumptions.targetPe,
    min: 14,
    max: 38,
    step: 0.5,
    format: "multiple",
    source: "assumption",
    description: "Normalized EPS multiple for Apple ecosystem durability.",
    category: "Valuation",
  },
  {
    key: "servicesRegulatoryHaircut",
    label: "Services Regulation Haircut",
    value: defaultAaplValuationAssumptions.servicesRegulatoryHaircut,
    min: 0,
    max: 0.18,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Valuation haircut for App Store take-rate, DMA, and search/TAC risks.",
    category: "Risk",
  },
  {
    key: "chinaRiskHaircut",
    label: "China Risk Haircut",
    value: defaultAaplValuationAssumptions.chinaRiskHaircut,
    min: 0,
    max: 0.20,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Valuation haircut for China demand, competition, and policy risk.",
    category: "Risk",
  },
  {
    key: "aiOptionalityPerShare",
    label: "AI Optionality / Share",
    value: defaultAaplValuationAssumptions.aiOptionalityPerShare,
    min: 0,
    max: 35,
    step: 1,
    format: "currency",
    source: "assumption",
    description: "Explicit per-share optionality for Apple Intelligence upgrade-cycle upside.",
    category: "AI Upgrade Cycle",
  },
  {
    key: "buybackYield",
    label: "Buyback Yield",
    value: defaultAaplValuationAssumptions.buybackYield,
    min: 0,
    max: 0.08,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Annual share count reduction contribution from capital return.",
    category: "Capital Return",
  },
];

export const aaplScenarioConfig: ValuationScenario[] = Object.entries(aaplScenarioPresets).map(([name, assumptions]) => ({
  name: name as keyof AaplScenarioPresetMap,
  assumptions,
}));

export function buildAaplValuationConfig(
  calculateValuation: StockValuationConfig["calculateValuation"],
): StockValuationConfig {
  return {
    ticker: "AAPL",
    modelType: "Apple DCF / FCF yield / P-E / EV-EBIT / SOTP with Services, China, AI, and capital-return drivers",
    assumptions: aaplValuationAssumptionDefinitions,
    scenarios: aaplScenarioConfig,
    calculateValuation,
  };
}
