import type { AaplDataset } from "./model";

export const aaplDataset: AaplDataset = {
  latestReportingPeriod: "FY2026 Q2",
  marketData: {
    currentPrice: 212,
    priceDate: "2026-05-12",
    sharesForMarketCap: 14_850,
    marketCap: 3_148_200,
    source: "research_only offline fallback; backend daily price bars override this when API is online",
    sourceStatus: "research_only",
  },
  periods: [
    {
      id: "fy2025",
      label: "FY2025",
      fiscalYear: 2025,
      periodType: "annual",
      sourceStatus: "research_only",
      sourceId: "aapl-static-fallback-fy2025",
      revenue: 416_161,
      grossProfit: 194_000,
      grossMargin: 0.466,
      operatingIncome: 133_000,
      operatingMargin: 0.319,
      netIncome: 112_000,
      dilutedShares: 14_950,
      operatingCashFlow: 121_000,
      capex: 12_000,
      freeCashFlow: 109_000,
      dividendsPaid: 15_500,
      buybacks: 86_000,
      cashAndMarketableSecurities: 132_000,
      debt: 98_000,
      netCashDebt: 34_000,
      notes: "Static offline fallback used only when the AAPL backend API is unavailable.",
    },
    {
      id: "q2-fy26",
      label: "FY2026 Q2",
      fiscalYear: 2026,
      fiscalQuarter: "Q2",
      periodType: "quarter",
      sourceStatus: "research_only",
      sourceId: "aapl-static-fallback-q2-fy26",
      revenue: 95_400,
      grossProfit: 45_300,
      grossMargin: 0.475,
      operatingIncome: 30_000,
      operatingMargin: 0.314,
      netIncome: 25_200,
      dilutedShares: 14_850,
      operatingCashFlow: 28_000,
      capex: 3_200,
      freeCashFlow: 24_800,
      dividendsPaid: 3_900,
      buybacks: 23_000,
      cashAndMarketableSecurities: 132_000,
      debt: 98_000,
      netCashDebt: 34_000,
      notes: "Static offline fallback used only when the AAPL backend API is unavailable.",
    },
  ],
  productFinancials: [
    { periodId: "q2-fy26", productCategory: "iPhone", revenue: 46_800, sourceStatus: "research_only" },
    { periodId: "q2-fy26", productCategory: "Services", revenue: 26_600, grossMargin: 0.75, sourceStatus: "research_only" },
    { periodId: "q2-fy26", productCategory: "Mac", revenue: 7_900, sourceStatus: "research_only" },
    { periodId: "q2-fy26", productCategory: "iPad", revenue: 6_400, sourceStatus: "research_only" },
    { periodId: "q2-fy26", productCategory: "Wearables, Home and Accessories", revenue: 7_700, sourceStatus: "research_only" },
    { periodId: "q2-fy26", productCategory: "Products", revenue: 68_800, grossMargin: 0.37, sourceStatus: "research_only" },
  ],
  geographicFinancials: [
    { periodId: "q2-fy26", geography: "Americas", revenue: 40_800, sourceStatus: "research_only" },
    { periodId: "q2-fy26", geography: "Europe", revenue: 24_500, sourceStatus: "research_only" },
    { periodId: "q2-fy26", geography: "Greater China", revenue: 16_100, sourceStatus: "research_only" },
    { periodId: "q2-fy26", geography: "Japan", revenue: 6_900, sourceStatus: "research_only" },
    { periodId: "q2-fy26", geography: "Rest of Asia Pacific", revenue: 7_100, sourceStatus: "research_only" },
  ],
  operatingMetrics: [
    {
      periodId: "q2-fy26",
      asOfDate: "2026-05-12",
      sourceStatus: "research_only",
      installedBaseCommentary: "Backend offline fallback: installed base durability is treated as the core Services monetization substrate.",
      iphoneCycleCommentary: "Backend offline fallback: replacement cycle is assumed mature, with Apple Intelligence upside handled as scenario optionality.",
      appStoreRegulationCommentary: "Backend offline fallback: Services take-rate risk is modeled as an explicit valuation haircut.",
      chinaCommentary: "Backend offline fallback: Greater China is separated as a risk panel and valuation haircut rather than buried in total growth.",
      aiAppleIntelligenceCommentary: "Backend offline fallback: AI optionality is zeroed out for historical pre-2024 backend runs.",
      capitalReturnCommentary: "Backend offline fallback: buybacks and share-count decline are explicit valuation drivers.",
    },
  ],
};
