export const RTX_BACKEND_MODEL_VERSION = {
  version: "rtx_v1_backend_pilot",
  name: "RTX backend-separated valuation pilot",
  description:
    "Maps RTX SQLite reporting-event snapshots into the existing defense-prime frontend valuation engine while preserving event-date source boundaries.",
  sourceIsolationPolicy: {
    officialActuals: "RTX official releases cached locally plus event-dated source metadata.",
    managementGuidance: "Stored separately in guidance_items and not valuation-impacting unless explicitly promoted.",
    forecastAssumptions: "Event-dated assumption_sets generated by scenario and reporting event.",
    transcriptCommentary: "Stored as candidate commentary with modelReady=false.",
    researchOnly: "Pre-merger and missing-quarter continuity rows are marked research_only and surfaced in validation warnings.",
    marketData: "Daily price bars anchor historical currentPrice using nearest prior trading day.",
  },
};
