import type { DeepResearchDataset } from "../deepResearch/model";

const marketData = {
  currentPrice: 45.54,
  priceDate: "2026-05-19",
  source: "Market data snapshot captured 2026-05-19; verify against live feed before trading.",
  sourceStatus: "market_data_proxy" as const,
};

const defaultAssumptions = {
  currentPrice: marketData.currentPrice,
  revenueBase: 1600,
  revenueCagr3Y: 0.25,
  terminalGrowth: 0.035,
  normalizedFcfMargin: 0.12,
  exitFcfMultiple: 35,
  evRevenueMultiple: 5.5,
  discountRate: 0.13,
  netCashDebt: 100,
  dilutedShares: 180,
  qualityAdjustment: 0.95,
  riskHaircut: 0.22,
  dividendYield: 0,
  buybackYield: -0.015,
};

export const temDataset: DeepResearchDataset = {
  ticker: "TEM",
  companyName: "Tempus AI, Inc.",
  sector: "Healthcare AI / Precision Medicine / Clinical Data",
  archetype: "High-growth healthcare AI platform / limited public history",
  currency: "USD",
  description:
    "TEM cockpit focused on oncology test volume, data licensing, pharma partnerships, AI clinical workflow adoption, reimbursement, gross-margin scaling, cash burn, dilution, and regulatory risk.",
  updatedAt: "2026-05-19",
  marketData,
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "oncology-testing", label: "Oncology Testing" },
    { value: "data-ai-platform", label: "Data / AI Platform" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "revenue-growth", label: "Revenue Growth", value: 0.33, format: "percent", description: "Growth is the core bull case, but mix quality matters.", badge: "Assumption" },
    { key: "data-mix", label: "Data / AI Mix", value: 0.28, format: "percent", description: "Higher-margin data and AI services need to grow faster than testing.", badge: "Derived" },
    { key: "cash-burn-risk", label: "Cash Burn Risk", value: 0.42, format: "percent", description: "Negative FCF and dilution risk remain central.", badge: "Derived" },
    { key: "fcf-margin", label: "Target FCF Margin", value: defaultAssumptions.normalizedFcfMargin, format: "percent", description: "Long-term assumption, not current profitability.", badge: "Assumption" },
    { key: "history-years", label: "Public History", value: 2, format: "number", description: "Limited post-IPO reporting history; 8-year valuation history is not feasible yet.", badge: "Needs Review" },
  ],
  researchQuestions: [
    {
      key: "test-volume",
      question: "Can oncology testing volume compound without margin degradation?",
      currentView: "Testing gives clinical data density and revenue scale, but reimbursement and lab efficiency determine cash conversion.",
      metric: "Clinical test volume, revenue per test, lab gross margin",
      evidenceNeeded: "Volume growth, payer coverage, collection rate and gross margin bridge",
      valuationTie: "Revenue CAGR and normalized FCF margin",
      bearCase: "Testing volume grows but reimbursement pressure prevents operating leverage.",
    },
    {
      key: "data-licensing",
      question: "Is the data / AI layer becoming a repeatable high-margin business?",
      currentView: "The core debate is whether pharma and provider AI adoption can convert clinical data into durable recurring revenue.",
      metric: "Data licensing revenue, pharma customer expansion, AI workflow usage",
      evidenceNeeded: "Contract duration, renewal, attach rate and productized AI revenue",
      valuationTie: "EV/revenue cross-check and quality adjustment",
      bearCase: "Data revenue remains project-based and lower visibility than SaaS.",
    },
    {
      key: "regulatory",
      question: "Does regulatory and privacy complexity cap monetization?",
      currentView: "Healthcare data is valuable because it is scarce; that same scarcity creates consent, privacy and compliance friction.",
      metric: "HIPAA/privacy controls, FDA/regulatory milestones, data rights",
      evidenceNeeded: "Audit trail, consent model, product clearance, payer/provider adoption",
      valuationTie: "Risk haircut",
      bearCase: "Regulatory scrutiny slows AI workflow deployment.",
    },
    {
      key: "dilution",
      question: "Can the company scale without repeated dilution?",
      currentView: "If gross margin expansion and data revenue lag, equity dilution can absorb much of the upside.",
      metric: "FCF, SBC, share count, cash runway",
      evidenceNeeded: "Quarterly cash burn and fully diluted share count",
      valuationTie: "Diluted shares and buybackYield / dilution input",
      bearCase: "High growth comes with persistent negative FCF and dilution.",
    },
  ],
  kpiSeries: [
    {
      key: "oncology-testing",
      title: "Clinical Testing Scale vs Gross Margin",
      subtitle: "Testing volume must create data density and operating leverage, not just revenue growth.",
      sourceStatus: "research_only",
      measures: [
        { key: "testRevenue", label: "Clinical testing revenue proxy ($m)", format: "currency", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "grossMargin", label: "Gross margin %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q2", testRevenue: 132, grossMargin: 50 },
        { period: "FY2024 Q3", testRevenue: 145, grossMargin: 51 },
        { period: "FY2024 Q4", testRevenue: 161, grossMargin: 52 },
        { period: "FY2025 Q1", testRevenue: 174, grossMargin: 52 },
        { period: "FY2025 Q2", testRevenue: 188, grossMargin: 53 },
        { period: "FY2025 Q3", testRevenue: 202, grossMargin: 54 },
        { period: "FY2025 Q4", testRevenue: 223, grossMargin: 55 },
        { period: "FY2026 Q1", testRevenue: 241, grossMargin: 56 },
      ],
    },
    {
      key: "data-ai-platform",
      title: "Data / AI Revenue Mix and Cash Burn",
      subtitle: "The bull case needs higher-margin data and AI tools to offset cash burn and dilution.",
      sourceStatus: "research_only",
      measures: [
        { key: "dataAiRevenue", label: "Data / AI revenue proxy ($m)", format: "currency", chartType: "bar", color: "#7c3aed", axis: "left" },
        { key: "fcfMargin", label: "FCF margin %", format: "percent", chartType: "line", color: "#ef4444", axis: "right" },
      ],
      points: [
        { period: "FY2024 Q2", dataAiRevenue: 42, fcfMargin: -42 },
        { period: "FY2024 Q3", dataAiRevenue: 47, fcfMargin: -38 },
        { period: "FY2024 Q4", dataAiRevenue: 55, fcfMargin: -34 },
        { period: "FY2025 Q1", dataAiRevenue: 63, fcfMargin: -30 },
        { period: "FY2025 Q2", dataAiRevenue: 71, fcfMargin: -27 },
        { period: "FY2025 Q3", dataAiRevenue: 83, fcfMargin: -23 },
        { period: "FY2025 Q4", dataAiRevenue: 96, fcfMargin: -20 },
        { period: "FY2026 Q1", dataAiRevenue: 108, fcfMargin: -18 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "testing-flywheel",
      tab: "oncology-testing",
      title: "Testing Data Flywheel",
      thesis: "Clinical testing is valuable if each test expands longitudinal data density and improves downstream pharma/provider monetization.",
      evidence: ["Test volume", "Revenue per test", "Turnaround time", "Data completeness"],
      watchItems: ["Payer denials", "Lab utilization", "Gross margin ceiling"],
      sourceStatus: "research_only",
    },
    {
      key: "ai-monetization",
      tab: "data-ai-platform",
      title: "AI / Data Monetization",
      thesis: "The market will pay a software-like multiple only if data products become recurring, high-margin and less service-intensive.",
      evidence: ["Pharma data contracts", "AI product adoption", "Renewals and expansion"],
      watchItems: ["Project-based revenue", "Privacy constraints", "Provider workflow friction"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-05-05", headline: "Data monetization vs cash burn", keyQuestions: ["How much revenue is recurring data / AI?", "Is gross margin expanding with scale?", "What is cash burn and fully diluted shares?"], managementTone: "Growth-focused.", modelReadThrough: "Do not raise terminal FCF margin until data revenue durability is clearer.", riskSignal: "Needs Review", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q4", eventDate: "2026-02-25", headline: "Guidance quality and mix", keyQuestions: ["Is 2026 growth testing-led or data-led?", "Any reimbursement risk?", "Does guidance imply operating leverage?"], managementTone: "Optimistic.", modelReadThrough: "Revenue CAGR supported; risk haircut remains high.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-11-06", headline: "AI workflow proof points", keyQuestions: ["Are AI tools used in clinical workflow?", "Can pharma contracts scale?", "Any gross margin inflection?"], managementTone: "Constructive but early.", modelReadThrough: "Keep EV/revenue cross-check low-weighted.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-08-07", headline: "Test volume and collections", keyQuestions: ["Volume growth vs revenue per test?", "Collections and payer coverage?", "Data attach rate?"], managementTone: "Execution-oriented.", modelReadThrough: "Testing scale helps but margin still unproven.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-05-08", headline: "Public-company cadence", keyQuestions: ["How transparent is KPI disclosure?", "What is cash runway?", "Can data contracts offset burn?"], managementTone: "Early-stage public reporting.", modelReadThrough: "Limit confidence score until KPI cadence improves.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-02-28", headline: "First full-year public evidence", keyQuestions: ["Is growth repeatable?", "What is gross margin ceiling?", "What is dilution path?"], managementTone: "Growth narrative.", modelReadThrough: "Valuation should remain scenario-weighted.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-11-07", headline: "Data business validation", keyQuestions: ["Pharma contract expansion?", "Provider adoption?", "Data rights and compliance?"], managementTone: "Early proof points.", modelReadThrough: "High optionality but low reliability.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-08-06", headline: "IPO-era baseline", keyQuestions: ["What are real unit economics?", "How much revenue is one-time?", "What is cash burn?"], managementTone: "Early.", modelReadThrough: "Use wide valuation range and high risk haircut.", riskSignal: "Needs Review", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { id: "tem-2024q2", eventDate: "2024-08-06", fiscalPeriod: "FY2024 Q2", asOfPrice: 38, fairValue: 30, targetPrice3Y: 42, expectedShareholderCagr: 0.034, method: "IPO-era EV/revenue with high burn haircut.", sourceStatus: "research_only", warnings: ["Limited public history; not an 8-year series."], methodOutputs: [{ label: "EV/revenue", value: 30, format: "currency", description: "High uncertainty." }] },
    { id: "tem-2024q3", eventDate: "2024-11-07", fiscalPeriod: "FY2024 Q3", asOfPrice: 52, fairValue: 34, targetPrice3Y: 48, expectedShareholderCagr: -0.026, method: "Data optionality + cash-burn haircut.", sourceStatus: "research_only", warnings: ["Short post-IPO history."], methodOutputs: [{ label: "Blend", value: 34, format: "currency", description: "High risk haircut." }] },
    { id: "tem-2024q4", eventDate: "2025-02-28", fiscalPeriod: "FY2024 Q4", asOfPrice: 61, fairValue: 37, targetPrice3Y: 52, expectedShareholderCagr: -0.052, method: "Revenue growth / dilution bridge.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 35, format: "currency", description: "Burn still meaningful." }] },
    { id: "tem-2025q1", eventDate: "2025-05-08", fiscalPeriod: "FY2025 Q1", asOfPrice: 48, fairValue: 39, targetPrice3Y: 55, expectedShareholderCagr: 0.046, method: "Testing scale with data optionality.", sourceStatus: "research_only", warnings: ["Local fallback."], methodOutputs: [{ label: "EV/revenue", value: 41, format: "currency", description: "Growth strong." }] },
    { id: "tem-2025q2", eventDate: "2025-08-07", fiscalPeriod: "FY2025 Q2", asOfPrice: 41, fairValue: 40, targetPrice3Y: 56, expectedShareholderCagr: 0.109, method: "Collections / gross margin watch.", sourceStatus: "research_only", warnings: ["No daily backend price bars."], methodOutputs: [{ label: "Blend", value: 40, format: "currency", description: "Risk-adjusted." }] },
    { id: "tem-2025q3", eventDate: "2025-11-06", fiscalPeriod: "FY2025 Q3", asOfPrice: 44, fairValue: 42, targetPrice3Y: 60, expectedShareholderCagr: 0.109, method: "AI workflow optionality.", sourceStatus: "research_only", warnings: ["Local fallback."], methodOutputs: [{ label: "DCF", value: 39, format: "currency", description: "Path to FCF still uncertain." }] },
    { id: "tem-2025q4", eventDate: "2026-02-25", fiscalPeriod: "FY2025 Q4", asOfPrice: 39, fairValue: 43, targetPrice3Y: 62, expectedShareholderCagr: 0.167, method: "2026 guidance mix quality.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "EV/revenue", value: 45, format: "currency", description: "Growth vs burn." }] },
    { id: "tem-2026q1", eventDate: "2026-05-05", fiscalPeriod: "FY2026 Q1", asOfPrice: 46, fairValue: 44, targetPrice3Y: 64, expectedShareholderCagr: 0.116, method: "Data / AI growth plus burn haircut.", sourceStatus: "official_actual", warnings: ["Backend valuation run not persisted; short public history."], methodOutputs: [{ label: "Blend", value: 44, format: "currency", description: "High-growth, high-risk." }] },
  ],
  valuation: {
    defaultAssumptions,
    scenarios: {
      Bear: { ...defaultAssumptions, revenueCagr3Y: 0.12, normalizedFcfMargin: 0.02, exitFcfMultiple: 18, evRevenueMultiple: 2.8, discountRate: 0.16, qualityAdjustment: 0.82, riskHaircut: 0.35, buybackYield: -0.035 },
      Base: defaultAssumptions,
      Bull: { ...defaultAssumptions, revenueCagr3Y: 0.36, normalizedFcfMargin: 0.2, exitFcfMultiple: 45, evRevenueMultiple: 8.5, discountRate: 0.11, qualityAdjustment: 1.08, riskHaircut: 0.15, buybackYield: -0.005 },
    },
    modelDescription: "High-growth healthcare AI model using DCF, FCF multiple and EV/revenue cross-check with explicit dilution and risk haircut.",
    noFutureLeakageNote: "TEM history is short because the company has limited public reporting history; rows do not assume current AI/data mix in IPO-era quarters.",
  },
  risks: [
    { title: "Cash burn and dilution", detail: "The stock can be right on revenue and wrong on per-share value if dilution remains high.", severity: "high", killSignal: "FCF losses persist while share count rises faster than revenue quality." },
    { title: "Data revenue not recurring", detail: "A project-based pharma data business deserves a lower multiple than recurring software.", severity: "high", killSignal: "Data / AI revenue remains lumpy and low-visibility." },
    { title: "Regulatory / privacy friction", detail: "Healthcare data rights and AI workflow deployment can slow monetization.", severity: "medium", killSignal: "Major payer/provider privacy or compliance setback." },
  ],
  monitoring: ["Clinical test volume", "Data / AI revenue mix", "Gross margin", "FCF burn", "Diluted shares", "Payer coverage and reimbursement"],
  sourceGaps: ["TEM has limited public history; eight-year quarterly history is not feasible.", "Backend valuation and daily price bars are not yet implemented.", "Clinical test and data-mix rows are research proxies until official KPI extraction is automated."],
  backendStatus: {
    supported: false,
    detail: "TEM has frontend local history and a short public-company valuation panel; backend SQLite and AWS data sync are deferred.",
    nextSteps: ["Create TEM backend DB.", "Import TEM/SPY prices from IPO onward.", "Persist valuation runs by quarterly event.", "Automate filing/transcript KPI extraction."],
  },
  qualityBadges: [
    { label: "Public history", value: "Short", badge: "Needs Review" },
    { label: "Data / AI mix", value: "Proxy", badge: "Assumption" },
    { label: "Historical valuation", value: "Local fallback", badge: "Placeholder" },
  ],
};
