import type { Scenario, ValuationAssumption, ValuationScenario } from "../types";
import type { LegnValuationAssumptions } from "./types";
import { legnDataset } from "./data";

export const defaultLegnValuationAssumptions: LegnValuationAssumptions = {
  currentPrice: legnDataset.marketData.currentPrice,
  approvedPeakNts: legnDataset.assumptions.commercialScenarios.Base.approvedPeakNts,
  ntsToLegendRevenueRatio: legnDataset.collaborationEconomicsBridge.ntsToCollaborationRevenueRatio,
  productDiscountRate: 0.105,
  labelExpansionProbabilityScalar: 1,
  platformOptionScalar: 1,
  bearDilutionUsdM: 450,
};

export const legnScenarioPresets: Record<Scenario, LegnValuationAssumptions> = {
  Bear: {
    currentPrice: legnDataset.marketData.currentPrice,
    approvedPeakNts: legnDataset.assumptions.commercialScenarios.Bear.approvedPeakNts,
    ntsToLegendRevenueRatio: legnDataset.collaborationEconomicsBridge.ntsToCollaborationRevenueRatio * 0.96,
    productDiscountRate: 0.115,
    labelExpansionProbabilityScalar: 0.72,
    platformOptionScalar: 0.65,
    bearDilutionUsdM: 450,
  },
  Base: defaultLegnValuationAssumptions,
  Bull: {
    currentPrice: legnDataset.marketData.currentPrice,
    approvedPeakNts: legnDataset.assumptions.commercialScenarios.Bull.approvedPeakNts,
    ntsToLegendRevenueRatio: legnDataset.collaborationEconomicsBridge.ntsToCollaborationRevenueRatio * 1.02,
    productDiscountRate: 0.095,
    labelExpansionProbabilityScalar: 1.35,
    platformOptionScalar: 1.45,
    bearDilutionUsdM: 0,
  },
};

export const legnValuationAssumptionKeys = [
  "currentPrice",
  "approvedPeakNts",
  "ntsToLegendRevenueRatio",
  "productDiscountRate",
  "labelExpansionProbabilityScalar",
  "platformOptionScalar",
  "bearDilutionUsdM",
] as const;

export const legnAssumptionDefinitions: ValuationAssumption[] = [
  {
    key: "currentPrice",
    label: "Current ADS Price",
    value: defaultLegnValuationAssumptions.currentPrice,
    min: 10,
    max: 80,
    step: 1,
    format: "currency",
    source: "actual",
    description: "Dated public market snapshot per LEGN ADS.",
    category: "Market",
    unit: "USD",
    periodicity: "LTM",
    asOfDate: legnDataset.marketData.priceDate,
    provenance: "market_data: StockAnalysis snapshot, per ADS.",
  },
  {
    key: "approvedPeakNts",
    label: "Approved-Label Peak NTS",
    value: defaultLegnValuationAssumptions.approvedPeakNts,
    min: 3_000,
    max: 8_000,
    step: 250,
    format: "currency",
    source: "assumption",
    description: "CARVYKTI gross net trade sales peak excluding frontline optionality.",
    category: "CARVYKTI Commercial",
    unit: "USD",
    periodicity: "annual",
    asOfDate: "2026-05-12",
    provenance: "research_assumption: commercial launch curve.",
  },
  {
    key: "ntsToLegendRevenueRatio",
    label: "NTS to Legend Revenue",
    value: defaultLegnValuationAssumptions.ntsToLegendRevenueRatio,
    min: 0.42,
    max: 0.58,
    step: 0.01,
    format: "percent",
    source: "derived",
    description: "Bridge from CARVYKTI NTS to Legend collaboration revenue using FY 2025 reported data.",
    category: "Collaboration Economics",
    unit: "percent",
    periodicity: "annual",
    asOfDate: "2025-12-31",
    provenance: "derived: FY 2025 collaboration revenue divided by CARVYKTI NTS.",
  },
  {
    key: "productDiscountRate",
    label: "Product Discount Rate",
    value: defaultLegnValuationAssumptions.productDiscountRate,
    min: 0.08,
    max: 0.14,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Approved commercial product discount rate; not a mature-pharma terminal WACC.",
    category: "Valuation",
    unit: "percent",
    periodicity: "annual",
    asOfDate: "2026-05-12",
    provenance: "research_assumption: stage-gated biotech NAV.",
  },
  {
    key: "labelExpansionProbabilityScalar",
    label: "Label POS Scalar",
    value: defaultLegnValuationAssumptions.labelExpansionProbabilityScalar,
    min: 0.5,
    max: 1.6,
    step: 0.05,
    format: "number",
    source: "assumption",
    description: "Applies to CARTITUDE-5/6/10 label-expansion probabilities.",
    category: "Label Expansion",
    unit: "number",
    periodicity: "annual",
    asOfDate: "2026-05-12",
    provenance: "research_assumption: scenario probability scalar.",
  },
  {
    key: "platformOptionScalar",
    label: "Platform Option Scalar",
    value: defaultLegnValuationAssumptions.platformOptionScalar,
    min: 0,
    max: 2,
    step: 0.1,
    format: "number",
    source: "assumption",
    description: "Scalar for speculative in vivo/allogeneic/autoimmune platform value.",
    category: "Platform",
    unit: "number",
    periodicity: "annual",
    asOfDate: "2026-05-12",
    provenance: "research_assumption: option value only.",
  },
  {
    key: "bearDilutionUsdM",
    label: "Bear Dilution",
    value: defaultLegnValuationAssumptions.bearDilutionUsdM,
    min: 0,
    max: 1_000,
    step: 50,
    format: "currency",
    source: "assumption",
    description: "Bear-case equity raise placeholder if profitability slips.",
    category: "Funding",
    unit: "USD",
    periodicity: "annual",
    asOfDate: "2026-05-12",
    provenance: "research_assumption: dilution stress case.",
  },
];

export const legnScenarioDefinitions: ValuationScenario[] = (["Bear", "Base", "Bull"] as Scenario[]).map((name) => ({
  name,
  assumptions: Object.fromEntries(legnValuationAssumptionKeys.map((key) => [key, legnScenarioPresets[name][key]])),
}));
