import type { EarningsCallDataset, EarningsFocusTopic } from "../earningsCall/types";

const focus = (topic: EarningsFocusTopic, intensity: number, summary: string) => ({ topic, intensity, summary });

export const autlEarningsDataset: EarningsCallDataset = {
  ticker: "AUTL",
  name: "Autolus Therapeutics",
  sector: "Commercial-stage cell therapy / AUCATZYL / obe-cel platform",
  currency: "USD",
  currentPrice: 1.61,
  priceDate: "2026-05-07",
  primaryMetricName: "AUCATZYL Revenue",
  currentPeriodId: "q4-2025",
  moduleSummary:
    "AUTL is framed around whether AUCATZYL can scale from a first-year launch into a profitable niche cell-therapy business while the obe-cel platform expands into pediatric ALL and autoimmune indications.",
  valuationNote: "This module is earnings-call intelligence only; a full AUTL valuation would require AUCATZYL launch curve, manufacturing COGS, cash runway and pipeline rNPV.",
  evidence: [
    { id: "autl-q1-2024", title: "AUTL Q1 2024 results", sourceType: "official_press_release", date: "2024-05-09", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-first-quarter-2024-financial", extractedMetric: "Pre-approval obe-cel launch prep and cash runway", confidence: "medium" },
    { id: "autl-q2-2024", title: "AUTL Q2 2024 results", sourceType: "official_press_release", date: "2024-08-08", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-second-quarter-2024-financial", extractedMetric: "AUCATZYL regulatory preparation and manufacturing readiness", confidence: "medium" },
    { id: "autl-q3-2024", title: "AUTL Q3 2024 results", sourceType: "official_press_release", date: "2024-11-07", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-third-quarter-2024-financial", extractedMetric: "AUCATZYL approval and launch preparation", confidence: "medium" },
    { id: "autl-q4-2024", title: "AUTL Q4/FY 2024 results", sourceType: "official_press_release", date: "2025-03-20", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-fourth-quarter-and-full-year-2024", extractedMetric: "First commercial period after AUCATZYL approval", confidence: "medium" },
    { id: "autl-q1-2025", title: "AUTL Q1 2025 results", sourceType: "official_press_release", date: "2025-05-08", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-first-quarter-2025-financial", extractedMetric: "Initial AUCATZYL launch revenue and centers", confidence: "medium" },
    { id: "autl-q2-2025", title: "AUTL Q2 2025 results", sourceType: "official_press_release", date: "2025-08-07", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-second-quarter-2025-financial", extractedMetric: "AUCATZYL launch progress, manufacturing and cash", confidence: "medium" },
    { id: "autl-q3-2025", title: "AUTL Q3 2025 results", sourceType: "official_press_release", date: "2025-11-06", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-third-quarter-2025-financial", extractedMetric: "AUCATZYL revenue ramp and guidance setup", confidence: "medium" },
    { id: "autl-q4-2025", title: "AUTL Q4/FY 2025 results", sourceType: "official_press_release", date: "2026-03-27", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-reports-fourth-quarter-and-full-year-2025/", extractedMetric: "Q4 2025 AUCATZYL revenue $23.3m; FY $74.3m; 2026 guide $120-135m", confidence: "high" },
    { id: "autl-jan-2026-prelim", title: "AUTL preliminary FY 2025 AUCATZYL update", sourceType: "official_press_release", date: "2026-01-12", url: "https://autolus.gcs-web.com/news-releases/news-release-details/autolus-therapeutics-announces-preliminary-unaudited-fourth/", extractedMetric: "Preliminary Q4 2025 AUCATZYL revenue about $24m and FY about $75m", confidence: "high" },
    { id: "autl-market-2026-05-07", title: "AUTL market data snapshot", sourceType: "market_data", date: "2026-05-07", url: "https://stockanalysis.com/stocks/autl/", extractedMetric: "AUTL closed at $1.61 on May 7, 2026", confidence: "medium" },
  ],
  quarters: [
    { id: "q1-2024", label: "Q1 2024", callDate: "2024-05-09", totalRevenue: 0, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 0, cashOrLiquidity: 758, managementTone: "pipeline", marketFocus: [focus("regulatory", 9, "AUCATZYL approval path dominated."), focus("cash_runway", 8, "Cash runway mattered before commercial revenue."), focus("launch_execution", 5, "Launch prep was visible but not yet measurable."), focus("pipeline", 6, "Obe-cel platform optionality supported the story.")], analystQuestions: ["Can obe-cel get approved?", "How long is cash runway?", "What launch infrastructure is needed?"], aiSummary: "AUTL was still a pre-commercial regulatory story, with cash runway and launch preparation as the key investor questions.", sourceEvidenceIds: ["autl-q1-2024"] },
    { id: "q2-2024", label: "Q2 2024", callDate: "2024-08-08", totalRevenue: 0, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 0, cashOrLiquidity: 720, managementTone: "pipeline", marketFocus: [focus("regulatory", 9, "Approval and label remained central."), focus("launch_execution", 6, "Manufacturing and center readiness became more concrete."), focus("cash_runway", 8, "Runway still shaped risk."), focus("cell_therapy", 7, "Safety/differentiation versus other CAR-T was a key theme.")], analystQuestions: ["What label can AUCATZYL receive?", "Can manufacturing support launch?", "What is the center onboarding plan?"], aiSummary: "The debate began shifting from binary approval to whether AUTL could launch a reliable cell therapy product.", sourceEvidenceIds: ["autl-q2-2024"] },
    { id: "q3-2024", label: "Q3 2024", callDate: "2024-11-07", totalRevenue: 0, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 0, cashOrLiquidity: 690, managementTone: "inflection", marketFocus: [focus("regulatory", 10, "AUCATZYL approval was the quarter's inflection."), focus("launch_execution", 8, "Initial center activation and reimbursement moved front and center."), focus("cell_therapy", 8, "Safety profile and low high-grade CRS/ICANS were key differentiation points."), focus("cash_runway", 7, "Commercial spend made runway still important.")], analystQuestions: ["How fast can centers come online?", "What is the early revenue curve?", "Can safety drive adoption?"], aiSummary: "Q3 2024 was the pivot from regulatory risk to launch execution risk.", sourceEvidenceIds: ["autl-q3-2024"] },
    { id: "q4-2024", label: "Q4 2024", callDate: "2025-03-20", totalRevenue: 2, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 2, cashOrLiquidity: 640, managementTone: "execution", marketFocus: [focus("launch_execution", 9, "First commercial sales made launch slope the core debate."), focus("cell_therapy", 8, "Manufacturing turnaround and safety experience drove adoption questions."), focus("cash_runway", 7, "Cash burn versus commercial ramp mattered."), focus("pipeline", 6, "Pediatric ALL and autoimmune expansion remained option value.")], analystQuestions: ["What is early demand?", "Can margins improve?", "How many centers are active?"], aiSummary: "The market started judging AUTL on commercial execution rather than approval probability.", sourceEvidenceIds: ["autl-q4-2024"] },
    { id: "q1-2025", label: "Q1 2025", callDate: "2025-05-08", totalRevenue: 9, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 9, cashOrLiquidity: 590, managementTone: "execution", marketFocus: [focus("launch_execution", 9, "Initial ramp and center onboarding dominated."), focus("margin", 6, "Gross margin path entered the debate."), focus("cash_runway", 7, "Cash runway still limited valuation flexibility."), focus("cell_therapy", 8, "Reliability and safety were adoption levers.")], analystQuestions: ["Is the launch ahead of expectations?", "What drives gross margin?", "Can AUTL avoid a financing overhang?"], aiSummary: "Q1 2025 showed early commercial traction, but investors still treated cash runway and manufacturing economics as gating issues.", sourceEvidenceIds: ["autl-q1-2025"] },
    { id: "q2-2025", label: "Q2 2025", callDate: "2025-08-07", totalRevenue: 17, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 17, cashOrLiquidity: 540, managementTone: "execution", marketFocus: [focus("launch_execution", 9, "Quarterly AUCATZYL revenue growth became the main scorecard."), focus("margin", 7, "Manufacturing COGS and gross margin mattered more."), focus("pipeline", 7, "CATULUS and autoimmune trials gained attention."), focus("cash_runway", 7, "Runway remained part of the risk case.")], analystQuestions: ["Can revenue keep compounding?", "When does gross margin turn positive?", "Which pipeline expansion matters first?"], aiSummary: "The conversation moved toward whether AUCATZYL could become a self-funding launch asset.", sourceEvidenceIds: ["autl-q2-2025"] },
    { id: "q3-2025", label: "Q3 2025", callDate: "2025-11-06", totalRevenue: 25, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 25, cashOrLiquidity: 500, managementTone: "inflection", marketFocus: [focus("launch_execution", 9, "AUCATZYL's first-year run-rate became measurable."), focus("margin", 8, "Positive gross margin in 2026 became a key debate."), focus("cash_runway", 6, "Improving revenue reduced but did not remove runway concerns."), focus("pipeline", 8, "Pediatric ALL, lupus and MS expanded the platform debate.")], analystQuestions: ["Is 2026 guidance credible?", "Can manufacturing scale without margin damage?", "What real-world data matter?"], aiSummary: "Q3 2025 reframed AUTL as a launch-growth and operating-leverage story.", sourceEvidenceIds: ["autl-q3-2025"] },
    { id: "q4-2025", label: "Q4 2025", callDate: "2026-03-27", totalRevenue: 23.3, revenueUnit: "USDm", primaryMetricLabel: "AUCATZYL", primaryMetric: 23.3, cashOrLiquidity: 460, managementTone: "execution", marketFocus: [focus("launch_execution", 10, "FY 2025 AUCATZYL revenue $74.3m and 2026 guide $120-135m drove the thesis."), focus("margin", 9, "Positive gross margin target became central."), focus("cell_therapy", 8, "Real-world favorable safety data were used to support adoption."), focus("pipeline", 8, "CATULUS, LUMINA and BOBCAT created platform optionality."), focus("cash_runway", 6, "Runway risk faded but remains relevant.")], analystQuestions: ["Can AUCATZYL hit $120-135m in 2026?", "How fast can gross margin turn positive?", "Does real-world safety improve adoption?"], aiSummary: "The current AUTL debate is whether a strong first-year launch can become a profitable, expandable cell-therapy franchise.", sourceEvidenceIds: ["autl-q4-2025", "autl-jan-2026-prelim"] },
  ],
};
