import type { TsmDataset } from "./model";

const tsmInvestorQ126 = "https://investor.tsmc.com/english/quarterly-results/2026/q1";
const tsmInvestorQ425 = "https://investor.tsmc.com/english/quarterly-results/2025/q4";
const tsmAnnual2025 = "https://investor.tsmc.com/static/annualReports/2025/english/index.html";

export const tsmDataset: TsmDataset = {
  latestReportingPeriod: "1Q26",
  marketData: {
    currentPrice: 414.15,
    priceDate: "2026-05-15",
    adrEquivalentShares: 5_186,
    netCashUsd: 55_000,
    source:
      "Market-data proxy for the NYSE ADR. Add TSM backend daily_price_bars before using historical valuation or backtest conclusions.",
    sourceStatus: "market_data_proxy",
  },
  periods: [
    {
      id: "fy2024",
      label: "FY2024",
      fiscalYear: 2024,
      periodType: "annual",
      asOfDate: "2025-02-13",
      sourceStatus: "official_actual",
      sourceUrl: tsmAnnual2025,
      revenueUsd: 90_080,
      revenueGrowth: null,
      grossMargin: 0.561,
      operatingMargin: 0.457,
      netIncomeUsd: 36_520,
      netMargin: 0.405,
      notes: "2025 annual report comparison table gives 2024 US dollar revenue and net income plus 2024 margin comparisons.",
    },
    {
      id: "fy2025",
      label: "FY2025",
      fiscalYear: 2025,
      periodType: "annual",
      asOfDate: "2026-02-12",
      sourceStatus: "official_actual",
      sourceUrl: tsmAnnual2025,
      revenueUsd: 122_420,
      revenueGrowth: 0.359,
      grossMargin: 0.599,
      operatingMargin: 0.508,
      netIncomeUsd: 55_210,
      netMargin: 0.451,
      dividendPerAdr: 18.0 / 31.59 * 5,
      notes:
        "Official annual report: 2025 US dollar revenue, net income, gross margin, operating margin, advanced-node mix and annual cash dividend per ordinary share.",
    },
    {
      id: "fy2025-q4",
      label: "4Q25",
      fiscalYear: 2025,
      fiscalQuarter: "Q4",
      periodType: "quarter",
      asOfDate: "2026-01-15",
      sourceStatus: "official_actual",
      sourceUrl: tsmInvestorQ425,
      revenueUsd: 33_730,
      revenueGrowth: null,
      grossMargin: 0.623,
      operatingMargin: 0.54,
      notes: "Official quarterly results page shows US dollar revenue and actual gross/operating margins.",
    },
    {
      id: "fy2026-q1",
      label: "1Q26",
      fiscalYear: 2026,
      fiscalQuarter: "Q1",
      periodType: "quarter",
      asOfDate: "2026-04-16",
      sourceStatus: "official_actual",
      sourceUrl: tsmInvestorQ126,
      revenueUsd: 35_900,
      revenueGrowth: 0.406,
      grossMargin: 0.662,
      operatingMargin: 0.581,
      netIncomeUsd: 18_122,
      netMargin: 0.505,
      dilutedEpsPerAdr: 3.49,
      notes:
        "Official Q1 2026 quarterly page gives US dollar revenue and margins. Net income and ADR EPS are from the Q1 2026 earnings release summary.",
    },
    {
      id: "fy2026-q2e",
      label: "2Q26E",
      fiscalYear: 2026,
      fiscalQuarter: "Q2",
      periodType: "forecast",
      asOfDate: "2026-04-16",
      sourceStatus: "management_guidance",
      sourceUrl: tsmInvestorQ126,
      revenueUsd: 39_600,
      revenueGrowth: null,
      grossMargin: 0.665,
      operatingMargin: 0.575,
      notes: "Midpoint of official Q2 2026 revenue, gross margin and operating margin guidance ranges.",
    },
  ],
  technologyMix: [
    { periodId: "fy2025", node: "Advanced nodes", revenueMix: 0.74, sourceStatus: "official_actual", notes: "7nm and beyond as a share of 2025 wafer revenue." },
    { periodId: "fy2026-q1", node: "3nm", revenueMix: 0.25, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", node: "5nm", revenueMix: 0.36, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", node: "7nm", revenueMix: 0.07, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", node: "Other", revenueMix: 0.32, sourceStatus: "official_actual" },
  ],
  platformMix: [
    { periodId: "fy2026-q1", platform: "HPC", revenueMix: 0.61, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", platform: "Smartphone", revenueMix: 0.26, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", platform: "IoT", revenueMix: 0.06, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", platform: "Automotive", revenueMix: 0.04, sourceStatus: "official_actual" },
    { periodId: "fy2026-q1", platform: "DCE / Other", revenueMix: 0.03, sourceStatus: "research_only", notes: "Residual mix after official platform disclosures." },
  ],
  operatingMetrics: [
    {
      periodId: "fy2025",
      sourceStatus: "official_actual",
      advancedNodeMix: 0.74,
      waferShipments12InchEqM: 15.0,
      customerCount: 534,
      productCount: 12_682,
      processTechnologyCount: 305,
      annualCapacity12InchEqM: 17.0,
      sourceUrl: tsmAnnual2025,
      commentary:
        "2025 annual report highlights advanced technologies, wafer shipments, customer count, product count and capacity. These are model evidence, not direct valuation inputs.",
    },
    {
      periodId: "fy2026-q1",
      sourceStatus: "official_actual",
      advancedNodeMix: 0.68,
      hpcMix: 0.61,
      smartphoneMix: 0.26,
      q2RevenueGuidanceMidUsd: 39_600,
      q2GrossMarginGuidanceMid: 0.665,
      q2OperatingMarginGuidanceMid: 0.575,
      capexGuidanceUsd: 54_000,
      sourceUrl: tsmInvestorQ126,
      commentary:
        "Q1 2026 showed record profitability and Q2 guidance stepped higher. Capex guidance is treated as a research-only cycle variable until the full official capex bridge is imported.",
    },
  ],
  sourceNotes: [
    "Official actuals are seeded from TSMC quarterly results and the 2025 annual report.",
    "Current ADR price and ADR-equivalent share count are market-data proxies until a TSM backend daily_price_bars table is added.",
    "Technology and platform mix are research evidence; they do not directly change valuation unless mapped to revenue growth, margin, capex or risk assumptions.",
  ],
  selectedPeriodId: "fy2026-q1",
};
