import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const jpmDataset = createLocalDeepResearchDataset({
  ticker: "JPM",
  companyName: "JPMorgan Chase & Co.",
  sector: "Large-Cap Bank / Universal Banking / Capital Markets",
  archetype: "Systemically important bank / NII, credit and capital-return compounder",
  description:
    "JPM research cockpit focused on net interest income durability, deposit beta, credit normalization, investment banking and markets share, CET1 capital, buybacks, regulatory capital risk, and whether the premium bank multiple remains deserved.",
  updatedAt: "2026-05-20",
  currentPrice: 295.7,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "nii-deposits", label: "NII / Deposits" },
    { value: "credit-capital", label: "Credit / Capital" },
    { value: "markets-ib", label: "Markets / IB" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "nii-durability", label: "NII Durability", value: 0.74, format: "percent", description: "Research score for deposit franchise and asset repricing resilience.", badge: "Assumption" },
    { key: "credit-cycle", label: "Credit Normalization Risk", value: 0.18, format: "percent", description: "Risk haircut for cards, commercial real estate and reserve cycle.", badge: "Assumption" },
    { key: "capital-return", label: "Capital Return Capacity", value: 0.055, format: "percent", description: "Dividend plus buyback yield framework; official CCAR import pending.", badge: "Placeholder" },
    { key: "normalized-roe", label: "Normalized ROE Proxy", value: 0.17, format: "percent", description: "Bank-specific economic engine mapped into generic valuation inputs.", badge: "Assumption" },
    { key: "base-gap", label: "Base Upside / Downside", value: -0.04, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "nii-peak",
      question: "Has NII peaked, or can JPM defend spread income through deposit franchise strength?",
      currentView: "JPM deserves a premium if deposit costs normalize slower than peers and balance-sheet mix remains advantaged.",
      metric: "NII, deposit beta, non-interest-bearing deposit mix",
      evidenceNeeded: "NII guide bridge, deposit costs, loan growth and securities reinvestment yield",
      valuationTie: "Revenue growth, normalized earnings power and quality adjustment",
      bearCase: "Deposit costs rise faster and NII fades into credit normalization.",
    },
    {
      key: "credit-cycle",
      question: "Is credit normalization contained or starting to pressure capital return?",
      currentView: "Credit is manageable if card losses normalize without commercial real estate contagion.",
      metric: "Net charge-offs, reserve build, criticized loans",
      evidenceNeeded: "Provision bridge and loss-rate commentary by portfolio",
      valuationTie: "Risk haircut and discount rate",
      bearCase: "Provisioning absorbs pre-provision earnings and buybacks slow.",
    },
    {
      key: "ib-markets",
      question: "Can IB and markets offset slower NII?",
      currentView: "A healthier issuance/M&A cycle can stabilize growth, but trading revenue is volatile.",
      metric: "IB fees, markets revenue, wallet share",
      evidenceNeeded: "Pipeline commentary and league-table share",
      valuationTie: "Revenue CAGR and exit multiple",
      bearCase: "Capital markets recovery disappoints while NII declines.",
    },
    {
      key: "capital-rules",
      question: "Does regulatory capital change the buyback story?",
      currentView: "JPM can compound capital, but Basel/endgame and GSIB surcharge risk define excess capital.",
      metric: "CET1 ratio, SCB, buyback pace",
      evidenceNeeded: "Stress-capital buffer and management capital target",
      valuationTie: "Buyback yield and risk haircut",
      bearCase: "Higher capital requirements cap ROE and buybacks.",
    },
  ],
  kpiSeries: [
    {
      key: "nii-deposits",
      title: "NII Durability vs Deposit Cost Pressure",
      subtitle: "The core JPM debate is whether NII normalization is shallow enough to keep premium ROE intact.",
      sourceStatus: "research_only",
      measures: [
        { key: "niiIndex", label: "NII index", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "depositBeta", label: "Deposit beta %", format: "percent", chartType: "line", color: "#dc2626", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", niiIndex: 100, depositBeta: 0.39 },
        { period: "2024 Q2", niiIndex: 103, depositBeta: 0.41 },
        { period: "2024 Q3", niiIndex: 104, depositBeta: 0.42 },
        { period: "2024 Q4", niiIndex: 105, depositBeta: 0.43 },
        { period: "2025 Q1", niiIndex: 106, depositBeta: 0.43 },
        { period: "2025 Q2", niiIndex: 105, depositBeta: 0.44 },
        { period: "2025 Q3", niiIndex: 104, depositBeta: 0.44 },
        { period: "2025 Q4", niiIndex: 103, depositBeta: 0.43 },
        { period: "2026 Q1", niiIndex: 102, depositBeta: 0.42 },
      ],
    },
    {
      key: "credit-capital",
      title: "Credit Risk vs Capital Buffer",
      subtitle: "Capital return only works if provision normalization stays within pre-provision earnings power.",
      sourceStatus: "research_only",
      measures: [
        { key: "chargeOffIndex", label: "Charge-off index", format: "number", chartType: "bar", color: "#92400e", axis: "left" },
        { key: "cet1", label: "CET1 %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", chargeOffIndex: 82, cet1: 0.153 },
        { period: "2024 Q2", chargeOffIndex: 86, cet1: 0.154 },
        { period: "2024 Q3", chargeOffIndex: 89, cet1: 0.155 },
        { period: "2024 Q4", chargeOffIndex: 92, cet1: 0.156 },
        { period: "2025 Q1", chargeOffIndex: 96, cet1: 0.155 },
        { period: "2025 Q2", chargeOffIndex: 99, cet1: 0.154 },
        { period: "2025 Q3", chargeOffIndex: 101, cet1: 0.154 },
        { period: "2025 Q4", chargeOffIndex: 100, cet1: 0.155 },
        { period: "2026 Q1", chargeOffIndex: 98, cet1: 0.156 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "nii-deposits",
      tab: "nii-deposits",
      title: "Deposit Franchise and NII Fade",
      thesis: "JPM's quality premium survives if deposit repricing remains better than peers and NII fade is orderly.",
      evidence: ["Deposit beta", "NII guide bridge", "Loan growth and reinvestment yield"],
      watchItems: ["Non-interest-bearing deposit outflows", "Loan demand slowdown", "Deposit pricing competition"],
      sourceStatus: "research_only",
    },
    {
      key: "credit-capital",
      tab: "credit-capital",
      title: "Credit and Capital Return",
      thesis: "Capital return is the transmission mechanism from ROE to per-share compounding, but regulation and credit can interrupt it.",
      evidence: ["CET1 ratio", "SCB/CCAR result", "NCO and reserve build"],
      watchItems: ["CRE losses", "Card delinquency acceleration", "Basel capital headwind"],
      sourceStatus: "research_only",
    },
    {
      key: "markets-ib",
      tab: "markets-ib",
      title: "IB / Markets Offset",
      thesis: "Capital markets normalization can offset lower NII, but trading revenue should not be capitalized like recurring spread income.",
      evidence: ["IB pipeline", "Markets wallet share", "Expense efficiency"],
      watchItems: ["Fee pool recovery", "Trading volatility", "Compensation ratio"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-14", headline: "NII guide versus credit normalization", keyQuestions: ["Is NII guide stable?", "Are card losses peaking?", "Can buybacks continue?"], managementTone: "Confident but macro-aware.", modelReadThrough: "Keep quality premium, preserve credit haircut.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-01-14", headline: "Capital return after year-end", keyQuestions: ["How much excess CET1?", "Is IB recovering?", "Are provisions rising?"], managementTone: "Capital-disciplined.", modelReadThrough: "Buyback yield depends on CCAR visibility.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-14", headline: "Credit and deposit competition", keyQuestions: ["Deposit beta trend?", "Card losses?", "CRE reserve build?"], managementTone: "Measured.", modelReadThrough: "NII fade should not be ignored.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-15", headline: "Markets and IB recovery", keyQuestions: ["Is fee recovery broad?", "Does expense growth offset revenue?", "Any capital rule update?"], managementTone: "Constructive on pipeline.", modelReadThrough: "Revenue mix improves but multiple should stay bank-like.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-11", headline: "NII peak debate", keyQuestions: ["Is NII at peak?", "Are deposit balances stable?", "What is provision outlook?"], managementTone: "Cautious on NII.", modelReadThrough: "Lower growth, keep ROE premium.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-01-15", headline: "Premium bank multiple", keyQuestions: ["Can JPM sustain ROTCE?", "Any buyback acceleration?", "How is credit trending?"], managementTone: "Strong execution.", modelReadThrough: "Quality adjustment stays high.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-11", headline: "Deposit and loan growth balance", keyQuestions: ["Loan growth?", "Deposit migration?", "Expense discipline?"], managementTone: "Balanced.", modelReadThrough: "No major fair value change.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-12", headline: "NII strength versus regulatory risk", keyQuestions: ["Does NII beat recur?", "How much capital buffer?", "What is Basel sensitivity?"], managementTone: "Confident.", modelReadThrough: "Higher near-term earnings, unchanged capital haircut.", riskSignal: "Positive", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-12", fiscalPeriod: "FY2024 Q2", asOfPrice: 205, fairValue: 212, method: "Bank earnings power and capital-return local fallback." },
    { eventDate: "2024-10-11", fiscalPeriod: "FY2024 Q3", asOfPrice: 222, fairValue: 226, method: "Deposit durability and credit normalization." },
    { eventDate: "2025-01-15", fiscalPeriod: "FY2024 Q4", asOfPrice: 248, fairValue: 242, method: "Premium bank ROE durability audited." },
    { eventDate: "2025-04-11", fiscalPeriod: "FY2025 Q1", asOfPrice: 235, fairValue: 250, method: "NII peak debate with quality premium." },
    { eventDate: "2025-07-15", fiscalPeriod: "FY2025 Q2", asOfPrice: 262, fairValue: 262, method: "IB recovery and capital return bridge." },
    { eventDate: "2025-10-14", fiscalPeriod: "FY2025 Q3", asOfPrice: 274, fairValue: 270, method: "Credit and deposit competition haircut." },
    { eventDate: "2026-01-14", fiscalPeriod: "FY2025 Q4", asOfPrice: 288, fairValue: 282, method: "Capital return after year-end." },
    { eventDate: "2026-04-14", fiscalPeriod: "FY2026 Q1", asOfPrice: 296, fairValue: 284, method: "Base earnings power / capital-return local run." },
  ],
  valuationBase: {
    revenueBase: 177000,
    revenueCagr3Y: 0.035,
    terminalGrowth: 0.025,
    normalizedFcfMargin: 0.18,
    exitFcfMultiple: 10,
    evRevenueMultiple: 4.4,
    discountRate: 0.095,
    netCashDebt: 0,
    dilutedShares: 2768,
    qualityAdjustment: 1.14,
    riskHaircut: 0.1,
    dividendYield: 0.018,
    buybackYield: 0.035,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: -0.01, normalizedFcfMargin: 0.13, exitFcfMultiple: 8, evRevenueMultiple: 3.2, riskHaircut: 0.22, qualityAdjustment: 1.0, buybackYield: 0.015 },
    Base: {},
    Bull: { revenueCagr3Y: 0.055, normalizedFcfMargin: 0.21, exitFcfMultiple: 12, evRevenueMultiple: 5.1, riskHaircut: 0.06, qualityAdjustment: 1.2, buybackYield: 0.045 },
  },
  valuationDescription: "Maps bank earnings power into DCF, earnings-capitalization and revenue cross-check outputs until a BVPS/ROE backend model is added.",
  risks: [
    { title: "Deposit repricing pressure", detail: "Higher deposit costs can turn NII strength into a fade.", severity: "high", killSignal: "Deposit beta accelerates while NII guide falls." },
    { title: "Credit losses", detail: "Card, CRE or macro credit weakness can absorb excess capital.", severity: "high", killSignal: "Provision build rises and buybacks slow." },
    { title: "Regulatory capital", detail: "Higher capital requirements reduce ROE and buyback capacity.", severity: "medium", killSignal: "Management raises capital target materially." },
  ],
  monitoring: ["NII guide", "Deposit beta", "NCOs and reserves", "CET1 / SCB", "Buyback pace", "IB fee pipeline"],
  sourceGaps: ["Bank-specific BVPS/ROTCE valuation backend is not implemented yet.", "Official NII, CET1 and credit data should be imported from filings and earnings supplements."],
});
