import type { DeepResearchDataset } from "../deepResearch/model";

const marketData = {
  currentPrice: 215.17,
  priceDate: "2026-05-19",
  source: "Market data snapshot captured 2026-05-19; verify against live feed before trading.",
  sourceStatus: "market_data_proxy" as const,
};

const defaultAssumptions = {
  currentPrice: marketData.currentPrice,
  revenueBase: 4300,
  revenueCagr3Y: 0.24,
  terminalGrowth: 0.035,
  normalizedFcfMargin: 0.3,
  exitFcfMultiple: 34,
  evRevenueMultiple: 13,
  discountRate: 0.095,
  netCashDebt: 3500,
  dilutedShares: 365,
  qualityAdjustment: 1.08,
  riskHaircut: 0.1,
  dividendYield: 0,
  buybackYield: -0.005,
};

export const ddogDataset: DeepResearchDataset = {
  ticker: "DDOG",
  companyName: "Datadog, Inc.",
  sector: "Cloud Software / Observability / Security",
  archetype: "Cloud observability platform / AI workload monetization",
  currency: "USD",
  description:
    "DDOG cockpit focused on usage-based growth, NRR, cloud optimization, AI-native workload observability, platform consolidation, security attach, SBC, FCF durability, and premium software valuation risk.",
  updatedAt: "2026-05-19",
  marketData,
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "usage-nrr", label: "Usage / NRR" },
    { value: "ai-security", label: "AI / Security" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "revenue-growth", label: "Revenue Growth", value: 0.27, format: "percent", description: "Growth must reaccelerate enough to justify the premium multiple.", badge: "Assumption" },
    { key: "nrr-proxy", label: "NRR Proxy", value: 1.17, format: "multiple", description: "Usage expansion and platform consolidation proxy.", badge: "Derived" },
    { key: "rule-of-40", label: "Rule of 40", value: 0.57, format: "percent", description: "Growth plus FCF margin proxy for software quality.", badge: "Derived" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: defaultAssumptions.normalizedFcfMargin, format: "percent", description: "FCF margin must remain high despite AI and sales reinvestment.", badge: "Assumption" },
    { key: "sbc-watch", label: "SBC / Dilution Watch", value: 0.12, format: "percent", description: "Per-share compounding depends on SBC discipline.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "usage-reacceleration",
      question: "Is usage growth reaccelerating after cloud optimization?",
      currentView: "DDOG is a high-quality platform if usage expansion improves without simply relying on price increases.",
      metric: "Revenue growth, NRR proxy, customer cohorts",
      evidenceNeeded: "Large-customer growth, usage trends, optimization commentary, current RPO",
      valuationTie: "Revenue CAGR",
      bearCase: "Cloud optimization persists and usage growth normalizes below premium expectations.",
    },
    {
      key: "ai-workloads",
      question: "Do AI-native workloads create incremental observability demand?",
      currentView: "AI infrastructure can expand logs, traces and monitoring complexity, but customers may optimize data ingestion costs.",
      metric: "AI customer count, LLM observability adoption, data ingest volume",
      evidenceNeeded: "AI product attach and durable customer spend",
      valuationTie: "EV/revenue cross-check and quality adjustment",
      bearCase: "AI workload monitoring remains feature-level, not revenue-level.",
    },
    {
      key: "security-consolidation",
      question: "Can security attach expand the platform without diluting focus?",
      currentView: "Security can raise platform TAM and retention if it is truly integrated into observability workflow.",
      metric: "Multi-product customers, security ARR proxy, product adoption",
      evidenceNeeded: "Attach rate, customer count by product, win/loss vs security incumbents",
      valuationTie: "Exit multiple",
      bearCase: "Security remains a cross-sell story with limited standalone scale.",
    },
    {
      key: "fcf-sbc",
      question: "How much of FCF converts to per-share value after SBC?",
      currentView: "High FCF margins are valuable only if dilution is contained and buybacks are not merely offsetting SBC.",
      metric: "FCF margin, SBC as % revenue, diluted shares",
      evidenceNeeded: "Share count, SBC, buyback effectiveness",
      valuationTie: "Diluted shares and normalized FCF margin",
      bearCase: "Reported FCF overstates owner earnings due to persistent dilution.",
    },
  ],
  kpiSeries: [
    {
      key: "usage-nrr",
      title: "Usage Growth Proxy vs FCF Margin",
      subtitle: "Usage-based models should be judged on reacceleration and cash conversion together.",
      sourceStatus: "research_only",
      measures: [
        { key: "revenue", label: "Revenue ($m)", format: "currency", chartType: "bar", color: "#2563eb", axis: "left" },
        { key: "fcfMargin", label: "FCF margin %", format: "percent", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "FY2023 Q2", revenue: 510, fcfMargin: 24 },
        { period: "FY2023 Q3", revenue: 548, fcfMargin: 25 },
        { period: "FY2023 Q4", revenue: 590, fcfMargin: 26 },
        { period: "FY2024 Q1", revenue: 611, fcfMargin: 27 },
        { period: "FY2024 Q2", revenue: 645, fcfMargin: 28 },
        { period: "FY2024 Q3", revenue: 690, fcfMargin: 29 },
        { period: "FY2024 Q4", revenue: 738, fcfMargin: 30 },
        { period: "FY2025 Q1", revenue: 780, fcfMargin: 30 },
        { period: "FY2025 Q2", revenue: 832, fcfMargin: 31 },
        { period: "FY2025 Q3", revenue: 890, fcfMargin: 31 },
        { period: "FY2025 Q4", revenue: 955, fcfMargin: 32 },
        { period: "FY2026 Q1", revenue: 1025, fcfMargin: 31 },
      ],
    },
    {
      key: "ai-security",
      title: "Multi-Product / AI-Security Attach",
      subtitle: "The key platform question is whether customers adopt more modules as workloads become more complex.",
      sourceStatus: "research_only",
      measures: [
        { key: "multiProductCustomers", label: "Multi-product customers proxy", format: "number", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "aiSecurityAttach", label: "AI/security attach %", format: "percent", chartType: "line", color: "#7c3aed", axis: "right" },
      ],
      points: [
        { period: "FY2023 Q2", multiProductCustomers: 3400, aiSecurityAttach: 14 },
        { period: "FY2023 Q3", multiProductCustomers: 3600, aiSecurityAttach: 15 },
        { period: "FY2023 Q4", multiProductCustomers: 3850, aiSecurityAttach: 16 },
        { period: "FY2024 Q1", multiProductCustomers: 4100, aiSecurityAttach: 17 },
        { period: "FY2024 Q2", multiProductCustomers: 4400, aiSecurityAttach: 19 },
        { period: "FY2024 Q3", multiProductCustomers: 4750, aiSecurityAttach: 21 },
        { period: "FY2024 Q4", multiProductCustomers: 5100, aiSecurityAttach: 23 },
        { period: "FY2025 Q1", multiProductCustomers: 5450, aiSecurityAttach: 25 },
        { period: "FY2025 Q2", multiProductCustomers: 5850, aiSecurityAttach: 27 },
        { period: "FY2025 Q3", multiProductCustomers: 6300, aiSecurityAttach: 29 },
        { period: "FY2025 Q4", multiProductCustomers: 6800, aiSecurityAttach: 31 },
        { period: "FY2026 Q1", multiProductCustomers: 7200, aiSecurityAttach: 32 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "usage-engine",
      tab: "usage-nrr",
      title: "Usage Reacceleration Engine",
      thesis: "DDOG's multiple needs proof that cloud optimization is behind the company and that usage expands naturally with customer workloads.",
      evidence: ["Large customer net expansion", "Current RPO", "Consumption commentary", "Product attach"],
      watchItems: ["Optimization cycles", "Data ingest cost pressure", "NRR proxy deterioration"],
      sourceStatus: "research_only",
    },
    {
      key: "ai-security-platform",
      tab: "ai-security",
      title: "AI + Security Platform Expansion",
      thesis: "AI observability and security can raise TAM, but the evidence has to show module adoption and revenue, not just product launches.",
      evidence: ["LLM observability adoption", "Security customers", "Multi-product customer mix"],
      watchItems: ["Feature bundling with weak monetization", "Competition from hyperscalers", "SBC reinvestment intensity"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-05-07", headline: "AI workload monetization and usage growth", keyQuestions: ["Is usage growth reaccelerating?", "Are AI products material to revenue?", "Is FCF margin durable despite reinvestment?"], managementTone: "Confident on platform demand.", modelReadThrough: "Keep growth high, but do not raise margin without SBC discipline.", riskSignal: "Positive", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q4", eventDate: "2026-02-12", headline: "Rule of 40 and platform attach", keyQuestions: ["How broad is multi-product adoption?", "Is security attach measurable?", "What is current RPO growth?"], managementTone: "Constructive.", modelReadThrough: "Platform attach supports quality adjustment.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-11-06", headline: "Cloud optimization watch", keyQuestions: ["Any usage slowdown?", "Large-customer adds?", "AI observability contribution?"], managementTone: "Balanced.", modelReadThrough: "Revenue CAGR stays strong but watch optimization language.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-08-07", headline: "FCF and SBC quality", keyQuestions: ["FCF margin sustainability?", "SBC as % revenue?", "Share count growth?"], managementTone: "Disciplined.", modelReadThrough: "Per-share value depends on dilution control.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-05-08", headline: "Usage recovery", keyQuestions: ["Are optimization headwinds easing?", "Are enterprise customers expanding?", "Security attach?"], managementTone: "Improving.", modelReadThrough: "Growth reliability improves modestly.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-02-13", headline: "Growth vs multiple", keyQuestions: ["Can growth hold >25%?", "Is platform consolidation visible?", "How much is AI?"], managementTone: "Positive.", modelReadThrough: "Premium multiple needs sustained growth.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-11-07", headline: "Cloud optimization aftershock", keyQuestions: ["Are customers still optimizing spend?", "What is NRR direction?", "Any product-led acceleration?"], managementTone: "Cautious optimism.", modelReadThrough: "Keep discount rate elevated.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-08-08", headline: "Large-customer growth", keyQuestions: ["Large customer count?", "Usage growth?", "FCF margin?"], managementTone: "Execution-focused.", modelReadThrough: "Quality high, but revenue deceleration risk remains.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q1", eventDate: "2024-05-07", headline: "Software multiple reset", keyQuestions: ["Is growth stabilizing?", "Any signs of AI attach?", "Sales productivity?"], managementTone: "Measured.", modelReadThrough: "Lower terminal multiple until reacceleration appears.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2023 Q4", eventDate: "2024-02-13", headline: "Optimization headwinds", keyQuestions: ["How severe is cloud optimization?", "Can FCF offset growth slowdown?", "Is NRR bottoming?"], managementTone: "Cautious.", modelReadThrough: "Reduce revenue CAGR, keep FCF margin.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2023 Q3", eventDate: "2023-11-07", headline: "Usage deceleration", keyQuestions: ["Is customer spend tightening?", "Product attach?", "RPO trend?"], managementTone: "Cautious.", modelReadThrough: "Compress revenue multiple.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2023 Q2", eventDate: "2023-08-08", headline: "Cloud optimization shock", keyQuestions: ["How long does optimization last?", "What is NRR?", "Can FCF hold?"], managementTone: "Defensive.", modelReadThrough: "Increase risk haircut.", riskSignal: "Negative", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { id: "ddog-2023q2", eventDate: "2023-08-08", fiscalPeriod: "FY2023 Q2", asOfPrice: 90, fairValue: 84, targetPrice3Y: 115, expectedShareholderCagr: 0.085, method: "Optimization shock / FCF support.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 82, format: "currency", description: "Lower growth." }] },
    { id: "ddog-2023q3", eventDate: "2023-11-07", fiscalPeriod: "FY2023 Q3", asOfPrice: 102, fairValue: 92, targetPrice3Y: 126, expectedShareholderCagr: 0.073, method: "Usage deceleration with FCF floor.", sourceStatus: "research_only", warnings: ["Local row."], methodOutputs: [{ label: "FCF multiple", value: 95, format: "currency", description: "FCF resilience." }] },
    { id: "ddog-2023q4", eventDate: "2024-02-13", fiscalPeriod: "FY2023 Q4", asOfPrice: 129, fairValue: 105, targetPrice3Y: 145, expectedShareholderCagr: 0.039, method: "Platform quality but premium multiple.", sourceStatus: "research_only", warnings: ["No backend price bars."], methodOutputs: [{ label: "Blend", value: 105, format: "currency", description: "Quality vs price." }] },
    { id: "ddog-2024q1", eventDate: "2024-05-07", fiscalPeriod: "FY2024 Q1", asOfPrice: 120, fairValue: 112, targetPrice3Y: 156, expectedShareholderCagr: 0.091, method: "Growth stabilization.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 110, format: "currency", description: "Stabilizing." }] },
    { id: "ddog-2024q2", eventDate: "2024-08-08", fiscalPeriod: "FY2024 Q2", asOfPrice: 113, fairValue: 120, targetPrice3Y: 168, expectedShareholderCagr: 0.141, method: "Large-customer expansion.", sourceStatus: "research_only", warnings: ["Local row."], methodOutputs: [{ label: "FCF multiple", value: 122, format: "currency", description: "Cash conversion." }] },
    { id: "ddog-2024q3", eventDate: "2024-11-07", fiscalPeriod: "FY2024 Q3", asOfPrice: 128, fairValue: 132, targetPrice3Y: 185, expectedShareholderCagr: 0.131, method: "Cloud optimization easing.", sourceStatus: "research_only", warnings: ["No current data backfilled."], methodOutputs: [{ label: "Blend", value: 132, format: "currency", description: "Recovery begins." }] },
    { id: "ddog-2024q4", eventDate: "2025-02-13", fiscalPeriod: "FY2024 Q4", asOfPrice: 142, fairValue: 145, targetPrice3Y: 204, expectedShareholderCagr: 0.129, method: "Platform attach improves.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 144, format: "currency", description: "Attach improves." }] },
    { id: "ddog-2025q1", eventDate: "2025-05-08", fiscalPeriod: "FY2025 Q1", asOfPrice: 151, fairValue: 158, targetPrice3Y: 223, expectedShareholderCagr: 0.138, method: "Usage recovery.", sourceStatus: "research_only", warnings: ["Local row."], methodOutputs: [{ label: "Blend", value: 158, format: "currency", description: "Growth recovery." }] },
    { id: "ddog-2025q2", eventDate: "2025-08-07", fiscalPeriod: "FY2025 Q2", asOfPrice: 166, fairValue: 168, targetPrice3Y: 237, expectedShareholderCagr: 0.126, method: "FCF and SBC audit.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "FCF multiple", value: 169, format: "currency", description: "Cash high, dilution watch." }] },
    { id: "ddog-2025q3", eventDate: "2025-11-06", fiscalPeriod: "FY2025 Q3", asOfPrice: 185, fairValue: 178, targetPrice3Y: 252, expectedShareholderCagr: 0.108, method: "AI observability optionality.", sourceStatus: "research_only", warnings: ["Local fallback."], methodOutputs: [{ label: "EV/revenue", value: 180, format: "currency", description: "AI optionality." }] },
    { id: "ddog-2025q4", eventDate: "2026-02-12", fiscalPeriod: "FY2025 Q4", asOfPrice: 205, fairValue: 190, targetPrice3Y: 270, expectedShareholderCagr: 0.096, method: "Rule of 40 premium.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 188, format: "currency", description: "Premium but quality high." }] },
    { id: "ddog-2026q1", eventDate: "2026-05-07", fiscalPeriod: "FY2026 Q1", asOfPrice: 215, fairValue: 198, targetPrice3Y: 281, expectedShareholderCagr: 0.092, method: "Base software DCF / FCF triangulation.", sourceStatus: "official_actual", warnings: ["Backend valuation run not persisted."], methodOutputs: [{ label: "Blend", value: 198, format: "currency", description: "Quality mostly priced." }] },
  ],
  valuation: {
    defaultAssumptions,
    scenarios: {
      Bear: { ...defaultAssumptions, revenueCagr3Y: 0.14, normalizedFcfMargin: 0.24, exitFcfMultiple: 24, evRevenueMultiple: 8, discountRate: 0.11, qualityAdjustment: 0.98, riskHaircut: 0.18, buybackYield: -0.015 },
      Base: defaultAssumptions,
      Bull: { ...defaultAssumptions, revenueCagr3Y: 0.31, normalizedFcfMargin: 0.35, exitFcfMultiple: 42, evRevenueMultiple: 16, discountRate: 0.085, qualityAdjustment: 1.15, riskHaircut: 0.06, buybackYield: 0 },
    },
    modelDescription: "Software DCF / FCF multiple model with Rule-of-40 and usage-reacceleration checks.",
    noFutureLeakageNote: "Historical DDOG rows use event-specific usage/optimization framing and do not backfill current AI-product assumptions into older quarters.",
  },
  risks: [
    { title: "Usage optimization resumes", detail: "Usage-based software can decelerate quickly when customers optimize cloud spend.", severity: "high", killSignal: "Revenue growth slows while RPO and large-customer adds also deteriorate." },
    { title: "AI monetization overstated", detail: "AI observability may be a feature rather than a separate revenue leg.", severity: "medium", killSignal: "AI product mentions rise but attach and revenue metrics do not." },
    { title: "SBC dilution", detail: "High FCF can overstate owner earnings if stock compensation remains elevated.", severity: "medium", killSignal: "Diluted share count rises despite strong FCF." },
  ],
  monitoring: ["Revenue growth", "Current RPO", "Large customer count", "NRR proxy", "FCF margin", "SBC and diluted shares", "AI/security attach"],
  sourceGaps: ["Historical valuation rows are local fallback.", "DDOG/SPY daily price bars not imported into backend.", "NRR and AI/security attach are research proxies until official KPI extraction is automated."],
  backendStatus: {
    supported: false,
    detail: "DDOG has frontend research history and valuation now, but no per-ticker SQLite backend or AWS data deployment yet.",
    nextSteps: ["Create DDOG backend DB.", "Import DDOG/SPY daily prices.", "Persist valuation runs by event.", "Automate transcript extraction for usage, AI and security commentary."],
  },
  qualityBadges: [
    { label: "Usage / NRR", value: "Proxy", badge: "Assumption" },
    { label: "Historical valuation", value: "Local fallback", badge: "Placeholder" },
    { label: "Market price", value: "Proxy snapshot", badge: "Placeholder" },
  ],
};
