import type { DeepResearchDataset } from "../deepResearch/model";

const marketData = {
  currentPrice: 1094.69,
  priceDate: "2026-05-19",
  source: "Market data snapshot captured 2026-05-19; verify against live feed before trading.",
  sourceStatus: "market_data_proxy" as const,
};

const defaultAssumptions = {
  currentPrice: marketData.currentPrice,
  revenueBase: 284000,
  revenueCagr3Y: 0.075,
  terminalGrowth: 0.03,
  normalizedFcfMargin: 0.032,
  exitFcfMultiple: 40,
  evRevenueMultiple: 1.7,
  discountRate: 0.075,
  netCashDebt: 2000,
  dilutedShares: 444,
  qualityAdjustment: 1.1,
  riskHaircut: 0.06,
  dividendYield: 0.0045,
  buybackYield: 0.002,
};

export const costDataset: DeepResearchDataset = {
  ticker: "COST",
  companyName: "Costco Wholesale Corporation",
  sector: "Consumer Staples / Membership Warehouse Retail",
  archetype: "Membership retail compounder / premium multiple durability",
  currency: "USD",
  description:
    "COST cockpit focused on membership fee economics, traffic and renewal durability, merchandise margin, international unit growth, e-commerce, wage inflation, and whether a premium multiple is justified by low-volatility compounding.",
  updatedAt: "2026-05-19",
  marketData,
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "membership-traffic", label: "Membership / Traffic" },
    { value: "margin-units", label: "Margin / Units" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q2", label: "FY2026 Q2" },
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "membership-fee-growth", label: "Membership Fee Growth", value: 0.14, format: "percent", description: "Fee income growth boosted by renewal strength and fee increase flow-through.", badge: "Actual" },
    { key: "renewal-quality", label: "Renewal Quality", value: 0.92, format: "percent", description: "North America renewal-rate quality remains the key moat KPI.", badge: "Derived" },
    { key: "traffic-growth", label: "Traffic Growth", value: 0.052, format: "percent", description: "Traffic, not basket inflation, should do most of the comp work.", badge: "Derived" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: defaultAssumptions.normalizedFcfMargin, format: "percent", description: "Warehouse model is low margin but high turn and high loyalty.", badge: "Assumption" },
    { key: "price-gap", label: "Base Upside / Downside", value: -0.15, format: "percent", description: "Premium multiple risk remains the central valuation debate.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "membership-durability",
      question: "Is membership fee income still a bond-like annuity with pricing power?",
      currentView: "The investment case rests less on retail margin and more on high-renewal, low-churn membership economics.",
      metric: "Membership fees, renewal rate, executive mix",
      evidenceNeeded: "Renewal rates, paid household growth, executive penetration, churn after fee increase",
      valuationTie: "Quality adjustment and terminal growth",
      bearCase: "Fee increase pulls forward economics while traffic normalizes.",
    },
    {
      key: "traffic-ticket",
      question: "Are comps driven by traffic or by price/mix?",
      currentView: "Traffic-led comps deserve a higher multiple than inflation-led comps because they imply share gains.",
      metric: "Comparable traffic vs average ticket",
      evidenceNeeded: "US traffic, international traffic, gasoline / FX adjusted comps",
      valuationTie: "Revenue CAGR",
      bearCase: "Ticket fades and traffic slows as consumers trade down elsewhere.",
    },
    {
      key: "international-runway",
      question: "Can international warehouses keep extending the growth runway?",
      currentView: "International productivity and membership adoption decide whether COST can outgrow US retail saturation.",
      metric: "Net new warehouses, sales per warehouse, international renewal",
      evidenceNeeded: "New unit productivity and market-level payback periods",
      valuationTie: "Revenue multiple cross-check",
      bearCase: "International expansion is slower and less profitable than embedded expectations.",
    },
    {
      key: "margin-wage",
      question: "Can Costco protect margin while reinvesting in wages and price leadership?",
      currentView: "Gross margin expansion is not the thesis; SG&A discipline and vendor scale matter more.",
      metric: "Core merchandise margin, SG&A rate, wage investments",
      evidenceNeeded: "Margin bridge excluding gas, LIFO, and one-time items",
      valuationTie: "Normalized FCF margin",
      bearCase: "Wage and shrink pressure reduce cash conversion.",
    },
  ],
  kpiSeries: [
    {
      key: "membership-traffic",
      title: "Membership Fee Income vs Traffic Growth",
      subtitle: "Costco should be underwritten as a traffic-led subscription-like retailer, not a gross-margin retailer.",
      sourceStatus: "research_only",
      measures: [
        { key: "membershipFees", label: "Membership fees ($m)", format: "currency", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "trafficGrowth", label: "Traffic growth %", format: "percent", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "FY2023 Q3", membershipFees: 1044, trafficGrowth: 4.8 },
        { period: "FY2023 Q4", membershipFees: 1509, trafficGrowth: 5.2 },
        { period: "FY2024 Q1", membershipFees: 1082, trafficGrowth: 4.7 },
        { period: "FY2024 Q2", membershipFees: 1111, trafficGrowth: 5.0 },
        { period: "FY2024 Q3", membershipFees: 1123, trafficGrowth: 5.5 },
        { period: "FY2024 Q4", membershipFees: 1512, trafficGrowth: 5.8 },
        { period: "FY2025 Q1", membershipFees: 1166, trafficGrowth: 5.1 },
        { period: "FY2025 Q2", membershipFees: 1193, trafficGrowth: 5.7 },
        { period: "FY2025 Q3", membershipFees: 1226, trafficGrowth: 5.4 },
        { period: "FY2025 Q4", membershipFees: 1600, trafficGrowth: 5.8 },
        { period: "FY2026 Q1", membershipFees: 1329, trafficGrowth: 5.1 },
        { period: "FY2026 Q2", membershipFees: 1355, trafficGrowth: 5.0 },
      ],
    },
    {
      key: "margin-units",
      title: "Warehouse Growth and Core Margin Discipline",
      subtitle: "A premium multiple needs visible unit runway without sacrificing price leadership.",
      sourceStatus: "research_only",
      measures: [
        { key: "warehouses", label: "Warehouses", format: "number", chartType: "bar", color: "#334155", axis: "left" },
        { key: "operatingMargin", label: "Operating margin %", format: "percent", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "FY2020", warehouses: 795, operatingMargin: 3.5 },
        { period: "FY2021", warehouses: 815, operatingMargin: 3.7 },
        { period: "FY2022", warehouses: 838, operatingMargin: 3.5 },
        { period: "FY2023", warehouses: 861, operatingMargin: 3.4 },
        { period: "FY2024", warehouses: 891, operatingMargin: 3.6 },
        { period: "FY2025", warehouses: 914, operatingMargin: 3.7 },
        { period: "FY2026E", warehouses: 940, operatingMargin: 3.7 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "membership-flywheel",
      tab: "membership-traffic",
      title: "Membership Flywheel",
      thesis: "Membership economics create a low-volatility profit stream, but the stock already discounts unusually durable renewal and traffic.",
      evidence: ["Membership fees grow faster than sales after fee increases.", "Executive membership mix supports basket size and loyalty.", "Traffic growth is the cleanest evidence of share gain."],
      watchItems: ["Renewal rate slippage", "Any drop in paid household growth", "Elasticity after fee increase anniversary"],
      sourceStatus: "research_only",
    },
    {
      key: "unit-runway",
      tab: "margin-units",
      title: "Unit Growth / International Payback",
      thesis: "International warehouses are the main path to extending the compounding runway once US penetration matures.",
      evidence: ["New warehouse count", "International comparable sales", "Market-level membership adoption"],
      watchItems: ["Lower productivity outside core markets", "Real estate / labor cost inflation", "E-commerce cannibalization"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q2", eventDate: "2026-03-05", headline: "Fee-income flow-through vs traffic normalization", keyQuestions: ["How much membership fee growth is fee increase vs new households?", "Are US traffic gains still above sector?", "Is core merchandise margin stable excluding gas?"], managementTone: "Confident on loyalty and traffic.", modelReadThrough: "Keep revenue CAGR high quality but do not raise terminal margin without margin bridge.", riskSignal: "Neutral", sourceStatus: "official_actual" },
    { quarter: "FY2026 Q1", eventDate: "2025-12-11", headline: "Fee increase benefit starts to show", keyQuestions: ["Does the renewal rate hold after the higher fee?", "Are executive members still mixing up?", "Is e-commerce growth profitable?"], managementTone: "Solid traffic and digital momentum.", modelReadThrough: "Supports quality adjustment; watch valuation multiple.", riskSignal: "Positive", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q4", eventDate: "2025-09-25", headline: "Premium multiple after strong year", keyQuestions: ["Can warehouse openings accelerate?", "Does gasoline distort comp optics?", "Are wages pressuring SG&A?"], managementTone: "Measured but resilient.", modelReadThrough: "Do not extrapolate one quarter of margin expansion.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-05-29", headline: "Traffic durability", keyQuestions: ["Traffic vs ticket split?", "International comp strength?", "Private-label share gains?"], managementTone: "Constructive on traffic.", modelReadThrough: "Traffic-led comps support premium revenue durability.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-03-06", headline: "Membership renewal watch", keyQuestions: ["Any renewal pressure?", "Are digital investments improving basket?", "What is wage inflation run rate?"], managementTone: "Stable.", modelReadThrough: "Keep FCF margin conservative.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2024-12-12", headline: "Holiday traffic and fee timing", keyQuestions: ["Does fee increase create churn?", "Are discretionary categories recovering?", "Is food inflation helping or hurting?"], managementTone: "Traffic remains the bright spot.", modelReadThrough: "Revenue growth quality remains stronger than margin story.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2024-09-26", headline: "First read after membership fee increase", keyQuestions: ["What is elasticity to new fee level?", "Do higher fees improve renewal economics?", "How much cash return is possible?"], managementTone: "Confident.", modelReadThrough: "Raise near-term fee income; no automatic terminal multiple change.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-05-30", headline: "Comp quality vs valuation risk", keyQuestions: ["Are traffic gains broad-based?", "Is average ticket weakening?", "Are new units diluting productivity?"], managementTone: "Balanced.", modelReadThrough: "Multiple deserves premium only if traffic remains durable.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-03-07", headline: "Margin and wage pressure", keyQuestions: ["Core margin bridge?", "Wage inflation?", "Membership renewal trends?"], managementTone: "Cost disciplined.", modelReadThrough: "FCF margin should stay bounded.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2024 Q1", eventDate: "2023-12-14", headline: "Resilient traffic in uncertain consumer backdrop", keyQuestions: ["Does traffic resilience persist?", "How much is gas impact?", "International expansion cadence?"], managementTone: "Resilient.", modelReadThrough: "Maintain premium quality score.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2023 Q4", eventDate: "2023-09-26", headline: "Renewal and traffic debate", keyQuestions: ["Are renewal rates peaking?", "Can fee increase wait?", "How durable is discretionary mix?"], managementTone: "Conservative.", modelReadThrough: "No fee increase yet; keep revenue CAGR modest.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2023 Q3", eventDate: "2023-05-25", headline: "Discretionary softness", keyQuestions: ["Is basket weakness temporary?", "Do food and essentials offset discretionary?", "Are club share gains accelerating?"], managementTone: "Cautious.", modelReadThrough: "Lower near-term margin but not membership moat.", riskSignal: "Negative", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { id: "cost-2023q3", eventDate: "2023-05-25", fiscalPeriod: "FY2023 Q3", asOfPrice: 483, fairValue: 520, targetPrice3Y: 585, expectedShareholderCagr: 0.066, method: "Membership annuity + FCF yield local fallback.", sourceStatus: "research_only", warnings: ["Proxy price; backend daily bars not yet imported."], methodOutputs: [{ label: "DCF", value: 515, format: "currency", description: "Known-as-of traffic slowdown." }] },
    { id: "cost-2023q4", eventDate: "2023-09-26", fiscalPeriod: "FY2023 Q4", asOfPrice: 552, fairValue: 560, targetPrice3Y: 625, expectedShareholderCagr: 0.044, method: "Membership annuity + warehouse growth.", sourceStatus: "research_only", warnings: ["Local fallback valuation row."], methodOutputs: [{ label: "FCF multiple", value: 548, format: "currency", description: "Premium compounder but no fee increase yet." }] },
    { id: "cost-2024q1", eventDate: "2023-12-14", fiscalPeriod: "FY2024 Q1", asOfPrice: 646, fairValue: 610, targetPrice3Y: 684, expectedShareholderCagr: 0.026, method: "Traffic-led comp bridge.", sourceStatus: "research_only", warnings: ["Do not use 2026 fee income in this row."], methodOutputs: [{ label: "DCF", value: 602, format: "currency", description: "Traffic resilience." }] },
    { id: "cost-2024q2", eventDate: "2024-03-07", fiscalPeriod: "FY2024 Q2", asOfPrice: 725, fairValue: 655, targetPrice3Y: 735, expectedShareholderCagr: 0.005, method: "Margin discipline / membership bridge.", sourceStatus: "research_only", warnings: ["Local fair value only."], methodOutputs: [{ label: "FCF multiple", value: 660, format: "currency", description: "Wage pressure bounded." }] },
    { id: "cost-2024q3", eventDate: "2024-05-30", fiscalPeriod: "FY2024 Q3", asOfPrice: 815, fairValue: 700, targetPrice3Y: 785, expectedShareholderCagr: -0.012, method: "Traffic durability premium.", sourceStatus: "research_only", warnings: ["Price may not equal nearest prior close."], methodOutputs: [{ label: "DCF", value: 695, format: "currency", description: "Traffic outperformance." }] },
    { id: "cost-2024q4", eventDate: "2024-09-26", fiscalPeriod: "FY2024 Q4", asOfPrice: 890, fairValue: 760, targetPrice3Y: 855, expectedShareholderCagr: -0.013, method: "Fee increase flow-through starts.", sourceStatus: "research_only", warnings: ["No future leakage: only fee increase known then."], methodOutputs: [{ label: "Blend", value: 760, format: "currency", description: "Higher fee income." }] },
    { id: "cost-2025q1", eventDate: "2024-12-12", fiscalPeriod: "FY2025 Q1", asOfPrice: 990, fairValue: 780, targetPrice3Y: 875, expectedShareholderCagr: -0.041, method: "Fee benefit / traffic check.", sourceStatus: "research_only", warnings: ["Proxy local row."], methodOutputs: [{ label: "DCF", value: 780, format: "currency", description: "Fee benefit partly priced." }] },
    { id: "cost-2025q2", eventDate: "2025-03-06", fiscalPeriod: "FY2025 Q2", asOfPrice: 1040, fairValue: 805, targetPrice3Y: 902, expectedShareholderCagr: -0.046, method: "Renewal and margin bridge.", sourceStatus: "research_only", warnings: ["Local fallback valuation row."], methodOutputs: [{ label: "FCF multiple", value: 815, format: "currency", description: "Renewal stable." }] },
    { id: "cost-2025q3", eventDate: "2025-05-29", fiscalPeriod: "FY2025 Q3", asOfPrice: 985, fairValue: 830, targetPrice3Y: 932, expectedShareholderCagr: -0.018, method: "Traffic-led comp premium.", sourceStatus: "research_only", warnings: ["Source needs daily price import."], methodOutputs: [{ label: "DCF", value: 828, format: "currency", description: "Traffic quality." }] },
    { id: "cost-2025q4", eventDate: "2025-09-25", fiscalPeriod: "FY2025 Q4", asOfPrice: 960, fairValue: 850, targetPrice3Y: 956, expectedShareholderCagr: -0.001, method: "Premium multiple audit.", sourceStatus: "research_only", warnings: ["Static local row."], methodOutputs: [{ label: "Blend", value: 850, format: "currency", description: "Stable economics, valuation heavy." }] },
    { id: "cost-2026q1", eventDate: "2025-12-11", fiscalPeriod: "FY2026 Q1", asOfPrice: 905, fairValue: 875, targetPrice3Y: 982, expectedShareholderCagr: 0.027, method: "Membership fee growth actualized.", sourceStatus: "official_actual", warnings: ["Official event, proxy price."], methodOutputs: [{ label: "DCF", value: 872, format: "currency", description: "Fee growth actualized." }] },
    { id: "cost-2026q2", eventDate: "2026-03-05", fiscalPeriod: "FY2026 Q2", asOfPrice: 1020, fairValue: 905, targetPrice3Y: 1018, expectedShareholderCagr: -0.001, method: "Base DCF / FCF multiple local run.", sourceStatus: "official_actual", warnings: ["Backend valuation run not persisted yet."], methodOutputs: [{ label: "Blend", value: 905, format: "currency", description: "Traffic good, multiple demanding." }] },
  ],
  valuation: {
    defaultAssumptions,
    scenarios: {
      Bear: { ...defaultAssumptions, revenueCagr3Y: 0.045, normalizedFcfMargin: 0.027, exitFcfMultiple: 30, evRevenueMultiple: 1.25, discountRate: 0.085, qualityAdjustment: 1.0, riskHaircut: 0.12 },
      Base: defaultAssumptions,
      Bull: { ...defaultAssumptions, revenueCagr3Y: 0.095, normalizedFcfMargin: 0.036, exitFcfMultiple: 45, evRevenueMultiple: 1.95, discountRate: 0.07, qualityAdjustment: 1.16, riskHaircut: 0.03 },
    },
    modelDescription: "Blends DCF, forward FCF multiple and EV/revenue cross-check for membership-retail economics.",
    noFutureLeakageNote: "Historical rows use event-specific local snapshots and do not backfill current fee income, current traffic, or current valuation multiples into prior quarters.",
  },
  risks: [
    { title: "Premium multiple compression", detail: "The biggest risk is not business failure; it is a long-duration multiple that cannot absorb slower comps.", severity: "high", killSignal: "Traffic falls below sector while valuation remains >40x forward earnings." },
    { title: "Membership renewal erosion", detail: "A fee increase that weakens renewal quality would damage the annuity thesis.", severity: "high", killSignal: "Renewal rate declines for multiple quarters after fee increase." },
    { title: "Wage and shrink pressure", detail: "Costco protects price leadership; labor and shrink can cap margin upside.", severity: "medium", killSignal: "Core operating margin misses despite healthy comps." },
  ],
  monitoring: ["Renewal rate and paid households", "Traffic vs ticket", "International unit productivity", "Core merchandise margin", "SG&A wage pressure"],
  sourceGaps: [
    "Historical valuation rows are local research fallback, not backend valuation_runs.",
    "Daily price bars for COST and SPY have not been imported into a COST backend database.",
    "Quarterly transcript parsing is not yet automated.",
  ],
  backendStatus: {
    supported: false,
    detail: "COST has frontend research history and valuation now, but no per-ticker SQLite backend or AWS data deployment yet.",
    nextSteps: ["Create data/local/cost/backend/cost_research.sqlite.", "Import COST/SPY daily prices.", "Persist valuation runs by reporting event.", "Add COST to backend manifest."],
  },
  qualityBadges: [
    { label: "Market price", value: "Proxy snapshot", badge: "Placeholder" },
    { label: "Operating KPIs", value: "Manual research", badge: "Assumption" },
    { label: "Historical valuation", value: "Local fallback", badge: "Placeholder" },
  ],
};
