import type { VDataset } from "./model";

export const vDataset: VDataset = {
  latestReportingPeriod: "FY2026 Q2",
  marketData: {
    currentPrice: 350,
    priceDate: "2026-05-14",
    sharesForMarketCap: 1_932,
    marketCap: 676_200,
    source: "research_only offline fallback; backend daily price bars override this when API is online",
    sourceStatus: "research_only",
  },
  periods: [
    {
      id: "fy2025",
      label: "FY2025",
      fiscalYear: 2025,
      periodType: "annual",
      sourceStatus: "market_data_proxy",
      sourceId: "v-static-fallback-fy2025",
      revenue: 39_500,
      operatingIncome: 26_600,
      operatingMargin: 0.673,
      netIncome: 21_600,
      dilutedEps: 11.00,
      dilutedShares: 1_960,
      operatingCashFlow: 24_700,
      capex: 1_200,
      freeCashFlow: 23_500,
      dividendsPaid: 4_700,
      buybacks: 17_000,
      dividendPerShare: 2.40,
      notes: "Static fallback; backend SQLite rows replace this when the API is online.",
    },
    {
      id: "fy2026-q2",
      label: "FY2026 Q2",
      fiscalYear: 2026,
      fiscalQuarter: "Q2",
      periodType: "quarter",
      sourceStatus: "market_data_proxy",
      sourceId: "v-static-fallback-fy2026-q2",
      revenue: 10_400,
      operatingIncome: 7_000,
      operatingMargin: 0.673,
      netIncome: 5_650,
      dilutedEps: 2.92,
      dilutedShares: 1_932,
      operatingCashFlow: 6_400,
      capex: 320,
      freeCashFlow: 6_080,
      dividendsPaid: 1_250,
      buybacks: 4_500,
      dividendPerShare: 0.65,
      notes: "Static fallback; backend SQLite rows replace this when the API is online.",
    },
  ],
  operatingMetrics: [
    {
      periodId: "fy2026-q2",
      asOfDate: "2026-04-29",
      sourceStatus: "market_data_proxy",
      grossDollarVolume: 4_050_000,
      purchaseVolume: 3_020_000,
      crossBorderVolumeGrowth: 0.11,
      switchedTransactions: 69_000,
      switchedTransactionsGrowth: 0.11,
      processedTransactions: 69_000,
      cardsAccounts: 4_650,
      rebatesIncentives: 4_350,
      takeRate: 10_400 / 4_050_000,
      takeRateCommentary: "Net revenue yield is monitored against gross dollar volume and rebates/incentives.",
      crossBorderCommentary: "Cross-border remains the most travel-sensitive premium-growth driver.",
      valueAddedServicesCommentary: "Cybersecurity, fraud, identity, loyalty, data analytics, and consulting mix should support margins if growth stays above core network volume.",
      regulatoryCommentary: "Risk focus is network fees, routing, and interchange pressure rather than assuming every merchant fee headline is a direct V revenue cut.",
      competitionCommentary: "Mastercard, Amex, domestic schemes, RTP, and account-to-account rails pressure different parts of the Visa model.",
      capitalReturnCommentary: "Buybacks are material to EPS growth and must be compared with FCF coverage.",
      normalizedFcfCommentary: "Capex-light economics support high FCF conversion, but incentives and regulation can change conversion quality.",
    },
  ],
  segmentFinancials: [
    { periodId: "fy2026-q2", segment: "Payment Network / Switched Transactions", taxonomy: "payments_network", revenue: 4_368, operatingIncome: 2_883, operatingMargin: 0.66, growth: 0.11, sourceStatus: "research_only" },
    { periodId: "fy2026-q2", segment: "Cross-Border Assessment and Travel", taxonomy: "cross_border", revenue: 2_392, operatingIncome: 1_722, operatingMargin: 0.72, growth: 0.11, sourceStatus: "research_only" },
    { periodId: "fy2026-q2", segment: "Value-Added Services and Cyber/Data", taxonomy: "value_added_services", revenue: 3_640, operatingIncome: 2_111, operatingMargin: 0.58, growth: 0.16, sourceStatus: "research_only" },
  ],
};
