import type { StockValuationConfig } from "../types";
import type { TslaScenarioPresetMap, TslaValuationAssumptions } from "./model";

export const defaultTslaValuationAssumptions: TslaValuationAssumptions = {
  currentPrice: 406.96,
  dilutedShares: 3538,
  normalizedRevenue: 105_000,
  revenueGrowth: 0.07,
  autoRevenueMix: 0.78,
  energyRevenueMix: 0.13,
  autoOperatingMargin: 0.075,
  energyRevenueGrowth: 0.22,
  normalizedFcfMargin: 0.075,
  targetAutoPe: 34,
  energySalesMultiple: 5.0,
  targetFcfYield: 0.035,
  discountRate: 0.09,
  terminalGrowth: 0.03,
  netCashUsd: 15_000,
  autonomyOptionValuePerShare: 120,
  autonomyProbability: 0.28,
  evCompetitionHaircut: 0.12,
  executionHaircut: 0.08,
  regulatoryHaircut: 0.04,
  dividendYield: 0,
  buybackYield: 0,
};

export const tslaScenarioPresets: TslaScenarioPresetMap = {
  Bear: {
    ...defaultTslaValuationAssumptions,
    normalizedRevenue: 88_000,
    revenueGrowth: -0.02,
    autoRevenueMix: 0.82,
    energyRevenueMix: 0.10,
    autoOperatingMargin: 0.035,
    energyRevenueGrowth: 0.10,
    normalizedFcfMargin: 0.035,
    targetAutoPe: 18,
    energySalesMultiple: 2.5,
    targetFcfYield: 0.06,
    discountRate: 0.11,
    autonomyOptionValuePerShare: 45,
    autonomyProbability: 0.12,
    evCompetitionHaircut: 0.22,
    executionHaircut: 0.16,
    regulatoryHaircut: 0.08,
  },
  Base: defaultTslaValuationAssumptions,
  Bull: {
    ...defaultTslaValuationAssumptions,
    normalizedRevenue: 130_000,
    revenueGrowth: 0.15,
    autoRevenueMix: 0.70,
    energyRevenueMix: 0.20,
    autoOperatingMargin: 0.115,
    energyRevenueGrowth: 0.34,
    normalizedFcfMargin: 0.12,
    targetAutoPe: 48,
    energySalesMultiple: 8.0,
    targetFcfYield: 0.025,
    discountRate: 0.08,
    autonomyOptionValuePerShare: 260,
    autonomyProbability: 0.42,
    evCompetitionHaircut: 0.07,
    executionHaircut: 0.05,
    regulatoryHaircut: 0.03,
  },
};

export function buildTslaValuationConfig(
  calculateValuation: StockValuationConfig["calculateValuation"],
): StockValuationConfig {
  return {
    ticker: "TSLA",
    modelType: "auto-energy-autonomy-dcf-fcf-sotp-triangulation",
    assumptions: [
      { key: "normalizedRevenue", label: "Normalized Revenue", value: defaultTslaValuationAssumptions.normalizedRevenue, min: 70_000, max: 180_000, step: 1000, format: "currency", source: "assumption", description: "Forward annual revenue base across auto, energy, services and software.", category: "Scale", unit: "USD", periodicity: "forward annual" },
      { key: "revenueGrowth", label: "Revenue Growth", value: defaultTslaValuationAssumptions.revenueGrowth, min: -0.08, max: 0.25, step: 0.005, format: "percent", source: "assumption", description: "Consolidated growth before energy-specific mix adjustment.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "autoRevenueMix", label: "Auto Revenue Mix", value: defaultTslaValuationAssumptions.autoRevenueMix, min: 0.50, max: 0.90, step: 0.005, format: "percent", source: "assumption", description: "Core auto share of normalized revenue.", category: "Mix", unit: "percent" },
      { key: "energyRevenueMix", label: "Energy Revenue Mix", value: defaultTslaValuationAssumptions.energyRevenueMix, min: 0.05, max: 0.35, step: 0.005, format: "percent", source: "assumption", description: "Energy storage and generation share of normalized revenue.", category: "Mix", unit: "percent" },
      { key: "autoOperatingMargin", label: "Auto Operating Margin", value: defaultTslaValuationAssumptions.autoOperatingMargin, min: 0.00, max: 0.18, step: 0.005, format: "percent", source: "assumption", description: "Normalized auto operating margin after price competition and mix.", category: "Margins", unit: "percent" },
      { key: "energyRevenueGrowth", label: "Energy Growth", value: defaultTslaValuationAssumptions.energyRevenueGrowth, min: 0, max: 0.50, step: 0.005, format: "percent", source: "assumption", description: "Energy storage growth used in the separate SOTP leg.", category: "Growth", unit: "percent" },
      { key: "normalizedFcfMargin", label: "FCF Margin", value: defaultTslaValuationAssumptions.normalizedFcfMargin, min: 0.00, max: 0.18, step: 0.005, format: "percent", source: "assumption", description: "Normalized free cash flow conversion after factories, AI compute and working capital.", category: "Cash Flow", unit: "percent" },
      { key: "targetAutoPe", label: "Auto P/E", value: defaultTslaValuationAssumptions.targetAutoPe, min: 10, max: 60, step: 1, format: "multiple", source: "assumption", description: "Core auto earnings multiple before separate energy and autonomy value.", category: "Valuation", unit: "multiple" },
      { key: "energySalesMultiple", label: "Energy EV/Sales", value: defaultTslaValuationAssumptions.energySalesMultiple, min: 1, max: 12, step: 0.25, format: "multiple", source: "assumption", description: "Separate sales multiple for energy storage scale.", category: "Valuation", unit: "multiple" },
      { key: "targetFcfYield", label: "Target FCF Yield", value: defaultTslaValuationAssumptions.targetFcfYield, min: 0.02, max: 0.08, step: 0.001, format: "percent", source: "assumption", description: "FCF-yield guardrail against premium multiple overreach.", category: "Valuation", unit: "percent" },
      { key: "discountRate", label: "Discount Rate", value: defaultTslaValuationAssumptions.discountRate, min: 0.065, max: 0.13, step: 0.0025, format: "percent", source: "assumption", description: "Cost of equity reflecting auto cyclicality, AI execution and regulatory risk.", category: "Valuation", unit: "percent" },
      { key: "autonomyOptionValuePerShare", label: "Autonomy Option / Share", value: defaultTslaValuationAssumptions.autonomyOptionValuePerShare, min: 0, max: 400, step: 5, format: "currency", source: "assumption", description: "Standalone autonomy/robotaxi option value before probability weighting.", category: "Optionality", unit: "USD" },
      { key: "autonomyProbability", label: "Autonomy Probability", value: defaultTslaValuationAssumptions.autonomyProbability, min: 0, max: 0.65, step: 0.01, format: "percent", source: "assumption", description: "Probability weight applied to autonomy optionality; not embedded in core auto margin.", category: "Optionality", unit: "percent" },
      { key: "evCompetitionHaircut", label: "EV Competition Haircut", value: defaultTslaValuationAssumptions.evCompetitionHaircut, min: 0, max: 0.30, step: 0.005, format: "percent", source: "assumption", description: "China/global EV pricing, mix and demand risk.", category: "Risk", unit: "percent" },
      { key: "executionHaircut", label: "Execution Haircut", value: defaultTslaValuationAssumptions.executionHaircut, min: 0, max: 0.25, step: 0.005, format: "percent", source: "assumption", description: "Factory, product-cycle, energy deployment and AI compute execution risk.", category: "Risk", unit: "percent" },
      { key: "regulatoryHaircut", label: "Regulatory Haircut", value: defaultTslaValuationAssumptions.regulatoryHaircut, min: 0, max: 0.18, step: 0.005, format: "percent", source: "assumption", description: "Autonomy, safety, labor, subsidy and trade-policy risk.", category: "Risk", unit: "percent" },
    ],
    scenarios: [
      { name: "Bear", assumptions: tslaScenarioPresets.Bear },
      { name: "Base", assumptions: tslaScenarioPresets.Base },
      { name: "Bull", assumptions: tslaScenarioPresets.Bull },
    ],
    calculateValuation,
  };
}
