import type { TslaDataset } from "./model";

export const tslaDataset: TslaDataset = {
  ticker: "TSLA",
  companyName: "Tesla, Inc.",
  currency: "USD",
  latestReportingPeriod: "Q1 2026",
  marketData: {
    currentPrice: 406.96,
    priceDate: "2026-05-19",
    sharesForMarketCap: 3538,
    source: "SEC companyfacts for reported data; Nasdaq quote API primary price with Stooq close cross-check",
    sourceStatus: "market_data",
  },
  periods: [
    {
      id: "fy2023",
      label: "FY 2023",
      fiscalYear: 2023,
      periodType: "annual",
      asOfDate: "2024-01-29",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2023 / FY2023 10-K",
      revenue: 96773,
      grossProfit: 17660,
      grossMargin: 0.182,
      operatingIncome: 8891,
      operatingMargin: 0.092,
      netIncome: 14997,
      dilutedEps: 4.3,
      dilutedShares: 3485,
      operatingCashFlow: 13256,
      capex: 8899,
      freeCashFlow: 4357,
      notes: "Reported net income benefited from tax items; operating income and FCF are cleaner anchors.",
    },
    {
      id: "fy2024",
      label: "FY 2024",
      fiscalYear: 2024,
      periodType: "annual",
      asOfDate: "2025-01-30",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2024 / FY2024 10-K",
      revenue: 97690,
      grossProfit: 17450,
      grossMargin: 0.179,
      operatingIncome: 7076,
      operatingMargin: 0.072,
      netIncome: 7091,
      dilutedEps: 2.04,
      dilutedShares: 3498,
      operatingCashFlow: 14923,
      capex: 11342,
      freeCashFlow: 3581,
      notes: "Revenue grew little while pricing and product-mix pressure compressed operating margin.",
    },
    {
      id: "fy2025",
      label: "FY 2025",
      fiscalYear: 2025,
      periodType: "annual",
      asOfDate: "2026-01-29",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2025 / FY2025 10-K",
      revenue: 94827,
      grossProfit: 17094,
      grossMargin: 0.18,
      operatingIncome: 4355,
      operatingMargin: 0.046,
      netIncome: 3794,
      dilutedEps: 1.08,
      dilutedShares: 3528,
      operatingCashFlow: 14747,
      capex: 8527,
      freeCashFlow: 6220,
      notes: "Margins weakened while cash generation improved; valuation depends heavily on whether future growth comes from auto, energy or autonomy.",
    },
    {
      id: "fy2026-q1",
      label: "Q1 2026",
      fiscalYear: 2026,
      fiscalQuarter: "Q1",
      periodType: "quarter",
      asOfDate: "2026-04-23",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2026Q1 / Q1 10-Q",
      revenue: 22387,
      grossProfit: 4720,
      grossMargin: 0.211,
      operatingIncome: 941,
      operatingMargin: 0.042,
      netIncome: 477,
      dilutedEps: 0.13,
      dilutedShares: 3538,
      operatingCashFlow: 3937,
      capex: 2493,
      freeCashFlow: 1444,
      notes: "Latest reported quarter; auto margin, energy scale and autonomy progress need separate attribution.",
    },
  ],
  operatingMetrics: [
    {
      periodId: "fy2023",
      asOfDate: "2024-01-29",
      sourceStatus: "research_only",
      autoDemandSignal: 0.65,
      energyStorageSignal: 0.45,
      autonomyProgressSignal: 0.25,
      grossMarginDurabilitySignal: 0.4,
      evCompetitionCommentary: "The EV category remained structurally growing but price competition already started to matter.",
      energyCommentary: "Energy storage was an emerging contributor, but not yet enough to carry enterprise valuation alone.",
      autonomyCommentary: "Autonomy value was mostly option value and should not be embedded inside the base auto margin.",
      chinaRiskCommentary: "China competition and local pricing are core risks to global auto gross margin.",
    },
    {
      periodId: "fy2024",
      asOfDate: "2025-01-30",
      sourceStatus: "research_only",
      autoDemandSignal: 0.45,
      energyStorageSignal: 0.6,
      autonomyProgressSignal: 0.35,
      grossMarginDurabilitySignal: 0.32,
      evCompetitionCommentary: "Pricing pressure and model-cycle aging made the auto business look more cyclical.",
      energyCommentary: "Energy storage became more important to the growth story and deserves separate valuation treatment.",
      autonomyCommentary: "Software/autonomy progress remained difficult to map into audited revenue.",
      chinaRiskCommentary: "China pricing and local EV share gains increased risk to global margin durability.",
    },
    {
      periodId: "fy2025",
      asOfDate: "2026-01-29",
      sourceStatus: "research_only",
      autoDemandSignal: 0.35,
      energyStorageSignal: 0.72,
      autonomyProgressSignal: 0.45,
      grossMarginDurabilitySignal: 0.28,
      evCompetitionCommentary: "Auto revenue and operating margin deterioration force the model to prove non-auto value separately.",
      energyCommentary: "Energy storage scale is now a real offset, but segment-level margin data still needs official extraction.",
      autonomyCommentary: "Autonomy remains the main premium-multiple debate and is modeled as probability-weighted optionality.",
      chinaRiskCommentary: "China remains a margin and demand risk, not only a unit-growth risk.",
    },
    {
      periodId: "fy2026-q1",
      asOfDate: "2026-04-23",
      sourceStatus: "research_only",
      autoDemandSignal: 0.42,
      energyStorageSignal: 0.76,
      autonomyProgressSignal: 0.5,
      grossMarginDurabilitySignal: 0.31,
      evCompetitionCommentary: "The stock requires evidence that auto margins can stabilize while volumes resume growth.",
      energyCommentary: "Energy should be tracked as a separate compounding asset rather than buried in consolidated revenue.",
      autonomyCommentary: "Autonomy optionality is valuable only if deployment, regulation and take-rate milestones become measurable.",
      chinaRiskCommentary: "China local competition can keep pressure on realized ASP and gross margin.",
    },
  ],
  researchQuestions: [
    {
      key: "auto",
      question: "Is Tesla still an auto volume compounder or a maturing EV OEM?",
      currentView: "The model separates core auto earnings power from energy and autonomy optionality.",
      evidenceNeeded: "Deliveries, ASP, gross margin ex credits, model refresh cadence, factory utilization and regional price cuts.",
    },
    {
      key: "energy",
      question: "Can energy storage become a large second profit pool?",
      currentView: "Energy gets its own sales multiple, but segment margin requires official extraction before high confidence.",
      evidenceNeeded: "Megapack backlog, deployments, gross margin, revenue recognition and project concentration.",
    },
    {
      key: "autonomy",
      question: "How much autonomy / robotaxi value is already priced in?",
      currentView: "Autonomy is probability-weighted optionality, not a hidden boost to core auto valuation.",
      evidenceNeeded: "Miles driven, disengagement/safety metrics, regulatory approvals, monetization, take-rate and fleet economics.",
    },
    {
      key: "capital-intensity",
      question: "Does FCF support the premium multiple?",
      currentView: "FCF yield is a guardrail because capex, AI compute and factories can absorb cash.",
      evidenceNeeded: "Capex plan, AI training spend, working capital, inventory and buyback/dividend policy.",
    },
  ],
  sourceGaps: [
    "Automotive, energy and services segment data are not yet parsed from Tesla custom XBRL tags or official tables.",
    "Autonomy progress metrics are research-only and do not represent audited financial results.",
    "No TSLA backend SQLite workflow is registered yet; historical event-based valuation and daily-price backtests are deferred.",
    "The Stooq market price snapshot should be cross-checked before IC use because market-data vendors can differ on adjusted prices.",
  ],
};
