import type { TslaDataset } from "./model";

export const tslaDataset: TslaDataset = {
  ticker: "TSLA",
  companyName: "Tesla, Inc.",
  currency: "USD",
  latestReportingPeriod: "Q1 2026",
  marketData: {
    currentPrice: 406.96,
    priceDate: "2026-05-19",
    sharesForMarketCap: 3538,
    source: "SEC companyfacts for reported data; Nasdaq quote API primary price with Stooq close cross-check",
    sourceStatus: "market_data",
  },
  periods: [
    {
      id: "fy2023",
      label: "FY 2023",
      fiscalYear: 2023,
      periodType: "annual",
      asOfDate: "2024-01-29",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2023 / FY2023 10-K",
      revenue: 96773,
      grossProfit: 17660,
      grossMargin: 0.182,
      operatingIncome: 8891,
      operatingMargin: 0.092,
      netIncome: 14997,
      dilutedEps: 4.3,
      dilutedShares: 3485,
      operatingCashFlow: 13256,
      capex: 8899,
      freeCashFlow: 4357,
      notes: "Reported net income benefited from tax items; operating income and FCF are cleaner anchors.",
    },
    {
      id: "fy2024",
      label: "FY 2024",
      fiscalYear: 2024,
      periodType: "annual",
      asOfDate: "2025-01-30",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2024 / FY2024 10-K",
      revenue: 97690,
      grossProfit: 17450,
      grossMargin: 0.179,
      operatingIncome: 7076,
      operatingMargin: 0.072,
      netIncome: 7091,
      dilutedEps: 2.04,
      dilutedShares: 3498,
      operatingCashFlow: 14923,
      capex: 11342,
      freeCashFlow: 3581,
      notes: "Revenue grew little while pricing and product-mix pressure compressed operating margin.",
    },
    {
      id: "fy2025",
      label: "FY 2025",
      fiscalYear: 2025,
      periodType: "annual",
      asOfDate: "2026-01-29",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2025 / FY2025 10-K",
      revenue: 94827,
      grossProfit: 17094,
      grossMargin: 0.18,
      operatingIncome: 4355,
      operatingMargin: 0.046,
      netIncome: 3794,
      dilutedEps: 1.08,
      dilutedShares: 3528,
      operatingCashFlow: 14747,
      capex: 8527,
      freeCashFlow: 6220,
      notes: "Margins weakened while cash generation improved; valuation depends heavily on whether future growth comes from auto, energy or autonomy.",
    },
    {
      id: "fy2026-q1",
      label: "Q1 2026",
      fiscalYear: 2026,
      fiscalQuarter: "Q1",
      periodType: "quarter",
      asOfDate: "2026-04-23",
      sourceStatus: "official_actual",
      sourceId: "SEC companyfacts CY2026Q1 / Q1 10-Q",
      revenue: 22387,
      grossProfit: 4720,
      grossMargin: 0.211,
      operatingIncome: 941,
      operatingMargin: 0.042,
      netIncome: 477,
      dilutedEps: 0.13,
      dilutedShares: 3538,
      operatingCashFlow: 3937,
      capex: 2493,
      freeCashFlow: 1444,
      notes: "Latest reported quarter; auto margin, energy scale and autonomy progress need separate attribution.",
    },
  ],
  operatingMetrics: [
    {
      periodId: "fy2023",
      asOfDate: "2024-01-29",
      sourceStatus: "research_only",
      autoDemandSignal: 0.65,
      energyStorageSignal: 0.45,
      autonomyProgressSignal: 0.25,
      grossMarginDurabilitySignal: 0.4,
      evCompetitionCommentary: "The EV category remained structurally growing but price competition already started to matter.",
      energyCommentary: "Energy storage was an emerging contributor, but not yet enough to carry enterprise valuation alone.",
      autonomyCommentary: "Autonomy value was mostly option value and should not be embedded inside the base auto margin.",
      chinaRiskCommentary: "China competition and local pricing are core risks to global auto gross margin.",
    },
    {
      periodId: "fy2024",
      asOfDate: "2025-01-30",
      sourceStatus: "research_only",
      autoDemandSignal: 0.45,
      energyStorageSignal: 0.6,
      autonomyProgressSignal: 0.35,
      grossMarginDurabilitySignal: 0.32,
      evCompetitionCommentary: "Pricing pressure and model-cycle aging made the auto business look more cyclical.",
      energyCommentary: "Energy storage became more important to the growth story and deserves separate valuation treatment.",
      autonomyCommentary: "Software/autonomy progress remained difficult to map into audited revenue.",
      chinaRiskCommentary: "China pricing and local EV share gains increased risk to global margin durability.",
    },
    {
      periodId: "fy2025",
      asOfDate: "2026-01-29",
      sourceStatus: "research_only",
      autoDemandSignal: 0.35,
      energyStorageSignal: 0.72,
      autonomyProgressSignal: 0.45,
      grossMarginDurabilitySignal: 0.28,
      evCompetitionCommentary: "Auto revenue and operating margin deterioration force the model to prove non-auto value separately.",
      energyCommentary: "Energy storage scale is now a real offset, but segment-level margin data still needs official extraction.",
      autonomyCommentary: "Autonomy remains the main premium-multiple debate and is modeled as probability-weighted optionality.",
      chinaRiskCommentary: "China remains a margin and demand risk, not only a unit-growth risk.",
    },
    {
      periodId: "fy2026-q1",
      asOfDate: "2026-04-23",
      sourceStatus: "research_only",
      autoDemandSignal: 0.42,
      energyStorageSignal: 0.76,
      autonomyProgressSignal: 0.5,
      grossMarginDurabilitySignal: 0.31,
      evCompetitionCommentary: "The stock requires evidence that auto margins can stabilize while volumes resume growth.",
      energyCommentary: "Energy should be tracked as a separate compounding asset rather than buried in consolidated revenue.",
      autonomyCommentary: "Autonomy optionality is valuable only if deployment, regulation and take-rate milestones become measurable.",
      chinaRiskCommentary: "China local competition can keep pressure on realized ASP and gross margin.",
    },
  ],
  historicalValuations: [
    {
      id: "tsla-fy2018",
      label: "FY2018 close",
      eventDate: "2019-02-19",
      fiscalPeriod: "FY2018",
      asOfPrice: 20.17,
      fairValue: 18,
      targetPrice3Y: 28,
      expectedShareholderCagr: 0.115,
      method: "Auto production ramp probability-weighted DCF",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Autonomy and energy are treated as small options because audited evidence was limited at this event date.",
        "No later Megapack or FSD subscription framing is backfilled into this older valuation.",
      ],
      methodOutputs: [
        { label: "Auto DCF", value: 17, format: "currency", description: "Production ramp DCF with high execution risk." },
        { label: "Energy option", value: 1.2, format: "currency", description: "Small option credit before scaled storage deployment evidence." },
        { label: "Execution haircut", value: -0.24, format: "percent", description: "Discount for Model 3 ramp, liquidity and manufacturing risk." },
      ],
    },
    {
      id: "tsla-fy2019",
      label: "FY2019 close",
      eventDate: "2020-02-13",
      fiscalPeriod: "FY2019",
      asOfPrice: 53.6,
      fairValue: 41,
      targetPrice3Y: 67,
      expectedShareholderCagr: 0.077,
      method: "Auto growth DCF with early software option",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Valuation recognized improving scale but kept autonomy probability low.",
        "Energy storage had not yet become large enough to drive full-company fair value.",
      ],
      methodOutputs: [
        { label: "Auto earnings path", value: 38, format: "currency", description: "Higher delivery scale and improving manufacturing cost." },
        { label: "Autonomy option", value: 5, format: "currency", description: "Low-probability software upside kept separate." },
        { label: "Competition haircut", value: -0.12, format: "percent", description: "EV competition and capacity execution risk." },
      ],
    },
    {
      id: "tsla-fy2020",
      label: "FY2020 close",
      eventDate: "2021-02-08",
      fiscalPeriod: "FY2020",
      asOfPrice: 287.81,
      fairValue: 150,
      targetPrice3Y: 210,
      expectedShareholderCagr: -0.1,
      method: "Auto hypergrowth multiple stress",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Stock price already embedded aggressive growth and optionality after the 2020 rerating.",
        "Fair value does not use later energy deployment data or current autonomy narratives.",
      ],
      methodOutputs: [
        { label: "Auto growth value", value: 132, format: "currency", description: "High delivery growth with margin normalization." },
        { label: "Software option", value: 28, format: "currency", description: "Explicit optionality rather than buried multiple expansion." },
        { label: "Multiple risk", value: -0.3, format: "percent", description: "Premium multiple compression risk after rerating." },
      ],
    },
    {
      id: "tsla-fy2021",
      label: "FY2021 close",
      eventDate: "2022-02-07",
      fiscalPeriod: "FY2021",
      asOfPrice: 302.45,
      fairValue: 250,
      targetPrice3Y: 360,
      expectedShareholderCagr: 0.06,
      method: "Auto scale plus software option bridge",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Operating leverage gets more credit, but valuation still depends on sustaining auto gross margin.",
        "Energy storage remains a visible but not dominant value contributor.",
      ],
      methodOutputs: [
        { label: "Core auto", value: 210, format: "currency", description: "Delivery growth and higher auto margin." },
        { label: "Energy SOTP", value: 18, format: "currency", description: "Early storage scaling credit." },
        { label: "Autonomy option", value: 32, format: "currency", description: "Probability-weighted software optionality." },
      ],
    },
    {
      id: "tsla-fy2022",
      label: "FY2022 close",
      eventDate: "2023-01-31",
      fiscalPeriod: "FY2022",
      asOfPrice: 173.22,
      fairValue: 205,
      targetPrice3Y: 295,
      expectedShareholderCagr: 0.194,
      method: "Reset auto multiple plus energy growth",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Price reset creates upside, but China pricing and demand elasticity are the central risks.",
        "Autonomy remains separate option value to avoid double counting in core auto margin.",
      ],
      methodOutputs: [
        { label: "Core auto", value: 166, format: "currency", description: "Lower multiple but still above-market growth." },
        { label: "Energy SOTP", value: 27, format: "currency", description: "Storage deployments increasingly material." },
        { label: "China haircut", value: -0.1, format: "percent", description: "Risk from local competition and ASP pressure." },
      ],
    },
    {
      id: "tsla-fy2023",
      label: "FY2023 close",
      eventDate: "2024-01-29",
      fiscalPeriod: "FY2023",
      asOfPrice: 190.93,
      fairValue: 225,
      targetPrice3Y: 325,
      expectedShareholderCagr: 0.193,
      method: "Auto margin reset with energy SOTP",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Reported net income had tax noise; operating income and FCF are cleaner anchors.",
        "Energy value rises, but segment margin needs official extraction before high confidence.",
      ],
      methodOutputs: [
        { label: "Core auto", value: 158, format: "currency", description: "Lower auto margin after price cuts." },
        { label: "Energy SOTP", value: 44, format: "currency", description: "Storage deployment scale begins to support standalone value." },
        { label: "Autonomy option", value: 32, format: "currency", description: "Visible but still low-confidence optionality." },
      ],
    },
    {
      id: "tsla-fy2024",
      label: "FY2024 close",
      eventDate: "2025-01-30",
      fiscalPeriod: "FY2024",
      asOfPrice: 400.28,
      fairValue: 330,
      targetPrice3Y: 470,
      expectedShareholderCagr: 0.055,
      method: "Premium multiple stress with energy scale",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Price embeds a premium for autonomy and energy before audited software revenue is separately disclosed.",
        "Auto revenue growth normalized, so valuation confidence falls unless non-auto economics become measurable.",
      ],
      methodOutputs: [
        { label: "Core auto", value: 210, format: "currency", description: "Stabilized but not expanding auto margin." },
        { label: "Energy SOTP", value: 78, format: "currency", description: "Megapack scale and grid storage demand." },
        { label: "Autonomy option", value: 70, format: "currency", description: "Probability-weighted optionality, not current revenue." },
      ],
    },
    {
      id: "tsla-fy2025",
      label: "FY2025 close",
      eventDate: "2026-01-29",
      fiscalPeriod: "FY2025",
      asOfPrice: 381.55,
      fairValue: 360,
      targetPrice3Y: 520,
      expectedShareholderCagr: 0.078,
      method: "Energy growth plus autonomy option guardrailed by FCF",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Uses FY2025 data only; Q1 2026 stabilization is not included.",
        "FSD subscription revenue is not disclosed, so software share is a model proxy.",
      ],
      methodOutputs: [
        { label: "Core auto", value: 196, format: "currency", description: "Auto margin pressured but cash generation stronger." },
        { label: "Energy SOTP", value: 96, format: "currency", description: "Storage growth now a meaningful second value pool." },
        { label: "FSD/autonomy option", value: 96, format: "currency", description: "Explicit option value with low source confidence." },
      ],
    },
    {
      id: "tsla-q1-2026",
      label: "Q1 2026",
      eventDate: "2026-04-23",
      fiscalPeriod: "Q1 2026",
      asOfPrice: 373.72,
      fairValue: 382,
      targetPrice3Y: 565,
      expectedShareholderCagr: 0.125,
      method: "Latest auto stabilization plus energy/FSD option bridge",
      sourceStatus: "research_only",
      sourceId: "Local research snapshot; price should be refreshed by backend daily-price import before IC use",
      warnings: [
        "Latest valuation still separates core auto, energy and FSD/autonomy rather than using one full-company multiple.",
        "Backend price import and persisted valuation runs are still required for production-grade no-leakage audit.",
      ],
      methodOutputs: [
        { label: "Core auto", value: 205, format: "currency", description: "Auto margin stabilization case." },
        { label: "Energy SOTP", value: 108, format: "currency", description: "Storage deployments and forward grid demand." },
        { label: "FSD/autonomy option", value: 104, format: "currency", description: "Probability-weighted software and autonomy value." },
      ],
    },
  ],
  earningsCalls: [
    {
      id: "tsla-call-q2-2025",
      quarter: "Q2 2025",
      callDate: "2025-07-23",
      sourceStatus: "research_only",
      managementTone: "balanced",
      reportedFacts: [
        "Auto margin pressure remained the core near-term earnings issue.",
        "Energy storage was becoming more relevant to the growth story.",
        "Autonomy narrative needed clearer linkage to revenue, take-rate and regulatory milestones.",
      ],
      analystFocus: ["Auto gross margin", "Energy storage backlog", "FSD monetization", "China demand"],
      marketFocusSummary: "Investors were testing whether Tesla was becoming a mature auto OEM or a multi-vertical platform.",
      modelReadThrough: "Keep auto earnings multiple below peak levels and require energy/FSD to earn separate valuation credit.",
      focusScores: { autoMargin: 74, energyStorage: 62, autonomyFsd: 68, chinaCompetition: 66, capexFcf: 58, regulatoryRisk: 52 },
    },
    {
      id: "tsla-call-q3-2025",
      quarter: "Q3 2025",
      callDate: "2025-10-22",
      sourceStatus: "research_only",
      managementTone: "constructive",
      reportedFacts: [
        "Energy storage growth increasingly offset investor concern about slower auto growth.",
        "Autonomy commentary remained important but difficult to translate into audited revenue.",
        "Capex and AI compute spend were recurring questions for FCF durability.",
      ],
      analystFocus: ["Megapack demand", "Robotaxi / FSD milestones", "Capex intensity", "Model cycle"],
      marketFocusSummary: "The market focused on whether energy and autonomy could justify premium valuation despite auto margin pressure.",
      modelReadThrough: "Raise energy SOTP weight but keep FSD revenue-share proxy explicitly low confidence.",
      focusScores: { autoMargin: 68, energyStorage: 78, autonomyFsd: 74, chinaCompetition: 62, capexFcf: 64, regulatoryRisk: 58 },
    },
    {
      id: "tsla-call-q4-2025",
      quarter: "Q4 2025",
      callDate: "2026-01-29",
      sourceStatus: "research_only",
      managementTone: "constructive",
      reportedFacts: [
        "FY2025 margin profile showed auto earnings pressure while FCF held up better.",
        "Energy storage deployment scale made the segment too large to treat as an afterthought.",
        "Autonomy/FSD still lacked separate subscription revenue disclosure.",
      ],
      analystFocus: ["Energy deployment runway", "Auto margin floor", "FSD attach rate", "Regulatory path"],
      marketFocusSummary: "Investors were willing to pay for optionality, but the evidence burden shifted to measurable non-auto economics.",
      modelReadThrough: "Use FCF yield as a guardrail; do not let autonomy option value inflate core auto valuation.",
      focusScores: { autoMargin: 65, energyStorage: 84, autonomyFsd: 78, chinaCompetition: 64, capexFcf: 70, regulatoryRisk: 62 },
    },
    {
      id: "tsla-call-q1-2026",
      quarter: "Q1 2026",
      callDate: "2026-04-23",
      sourceStatus: "research_only",
      managementTone: "balanced",
      reportedFacts: [
        "Latest quarter required investors to separate auto stabilization from energy and software optionality.",
        "Energy storage remained the cleanest measurable non-auto growth vector.",
        "FSD subscription economics still needed proxy modeling because Tesla does not disclose the line item separately.",
      ],
      analystFocus: ["Auto demand recovery", "Storage deployment cadence", "FSD subscriptions", "AI compute spend"],
      marketFocusSummary: "The key debate is what share of revenue and value can come from software/energy rather than auto hardware.",
      modelReadThrough: "Maintain explicit option bridge and add FSD proxy revenue-share chart so the software thesis can be debated quantitatively.",
      focusScores: { autoMargin: 67, energyStorage: 86, autonomyFsd: 82, chinaCompetition: 65, capexFcf: 68, regulatoryRisk: 66 },
    },
  ],
  energyStorageDeployments: [
    {
      year: 2018,
      storageGwh: 1.04,
      yoyGrowth: null,
      sourceStatus: "official_actual",
      sourceId: "Tesla annual production and energy deployment disclosures",
      commentary: "Early storage deployments were still small relative to auto revenue.",
    },
    {
      year: 2019,
      storageGwh: 1.65,
      yoyGrowth: 0.587,
      sourceStatus: "official_actual",
      sourceId: "Tesla annual production and energy deployment disclosures",
      commentary: "Storage grew but remained an emerging second business.",
    },
    {
      year: 2020,
      storageGwh: 3.02,
      yoyGrowth: 0.83,
      sourceStatus: "official_actual",
      sourceId: "Tesla annual production and energy deployment disclosures",
      commentary: "Deployments nearly doubled as Megapack began to matter.",
    },
    {
      year: 2021,
      storageGwh: 3.99,
      yoyGrowth: 0.321,
      sourceStatus: "official_actual",
      sourceId: "Tesla annual production and energy deployment disclosures",
      commentary: "Growth continued but supply constraints limited the slope.",
    },
    {
      year: 2022,
      storageGwh: 6.54,
      yoyGrowth: 0.639,
      sourceStatus: "official_actual",
      sourceId: "Tesla annual production and energy deployment disclosures",
      commentary: "Megapack demand began to become a visible part of the thesis.",
    },
    {
      year: 2023,
      storageGwh: 14.72,
      yoyGrowth: 1.251,
      sourceStatus: "official_actual",
      sourceId: "Tesla annual production and energy deployment disclosures",
      commentary: "Storage deployments more than doubled, supporting separate SOTP treatment.",
    },
    {
      year: 2024,
      storageGwh: 31.4,
      yoyGrowth: 1.133,
      sourceStatus: "official_actual",
      sourceId: "Tesla Q4 2024 production, deliveries and deployments release",
      commentary: "Energy storage became too large to bury inside consolidated growth.",
    },
    {
      year: 2025,
      storageGwh: 44.5,
      yoyGrowth: 0.417,
      sourceStatus: "research_only",
      sourceId: "Local research snapshot pending production backend refresh",
      commentary: "The model treats 2025 as a high-growth but decelerating storage year until the backend imports official rows.",
    },
    {
      year: 2026,
      storageGwh: 58,
      yoyGrowth: 0.303,
      sourceStatus: "forecast_assumption",
      sourceId: "Research forward deployment assumption",
      commentary: "Forward case assumes grid storage and data-center power scarcity sustain growth.",
      isForecast: true,
    },
    {
      year: 2027,
      storageGwh: 73,
      yoyGrowth: 0.259,
      sourceStatus: "forecast_assumption",
      sourceId: "Research forward deployment assumption",
      commentary: "Growth fades but remains above auto volume growth if Megapack supply expands.",
      isForecast: true,
    },
    {
      year: 2028,
      storageGwh: 88,
      yoyGrowth: 0.205,
      sourceStatus: "forecast_assumption",
      sourceId: "Research forward deployment assumption",
      commentary: "Longer-run storage value depends on margins and backlog, not only GWh deployments.",
      isForecast: true,
    },
  ],
  fsdSubscriptionProxy: [
    {
      year: 2021,
      fsdSubscriptionRevenue: 250,
      totalRevenue: 53823,
      fsdRevenueShare: 0.0046,
      sourceStatus: "research_only",
      sourceId: "Proxy model; Tesla does not disclose FSD subscription revenue separately",
      assumptionLabel: "Early subscription proxy",
      commentary: "Proxy uses early FSD subscription availability and low assumed active attach rate.",
    },
    {
      year: 2022,
      fsdSubscriptionRevenue: 520,
      totalRevenue: 81462,
      fsdRevenueShare: 0.0064,
      sourceStatus: "research_only",
      sourceId: "Proxy model; Tesla does not disclose FSD subscription revenue separately",
      assumptionLabel: "Low attach-rate proxy",
      commentary: "Subscription mix remains small relative to auto hardware revenue.",
    },
    {
      year: 2023,
      fsdSubscriptionRevenue: 870,
      totalRevenue: 96773,
      fsdRevenueShare: 0.009,
      sourceStatus: "research_only",
      sourceId: "Proxy model; Tesla does not disclose FSD subscription revenue separately",
      assumptionLabel: "Fleet scale proxy",
      commentary: "Larger installed base raises possible software contribution, but disclosure is still absent.",
    },
    {
      year: 2024,
      fsdSubscriptionRevenue: 1180,
      totalRevenue: 97690,
      fsdRevenueShare: 0.0121,
      sourceStatus: "research_only",
      sourceId: "Proxy model; Tesla does not disclose FSD subscription revenue separately",
      assumptionLabel: "Take-rate sensitivity proxy",
      commentary: "Proxy assumes gradual attach-rate improvement rather than a robotaxi step-change.",
    },
    {
      year: 2025,
      fsdSubscriptionRevenue: 1550,
      totalRevenue: 94827,
      fsdRevenueShare: 0.0163,
      sourceStatus: "research_only",
      sourceId: "Proxy model; Tesla does not disclose FSD subscription revenue separately",
      assumptionLabel: "Measured-option proxy",
      commentary: "Software value remains mostly option value without audited subscription disclosure.",
    },
    {
      year: 2026,
      fsdSubscriptionRevenue: 2350,
      totalRevenue: 105000,
      fsdRevenueShare: 0.0224,
      sourceStatus: "forecast_assumption",
      sourceId: "Forward FSD proxy; not official guidance",
      assumptionLabel: "Base adoption forecast",
      commentary: "Forward case assumes better product capability and higher active subscription conversion.",
      isForecast: true,
    },
    {
      year: 2027,
      fsdSubscriptionRevenue: 3900,
      totalRevenue: 122000,
      fsdRevenueShare: 0.032,
      sourceStatus: "forecast_assumption",
      sourceId: "Forward FSD proxy; not official guidance",
      assumptionLabel: "Adoption ramp forecast",
      commentary: "FSD grows faster than revenue only if product, pricing and regulation all improve.",
      isForecast: true,
    },
    {
      year: 2028,
      fsdSubscriptionRevenue: 6500,
      totalRevenue: 142000,
      fsdRevenueShare: 0.0458,
      sourceStatus: "forecast_assumption",
      sourceId: "Forward FSD proxy; not official guidance",
      assumptionLabel: "High-confidence needed",
      commentary: "A mid-single-digit revenue share would be thesis-changing, but still requires external verification.",
      isForecast: true,
    },
  ],
  researchQuestions: [
    {
      key: "auto",
      question: "Is Tesla still an auto volume compounder or a maturing EV OEM?",
      currentView: "The model separates core auto earnings power from energy and autonomy optionality.",
      evidenceNeeded: "Deliveries, ASP, gross margin ex credits, model refresh cadence, factory utilization and regional price cuts.",
    },
    {
      key: "energy",
      question: "Can energy storage become a large second profit pool?",
      currentView: "Energy gets its own sales multiple, but segment margin requires official extraction before high confidence.",
      evidenceNeeded: "Megapack backlog, deployments, gross margin, revenue recognition and project concentration.",
    },
    {
      key: "autonomy",
      question: "How much autonomy / robotaxi value is already priced in?",
      currentView: "Autonomy is probability-weighted optionality, not a hidden boost to core auto valuation.",
      evidenceNeeded: "Miles driven, disengagement/safety metrics, regulatory approvals, monetization, take-rate and fleet economics.",
    },
    {
      key: "capital-intensity",
      question: "Does FCF support the premium multiple?",
      currentView: "FCF yield is a guardrail because capex, AI compute and factories can absorb cash.",
      evidenceNeeded: "Capex plan, AI training spend, working capital, inventory and buyback/dividend policy.",
    },
  ],
  sourceGaps: [
    "Automotive, energy and services segment data are not yet parsed from Tesla custom XBRL tags or official tables.",
    "FSD subscription revenue and FSD share of revenue are proxy estimates because Tesla does not disclose that line item separately.",
    "Autonomy progress metrics are research-only and do not represent audited financial results.",
    "TSLA historical valuation rows are local research snapshots; no SQLite persistence or daily-price backtest is registered yet.",
    "The Stooq market price snapshot should be cross-checked before IC use because market-data vendors can differ on adjusted prices.",
  ],
};
