import type { Scenario, ValuationAssumption } from "../types";
import { msftDataset } from "./data";
import type { MsftValuationAssumptions } from "./model";

const latest = msftDataset.periods.find((period) => period.id === "q3-fy26") ?? msftDataset.periods[0];
const fy26e = msftDataset.periods.find((period) => period.id === "fy26e") ?? latest;
const marketData = msftDataset.marketData;

export const defaultMsftValuationAssumptions: MsftValuationAssumptions = {
  currentPrice: marketData.currentPrice,
  baseSoftwareGrowth: 0.105,
  azureGrowth: 0.30,
  copilotPenetration: 0.32,
  copilotArpuAnnual: 300,
  copilotGrossMarginYear5: 0.64,
  openAiRevenueContribution: 0.018,
  openAiGrossMargin: 0.32,
  aiCapexIntensity: 0.25,
  normalizedCapexIntensity: 0.16,
  operatingMargin: 0.435,
  taxRate: 0.19,
  depreciationSalesRatio: (fy26e.depreciationAmortizationAndOther ?? 38_500) / fy26e.revenue,
  workingCapitalDragPctRevenueGrowth: 0.04,
  wacc: 0.084,
  terminalGrowth: 0.030,
  targetFcfYield: 0.031,
  targetPe: 31,
  targetEvEbit: 25,
  productivitySalesMultiple: 11.5,
  azureSalesMultiple: 12.5,
  windowsSearchGamingSalesMultiple: 6.0,
  aiOptionalityValue: 260_000,
  netCashDebt: (latest.cashAndShortTermInvestments ?? 78_272) - (latest.debt ?? 40_262) - (latest.operatingLeaseLiabilities ?? 16_703),
  dilutedShares: latest.dilutedShares ?? 7_445,
  dividendPerShare: 3.32,
  weightDcf: 0.35,
  weightFcfYield: 0.15,
  weightPe: 0.10,
  weightEvEbit: 0.10,
  weightSotp: 0.20,
  weightAiOptionality: 0.10,
};

export const msftScenarioPresets: Record<Scenario, MsftValuationAssumptions> = {
  Bear: {
    ...defaultMsftValuationAssumptions,
    baseSoftwareGrowth: 0.08,
    azureGrowth: 0.24,
    copilotPenetration: 0.18,
    copilotArpuAnnual: 240,
    copilotGrossMarginYear5: 0.54,
    openAiRevenueContribution: 0.010,
    openAiGrossMargin: 0.20,
    aiCapexIntensity: 0.30,
    normalizedCapexIntensity: 0.19,
    operatingMargin: 0.405,
    wacc: 0.092,
    terminalGrowth: 0.025,
    targetFcfYield: 0.038,
    targetPe: 25,
    targetEvEbit: 20,
    productivitySalesMultiple: 9.0,
    azureSalesMultiple: 9.5,
    windowsSearchGamingSalesMultiple: 4.8,
    aiOptionalityValue: 90_000,
  },
  Base: defaultMsftValuationAssumptions,
  Bull: {
    ...defaultMsftValuationAssumptions,
    baseSoftwareGrowth: 0.125,
    azureGrowth: 0.36,
    copilotPenetration: 0.48,
    copilotArpuAnnual: 340,
    copilotGrossMarginYear5: 0.72,
    openAiRevenueContribution: 0.028,
    openAiGrossMargin: 0.42,
    aiCapexIntensity: 0.21,
    normalizedCapexIntensity: 0.135,
    operatingMargin: 0.465,
    wacc: 0.078,
    terminalGrowth: 0.033,
    targetFcfYield: 0.027,
    targetPe: 36,
    targetEvEbit: 29,
    productivitySalesMultiple: 13.5,
    azureSalesMultiple: 15.5,
    windowsSearchGamingSalesMultiple: 7.2,
    aiOptionalityValue: 420_000,
  },
};

const AS_OF_DATE = "2026-04-29";
const OFFICIAL_GUIDANCE = "management_guidance: FY2026 Q3 earnings call and FY2026 Q4 outlook.";
const SCENARIO_NOTE = "scenario_assumption: analyst case design, not Microsoft official actual.";

export const msftValuationAssumptionDefinitions: ValuationAssumption[] = [
  {
    key: "currentPrice",
    label: "Current Price",
    value: defaultMsftValuationAssumptions.currentPrice,
    min: 250,
    max: 800,
    step: 1,
    format: "currency",
    source: "actual",
    description: "Local MSFT market-data anchor used only for upside/downside math.",
    category: "Market",
    unit: "USD",
    periodicity: "annual",
    asOfDate: marketData.priceDate,
    provenance: marketData.notes,
  },
  {
    key: "baseSoftwareGrowth",
    label: "Base Software Growth",
    value: defaultMsftValuationAssumptions.baseSoftwareGrowth,
    min: 0.04,
    max: 0.18,
    step: 0.0025,
    format: "percent",
    source: "assumption",
    description: "Growth for M365, Dynamics, LinkedIn, Search, and Windows before incremental AI uplift.",
    category: "Growth",
    unit: "percent",
    periodicity: "annual",
    asOfDate: AS_OF_DATE,
    provenance: `${SCENARIO_NOTE} Anchored to FY2026 segment growth and Q4 guidance.`,
  },
  {
    key: "azureGrowth",
    label: "Azure Growth",
    value: defaultMsftValuationAssumptions.azureGrowth,
    min: 0.12,
    max: 0.48,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Medium-term Azure growth driver, explicitly tied to capacity constraints and AI/non-AI consumption.",
    category: "Azure & AI",
    unit: "percent",
    periodicity: "annual",
    provenance: `${OFFICIAL_GUIDANCE} Q4 Azure CC growth guided to 39%-40%; medium-term growth is a scenario assumption.`,
  },
  {
    key: "copilotPenetration",
    label: "Copilot Penetration",
    value: defaultMsftValuationAssumptions.copilotPenetration,
    min: 0.05,
    max: 0.65,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "Target paid penetration of an eligible enterprise seat base; current paid seats are disclosed only as over 20m.",
    category: "Copilot",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Microsoft disclosed paid M365 Copilot seats over 20m, not the eligible denominator.`,
  },
  {
    key: "copilotArpuAnnual",
    label: "Copilot ARPU",
    value: defaultMsftValuationAssumptions.copilotArpuAnnual,
    min: 120,
    max: 480,
    step: 5,
    format: "currency",
    source: "assumption",
    description: "Annual realized Copilot ARPU across seat entitlement plus usage/overage mix.",
    category: "Copilot",
    unit: "USD",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Official ARPU and consumption overage are not disclosed.`,
  },
  {
    key: "copilotGrossMarginYear5",
    label: "Copilot GM Year 5",
    value: defaultMsftValuationAssumptions.copilotGrossMarginYear5,
    min: 0.40,
    max: 0.82,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Gross margin after inference cost, model routing, usage intensity, and platform efficiency gains.",
    category: "Margin",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Microsoft discusses margin effects qualitatively but does not disclose Copilot gross margin.`,
  },
  {
    key: "openAiRevenueContribution",
    label: "OpenAI Revenue Contribution",
    value: defaultMsftValuationAssumptions.openAiRevenueContribution,
    min: 0,
    max: 0.05,
    step: 0.001,
    format: "percent",
    source: "assumption",
    description: "Scenario-only share of company revenue attributable to OpenAI-related Azure usage, revenue share, and services economics.",
    category: "OpenAI",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Microsoft has not disclosed OpenAI revenue contribution or revenue-share percentage.`,
  },
  {
    key: "openAiGrossMargin",
    label: "OpenAI GM",
    value: defaultMsftValuationAssumptions.openAiGrossMargin,
    min: 0.05,
    max: 0.65,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Scenario gross margin for OpenAI-related economics after compute, model, and revenue-share costs.",
    category: "OpenAI",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Official data only covers investment P&L impact and broad contract commentary.`,
  },
  {
    key: "aiCapexIntensity",
    label: "AI Capex Intensity",
    value: defaultMsftValuationAssumptions.aiCapexIntensity,
    min: 0.12,
    max: 0.36,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Near-term capex as a percentage of revenue while Microsoft remains AI capacity constrained.",
    category: "Capex & FCF",
    unit: "percent",
    periodicity: "annual",
    provenance: `${OFFICIAL_GUIDANCE} CY2026 capex roughly $190bn; intensity path is scenario-driven.`,
  },
  {
    key: "normalizedCapexIntensity",
    label: "Normalized Capex Intensity",
    value: defaultMsftValuationAssumptions.normalizedCapexIntensity,
    min: 0.08,
    max: 0.24,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Terminal-period capex intensity after the AI capacity catch-up phase.",
    category: "Capex & FCF",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Explicitly separates near-term AI build from long-run steady state.`,
  },
  {
    key: "operatingMargin",
    label: "Operating Margin",
    value: defaultMsftValuationAssumptions.operatingMargin,
    min: 0.34,
    max: 0.52,
    step: 0.005,
    format: "percent",
    source: "assumption",
    description: "Long-run operating margin after AI infrastructure drag, Copilot monetization, and cloud efficiency gains.",
    category: "Margin",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} FY2026 Q3 operating margin was 46.3%; long-run margin includes AI mix assumptions.`,
  },
  {
    key: "taxRate",
    label: "Tax Rate",
    value: defaultMsftValuationAssumptions.taxRate,
    min: 0.15,
    max: 0.24,
    step: 0.001,
    format: "percent",
    source: "assumption",
    description: "Effective tax rate used for NOPAT and EPS bridge.",
    category: "Cash Flow",
    unit: "percent",
    periodicity: "annual",
    provenance: "management_guidance: Q4 FY2026 adjusted effective tax rate approximately 19%.",
  },
  {
    key: "wacc",
    label: "WACC",
    value: defaultMsftValuationAssumptions.wacc,
    min: 0.065,
    max: 0.11,
    step: 0.001,
    format: "percent",
    source: "assumption",
    description: "Discount rate for unlevered FCFF DCF.",
    category: "DCF",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Not a live market debt/equity curve.`,
  },
  {
    key: "terminalGrowth",
    label: "Terminal Growth",
    value: defaultMsftValuationAssumptions.terminalGrowth,
    min: 0.015,
    max: 0.04,
    step: 0.0005,
    format: "percent",
    source: "assumption",
    description: "Long-run nominal terminal growth.",
    category: "DCF",
    unit: "percent",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Platform durability with mature growth constraints.`,
  },
  {
    key: "targetFcfYield",
    label: "Target FCF Yield",
    value: defaultMsftValuationAssumptions.targetFcfYield,
    min: 0.022,
    max: 0.05,
    step: 0.0005,
    format: "percent",
    source: "assumption",
    description: "Normalized FCF yield cross-check that dampens near-term AI capex distortion.",
    category: "Multiples",
    unit: "percent",
    periodicity: "forward annual",
    provenance: `${SCENARIO_NOTE} Cash-flow triangulation method.`,
  },
  {
    key: "targetPe",
    label: "Target P/E",
    value: defaultMsftValuationAssumptions.targetPe,
    min: 18,
    max: 45,
    step: 0.25,
    format: "multiple",
    source: "assumption",
    description: "Forward earnings multiple cross-check.",
    category: "Multiples",
    unit: "multiple",
    periodicity: "forward annual",
    provenance: `${SCENARIO_NOTE} Triangulation multiple, not the primary method.`,
  },
  {
    key: "targetEvEbit",
    label: "Target EV / EBIT",
    value: defaultMsftValuationAssumptions.targetEvEbit,
    min: 14,
    max: 36,
    step: 0.25,
    format: "multiple",
    source: "assumption",
    description: "Enterprise value to EBIT cross-check.",
    category: "Multiples",
    unit: "multiple",
    periodicity: "forward annual",
    provenance: `${SCENARIO_NOTE} Used with net cash/debt and diluted shares.`,
  },
  {
    key: "aiOptionalityValue",
    label: "AI Optionality Value",
    value: defaultMsftValuationAssumptions.aiOptionalityValue,
    min: 0,
    max: 600_000,
    step: 10_000,
    format: "number",
    source: "assumption",
    description: "Scenario value in USDm for OpenAI/IP/agent-platform optionality not captured in core DCF/SOTP.",
    category: "OpenAI",
    unit: "USD",
    periodicity: "annual",
    provenance: `${SCENARIO_NOTE} Kept as a capped explicit layer to avoid silently double counting.`,
  },
  {
    key: "netCashDebt",
    label: "Net Cash / Debt",
    value: defaultMsftValuationAssumptions.netCashDebt,
    min: -80_000,
    max: 120_000,
    step: 1_000,
    format: "number",
    source: "derived",
    description: "Cash and short-term investments less debt and operating lease liabilities.",
    category: "Balance Sheet",
    unit: "USD",
    periodicity: "quarterly",
    asOfDate: AS_OF_DATE,
    provenance: "derived: FY2026 Q3 balance sheet.",
  },
  {
    key: "dilutedShares",
    label: "Diluted Shares",
    value: defaultMsftValuationAssumptions.dilutedShares,
    min: 7_000,
    max: 7_800,
    step: 5,
    format: "number",
    source: "actual",
    description: "Q3 FY2026 diluted weighted-average shares in millions.",
    category: "Share Count",
    unit: "share",
    periodicity: "quarterly",
    asOfDate: AS_OF_DATE,
    provenance: "official_actual: FY2026 Q3 income statement.",
  },
  {
    key: "weightDcf",
    label: "DCF Weight",
    value: defaultMsftValuationAssumptions.weightDcf,
    min: 0.05,
    max: 0.55,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "DCF weight in blended fair value.",
    category: "Blend",
  },
  {
    key: "weightFcfYield",
    label: "FCF Yield Weight",
    value: defaultMsftValuationAssumptions.weightFcfYield,
    min: 0.05,
    max: 0.35,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "FCF yield cross-check weight.",
    category: "Blend",
  },
  {
    key: "weightPe",
    label: "P/E Weight",
    value: defaultMsftValuationAssumptions.weightPe,
    min: 0.05,
    max: 0.30,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "P/E cross-check weight.",
    category: "Blend",
  },
  {
    key: "weightEvEbit",
    label: "EV / EBIT Weight",
    value: defaultMsftValuationAssumptions.weightEvEbit,
    min: 0.05,
    max: 0.30,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "EV / EBIT cross-check weight.",
    category: "Blend",
  },
  {
    key: "weightSotp",
    label: "SOTP Weight",
    value: defaultMsftValuationAssumptions.weightSotp,
    min: 0.05,
    max: 0.40,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "SOTP weight for Productivity, Azure, consumer franchises, and AI optionality.",
    category: "Blend",
  },
  {
    key: "weightAiOptionality",
    label: "AI Optionality Weight",
    value: defaultMsftValuationAssumptions.weightAiOptionality,
    min: 0,
    max: 0.25,
    step: 0.01,
    format: "percent",
    source: "assumption",
    description: "Explicit probability-weighted OpenAI/IP/agent optionality layer.",
    category: "Blend",
  },
];

export const msftScenarioConfig = (["Bear", "Base", "Bull"] as Scenario[]).map((scenario) => ({
  name: scenario,
  assumptions: msftScenarioPresets[scenario],
}));
