import { createLocalDeepResearchDataset } from "../deepResearch/localDatasetFactory";

export const eqtDataset = createLocalDeepResearchDataset({
  ticker: "EQT",
  companyName: "EQT Corporation",
  sector: "Natural Gas / Appalachian E&P / LNG Supply Chain",
  archetype: "Natural gas producer / LNG-cycle and basis-spread leverage",
  description:
    "EQT research cockpit focused on Henry Hub and Appalachian basis, LNG export demand, inventory cycle, hedging, production discipline, gathering/transport costs, free cash flow, leverage, and whether gas scarcity supports a higher normalized value.",
  updatedAt: "2026-05-20",
  currentPrice: 59.77,
  priceDate: "2026-05-20",
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "gas-lng", label: "Gas / LNG Cycle" },
    { value: "basis-hedges", label: "Basis / Hedges" },
    { value: "fcf-leverage", label: "FCF / Leverage" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "gas-beta", label: "Gas Price Beta", value: 1.35, format: "multiple", description: "Sensitivity framework to normalized Henry Hub and basis.", badge: "Assumption" },
    { key: "lng-demand", label: "LNG Demand Pull", value: 0.72, format: "percent", description: "Research score for LNG export-cycle support.", badge: "Assumption" },
    { key: "hedge-protection", label: "Hedge Protection", value: 0.38, format: "percent", description: "Assumed downside hedge coverage; official hedge schedule pending.", badge: "Placeholder" },
    { key: "fcf-yield", label: "Normalized FCF Yield", value: 0.09, format: "percent", description: "Mid-cycle FCF framework, not current strip economics.", badge: "Assumption" },
    { key: "base-gap", label: "Base Upside / Downside", value: 0.04, format: "percent", description: "Local fallback valuation gap versus live proxy price.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "lng-cycle",
      question: "Does LNG demand create a structurally higher U.S. gas clearing price?",
      currentView: "The bull case depends on export demand tightening the market after storage and associated-gas cycles normalize.",
      metric: "LNG export capacity, storage, Henry Hub strip",
      evidenceNeeded: "LNG ramp schedule, storage surplus/deficit and production response",
      valuationTie: "Revenue CAGR, terminal growth and exit multiple",
      bearCase: "Supply growth and weather normalize prices before LNG demand tightens balances.",
    },
    {
      key: "basis",
      question: "Can EQT manage Appalachian basis and takeaway constraints?",
      currentView: "Basis risk can consume Henry Hub upside if transport and local constraints widen.",
      metric: "Appalachian basis, firm transport, realized price",
      evidenceNeeded: "Basis hedge schedule and transport cost disclosures",
      valuationTie: "Risk haircut and normalized FCF margin",
      bearCase: "Widening basis offsets gas-price recovery.",
    },
    {
      key: "hedges",
      question: "Are hedges protecting downside or capping the upside?",
      currentView: "Hedge book matters because EQT's equity value is extremely sensitive to the next gas-price regime.",
      metric: "Hedge price, hedge volumes, duration",
      evidenceNeeded: "Quarterly hedge table by commodity and year",
      valuationTie: "Bear/base/bull scenario spread",
      bearCase: "Hedges cap upside during a price spike or leave too much downside open.",
    },
    {
      key: "capital-discipline",
      question: "Will management convert gas upside into FCF and deleveraging rather than production growth?",
      currentView: "Capital discipline and leverage reduction decide whether gas beta benefits equity holders.",
      metric: "Capex, production growth, net debt, buybacks",
      evidenceNeeded: "Maintenance capex and production guide",
      valuationTie: "FCF margin and buyback yield",
      bearCase: "Growth capex absorbs cash just as gas prices improve.",
    },
  ],
  kpiSeries: [
    {
      key: "gas-lng",
      title: "Gas Price Regime vs LNG Pull",
      subtitle: "EQT's upside case needs LNG demand to tighten gas balances faster than supply responds.",
      sourceStatus: "research_only",
      measures: [
        { key: "gasPrice", label: "Gas price proxy ($/mmbtu)", format: "currency", chartType: "bar", color: "#0f172a", axis: "left" },
        { key: "lngPull", label: "LNG pull index", format: "number", chartType: "line", color: "#2563eb", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", gasPrice: 2.1, lngPull: 72 },
        { period: "2024 Q2", gasPrice: 2.3, lngPull: 74 },
        { period: "2024 Q3", gasPrice: 2.5, lngPull: 77 },
        { period: "2024 Q4", gasPrice: 2.8, lngPull: 80 },
        { period: "2025 Q1", gasPrice: 3.1, lngPull: 84 },
        { period: "2025 Q2", gasPrice: 3.4, lngPull: 88 },
        { period: "2025 Q3", gasPrice: 3.6, lngPull: 92 },
        { period: "2025 Q4", gasPrice: 3.9, lngPull: 96 },
        { period: "2026 Q1", gasPrice: 4.1, lngPull: 100 },
      ],
    },
    {
      key: "basis-hedges",
      title: "Basis Risk vs Hedge Protection",
      subtitle: "Realized prices depend on Appalachian basis and hedge execution, not Henry Hub alone.",
      sourceStatus: "research_only",
      measures: [
        { key: "basisRisk", label: "Basis risk index", format: "number", chartType: "bar", color: "#92400e", axis: "left" },
        { key: "hedgeCoverage", label: "Hedge coverage %", format: "percent", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "2024 Q1", basisRisk: 92, hedgeCoverage: 0.55 },
        { period: "2024 Q2", basisRisk: 88, hedgeCoverage: 0.52 },
        { period: "2024 Q3", basisRisk: 84, hedgeCoverage: 0.49 },
        { period: "2024 Q4", basisRisk: 80, hedgeCoverage: 0.46 },
        { period: "2025 Q1", basisRisk: 76, hedgeCoverage: 0.43 },
        { period: "2025 Q2", basisRisk: 74, hedgeCoverage: 0.4 },
        { period: "2025 Q3", basisRisk: 72, hedgeCoverage: 0.37 },
        { period: "2025 Q4", basisRisk: 70, hedgeCoverage: 0.34 },
        { period: "2026 Q1", basisRisk: 69, hedgeCoverage: 0.32 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "gas-lng",
      tab: "gas-lng",
      title: "Gas Macro and LNG Export Pull",
      thesis: "EQT is a levered call on a tighter U.S. gas balance; the key is timing LNG demand against supply response.",
      evidence: ["LNG export ramp", "Storage balance", "Associated gas production", "Henry Hub curve"],
      watchItems: ["Warm winter", "Permian associated gas", "LNG project delays"],
      sourceStatus: "research_only",
    },
    {
      key: "basis-hedges",
      tab: "basis-hedges",
      title: "Appalachian Basis and Hedge Book",
      thesis: "Realized value can diverge sharply from Henry Hub if basis widens or hedges cap upside.",
      evidence: ["Basis differential", "Firm transport", "Hedge price and volume"],
      watchItems: ["Pipeline constraints", "Basis blowouts", "Hedge mark-to-market"],
      sourceStatus: "research_only",
    },
    {
      key: "fcf-leverage",
      tab: "fcf-leverage",
      title: "FCF, Deleveraging and Capital Discipline",
      thesis: "The investable thesis improves when gas upside is used for debt reduction and per-share returns rather than volume growth.",
      evidence: ["Maintenance capex", "Production guide", "Net debt", "Buyback authorization"],
      watchItems: ["Growth capex creep", "Acquisition leverage", "Dividend/buyback discipline"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-23", headline: "LNG pull and gas beta", keyQuestions: ["Is gas-price upside flowing into FCF?", "What is hedge coverage?", "Any basis pressure?"], managementTone: "Constructive on macro.", modelReadThrough: "Maintain upside but keep basis/hedge haircut.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q4", eventDate: "2026-02-12", headline: "Capital discipline into better strip", keyQuestions: ["Is capex disciplined?", "Debt reduction?", "Production growth target?"], managementTone: "Capital-return focused.", modelReadThrough: "Higher FCF margin only with capex proof.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-23", headline: "Basis and hedge audit", keyQuestions: ["How wide is basis?", "Are hedges capping upside?", "Any transport updates?"], managementTone: "Operationally focused.", modelReadThrough: "Keep risk haircut.", riskSignal: "Needs Review", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-07-24", headline: "Storage normalization", keyQuestions: ["Storage surplus/deficit?", "Production response?", "LNG timing?"], managementTone: "Macro constructive.", modelReadThrough: "Raise revenue sensitivity modestly.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-04-24", headline: "Gas cycle turn", keyQuestions: ["Is supply discipline real?", "What is realized price?", "How much FCF at strip?"], managementTone: "Improving.", modelReadThrough: "Begin bull-case optionality.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-02-13", headline: "Low gas price stress", keyQuestions: ["Cash breakeven?", "Hedge protection?", "Debt plan?"], managementTone: "Disciplined.", modelReadThrough: "Bear case protects with hedges but valuation muted.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-24", headline: "Basis pressure", keyQuestions: ["Basis differential?", "Transport cost?", "Capex discipline?"], managementTone: "Cautious.", modelReadThrough: "Keep basis haircut high.", riskSignal: "Negative", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-07-25", headline: "Supply response watch", keyQuestions: ["Production growth?", "Storage?", "Hedge book?"], managementTone: "Measured.", modelReadThrough: "No re-rating until macro improves.", riskSignal: "Neutral", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { eventDate: "2024-07-25", fiscalPeriod: "FY2024 Q2", asOfPrice: 36, fairValue: 34, method: "Low gas-price and basis-risk local fallback." },
    { eventDate: "2024-10-24", fiscalPeriod: "FY2024 Q3", asOfPrice: 39, fairValue: 36, method: "Basis pressure and capex discipline." },
    { eventDate: "2025-02-13", fiscalPeriod: "FY2024 Q4", asOfPrice: 47, fairValue: 44, method: "Low gas stress with hedge protection." },
    { eventDate: "2025-04-24", fiscalPeriod: "FY2025 Q1", asOfPrice: 51, fairValue: 49, method: "Gas-cycle turn and FCF option." },
    { eventDate: "2025-07-24", fiscalPeriod: "FY2025 Q2", asOfPrice: 55, fairValue: 55, method: "Storage normalization and LNG timing." },
    { eventDate: "2025-10-23", fiscalPeriod: "FY2025 Q3", asOfPrice: 58, fairValue: 58, method: "Basis and hedge audit." },
    { eventDate: "2026-02-12", fiscalPeriod: "FY2025 Q4", asOfPrice: 62, fairValue: 61, method: "Capital discipline into better strip." },
    { eventDate: "2026-04-23", fiscalPeriod: "FY2026 Q1", asOfPrice: 60, fairValue: 62, method: "Base gas / LNG local run." },
  ],
  valuationBase: {
    revenueBase: 6800,
    revenueCagr3Y: 0.08,
    terminalGrowth: 0.015,
    normalizedFcfMargin: 0.2,
    exitFcfMultiple: 12,
    evRevenueMultiple: 5.5,
    discountRate: 0.105,
    netCashDebt: -5200,
    dilutedShares: 629,
    qualityAdjustment: 0.98,
    riskHaircut: 0.18,
    dividendYield: 0.01,
    buybackYield: 0.02,
  },
  scenarioOverrides: {
    Bear: { revenueCagr3Y: -0.04, normalizedFcfMargin: 0.08, exitFcfMultiple: 7, evRevenueMultiple: 3, riskHaircut: 0.34, qualityAdjustment: 0.85, buybackYield: 0 },
    Base: {},
    Bull: { revenueCagr3Y: 0.16, normalizedFcfMargin: 0.29, exitFcfMultiple: 15, evRevenueMultiple: 7, riskHaircut: 0.1, qualityAdjustment: 1.08, buybackYield: 0.04 },
  },
  valuationDescription: "Blends mid-cycle gas cash flow, FCF multiple and commodity-cycle revenue cross-check, with basis and hedge risk explicitly haircut.",
  risks: [
    { title: "Gas price downside", detail: "Warm weather, storage surplus or supply response can crush FCF.", severity: "high", killSignal: "Henry Hub strip falls while hedges roll off." },
    { title: "Appalachian basis", detail: "Local basis and takeaway constraints can offset benchmark price upside.", severity: "high", killSignal: "Realized price underperforms Henry Hub by widening differential." },
    { title: "Capital discipline", detail: "Growth capex or acquisitions can absorb commodity upside.", severity: "medium", killSignal: "Production growth rises without per-share FCF growth." },
  ],
  monitoring: ["Henry Hub strip", "Storage balance", "LNG export capacity", "Appalachian basis", "Hedge book", "Capex and net debt"],
  sourceGaps: ["Official hedge schedule, basis differential and daily price bars need backend import.", "Commodity strip assumptions should be tied to a market-data source before investment use."],
});
