import type { NvdaDataset } from "./model";

export const nvdaDataset: NvdaDataset = {
  marketData: {
    currentPrice: 225.8,
    priceDate: "2026-05-12",
    sharesOutstanding: 24_514,
    currency: "USD",
    source: "Static offline fallback only; backend daily_price_bars is the required source for historical valuation and backtest views.",
    sourceStatus: "research_only",
  },
  periods: [
    {
      id: "fy26-q4",
      label: "FY2026 Q4",
      fiscalYear: 2026,
      fiscalQuarter: "Q4",
      periodType: "quarter",
      sourceStatus: "research_only",
      revenue: 68_127,
      grossProfit: 51_093,
      grossMargin: 0.75,
      operatingIncome: 44_299,
      operatingMargin: 0.65,
      netIncome: 38_461,
      dilutedShares: 24_514,
      operatingCashFlow: 39_800,
      capex: 1_000,
      freeCashFlow: 38_800,
      inventory: 15_000,
      accountsReceivable: 35_000,
      deferredRevenue: 3_000,
      cashAndMarketableSecurities: 60_000,
      debt: 8_000,
    },
  ],
  segments: [
    { periodId: "fy26-q4", segment: "Data Center", sourceStatus: "research_only", revenue: 58_500, growth: 0.55, grossMargin: 0.75 },
    { periodId: "fy26-q4", segment: "Gaming", sourceStatus: "research_only", revenue: 5_450, growth: 0.08, grossMargin: 0.75 },
    { periodId: "fy26-q4", segment: "Professional Visualization", sourceStatus: "research_only", revenue: 1_360, growth: 0.04, grossMargin: 0.75 },
    { periodId: "fy26-q4", segment: "Automotive", sourceStatus: "research_only", revenue: 1_360, growth: 0.12, grossMargin: 0.75 },
    { periodId: "fy26-q4", segment: "OEM / Other", sourceStatus: "research_only", revenue: 1_360, growth: 0.02, grossMargin: 0.75 },
  ],
  operatingMetrics: [
    {
      periodId: "fy26-q4",
      sourceStatus: "research_only",
      dataCenterRevenue: 58_500,
      gamingRevenue: 5_450,
      networkingRevenue: 13_500,
      computeRevenue: 45_000,
      dataCenterGrowth: 0.55,
      gamingGrowth: 0.08,
      grossMargin: 0.75,
      operatingMargin: 0.65,
      inventory: 15_000,
      fcfConversion: 1.0,
      productCyclePhase: "Blackwell ramp with Rubin roadmap awareness",
      acceleratorMoatScore: 8.5,
      chinaRiskScore: 6.5,
      supplyConstraintScore: 7.5,
    },
  ],
  sourceNotes: [
    "This is an offline fallback only. Backend historical valuations, financial history, segment history, and backtests must load from the NVDA SQLite backend.",
    "Segment/product rows are research-only unless official platform disclosures are imported into the backend.",
  ],
  selectedPeriodId: "fy26-q4",
};
