import type { Scenario, ValuationAssumption } from "../types";
import type { IsrgScenarioDefinition, IsrgValuationAssumptions } from "./model";

const AS_OF = "2026-05-11";
const ASSUMPTION_PROVENANCE = "manual assumption: buy-side underwriting input; see models_description/ISRG_explained.txt";
const MARKET_PROVENANCE = "market snapshot: unofficial market data used only for current price and reverse valuation.";
const OFFICIAL_GUIDANCE_PROVENANCE = "company disclosure: Q1 2026 FY procedure and margin guidance.";

export const defaultIsrgValuationAssumptions: IsrgValuationAssumptions = {
  currentPrice: 418.885009765625,
  baseDaVinciInstalledBase: 11395,
  installedBaseCagr: 0.085,
  procedureCagr: 0.125,
  utilizationGrowth: 0.018,
  revenuePerProcedureGrowth: 0.025,
  systemPlacementCagr: 0.055,
  systemAspGrowth: 0.015,
  serviceRevenuePerSystemGrowth: 0.025,
  daVinci5ReplacementCycleUplift: 0.035,
  operatingMargin: 0.31,
  fcfMargin: 0.27,
  taxRate: 0.21,
  wacc: 0.085,
  terminalGrowth: 0.035,
  targetPe: 38,
  targetFcfYield: 0.027,
  recurringRevenueMultiple: 14,
  systemsRevenueMultiple: 6.5,
  servicesRevenueMultiple: 9,
  ionProbability: 0.35,
  ionRevenueRamp: 850,
  spProbability: 0.18,
  spRevenueRamp: 350,
  optionalityDeduplicationHaircut: 0.65,
  competitionAspPressure: 0.005,
  tariffGrossMarginDrag: 0.01,
  marginCompression: 0.005,
  netCash: 7979.2,
  dilutedShares: 359.8,
  weightProcedureDcf: 0.45,
  weightSegment: 0.3,
  weightPe: 0.15,
  weightFcfYield: 0.1,
};

function assumption(
  key: keyof IsrgValuationAssumptions,
  label: string,
  value: number,
  min: number,
  max: number,
  step: number,
  format: ValuationAssumption["format"],
  category: string,
  description: string,
  provenance = ASSUMPTION_PROVENANCE,
): ValuationAssumption {
  return {
    key,
    label,
    value,
    min,
    max,
    step,
    format,
    source: key === "currentPrice" ? "placeholder" : "assumption",
    description,
    category,
    asOfDate: AS_OF,
    provenance,
  };
}

export const isrgAssumptionDefinitions: ValuationAssumption[] = [
  assumption("currentPrice", "Current Price", 418.885009765625, 200, 800, 1, "currency", "Market", "Current share price used for upside/downside and reverse valuation.", MARKET_PROVENANCE),
  assumption("baseDaVinciInstalledBase", "Base da Vinci Installed Base", 11395, 8000, 16000, 25, "number", "Installed Base", "Starting da Vinci installed base from Q1 2026 official disclosure.", OFFICIAL_GUIDANCE_PROVENANCE),
  assumption("installedBaseCagr", "Installed Base CAGR", 0.085, 0.02, 0.14, 0.0025, "percent", "Installed Base", "Long-run da Vinci installed-base growth assumption."),
  assumption("procedureCagr", "Procedure CAGR", 0.125, 0.06, 0.19, 0.0025, "percent", "Procedure", "Core da Vinci procedure growth assumption. This is the central debate variable."),
  assumption("utilizationGrowth", "Utilization Growth", 0.018, -0.02, 0.06, 0.001, "percent", "Procedure", "Annual growth in procedures per installed system."),
  assumption("revenuePerProcedureGrowth", "Revenue / Procedure Growth", 0.025, -0.01, 0.06, 0.001, "percent", "Recurring Revenue", "Pricing/mix assumption for instruments and accessories revenue per procedure."),
  assumption("systemPlacementCagr", "System Placement CAGR", 0.055, -0.03, 0.12, 0.0025, "percent", "Systems", "Growth in da Vinci placements including replacement and upgrade demand."),
  assumption("systemAspGrowth", "System ASP Growth", 0.015, -0.04, 0.05, 0.001, "percent", "Systems", "Recognized system ASP growth; lease mix and usage-based leases can pressure reported system revenue timing."),
  assumption("serviceRevenuePerSystemGrowth", "Service / System Growth", 0.025, 0, 0.06, 0.001, "percent", "Services", "Service revenue per installed da Vinci system growth."),
  assumption("daVinci5ReplacementCycleUplift", "da Vinci 5 Replacement Uplift", 0.035, 0, 0.12, 0.0025, "percent", "Product Cycle", "Incremental support to placements from the da Vinci 5 upgrade cycle."),
  assumption("operatingMargin", "Operating Margin", 0.31, 0.22, 0.4, 0.0025, "percent", "Margin", "Normalized operating margin used for EPS and margin bridge."),
  assumption("fcfMargin", "FCF Margin", 0.27, 0.18, 0.36, 0.0025, "percent", "Cash Flow", "Free cash flow margin used in procedure-based DCF."),
  assumption("taxRate", "Tax Rate", 0.21, 0.15, 0.28, 0.0025, "percent", "Cash Flow", "Cash tax assumption."),
  assumption("wacc", "WACC", 0.085, 0.065, 0.11, 0.001, "percent", "DCF", "Discount rate for unlevered cash flows."),
  assumption("terminalGrowth", "Terminal Growth", 0.035, 0.015, 0.05, 0.001, "percent", "DCF", "Long-run terminal growth. Keep below WACC."),
  assumption("targetPe", "Target P/E", 38, 20, 55, 0.5, "multiple", "Multiple", "Forward P/E sanity check only."),
  assumption("targetFcfYield", "Target FCF Yield", 0.027, 0.018, 0.05, 0.0005, "percent", "Multiple", "FCF yield sanity check only."),
  assumption("recurringRevenueMultiple", "I&A Revenue Multiple", 14, 7, 22, 0.25, "multiple", "Segment Valuation", "Revenue multiple for instruments and accessories recurring-like revenue."),
  assumption("systemsRevenueMultiple", "Systems Revenue Multiple", 6.5, 3, 12, 0.25, "multiple", "Segment Valuation", "Revenue multiple for systems revenue, discounted for cyclicality and lease timing."),
  assumption("servicesRevenueMultiple", "Services Revenue Multiple", 9, 5, 15, 0.25, "multiple", "Segment Valuation", "Revenue multiple for service revenue attached to installed base."),
  assumption("ionProbability", "Ion Probability", 0.35, 0, 0.75, 0.01, "percent", "Optionality", "Probability that Ion becomes a meaningful second platform."),
  assumption("ionRevenueRamp", "Ion Revenue Ramp", 850, 0, 2500, 25, "number", "Optionality", "Ten-year Ion incremental revenue ramp in USD millions before probability weighting."),
  assumption("spProbability", "SP Probability", 0.18, 0, 0.6, 0.01, "percent", "Optionality", "Probability that SP creates meaningful incremental TAM rather than narrow strategic optionality."),
  assumption("spRevenueRamp", "SP Revenue Ramp", 350, 0, 1500, 25, "number", "Optionality", "Ten-year SP incremental revenue ramp in USD millions before probability weighting."),
  assumption("optionalityDeduplicationHaircut", "Optionality De-Dup Haircut", 0.65, 0.25, 1, 0.01, "percent", "Optionality", "Haircut to prevent Ion/SP optionality from being double counted in the core revenue DCF."),
  assumption("competitionAspPressure", "Competition ASP Pressure", 0.005, 0, 0.05, 0.001, "percent", "Risk", "Annual ASP pressure from J&J, Medtronic, CMR, China local players, and tenders."),
  assumption("tariffGrossMarginDrag", "Tariff Gross Margin Drag", 0.01, 0, 0.04, 0.001, "percent", "Risk", "Explicit tariff gross margin drag anchor from FY 2026 guidance."),
  assumption("marginCompression", "Margin Compression", 0.005, 0, 0.06, 0.001, "percent", "Risk", "Long-run margin pressure from competition, tariffs, manufacturing, and mix."),
  assumption("netCash", "Net Cash", 7979.2, 0, 15000, 25, "number", "Balance Sheet", "Cash, equivalents, and investments less debt. ISRG has no debt in the starter model."),
  assumption("dilutedShares", "Diluted Shares", 359.8, 320, 390, 0.5, "number", "Per Share", "Diluted share count in millions."),
  assumption("weightProcedureDcf", "Procedure DCF Weight", 0.45, 0, 1, 0.01, "percent", "Blend", "Blend weight for procedure-based DCF."),
  assumption("weightSegment", "Segment Value Weight", 0.3, 0, 1, 0.01, "percent", "Blend", "Blend weight for segment-based valuation."),
  assumption("weightPe", "P/E Weight", 0.15, 0, 1, 0.01, "percent", "Blend", "Blend weight for P/E sanity check."),
  assumption("weightFcfYield", "FCF Yield Weight", 0.1, 0, 1, 0.01, "percent", "Blend", "Blend weight for FCF yield sanity check."),
];

export const isrgScenarioDefinitions: IsrgScenarioDefinition[] = [
  {
    name: "Bear",
    summary:
      "Procedure growth fades to low-teens, da Vinci 5 is mostly replacement, hospital capex and usage-based leasing slow reported systems revenue, competition/tenders pressure ASP, and tariffs compress gross margin.",
    assumptions: {
      installedBaseCagr: 0.06,
      procedureCagr: 0.085,
      utilizationGrowth: 0.004,
      revenuePerProcedureGrowth: 0.01,
      systemPlacementCagr: 0.015,
      systemAspGrowth: -0.015,
      serviceRevenuePerSystemGrowth: 0.015,
      daVinci5ReplacementCycleUplift: 0.01,
      operatingMargin: 0.27,
      fcfMargin: 0.225,
      terminalGrowth: 0.025,
      targetPe: 28,
      targetFcfYield: 0.038,
      recurringRevenueMultiple: 10,
      systemsRevenueMultiple: 4.5,
      servicesRevenueMultiple: 7,
      ionProbability: 0.15,
      spProbability: 0.08,
      competitionAspPressure: 0.02,
      tariffGrossMarginDrag: 0.02,
      marginCompression: 0.025,
    },
  },
  {
    name: "Base",
    summary:
      "Procedure growth moderates but remains durable, da Vinci 5 supports placements and upgrades, recurring revenue remains high quality, and margins normalize after tariff/supply-chain drag.",
    assumptions: {},
  },
  {
    name: "Bull",
    summary:
      "da Vinci 5 adoption is stronger, procedure growth stays mid-teens, OUS penetration outgrows the U.S., Ion becomes a meaningful second platform, and margin pressure is temporary.",
    assumptions: {
      installedBaseCagr: 0.105,
      procedureCagr: 0.155,
      utilizationGrowth: 0.03,
      revenuePerProcedureGrowth: 0.035,
      systemPlacementCagr: 0.085,
      systemAspGrowth: 0.025,
      serviceRevenuePerSystemGrowth: 0.035,
      daVinci5ReplacementCycleUplift: 0.075,
      operatingMargin: 0.35,
      fcfMargin: 0.315,
      terminalGrowth: 0.04,
      targetPe: 45,
      targetFcfYield: 0.022,
      recurringRevenueMultiple: 17,
      systemsRevenueMultiple: 8,
      servicesRevenueMultiple: 11,
      ionProbability: 0.55,
      ionRevenueRamp: 1400,
      spProbability: 0.28,
      spRevenueRamp: 650,
      competitionAspPressure: 0.002,
      tariffGrossMarginDrag: 0.004,
      marginCompression: 0.002,
    },
  },
];

export const isrgScenarioPresets: Record<Scenario, IsrgValuationAssumptions> = Object.fromEntries(
  isrgScenarioDefinitions.map((definition) => [
    definition.name,
    {
      ...defaultIsrgValuationAssumptions,
      ...definition.assumptions,
    },
  ]),
) as Record<Scenario, IsrgValuationAssumptions>;
