import type { StockValuationConfig } from "../types";
import type { AnetScenarioPresetMap, ValuationAssumptions } from "./model";

export const defaultAnetValuationAssumptions: ValuationAssumptions = {
  currentPrice: 141,
  dilutedShares: 1_255,
  revenueGrowth: 0.16,
  subscriptionGrowth: 0.17,
  currentRpoGrowth: 0.15,
  agenticAiGrowth: 0.45,
  proPlusAdoptionRate: 0.55,
  netRetentionRate: 1.10,
  operatingMargin: 0.38,
  normalizedFcfMargin: 0.34,
  targetFcfYield: 0.028,
  targetPe: 34,
  targetEvRevenue: 10,
  discountRate: 0.09,
  terminalGrowth: 0.035,
  aiExecutionHaircut: 0.04,
  platformCompetitionHaircut: 0.03,
  sbcDilutionHaircut: 0.02,
  buybackYield: 0.008,
  dividendYield: 0,
};

export const anetScenarioPresets: AnetScenarioPresetMap = {
  Bear: {
    ...defaultAnetValuationAssumptions,
    revenueGrowth: 0.08,
    subscriptionGrowth: 0.09,
    currentRpoGrowth: 0.05,
    agenticAiGrowth: 0.35,
    proPlusAdoptionRate: 0.45,
    netRetentionRate: 1.05,
    operatingMargin: 0.33,
    normalizedFcfMargin: 0.29,
    targetFcfYield: 0.035,
    targetPe: 32,
    targetEvRevenue: 8,
    discountRate: 0.095,
    aiExecutionHaircut: 0.10,
    platformCompetitionHaircut: 0.08,
    sbcDilutionHaircut: 0.04,
    buybackYield: 0.004,
  },
  Base: defaultAnetValuationAssumptions,
  Bull: {
    ...defaultAnetValuationAssumptions,
    revenueGrowth: 0.22,
    subscriptionGrowth: 0.23,
    currentRpoGrowth: 0.22,
    agenticAiGrowth: 0.75,
    proPlusAdoptionRate: 0.62,
    netRetentionRate: 1.12,
    operatingMargin: 0.41,
    normalizedFcfMargin: 0.36,
    targetFcfYield: 0.023,
    targetPe: 44,
    targetEvRevenue: 14,
    discountRate: 0.08,
    aiExecutionHaircut: 0.02,
    platformCompetitionHaircut: 0.015,
    sbcDilutionHaircut: 0.015,
    buybackYield: 0.012,
  },
};

export function buildAnetValuationConfig(
  calculateValuation: StockValuationConfig["calculateValuation"],
): StockValuationConfig {
  return {
    ticker: "ANET",
    modelType: "saas-agentic-ai-dcf-fcf-ev-revenue-triangulation",
    assumptions: [
      { key: "revenueGrowth", label: "Revenue Growth", value: defaultAnetValuationAssumptions.revenueGrowth, min: 0.04, max: 0.30, step: 0.005, format: "percent", source: "assumption", description: "Core growth after cloud titan demand, 400G/800G ramps and campus cyclicality.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "subscriptionGrowth", label: "Cloud Titan Growth", value: defaultAnetValuationAssumptions.subscriptionGrowth, min: 0.04, max: 0.32, step: 0.005, format: "percent", source: "assumption", description: "Cloud titan revenue growth durability.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "currentRpoGrowth", label: "Backlog Growth", value: defaultAnetValuationAssumptions.currentRpoGrowth, min: -0.05, max: 0.32, step: 0.005, format: "percent", source: "assumption", description: "Forward demand proxy from backlog and supply normalization.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "agenticAiGrowth", label: "AI Ethernet Growth", value: defaultAnetValuationAssumptions.agenticAiGrowth, min: 0, max: 1.2, step: 0.025, format: "percent", source: "assumption", description: "AI networking revenue growth proxy from 400G/800G fabrics.", category: "AI", unit: "percent", periodicity: "forward annual" },
      { key: "proPlusAdoptionRate", label: "Cloud Mix", value: defaultAnetValuationAssumptions.proPlusAdoptionRate, min: 0, max: 0.75, step: 0.01, format: "percent", source: "assumption", description: "Cloud titan revenue mix and concentration proxy.", category: "AI", unit: "percent" },
      { key: "operatingMargin", label: "Operating Margin", value: defaultAnetValuationAssumptions.operatingMargin, min: 0.25, max: 0.45, step: 0.005, format: "percent", source: "assumption", description: "Normalized operating margin after cloud pricing, supply-chain and opex leverage checks.", category: "Margins", unit: "percent", periodicity: "forward annual" },
      { key: "normalizedFcfMargin", label: "FCF Margin", value: defaultAnetValuationAssumptions.normalizedFcfMargin, min: 0.22, max: 0.42, step: 0.005, format: "percent", source: "assumption", description: "Normalized FCF conversion after capex and working-capital benefits.", category: "Cash Flow", unit: "percent", periodicity: "forward annual" },
      { key: "targetFcfYield", label: "Target FCF Yield", value: defaultAnetValuationAssumptions.targetFcfYield, min: 0.018, max: 0.045, step: 0.001, format: "percent", source: "assumption", description: "FCF yield used in valuation triangulation.", category: "Valuation", unit: "percent" },
      { key: "targetEvRevenue", label: "Target EV/Revenue", value: defaultAnetValuationAssumptions.targetEvRevenue, min: 4, max: 16, step: 0.25, format: "multiple", source: "assumption", description: "AI networking revenue multiple tied to growth, margins and customer concentration.", category: "Valuation", unit: "multiple" },
      { key: "aiExecutionHaircut", label: "AI Ethernet Haircut", value: defaultAnetValuationAssumptions.aiExecutionHaircut, min: 0, max: 0.15, step: 0.005, format: "percent", source: "assumption", description: "Risk haircut for AI Ethernet demand conversion, Nvidia Spectrum-X competition and customer qualification timing.", category: "Risk", unit: "percent" },
      { key: "platformCompetitionHaircut", label: "Competition Risk", value: defaultAnetValuationAssumptions.platformCompetitionHaircut, min: 0, max: 0.12, step: 0.005, format: "percent", source: "assumption", description: "Competition from Cisco, Nvidia, Broadcom merchant silicon, white-box and hyperscaler in-house designs.", category: "Risk", unit: "percent" },
      { key: "sbcDilutionHaircut", label: "SBC Dilution", value: defaultAnetValuationAssumptions.sbcDilutionHaircut, min: 0, max: 0.08, step: 0.005, format: "percent", source: "assumption", description: "SBC and dilution quality haircut.", category: "Risk", unit: "percent" },
      { key: "buybackYield", label: "Buyback Yield", value: defaultAnetValuationAssumptions.buybackYield, min: 0, max: 0.025, step: 0.001, format: "percent", source: "assumption", description: "Gross buyback offset to SBC dilution.", category: "Capital Return", unit: "percent" },
    ],
    scenarios: [
      { name: "Bear", assumptions: anetScenarioPresets.Bear },
      { name: "Base", assumptions: anetScenarioPresets.Base },
      { name: "Bull", assumptions: anetScenarioPresets.Bull },
    ],
    calculateValuation,
  };
}
