import type { DefenseDataset, DefenseSource } from "../defensePrime/model";

const sources: DefenseSource[] = [
  {
    id: "rtx-fy2025-results",
    title: "RTX Reports 2025 Results and Announces 2026 Outlook",
    url: "https://www.rtx.com/news/news-center/2026/01/27/rtx-reports-2025-results-and-announces-2026-outlook",
    sourceStatus: "official_actual",
    publisher: "RTX",
    publishedDate: "2026-01-27",
    accessedDate: "2026-05-12",
    notes: "Primary official FY2025 actuals, backlog, segment results, cash flow, and initial 2026 outlook.",
  },
  {
    id: "rtx-q1-2026-results",
    title: "RTX Reports Q1 2026 Results",
    url: "https://www.rtx.com/news/news-center/2026/04/21/rtx-reports-q1-2026-results-",
    sourceStatus: "official_actual",
    publisher: "RTX",
    publishedDate: "2026-04-21",
    accessedDate: "2026-05-12",
    notes: "Official Q1 2026 sales, EPS, FCF, backlog, segment detail, and updated 2026 outlook.",
  },
  {
    id: "rtx-2026-guidance",
    title: "RTX 2026 management guidance",
    url: "https://www.rtx.com/news/news-center/2026/04/21/rtx-reports-q1-2026-results-",
    sourceStatus: "management_guidance",
    publisher: "RTX",
    publishedDate: "2026-04-21",
    accessedDate: "2026-05-12",
    notes: "Management outlook fields for 2026 adjusted sales, adjusted EPS, and free cash flow.",
  },
  {
    id: "rtx-ir-quarterly-archive",
    title: "RTX investor relations quarterly results archive",
    url: "https://investors.rtx.com/financial-information/quarterly-results",
    sourceStatus: "official_actual",
    publisher: "RTX Investor Relations",
    accessedDate: "2026-05-12",
    notes: "Archive reference for historical reporting events. Older event summaries are research-only until the fetch script stores each source document.",
  },
  {
    id: "rtx-programs",
    title: "RTX businesses and defense technology pages",
    url: "https://www.rtx.com/who-we-are/our-businesses",
    sourceStatus: "research_only",
    publisher: "RTX",
    accessedDate: "2026-05-12",
    notes: "Qualitative source for program exposure tags. It is not used directly in valuation.",
  },
  {
    id: "rtx-market-snapshot",
    title: "External market-data snapshot for RTX",
    url: "https://www.marketwatch.com/investing/stock/rtx",
    sourceStatus: "market_data",
    publisher: "Market data provider",
    accessedDate: "2026-05-12",
    notes: "External market price, share-count, and market-cap snapshot. Not official company data.",
  },
  {
    id: "rtx-forecast-assumptions",
    title: "RTX local model forecast assumptions",
    url: "models_description/RTX_explained.txt",
    sourceStatus: "forecast_assumption",
    publisher: "Local model documentation",
    accessedDate: "2026-05-12",
    notes: "Scenario, WACC, terminal growth, target yield, multiple, and valuation-weight assumptions.",
  },
];

const sourceMap = Object.fromEntries(sources.map((source) => [source.id, source])) as Record<string, DefenseSource>;

export const rtxData: DefenseDataset = {
  ticker: "RTX",
  name: "RTX Corporation",
  company: "RTX Corporation",
  currency: "USD",
  sector: "Aerospace & Defense",
  description: "Defense and commercial aerospace prime with Collins Aerospace, Pratt & Whitney, and Raytheon.",
  latestReportingPeriod: "Q1 2026",
  investmentThesis:
    "RTX is a dual-cycle aerospace and defense compounder: commercial aftermarket and OE recovery fund cash generation, while Raytheon, F135, Patriot, GEM-T, naval munitions, and electronic defense demand support a durable defense backlog.",
  keyDebate:
    "The main underwriting debate is whether double-digit organic growth and defense backlog conversion can outrun GTF fleet-management costs, tariffs, supply-chain pressure, and the capital intensity of ramping output.",
  marketMayMiss:
    "The defense thesis is not only missile demand. The mix shift across Collins defense electronics, Pratt military engines, and Raytheon air and naval defense changes margin durability and working-capital timing.",
  reportingTrendSummary:
    "Across the last eight reporting events, market attention has shifted from GTF remediation and commercial-aerospace recovery toward defense backlog conversion, missile-defense volume, tariffs, and whether 2026 FCF can scale despite elevated output investments. The Q1 2026 event is the first clear period where management explicitly raised adjusted sales and EPS while confirming FCF, which moves the debate from demand proof to execution quality.",
  dataGaps: [
    "Segment-level backlog is not fully disclosed by Collins, Pratt & Whitney, and Raytheon in the official releases used here.",
    "Older quarterly transcript text has not yet been cached locally; the eight-event trend is research-only synthesis until each transcript is fetched.",
    "Market price and market capitalization are external market-data inputs, not official RTX actuals.",
    "Order intake for FY2025 is not directly disclosed in the source release; Q1 book-to-bill uses a derived awards proxy from backlog movement.",
  ],
  sources,
  sourceMap,
  periods: [
    {
      id: "FY2025",
      label: "FY2025A",
      fiscalYear: 2025,
      periodType: "FY",
      sourceStatus: "official_actual",
      sourceId: "rtx-fy2025-results",
      sales: 88603,
      adjustedOperatingProfit: 10849,
      adjustedEps: 6.29,
      gaapEps: 4.42,
      freeCashFlow: 7940,
      operatingCashFlow: 10567,
      capex: 2627,
      backlog: 268000,
      backlogCommercial: 161000,
      backlogDefense: 107000,
      netIncome: 5963,
      dilutedShares: 1349.8,
      dividendPerShare: 2.72,
      notes: "FY2025 official release. Order intake is left blank because the release discloses backlog but not total awards/order intake in the same field set.",
    },
    {
      id: "Q1-2026",
      label: "Q1 2026A",
      fiscalYear: 2026,
      periodType: "Q",
      sourceStatus: "official_actual",
      sourceId: "rtx-q1-2026-results",
      sales: 22076,
      operatingProfit: 2555,
      adjustedOperatingProfit: 3023,
      adjustedEps: 1.78,
      gaapEps: 1.51,
      freeCashFlow: 1309,
      operatingCashFlow: 1855,
      capex: 546,
      backlog: 271000,
      orderIntake: 25076,
      orderIntakeSourceStatus: "derived",
      backlogCommercial: 162000,
      backlogDefense: 109000,
      netIncome: 2059,
      dilutedShares: 1364.6,
      dividendPerShare: 0.68,
      notes: "Q1 2026 official release. Derived order-intake proxy equals quarterly sales plus backlog increase from FY2025 ending backlog.",
    },
  ],
  segments: [
    {
      id: "collins",
      name: "Collins Aerospace",
      sourceStatus: "official_actual",
      sourceId: "rtx-fy2025-results",
      sales: 30196,
      operatingProfit: 4893,
      margin: 0.162,
      strategicRole: "Avionics, mission systems, interiors, and defense electronics with commercial aftermarket and defense electronics mix.",
      keyPrograms: ["Commercial avionics", "Mission systems", "Connected battlespace", "Space sensors"],
      risks: ["Commercial OE mix", "Tariffs", "Defense electronics supply chain"],
    },
    {
      id: "pratt",
      name: "Pratt & Whitney",
      sourceStatus: "official_actual",
      sourceId: "rtx-fy2025-results",
      sales: 32916,
      operatingProfit: 2725,
      margin: 0.083,
      strategicRole: "Commercial engines, aftermarket, and military propulsion anchored by GTF and F135.",
      keyPrograms: ["GTF", "F135", "Military engines", "Aftermarket fleet management"],
      risks: ["Powder-metal remediation", "Engine removals", "Commercial OE delivery timing"],
    },
    {
      id: "raytheon",
      name: "Raytheon",
      sourceStatus: "official_actual",
      sourceId: "rtx-fy2025-results",
      sales: 28043,
      operatingProfit: 3231,
      margin: 0.115,
      strategicRole: "Missile defense, sensors, naval munitions, radars, command systems, and precision weapons.",
      keyPrograms: ["Patriot", "GEM-T", "LTAMDS", "AMRAAM", "NASAMS", "Naval munitions"],
      risks: ["Fixed-price defense execution", "Export approvals", "Munitions supply-chain capacity"],
    },
  ],
  guidance: {
    year: 2026,
    sourceStatus: "management_guidance",
    sourceId: "rtx-2026-guidance",
    salesLow: 92500,
    salesHigh: 93500,
    epsLow: 6.7,
    epsHigh: 6.9,
    fcfLow: 8250,
    fcfHigh: 8750,
    notes: "Q1 2026 release raised adjusted sales and adjusted EPS while confirming free cash flow guidance.",
  },
  marketData: {
    sourceStatus: "market_data",
    sourceId: "rtx-market-snapshot",
    price: 178.61,
    priceDate: "2026-05-11",
    shares: 1348.0,
    marketCap: 240766,
    enterpriseValue: 271361,
    dividendYield: 0.0152,
    notes: "External market snapshot around the May 2026 trading date; official actuals are not sourced from this feed.",
  },
  programs: [
    {
      name: "F135 propulsion and modernization",
      segment: "Pratt & Whitney",
      customer: "U.S. and allied F-35 operators",
      stage: "ramping",
      geography: "U.S. / allies",
      maturityScore: 78,
      marginQualityScore: 70,
      growthScore: 82,
      riskScore: 58,
      sourceStatus: "research_only",
      sourceId: "rtx-programs",
      strategicRelevance: "Military-engine installed base and modernization support a long-duration defense propulsion lane, but execution and fleet-management costs remain critical.",
      valuationMapping: "scenario_context_only",
    },
    {
      name: "Patriot, GEM-T, and integrated air defense",
      segment: "Raytheon",
      customer: "U.S., NATO, and partner governments",
      stage: "ramping",
      geography: "U.S. / Europe / Middle East / Asia-Pacific",
      maturityScore: 85,
      marginQualityScore: 76,
      growthScore: 88,
      riskScore: 45,
      sourceStatus: "research_only",
      sourceId: "rtx-programs",
      strategicRelevance: "Air-defense replenishment and missile-defense demand are central to Raytheon's revenue visibility and defense backlog conversion.",
      valuationMapping: "scenario_context_only",
    },
    {
      name: "LTAMDS and advanced sensors",
      segment: "Raytheon",
      customer: "U.S. Army and allied defense customers",
      stage: "ramping",
      geography: "U.S. / allies",
      maturityScore: 62,
      marginQualityScore: 72,
      growthScore: 80,
      riskScore: 54,
      sourceStatus: "research_only",
      sourceId: "rtx-programs",
      strategicRelevance: "Sensor modernization raises content per defense system and supports a higher-electronics mix.",
      valuationMapping: "scenario_context_only",
    },
    {
      name: "Commercial aftermarket and GTF fleet support",
      segment: "Pratt & Whitney",
      customer: "Airlines and lessors",
      stage: "mature",
      geography: "Global",
      maturityScore: 86,
      marginQualityScore: 68,
      growthScore: 72,
      riskScore: 72,
      sourceStatus: "research_only",
      sourceId: "rtx-programs",
      strategicRelevance: "Aftermarket demand supports cash durability, but GTF remediation and shop-visit timing are the largest thesis risks.",
      valuationMapping: "risk_discount_only",
    },
    {
      name: "Collins mission systems and defense electronics",
      segment: "Collins Aerospace",
      customer: "Defense primes and government customers",
      stage: "mature",
      geography: "U.S. / allied markets",
      maturityScore: 74,
      marginQualityScore: 80,
      growthScore: 70,
      riskScore: 44,
      sourceStatus: "research_only",
      sourceId: "rtx-programs",
      strategicRelevance: "Defense electronics exposure gives Collins a bridge between aerospace systems and multi-domain defense demand.",
      valuationMapping: "scenario_context_only",
    },
  ],
  risks: [
    { id: "gtf", name: "GTF fleet-management and powder-metal execution", probability: 0.55, impact: 0.78, affectedDriver: "FCF, margin, working capital", mitigation: "Track removals, compensation costs, aftermarket cadence, and Pratt margin progression.", sourceStatus: "research_only" },
    { id: "tariffs", name: "Tariffs and supply-chain cost inflation", probability: 0.45, impact: 0.55, affectedDriver: "Operating margin", mitigation: "Monitor segment commentary on tariff absorption and supplier recovery.", sourceStatus: "research_only" },
    { id: "defense-timing", name: "Defense procurement timing and export approvals", probability: 0.35, impact: 0.58, affectedDriver: "Revenue CAGR and backlog conversion", mitigation: "Track Raytheon awards, book-to-bill, and U.S./allied funding decisions.", sourceStatus: "research_only" },
    { id: "commercial-cycle", name: "Commercial aerospace cycle and OE delivery risk", probability: 0.35, impact: 0.52, affectedDriver: "Collins and Pratt sales growth", mitigation: "Watch airline capacity, OEM production schedules, and aftermarket mix.", sourceStatus: "research_only" },
    { id: "fixed-price", name: "Fixed-price defense contract margin pressure", probability: 0.3, impact: 0.5, affectedDriver: "Raytheon margin and EV/EBIT multiple", mitigation: "Monitor contract mix, unfavorable profit adjustments, and program disclosures.", sourceStatus: "research_only" },
  ],
  reportingEvents: [
    {
      quarter: "2024-Q2",
      eventDate: "2024-07",
      title: "Q2 2024 results event",
      sourceId: "rtx-ir-quarterly-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "GTF remediation and aerospace recovery", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "GTF fleet management", intensity: 5, direction: "stable", evidence: "Investor debate centered on remediation cost and timing." },
        { theme: "Commercial aero recovery", intensity: 4, direction: "rising", evidence: "Aftermarket and OE recovery were prominent." },
        { theme: "Defense backlog", intensity: 3, direction: "stable", evidence: "Defense demand was visible but not yet the dominant debate." },
        { theme: "Cash conversion", intensity: 4, direction: "stable", evidence: "FCF credibility remained central." },
      ],
      debateQuestions: ["Can GTF costs remain within expected bounds?", "How fast can commercial aftermarket convert into FCF?"],
      watchItems: ["Pratt margin", "Operating cash flow", "Commercial aftermarket growth"],
      aiSummary: { sourceStatus: "research_only", summary: "The event was dominated by GTF remediation and commercial recovery, with defense viewed as a stabilizer rather than the central upside driver." },
    },
    {
      quarter: "2024-Q3",
      eventDate: "2024-10",
      title: "Q3 2024 results event",
      sourceId: "rtx-ir-quarterly-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Cash bridge and segment recovery", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "GTF fleet management", intensity: 5, direction: "stable", evidence: "Remediation remained a top question." },
        { theme: "Commercial aero recovery", intensity: 4, direction: "stable", evidence: "Aftermarket recovery supported the bull case." },
        { theme: "Defense backlog", intensity: 3, direction: "rising", evidence: "Missile and air-defense demand gained attention." },
        { theme: "Cash conversion", intensity: 4, direction: "stable", evidence: "FCF timing was still debated." },
      ],
      debateQuestions: ["Is the cash bridge improving enough to support buybacks and dividends?", "Can Raytheon offset Pratt noise?"],
      watchItems: ["Segment profit bridge", "Backlog disclosures", "GTF milestones"],
      aiSummary: { sourceStatus: "research_only", summary: "The market began to connect RTX's defense backlog to normalized earnings power, while still discounting the stock for Pratt execution risk." },
    },
    {
      quarter: "2024-Q4",
      eventDate: "2025-01",
      title: "FY2024 results and 2025 outlook event",
      sourceId: "rtx-ir-quarterly-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "2025 guide, GTF, and FCF reset", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "GTF fleet management", intensity: 5, direction: "stable", evidence: "The guide depended on continued GTF containment." },
        { theme: "Commercial aero recovery", intensity: 4, direction: "stable", evidence: "Commercial aftermarket remained supportive." },
        { theme: "Defense backlog", intensity: 4, direction: "rising", evidence: "Defense backlog was increasingly framed as a durability lever." },
        { theme: "2026 guidance", intensity: 1, direction: "new", evidence: "Longer-dated guidance was not yet the main debate." },
      ],
      debateQuestions: ["How conservative is the 2025 FCF guide?", "Does defense demand deserve a higher multiple?"],
      watchItems: ["2025 FCF guide", "Raytheon backlog", "Collins margin"],
      aiSummary: { sourceStatus: "research_only", summary: "The FY2024 event set up 2025 as a proof year: investors wanted evidence that defense backlog and commercial recovery could coexist with Pratt remediation costs." },
    },
    {
      quarter: "2025-Q1",
      eventDate: "2025-04",
      title: "Q1 2025 results event",
      sourceId: "rtx-ir-quarterly-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Defense volume and early-year cash use", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "GTF fleet management", intensity: 4, direction: "falling", evidence: "Still important, but not the only debate." },
        { theme: "Defense backlog", intensity: 4, direction: "rising", evidence: "Air and missile defense volume became more visible." },
        { theme: "Cash conversion", intensity: 5, direction: "rising", evidence: "First-quarter working-capital seasonality was a key watch item." },
        { theme: "Missile defense demand", intensity: 4, direction: "rising", evidence: "Raytheon demand quality gained prominence." },
      ],
      debateQuestions: ["Is first-quarter cash seasonality normal?", "Are Raytheon margins inflecting?"],
      watchItems: ["Quarterly FCF", "Raytheon operating profit", "Defense backlog"],
      aiSummary: { sourceStatus: "research_only", summary: "Focus broadened from GTF containment toward whether Raytheon and Collins could create enough profit momentum to validate the defense-prime rerating." },
    },
    {
      quarter: "2025-Q2",
      eventDate: "2025-07",
      title: "Q2 2025 results event",
      sourceId: "rtx-ir-quarterly-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "Backlog conversion and margin durability", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "Defense backlog", intensity: 5, direction: "rising", evidence: "The market increasingly focused on backlog as revenue support." },
        { theme: "Missile defense demand", intensity: 4, direction: "rising", evidence: "Munitions and air-defense programs were central to read-throughs." },
        { theme: "Cash conversion", intensity: 4, direction: "stable", evidence: "FCF remained the proof point." },
        { theme: "Tariffs / supply chain", intensity: 3, direction: "new", evidence: "Cost inflation and tariffs started to appear more often in margin questions." },
      ],
      debateQuestions: ["Can order strength convert without margin leakage?", "How durable is Raytheon's defense demand?"],
      watchItems: ["Book-to-bill", "Raytheon margins", "Tariff commentary"],
      aiSummary: { sourceStatus: "research_only", summary: "The market's center of gravity moved toward backlog quality and missile-defense conversion, with cash and tariff effects as the main counterweights." },
    },
    {
      quarter: "2025-Q3",
      eventDate: "2025-10",
      title: "Q3 2025 results event",
      sourceId: "rtx-ir-quarterly-archive",
      sourceStatus: "research_only",
      transcriptStatus: "missing",
      keyMetrics: [{ label: "Focus", value: "2026 setup and defense acceleration", sourceStatus: "research_only" }],
      marketFocus: [
        { theme: "Defense backlog", intensity: 5, direction: "stable", evidence: "Backlog durability became a central underwriting point." },
        { theme: "Missile defense demand", intensity: 5, direction: "rising", evidence: "Air and naval defense volume drew sustained attention." },
        { theme: "2026 guidance", intensity: 3, direction: "rising", evidence: "Investors started framing 2026 as the normalized earnings-power year." },
        { theme: "GTF fleet management", intensity: 3, direction: "falling", evidence: "GTF remained important but less dominant than in 2024." },
      ],
      debateQuestions: ["What is the normalized 2026 earnings bridge?", "Does the defense business justify a lower risk discount?"],
      watchItems: ["2026 commentary", "Segment operating profit", "Pratt remediation cadence"],
      aiSummary: { sourceStatus: "research_only", summary: "By late 2025, investor focus had shifted to 2026 earnings power, defense backlog, and whether Pratt risk was becoming manageable rather than thesis-defining." },
    },
    {
      quarter: "2025-Q4",
      eventDate: "2026-01-27",
      title: "FY2025 results and 2026 outlook",
      sourceId: "rtx-fy2025-results",
      sourceStatus: "official_actual",
      transcriptStatus: "official_release_only",
      keyMetrics: [
        { label: "Sales", value: "$88.6bn", sourceStatus: "official_actual" },
        { label: "FCF", value: "$7.9bn", sourceStatus: "official_actual" },
        { label: "Backlog", value: "$268bn", sourceStatus: "official_actual" },
      ],
      marketFocus: [
        { theme: "Defense backlog", intensity: 5, direction: "stable", evidence: "RTX disclosed $268bn backlog, including $107bn defense." },
        { theme: "2026 guidance", intensity: 5, direction: "rising", evidence: "The 2026 outlook framed the next leg of the thesis." },
        { theme: "Cash conversion", intensity: 4, direction: "stable", evidence: "FY2025 FCF and 2026 FCF guide were core inputs." },
        { theme: "Commercial aero recovery", intensity: 4, direction: "stable", evidence: "Commercial backlog and aftermarket remained important." },
      ],
      debateQuestions: ["Can RTX convert $268bn backlog into clean FCF?", "Is the 2026 guide conservative after FY2025 execution?"],
      watchItems: ["2026 adjusted sales", "FCF guide", "Defense backlog mix"],
      aiSummary: { sourceStatus: "research_only", summary: "The FY2025 event crystallized the valuation debate: backlog was no longer a qualitative talking point, but a visible durability layer supporting the 2026 guide." },
    },
    {
      quarter: "2026-Q1",
      eventDate: "2026-04-21",
      title: "Q1 2026 results and raised 2026 sales/EPS outlook",
      sourceId: "rtx-q1-2026-results",
      sourceStatus: "official_actual",
      transcriptStatus: "official_release_only",
      keyMetrics: [
        { label: "Sales", value: "$22.1bn", sourceStatus: "official_actual" },
        { label: "Adjusted EPS", value: "$1.78", sourceStatus: "official_actual" },
        { label: "FCF", value: "$1.3bn", sourceStatus: "official_actual" },
        { label: "Backlog", value: "$271bn", sourceStatus: "official_actual" },
      ],
      marketFocus: [
        { theme: "Defense backlog", intensity: 5, direction: "stable", evidence: "Backlog rose to $271bn, including $109bn defense." },
        { theme: "2026 guidance", intensity: 5, direction: "rising", evidence: "Management raised adjusted sales and adjusted EPS guidance." },
        { theme: "Missile defense demand", intensity: 5, direction: "stable", evidence: "Raytheon cited land, air defense, Patriot, GEM-T, and naval munitions volume." },
        { theme: "Tariffs / supply chain", intensity: 4, direction: "rising", evidence: "Tariffs appeared in segment margin commentary." },
      ],
      debateQuestions: ["Does the raised guide mark a durable inflection or a strong first-quarter pull-forward?", "How much tariff pressure can RTX offset with volume and mix?"],
      watchItems: ["Raytheon volume", "Pratt margin", "FCF conversion", "Tariff impact"],
      aiSummary: { sourceStatus: "research_only", summary: "Q1 2026 moved the market debate from demand validation to execution quality: sales and EPS guidance rose, FCF was confirmed, and the backlog signal remained strong." },
    },
  ],
  scenarios: [
    {
      scenario: "Bear",
      revenueCagr: 0.025,
      operatingMargin: 0.112,
      wacc: 0.09,
      terminalGrowth: 0.018,
      targetFcfYield: 0.05,
      targetPe: 18,
      targetEvEbit: 17,
      probability: 0.25,
      narrative: "GTF costs, tariffs, and execution drag absorb the defense-demand benefit; backlog converts more slowly and margin expansion stalls.",
    },
    {
      scenario: "Base",
      revenueCagr: 0.055,
      operatingMargin: 0.126,
      wacc: 0.082,
      terminalGrowth: 0.025,
      targetFcfYield: 0.038,
      targetPe: 25,
      targetEvEbit: 23,
      probability: 0.5,
      narrative: "2026 guidance is achievable, defense backlog supports mid-single-digit growth, and commercial aftermarket plus Raytheon volume offset Pratt remediation noise.",
    },
    {
      scenario: "Bull",
      revenueCagr: 0.072,
      operatingMargin: 0.135,
      wacc: 0.076,
      terminalGrowth: 0.028,
      targetFcfYield: 0.034,
      targetPe: 28,
      targetEvEbit: 25,
      probability: 0.25,
      narrative: "Defense spending and commercial aftermarket both stay strong, GTF risk fades, and RTX earns a higher durability multiple on improving FCF conversion.",
    },
  ],
  assumptions: {
    currentPrice: 178.61,
    revenueCagr: 0.055,
    operatingMargin: 0.126,
    taxRate: 0.19,
    dAndAIntensity: 0.048,
    capexIntensity: 0.03,
    workingCapitalDragPctRevenueGrowth: 0.1,
    wacc: 0.082,
    terminalGrowth: 0.025,
    targetFcfYield: 0.038,
    targetPe: 25,
    targetEvEbit: 23,
    netDebt: 30595,
    dilutedShares: 1348,
    dividendPerShare: 2.72,
    backlogDurabilityMaxAdjustment: 0.1,
    weightDcf: 0.35,
    weightFcfYield: 0.25,
    weightEvEbit: 0.15,
    weightPe: 0.1,
    weightBacklogDurability: 0.15,
  },
  capitalReturns: {
    dividendPerShare: 2.72,
    dividendsPaid: 3588,
    fcfPayout: 3588 / 7940,
    payoutRatio: 2.72 / 6.29,
    policy: "Dividend plus repurchases, subject to cash flow, leverage, and GTF remediation needs.",
    sourceStatus: "derived",
    sourceId: "rtx-fy2025-results",
    sustainabilityView:
      "RTX's capital-return capacity is tied to FCF conversion after GTF remediation and output investments. The payout is supported in the base case, but buybacks are more sensitive than the dividend to working-capital and remediation shocks.",
  },
};
