import type { DeepResearchDataset } from "../deepResearch/model";

const marketData = {
  currentPrice: 1021.11,
  priceDate: "2026-05-19",
  source: "Market data snapshot captured 2026-05-19; verify against live feed before trading.",
  sourceStatus: "market_data_proxy" as const,
};

const defaultAssumptions = {
  currentPrice: marketData.currentPrice,
  revenueBase: 82000,
  revenueCagr3Y: 0.18,
  terminalGrowth: 0.035,
  normalizedFcfMargin: 0.32,
  exitFcfMultiple: 32,
  evRevenueMultiple: 13,
  discountRate: 0.085,
  netCashDebt: -30000,
  dilutedShares: 896,
  qualityAdjustment: 1.08,
  riskHaircut: 0.08,
  dividendYield: 0.005,
  buybackYield: 0.002,
};

export const llyDataset: DeepResearchDataset = {
  ticker: "LLY",
  companyName: "Eli Lilly and Company",
  sector: "Biopharma / Obesity / Diabetes / Oncology Pipeline",
  archetype: "GLP-1 mega-franchise / pipeline durability",
  currency: "USD",
  description:
    "LLY cockpit focused on Mounjaro/Zepbound demand, manufacturing capacity, gross-to-net and payer access, oral GLP-1 and retatrutide pipeline durability, margin expansion, capex, policy risk, and whether GLP-1 growth already supports the premium multiple.",
  updatedAt: "2026-05-19",
  marketData,
  tabs: [
    { value: "dashboard", label: "Dashboard" },
    { value: "glp1-capacity", label: "GLP-1 / Capacity" },
    { value: "pipeline-durability", label: "Pipeline Durability" },
    { value: "earnings-questions", label: "Earnings Questions" },
    { value: "valuation", label: "Valuation" },
    { value: "risk-red-team", label: "Risk Red Team" },
  ],
  periods: [
    { value: "fy2026-q1", label: "FY2026 Q1" },
    { value: "fy2025-q4", label: "FY2025 Q4" },
    { value: "fy2025", label: "FY2025" },
  ],
  summaryMetrics: [
    { key: "glp1-growth", label: "GLP-1 Growth", value: 0.36, format: "percent", description: "Mounjaro/Zepbound remain the central growth engine.", badge: "Derived" },
    { key: "capacity-score", label: "Capacity Expansion Score", value: 78, format: "number", description: "Manufacturing capacity is the main constraint and catalyst.", badge: "Derived" },
    { key: "pipeline-optionality", label: "Pipeline Optionality", value: 0.26, format: "percent", description: "Oral GLP-1, retatrutide and non-incretin pipeline support durability.", badge: "Assumption" },
    { key: "fcf-margin", label: "Normalized FCF Margin", value: defaultAssumptions.normalizedFcfMargin, format: "percent", description: "Long-term margin depends on scale, rebates and manufacturing cost.", badge: "Assumption" },
    { key: "policy-risk", label: "Policy / Access Risk", value: 0.18, format: "percent", description: "Pricing, access and Medicare policy risk are key bear-case variables.", badge: "Derived" },
  ],
  researchQuestions: [
    {
      key: "capacity-demand",
      question: "Is GLP-1 demand still supply-constrained or approaching normalized growth?",
      currentView: "The base case assumes capacity expansion keeps unlocking demand, but valuation already discounts a very large obesity franchise.",
      metric: "Mounjaro/Zepbound sales, supply commentary, prescription demand",
      evidenceNeeded: "Fill rates, manufacturing capacity, international launch pace, inventory",
      valuationTie: "Revenue CAGR",
      bearCase: "Supply expansion reveals slower underlying demand or price elasticity.",
    },
    {
      key: "gross-to-net",
      question: "Can LLY protect net price as payer access broadens?",
      currentView: "Volume growth is powerful, but rebates, access and competition decide how much becomes FCF.",
      metric: "Gross-to-net, payer coverage, realized price",
      evidenceNeeded: "Rebate commentary, formulary access, international pricing",
      valuationTie: "Normalized FCF margin",
      bearCase: "Coverage expands but net price falls faster than volume leverage.",
    },
    {
      key: "pipeline-durability",
      question: "Does the pipeline extend growth beyond injectable GLP-1s?",
      currentView: "Oral GLP-1 and next-gen obesity assets matter because the stock needs a long runway beyond first-wave drugs.",
      metric: "Orforglipron, retatrutide, oncology/immunology catalysts",
      evidenceNeeded: "Clinical readouts, regulatory timelines, safety/tolerability, label expansion",
      valuationTie: "Quality adjustment and terminal growth",
      bearCase: "Pipeline fails to extend beyond existing incretin franchise.",
    },
    {
      key: "competition-policy",
      question: "How much do Novo competition and policy risk compress the franchise?",
      currentView: "Competition is manageable if demand stays supply constrained, but policy could reset obesity drug economics.",
      metric: "Market share, access, legislation, Medicare/IRA exposure",
      evidenceNeeded: "Share trends, payer coverage and policy proposals",
      valuationTie: "Risk haircut",
      bearCase: "Pricing and policy compress the multiple before volume matures.",
    },
  ],
  kpiSeries: [
    {
      key: "glp1-capacity",
      title: "GLP-1 Franchise vs Capacity Score",
      subtitle: "The most important operating chart is GLP-1 revenue growth versus evidence that capacity keeps unlocking demand.",
      sourceStatus: "research_only",
      measures: [
        { key: "glp1Revenue", label: "Mounjaro/Zepbound proxy ($m)", format: "currency", chartType: "bar", color: "#2563eb", axis: "left" },
        { key: "capacityScore", label: "Capacity score", format: "number", chartType: "line", color: "#16a34a", axis: "right" },
      ],
      points: [
        { period: "FY2023 Q2", glp1Revenue: 979, capacityScore: 42 },
        { period: "FY2023 Q3", glp1Revenue: 1410, capacityScore: 45 },
        { period: "FY2023 Q4", glp1Revenue: 2105, capacityScore: 48 },
        { period: "FY2024 Q1", glp1Revenue: 2520, capacityScore: 52 },
        { period: "FY2024 Q2", glp1Revenue: 3365, capacityScore: 57 },
        { period: "FY2024 Q3", glp1Revenue: 4210, capacityScore: 61 },
        { period: "FY2024 Q4", glp1Revenue: 5050, capacityScore: 65 },
        { period: "FY2025 Q1", glp1Revenue: 6120, capacityScore: 68 },
        { period: "FY2025 Q2", glp1Revenue: 7200, capacityScore: 71 },
        { period: "FY2025 Q3", glp1Revenue: 8150, capacityScore: 74 },
        { period: "FY2025 Q4", glp1Revenue: 9250, capacityScore: 77 },
        { period: "FY2026 Q1", glp1Revenue: 10150, capacityScore: 78 },
      ],
    },
    {
      key: "pipeline-durability",
      title: "Pipeline Durability / Margin Bridge",
      subtitle: "LLY needs pipeline breadth and margin conversion to support a multi-year premium.",
      sourceStatus: "research_only",
      measures: [
        { key: "pipelineScore", label: "Pipeline score", format: "number", chartType: "bar", color: "#7c3aed", axis: "left" },
        { key: "operatingMargin", label: "Operating margin %", format: "percent", chartType: "line", color: "#0f172a", axis: "right" },
      ],
      points: [
        { period: "FY2023 Q2", pipelineScore: 55, operatingMargin: 28 },
        { period: "FY2023 Q3", pipelineScore: 57, operatingMargin: 30 },
        { period: "FY2023 Q4", pipelineScore: 60, operatingMargin: 31 },
        { period: "FY2024 Q1", pipelineScore: 62, operatingMargin: 32 },
        { period: "FY2024 Q2", pipelineScore: 65, operatingMargin: 33 },
        { period: "FY2024 Q3", pipelineScore: 67, operatingMargin: 34 },
        { period: "FY2024 Q4", pipelineScore: 69, operatingMargin: 35 },
        { period: "FY2025 Q1", pipelineScore: 71, operatingMargin: 36 },
        { period: "FY2025 Q2", pipelineScore: 74, operatingMargin: 37 },
        { period: "FY2025 Q3", pipelineScore: 76, operatingMargin: 38 },
        { period: "FY2025 Q4", pipelineScore: 79, operatingMargin: 39 },
        { period: "FY2026 Q1", pipelineScore: 81, operatingMargin: 39 },
      ],
    },
  ],
  deepDiveSections: [
    {
      key: "capacity-unlock",
      tab: "glp1-capacity",
      title: "Capacity Unlock",
      thesis: "LLY's earnings power is unusually dependent on physical manufacturing capacity, not just prescription demand.",
      evidence: ["Manufacturing expansion", "Supply status", "International launch pace", "Prescription demand"],
      watchItems: ["Supply shortage resolution", "Inventory channel build", "Gross-to-net pressure"],
      sourceStatus: "research_only",
    },
    {
      key: "pipeline-extension",
      tab: "pipeline-durability",
      title: "Beyond First-Wave GLP-1",
      thesis: "The premium multiple needs evidence that oral GLP-1, retatrutide and non-obesity assets extend growth after the first obesity wave.",
      evidence: ["Orforglipron readouts", "Retatrutide timelines", "Oncology/immunology catalysts", "Label expansion"],
      watchItems: ["Safety/tolerability", "Regulatory delays", "Pipeline concentration"],
      sourceStatus: "research_only",
    },
  ],
  quarterlyQuestions: [
    { quarter: "FY2026 Q1", eventDate: "2026-04-30", headline: "GLP-1 capacity and price/access", keyQuestions: ["Is GLP-1 still supply constrained?", "Any gross-to-net pressure?", "What pipeline catalysts change 2027+ growth?"], managementTone: "Confident on demand and capacity.", modelReadThrough: "Keep high growth but monitor access/pricing risk.", riskSignal: "Positive", sourceStatus: "official_actual" },
    { quarter: "FY2025 Q4", eventDate: "2026-02-06", headline: "2026 guidance and supply unlock", keyQuestions: ["How much growth is capacity-led?", "Can margin expand with capex?", "What is oral GLP-1 timeline?"], managementTone: "Strong.", modelReadThrough: "Higher revenue base, keep capex/FCF conversion watch.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q3", eventDate: "2025-10-30", headline: "Obesity demand vs payer friction", keyQuestions: ["Does payer access broaden?", "Any net price pressure?", "Competition update?"], managementTone: "Constructive.", modelReadThrough: "Revenue durability improves, risk haircut unchanged.", riskSignal: "Neutral", sourceStatus: "research_only" },
    { quarter: "FY2025 Q2", eventDate: "2025-08-07", headline: "Capacity, margin and pipeline", keyQuestions: ["Manufacturing progress?", "GLP-1 gross margin?", "Pipeline readout cadence?"], managementTone: "Bullish.", modelReadThrough: "Margin assumptions can rise only with proof of scale leverage.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2025 Q1", eventDate: "2025-05-01", headline: "Supply-constrained growth", keyQuestions: ["Is demand above supply?", "What is international launch pace?", "Any reimbursement pushback?"], managementTone: "Strong demand.", modelReadThrough: "Raise near-term growth but not terminal multiple.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q4", eventDate: "2025-02-06", headline: "Guidance reset higher", keyQuestions: ["How much is GLP-1 growth?", "Can production scale?", "Capex / FCF impact?"], managementTone: "Confident.", modelReadThrough: "Higher revenue base, capex drag on FCF.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q3", eventDate: "2024-10-30", headline: "Obesity franchise acceleration", keyQuestions: ["Zepbound launch trajectory?", "Supply allocation?", "Mounjaro diabetes growth?"], managementTone: "Strong.", modelReadThrough: "Increase franchise penetration assumption.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2024 Q2", eventDate: "2024-08-08", headline: "Capacity bottleneck", keyQuestions: ["What is supply constraint?", "How fast can plants ramp?", "Any pricing pressure?"], managementTone: "Demand exceeds supply.", modelReadThrough: "Demand high, capacity limits revenue timing.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2024 Q1", eventDate: "2024-05-06", headline: "GLP-1 demand visibility", keyQuestions: ["Mounjaro/Zepbound demand?", "Payer access?", "Margin path?"], managementTone: "Confident.", modelReadThrough: "Raise growth with supply caveat.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2023 Q4", eventDate: "2024-02-06", headline: "Zepbound early launch", keyQuestions: ["Launch demand?", "Supply capacity?", "Competitive response?"], managementTone: "Early strong demand.", modelReadThrough: "Optionality improves; still early.", riskSignal: "Inflecting", sourceStatus: "research_only" },
    { quarter: "FY2023 Q3", eventDate: "2023-11-02", headline: "Obesity market formation", keyQuestions: ["What is Mounjaro trajectory?", "Can obesity label expand?", "Manufacturing investment?"], managementTone: "Strong.", modelReadThrough: "Growth runway widens.", riskSignal: "Positive", sourceStatus: "research_only" },
    { quarter: "FY2023 Q2", eventDate: "2023-08-08", headline: "GLP-1 acceleration", keyQuestions: ["Is demand durable?", "Any supply shortages?", "Pipeline catalyst timing?"], managementTone: "Very strong.", modelReadThrough: "Increase revenue CAGR but keep policy risk.", riskSignal: "Positive", sourceStatus: "research_only" },
  ],
  historicalValuations: [
    { id: "lly-2023q2", eventDate: "2023-08-08", fiscalPeriod: "FY2023 Q2", asOfPrice: 522, fairValue: 560, targetPrice3Y: 720, expectedShareholderCagr: 0.113, method: "Early GLP-1 acceleration DCF.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 560, format: "currency", description: "Demand strong, early capacity limits." }] },
    { id: "lly-2023q3", eventDate: "2023-11-02", fiscalPeriod: "FY2023 Q3", asOfPrice: 590, fairValue: 645, targetPrice3Y: 835, expectedShareholderCagr: 0.122, method: "Obesity franchise widening.", sourceStatus: "research_only", warnings: ["Local row."], methodOutputs: [{ label: "Blend", value: 645, format: "currency", description: "Label and demand improving." }] },
    { id: "lly-2023q4", eventDate: "2024-02-06", fiscalPeriod: "FY2023 Q4", asOfPrice: 705, fairValue: 735, targetPrice3Y: 950, expectedShareholderCagr: 0.104, method: "Zepbound early launch.", sourceStatus: "research_only", warnings: ["No backend daily price."], methodOutputs: [{ label: "DCF", value: 730, format: "currency", description: "Launch demand." }] },
    { id: "lly-2024q1", eventDate: "2024-05-06", fiscalPeriod: "FY2024 Q1", asOfPrice: 780, fairValue: 815, targetPrice3Y: 1055, expectedShareholderCagr: 0.106, method: "Demand visibility / access watch.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "FCF multiple", value: 825, format: "currency", description: "Demand strong." }] },
    { id: "lly-2024q2", eventDate: "2024-08-08", fiscalPeriod: "FY2024 Q2", asOfPrice: 845, fairValue: 890, targetPrice3Y: 1150, expectedShareholderCagr: 0.108, method: "Capacity bottleneck valuation.", sourceStatus: "research_only", warnings: ["Local row."], methodOutputs: [{ label: "Blend", value: 890, format: "currency", description: "Capacity unlock." }] },
    { id: "lly-2024q3", eventDate: "2024-10-30", fiscalPeriod: "FY2024 Q3", asOfPrice: 910, fairValue: 940, targetPrice3Y: 1210, expectedShareholderCagr: 0.099, method: "Obesity franchise acceleration.", sourceStatus: "research_only", warnings: ["No current policy assumptions backfilled."], methodOutputs: [{ label: "DCF", value: 938, format: "currency", description: "Zepbound uptake." }] },
    { id: "lly-2024q4", eventDate: "2025-02-06", fiscalPeriod: "FY2024 Q4", asOfPrice: 875, fairValue: 975, targetPrice3Y: 1260, expectedShareholderCagr: 0.129, method: "Guidance reset higher.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "Blend", value: 975, format: "currency", description: "Guidance up." }] },
    { id: "lly-2025q1", eventDate: "2025-05-01", fiscalPeriod: "FY2025 Q1", asOfPrice: 812, fairValue: 1010, targetPrice3Y: 1305, expectedShareholderCagr: 0.171, method: "Supply constrained growth.", sourceStatus: "research_only", warnings: ["Local row."], methodOutputs: [{ label: "DCF", value: 1005, format: "currency", description: "Demand > supply." }] },
    { id: "lly-2025q2", eventDate: "2025-08-07", fiscalPeriod: "FY2025 Q2", asOfPrice: 900, fairValue: 1060, targetPrice3Y: 1370, expectedShareholderCagr: 0.15, method: "Capacity / margin bridge.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "FCF multiple", value: 1075, format: "currency", description: "Capacity ramp." }] },
    { id: "lly-2025q3", eventDate: "2025-10-30", fiscalPeriod: "FY2025 Q3", asOfPrice: 955, fairValue: 1115, targetPrice3Y: 1440, expectedShareholderCagr: 0.147, method: "Payer access and demand.", sourceStatus: "research_only", warnings: ["Local fallback."], methodOutputs: [{ label: "Blend", value: 1115, format: "currency", description: "Access broadens." }] },
    { id: "lly-2025q4", eventDate: "2026-02-06", fiscalPeriod: "FY2025 Q4", asOfPrice: 985, fairValue: 1160, targetPrice3Y: 1500, expectedShareholderCagr: 0.15, method: "2026 guidance and supply unlock.", sourceStatus: "research_only", warnings: ["Proxy price."], methodOutputs: [{ label: "DCF", value: 1150, format: "currency", description: "Guidance strength." }] },
    { id: "lly-2026q1", eventDate: "2026-04-30", fiscalPeriod: "FY2026 Q1", asOfPrice: 1021, fairValue: 1195, targetPrice3Y: 1545, expectedShareholderCagr: 0.148, method: "Base GLP-1 / pipeline triangulation.", sourceStatus: "official_actual", warnings: ["Backend valuation run not persisted."], methodOutputs: [{ label: "Blend", value: 1195, format: "currency", description: "Demand and capacity strong; policy risk retained." }] },
  ],
  valuation: {
    defaultAssumptions,
    scenarios: {
      Bear: { ...defaultAssumptions, revenueCagr3Y: 0.09, normalizedFcfMargin: 0.25, exitFcfMultiple: 22, evRevenueMultiple: 8, discountRate: 0.1, qualityAdjustment: 0.98, riskHaircut: 0.18 },
      Base: defaultAssumptions,
      Bull: { ...defaultAssumptions, revenueCagr3Y: 0.24, normalizedFcfMargin: 0.37, exitFcfMultiple: 38, evRevenueMultiple: 15.5, discountRate: 0.08, qualityAdjustment: 1.14, riskHaircut: 0.05 },
    },
    modelDescription: "GLP-1 franchise DCF with FCF multiple and EV/revenue cross-check, retaining explicit policy and access risk.",
    noFutureLeakageNote: "Historical LLY rows use the GLP-1, capacity and pipeline information available at each event; later pipeline/capacity evidence is not backfilled.",
  },
  risks: [
    { title: "Gross-to-net / payer pressure", detail: "Broader access may require higher rebates and lower realized price.", severity: "high", killSignal: "Net price declines faster than volume and margin expansion." },
    { title: "Capacity execution", detail: "Manufacturing scale is a physical constraint on revenue and a capex burden on FCF.", severity: "medium", killSignal: "Capacity delays or quality issues limit GLP-1 supply for multiple quarters." },
    { title: "Pipeline concentration", detail: "The premium multiple depends on obesity franchise depth and pipeline extension.", severity: "high", killSignal: "Oral/next-gen GLP-1 readouts disappoint while current franchise matures." },
    { title: "Policy and competition", detail: "Obesity drug pricing may face policy scrutiny and competition from Novo and other entrants.", severity: "medium", killSignal: "Major policy action or competitive data resets long-run pricing." },
  ],
  monitoring: ["Mounjaro/Zepbound sales", "Supply/capacity commentary", "Gross-to-net and payer access", "Pipeline readouts", "Capex and FCF conversion", "Policy headlines"],
  sourceGaps: ["Historical valuation rows are local fallback.", "LLY/SPY daily price bars not imported into backend.", "Product-level capacity and gross-to-net are research proxies until official KPI extraction is automated."],
  backendStatus: {
    supported: false,
    detail: "LLY has frontend research history and valuation now, but no per-ticker SQLite backend or AWS data deployment yet.",
    nextSteps: ["Create LLY backend DB.", "Import LLY/SPY daily prices.", "Persist valuation runs by quarterly event.", "Automate product/pipeline transcript extraction."],
  },
  qualityBadges: [
    { label: "GLP-1 KPIs", value: "Research proxy", badge: "Assumption" },
    { label: "Historical valuation", value: "Local fallback", badge: "Placeholder" },
    { label: "Market price", value: "Proxy snapshot", badge: "Placeholder" },
  ],
};
