import type { MckResearchAssumptions, MckScenarioDefinition } from "./types";
import { mckMarketSnapshot } from "./data/market/yfinance";

export const defaultMckAssumptions: MckResearchAssumptions = {
  currentPrice: mckMarketSnapshot.currentPrice,
  forwardAdjustedEps: 44.2,
  targetPe: 17,
  fcfPerShare: 44.1,
  targetFcfYield: 0.058,
  normalizedFcf: 5400,
  normalizedFcfGrowth: 0.08,
  ownerEarningsBase: 5200,
  wacc: 0.082,
  terminalGrowth: 0.025,
  taxRate: 0.18,
  netDebt: 6900,
  dilutedShares: 122.5,
  averageBuybackPrice: 760,
  annualFcf: 5400,
  dividendPayout: 400,
  buybackAmount: 4800,
  epsCagr3Y: 0.13,
  epsCagr5Y: 0.12,
  exitPe: 16.5,
  marginBpsChange: 8,
  fcfConversion: 1.05,
  downsideShock: 0,
  coreDistributionMultiple: 10,
  oncologyMultiple: 16,
  rxTechnologyMultiple: 17,
  medSurgMultiple: 8.5,
  corporateCostValue: -4500,
  weightPe: 0.25,
  weightFcfYield: 0.25,
  weightDcf: 0.25,
  weightSotp: 0.25,
};

export const mckScenarioPresets: Record<"Bear" | "Base" | "Bull", Partial<MckResearchAssumptions>> = {
  Bear: {
    currentPrice: mckMarketSnapshot.currentPrice,
    forwardAdjustedEps: 41.5,
    targetPe: 14,
    fcfPerShare: 38,
    targetFcfYield: 0.07,
    normalizedFcfGrowth: 0.04,
    wacc: 0.092,
    terminalGrowth: 0.015,
    averageBuybackPrice: 820,
    buybackAmount: 3000,
    epsCagr3Y: 0.07,
    epsCagr5Y: 0.06,
    exitPe: 13.5,
    marginBpsChange: -12,
    fcfConversion: 0.9,
    downsideShock: 0.12,
    coreDistributionMultiple: 8,
    oncologyMultiple: 13,
    rxTechnologyMultiple: 14,
    medSurgMultiple: 7,
  },
  Base: defaultMckAssumptions,
  Bull: {
    currentPrice: mckMarketSnapshot.currentPrice,
    forwardAdjustedEps: 46,
    targetPe: 19,
    fcfPerShare: 48,
    targetFcfYield: 0.052,
    normalizedFcfGrowth: 0.11,
    wacc: 0.078,
    terminalGrowth: 0.028,
    averageBuybackPrice: 720,
    buybackAmount: 5600,
    epsCagr3Y: 0.16,
    epsCagr5Y: 0.14,
    exitPe: 18.5,
    marginBpsChange: 18,
    fcfConversion: 1.12,
    downsideShock: 0,
    coreDistributionMultiple: 12,
    oncologyMultiple: 19,
    rxTechnologyMultiple: 20,
    medSurgMultiple: 10,
  },
};

export const mckScenarioDefinitions: MckScenarioDefinition[] = [
  {
    name: "Bear",
    assumptions: mckScenarioPresets.Bear,
    summary:
      "PBM/reimbursement pressure and customer mix compress margin, GLP-1 adds lower-margin volume, working capital normalizes against reported FCF, and buybacks are less accretive at higher execution prices.",
  },
  {
    name: "Base",
    assumptions: mckScenarioPresets.Base,
    summary:
      "Distribution profit grows mid-single digits, Oncology and RxTS compound faster, FCF conversion normalizes, and repurchases add durable per-share accretion without requiring multiple expansion.",
  },
  {
    name: "Bull",
    assumptions: mckScenarioPresets.Bull,
    summary:
      "Oncology/Biopharma mix drives sustained profit growth, RxTS earns a higher platform-like multiple, and buybacks remain value-accretive because FCF/share grows faster than the repurchase price.",
  },
];
