import type { MckDataset, MckRiskItem } from "./types";
import { defaultMckAssumptions, mckScenarioDefinitions } from "./assumptions";
import { mckReportedFinancials } from "./data/official/annualReports";
import { mckGuidance } from "./data/official/guidance";
import { mckSegmentFinancials } from "./data/official/segmentData";
import { mckMarketSnapshot } from "./data/market/yfinance";
import { mckPeerMetrics } from "./data/peers/peerMetrics";
import { mckManagementQuotes, mckQaPairs, mckTranscriptEvents } from "./data/transcripts";

const researchTag = {
  sourceType: "research" as const,
  source: "MCK buy-side risk framework",
  asOfDate: "2026-05-11",
  confidence: "medium" as const,
  notes: "Research-only risk score. Monitor against filings, calls, and peer reports.",
};

export const mckRisks: MckRiskItem[] = [
  {
    id: "reimbursement-pbm-pressure",
    name: "Reimbursement / PBM pressure",
    probability: 0.45,
    severity: 0.75,
    evidence: "Spread compression and access/prior-authorization economics can pressure profit per prescription even when volume is healthy.",
    earlyWarningIndicator: "RxTS access-solution growth decelerates or management cites reimbursement friction.",
    monitoringMetric: "RxTS adjusted operating profit growth and margin bps.",
    mitigation: "Diversified manufacturer, provider, pharmacy and payer connectivity.",
    score: 0,
    signal: "Negative",
    tag: researchTag,
  },
  {
    id: "customer-concentration",
    name: "Customer concentration",
    probability: 0.35,
    severity: 0.7,
    evidence: "Large national retail and health-system accounts can move revenue and working-capital intensity.",
    earlyWarningIndicator: "Major contract renewal shifts or retail national account volume commentary changes.",
    monitoringMetric: "North American Pharmaceutical revenue growth versus adjusted operating profit growth.",
    mitigation: "Scale, reliability, compliance, and breadth of service make switching difficult.",
    score: 0,
    signal: "Neutral",
    tag: researchTag,
  },
  {
    id: "opioid-litigation",
    name: "Opioid litigation",
    probability: 0.25,
    severity: 0.85,
    evidence: "Historical distributor litigation remains a low-frequency but high-severity cash and headline risk.",
    earlyWarningIndicator: "New state/federal claims, settlement accrual changes, or adverse legal rulings.",
    monitoringMetric: "Legal reserve and cash settlement disclosures.",
    mitigation: "Existing settlement framework and compliance investments reduce but do not eliminate risk.",
    score: 0,
    signal: "Negative",
    tag: researchTag,
  },
  {
    id: "working-capital-volatility",
    name: "Working capital volatility",
    probability: 0.55,
    severity: 0.55,
    evidence: "Tiny margins on very large revenue mean inventory, receivable, and payable timing can distort quarterly FCF.",
    earlyWarningIndicator: "OCF/FCF diverges sharply from adjusted net income for one or two quarters.",
    monitoringMetric: "Reported FCF versus normalized FCF conversion.",
    mitigation: "Scale and payable terms often offset inventory growth over a full cycle.",
    score: 0,
    signal: "Needs Review",
    tag: researchTag,
  },
  {
    id: "generic-deflation",
    name: "Generic price deflation",
    probability: 0.4,
    severity: 0.5,
    evidence: "Generic sell-side price deflation can pressure gross profit dollars even as branded/specialty revenue grows.",
    earlyWarningIndicator: "Distributor peers call out generic program weakness.",
    monitoringMetric: "NAP operating profit growth versus revenue growth.",
    mitigation: "Sourcing scale and specialty mix can offset moderate deflation.",
    score: 0,
    signal: "Neutral",
    tag: researchTag,
  },
  {
    id: "government-pricing",
    name: "Government pricing pressure",
    probability: 0.35,
    severity: 0.6,
    evidence: "Medicare, Medicaid, and broader drug-pricing reforms can reshape channel economics.",
    earlyWarningIndicator: "Policy proposals that alter reimbursement, channel spreads, or manufacturer service economics.",
    monitoringMetric: "Legislative/regulatory watchlist and management commentary.",
    mitigation: "Distributor fee-for-service economics are less exposed than manufacturers, but not immune.",
    score: 0,
    signal: "Neutral",
    tag: researchTag,
  },
  {
    id: "dscsa-compliance",
    name: "DSCSA / compliance cost",
    probability: 0.5,
    severity: 0.35,
    evidence: "Serialization, traceability, and data-exchange requirements can raise cost to serve.",
    earlyWarningIndicator: "Compliance cost spikes, delayed customer readiness, or manufacturer data issues.",
    monitoringMetric: "Corporate cost and distribution margin bps.",
    mitigation: "Scale may turn compliance into a moat versus smaller distributors.",
    score: 0,
    signal: "Neutral",
    tag: researchTag,
  },
  {
    id: "capital-allocation-mistake",
    name: "Debt / capital allocation mistake",
    probability: 0.25,
    severity: 0.65,
    evidence: "Buybacks at very high prices or large acquisitions can dilute the per-share compounding mechanism.",
    earlyWarningIndicator: "Average buyback price materially exceeds fair value or leverage rises above target.",
    monitoringMetric: "Buyback ROIC, net debt / EBITDA, and acquisition return disclosures.",
    mitigation: "Long record of repurchases and cash returns, but discipline must be re-underwritten each year.",
    score: 0,
    signal: "Needs Review",
    tag: researchTag,
  },
];

export const mckDataset: MckDataset = {
  company: {
    ticker: "MCK",
    name: "McKesson",
    fiscalYearEnd: "March 31",
    currency: "USD",
    unit: "USD millions unless otherwise noted",
  },
  reportedFinancials: mckReportedFinancials,
  segmentFinancials: mckSegmentFinancials,
  guidance: mckGuidance,
  market: mckMarketSnapshot,
  peers: mckPeerMetrics,
  risks: mckRisks,
  transcriptEvents: mckTranscriptEvents,
  managementQuotes: mckManagementQuotes,
  qaPairs: mckQaPairs,
  assumptions: defaultMckAssumptions,
  scenarios: mckScenarioDefinitions,
  validationWarnings: [],
};
