import type { TriDataset, TriScenarioDriver, TriSource } from "./model";

export const triSources: TriSource[] = [
  {
    id: "tri-q1-2026-results",
    title: "Thomson Reuters Reports First-Quarter 2026 Results",
    url: "https://investors.thomsonreuters.com/news-releases/news-release-details/thomson-reuters-reports-first-quarter-2026-results",
    publisher: "Thomson Reuters",
    sourceType: "official_actual",
    reportingPeriod: "Quarter ended March 31, 2026",
    accessedDate: "2026-05-12",
  },
  {
    id: "tri-fy-2025-results",
    title: "Thomson Reuters Reports Fourth-Quarter and Full-Year 2025 Results",
    url: "https://ir.thomsonreuters.com/news-releases/news-release-details/thomson-reuters-reports-fourth-quarter-and-full-year-2025",
    publisher: "Thomson Reuters",
    sourceType: "official_actual",
    reportingPeriod: "Year ended December 31, 2025",
    accessedDate: "2026-05-12",
  },
  {
    id: "tri-cocounsel-one-million",
    title: "One Million Professionals Turn to CoCounsel as Thomson Reuters Scales AI for Regulated Industries",
    url: "https://thomsonreuters.gcs-web.com/index.php/news-releases/news-release-details/one-million-professionals-turn-cocounsel-thomson-reuters-scales",
    publisher: "Thomson Reuters",
    sourceType: "management_commentary",
    reportingPeriod: "AI product milestone",
    accessedDate: "2026-05-12",
  },
  {
    id: "tri-cocounsel-legal-uk",
    title: "Thomson Reuters Expands CoCounsel Legal to UK",
    url: "https://www.thomsonreuters.com/en/press-releases/2026/january/thomson-reuters-expands-cocounsel-legal-to-uk-continuing-its-transformation-of-legal-work-with-agentic-ai-innovation",
    publisher: "Thomson Reuters",
    sourceType: "management_commentary",
    reportingPeriod: "AI product launch",
    accessedDate: "2026-05-12",
  },
  {
    id: "tri-market-stockanalysis",
    title: "TRI market snapshot",
    url: "https://stockanalysis.com/stocks/tri/",
    publisher: "StockAnalysis",
    sourceType: "market_data",
    reportingPeriod: "Market snapshot",
    accessedDate: "2026-05-12",
    notes: "Third-party delayed market data. Not an official Thomson Reuters actual.",
  },
];

export const triSourceMap = Object.fromEntries(triSources.map((source) => [source.id, source]));

export const triScenarioDrivers: TriScenarioDriver[] = [
  {
    scenario: "Bear",
    sourceType: "forecast_assumption",
    sourceId: "tri-forecast-assumptions",
    revenueCagr: 0.045,
    big3OrganicGrowth: 0.065,
    terminalAdjustedEbitdaMargin: 0.385,
    fcfConversionOfEbitda: 0.58,
    targetFcfYield: 0.058,
    targetEvEbitda: 13,
    targetPe: 18,
    wacc: 0.087,
    terminalGrowth: 0.02,
    aiPremium: 0.01,
    aiPremiumCap: 0.08,
    riskDiscount: -0.09,
    riskDiscountCap: 0.12,
    narrative: "AI uptake disappoints, legal/tax workflow conversion is slower, and elevated technology costs pressure margins.",
  },
  {
    scenario: "Base",
    sourceType: "forecast_assumption",
    sourceId: "tri-forecast-assumptions",
    revenueCagr: 0.074,
    big3OrganicGrowth: 0.092,
    terminalAdjustedEbitdaMargin: 0.405,
    fcfConversionOfEbitda: 0.64,
    targetFcfYield: 0.047,
    targetEvEbitda: 16,
    targetPe: 22,
    wacc: 0.079,
    terminalGrowth: 0.025,
    aiPremium: 0.04,
    aiPremiumCap: 0.08,
    riskDiscount: -0.035,
    riskDiscountCap: 0.12,
    narrative: "CoCounsel adoption supports high-single-digit organic growth in the Big 3 segments while AI investment is absorbed through operating leverage.",
  },
  {
    scenario: "Bull",
    sourceType: "forecast_assumption",
    sourceId: "tri-forecast-assumptions",
    revenueCagr: 0.095,
    big3OrganicGrowth: 0.115,
    terminalAdjustedEbitdaMargin: 0.425,
    fcfConversionOfEbitda: 0.68,
    targetFcfYield: 0.04,
    targetEvEbitda: 19,
    targetPe: 26,
    wacc: 0.073,
    terminalGrowth: 0.029,
    aiPremium: 0.07,
    aiPremiumCap: 0.08,
    riskDiscount: -0.02,
    riskDiscountCap: 0.12,
    narrative: "Professional-grade AI becomes a paid workflow layer across legal, tax, audit and compliance, lifting retention, ARPU and margin durability.",
  },
];

export const triDataset: TriDataset = {
  company: "Thomson Reuters Corporation",
  ticker: "TRI",
  currency: "USD",
  reportingCurrency: "USD",
  latestReportingPeriod: "Quarter ended March 31, 2026",
  sources: triSources,
  periods: [
    {
      id: "fy25",
      label: "FY2025A",
      fiscalYear: 2025,
      periodType: "annual",
      sourceType: "official_actual",
      sourceId: "tri-fy-2025-results",
      revenue: 7_476,
      organicRevenueGrowth: 0.07,
      adjustedEbitda: 7_476 * 0.392,
      adjustedEbitdaMargin: 0.392,
      adjustedEps: 3.92,
      freeCashFlow: 1_950,
      capexPctRevenue: 0.082,
      recurringRevenuePct: 0.81,
    },
    {
      id: "q1-26",
      label: "Q1 2026A",
      fiscalYear: 2026,
      periodType: "quarterly",
      sourceType: "official_actual",
      sourceId: "tri-q1-2026-results",
      revenue: 2_087,
      organicRevenueGrowth: 0.08,
      adjustedEbitda: 881,
      adjustedEbitdaMargin: 0.422,
      operatingProfit: 639,
      adjustedEps: 1.23,
      operatingCashFlow: 505,
      freeCashFlow: 332,
      recurringRevenuePct: 0.77,
    },
  ],
  segments: [
    { periodId: "fy25", segment: "Legal Professionals", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: 2_868, organicGrowth: 0.08, adjustedEbitda: 2_868 * 0.47, adjustedEbitdaMargin: 0.47, recurringRevenuePct: 0.98, aiExposure: "high" },
    { periodId: "fy25", segment: "Corporates", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: 1_987, organicGrowth: 0.09, adjustedEbitda: 1_987 * 0.37, adjustedEbitdaMargin: 0.37, recurringRevenuePct: 0.74, aiExposure: "high" },
    { periodId: "fy25", segment: "Tax, Audit & Accounting Professionals", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: 1_302, organicGrowth: 0.11, adjustedEbitda: 1_302 * 0.43, adjustedEbitdaMargin: 0.43, recurringRevenuePct: 0.56, aiExposure: "high" },
    { periodId: "fy25", segment: "Reuters News", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: 853, organicGrowth: 0.01, adjustedEbitda: 853 * 0.2, adjustedEbitdaMargin: 0.2, aiExposure: "medium" },
    { periodId: "fy25", segment: "Global Print", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: 490, organicGrowth: -0.05, adjustedEbitda: 490 * 0.37, adjustedEbitdaMargin: 0.37, aiExposure: "low" },
    { periodId: "fy25", segment: "Eliminations/Rounding", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: -24, adjustedEbitda: 0, adjustedEbitdaMargin: 0, aiExposure: "low" },
    { periodId: "fy25", segment: "Corporate Costs", sourceType: "derived", sourceId: "tri-fy-2025-results", revenue: 0, adjustedEbitda: -118, adjustedEbitdaMargin: 0, aiExposure: "medium" },
    { periodId: "q1-26", segment: "Legal Professionals", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: 756, organicGrowth: 0.09, adjustedEbitda: 365, adjustedEbitdaMargin: 0.483, recurringRevenuePct: 0.98, aiExposure: "high" },
    { periodId: "q1-26", segment: "Corporates", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: 608, organicGrowth: 0.09, adjustedEbitda: 243, adjustedEbitdaMargin: 0.4, recurringRevenuePct: 0.74, aiExposure: "high" },
    { periodId: "q1-26", segment: "Tax, Audit & Accounting Professionals", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: 410, organicGrowth: 0.1, adjustedEbitda: 221, adjustedEbitdaMargin: 0.538, recurringRevenuePct: 0.56, aiExposure: "high" },
    { periodId: "q1-26", segment: "Reuters News", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: 212, organicGrowth: 0.06, adjustedEbitda: 34, adjustedEbitdaMargin: 0.161, aiExposure: "medium" },
    { periodId: "q1-26", segment: "Global Print", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: 112, organicGrowth: -0.05, adjustedEbitda: 43, adjustedEbitdaMargin: 0.386, aiExposure: "low" },
    { periodId: "q1-26", segment: "Eliminations/Rounding", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: -11, adjustedEbitda: 0, adjustedEbitdaMargin: 0, aiExposure: "low" },
    { periodId: "q1-26", segment: "Corporate Costs", sourceType: "official_actual", sourceId: "tri-q1-2026-results", revenue: 0, adjustedEbitda: -25, adjustedEbitdaMargin: 0, aiExposure: "medium" },
  ],
  guidance: {
    sourceType: "management_guidance",
    sourceId: "tri-q1-2026-results",
    revenueGrowthLow: 0.075,
    revenueGrowthHigh: 0.08,
    organicRevenueGrowthLow: 0.075,
    organicRevenueGrowthHigh: 0.08,
    adjustedEbitdaMarginExpansionBps: 100,
    freeCashFlow: 2_100,
    capexPctRevenue: 0.08,
    q2OrganicGrowthLow: 0.07,
    q2OrganicGrowthHigh: 0.08,
    q2AdjustedEbitdaMargin: 0.38,
    big3OrganicGrowth: 0.095,
    big3MarginExpansionBps: 100,
  },
  aiMilestones: [
    {
      id: "fiduciary-grade-ai",
      date: "2026-05-05",
      title: "Management framed CoCounsel as fiduciary-grade AI for high-stakes professional work",
      sourceType: "management_commentary",
      sourceId: "tri-q1-2026-results",
      productArea: "Platform",
      status: "commercializing",
      thesisImpact: "Supports premium workflow positioning if adoption converts into recurring revenue and retention.",
    },
    {
      id: "cocounsel-one-million",
      date: "2026-02-24",
      title: "CoCounsel reached one million professionals across 107 countries and territories",
      sourceType: "management_commentary",
      sourceId: "tri-cocounsel-one-million",
      productArea: "CoCounsel",
      metric: "1.0m professionals; 107 countries and territories",
      status: "scaling",
      thesisImpact: "Moves the AI debate from pilots to scaled production usage in regulated workflows.",
    },
    {
      id: "cocounsel-legal-uk",
      date: "2026-01-26",
      title: "CoCounsel Legal launched in the UK with Deep Research on Westlaw Advantage and Practical Law",
      sourceType: "management_commentary",
      sourceId: "tri-cocounsel-legal-uk",
      productArea: "Westlaw",
      status: "launching",
      thesisImpact: "Tests whether U.S. legal AI workflow success can internationalize through local content and integrations.",
    },
    {
      id: "tax-ai-growth",
      date: "2026-05-05",
      title: "Tax, Audit & Accounting recurring organic growth was driven in part by CoCounsel",
      sourceType: "management_commentary",
      sourceId: "tri-q1-2026-results",
      productArea: "Tax & Accounting",
      metric: "Tax recurring organic growth +10%",
      status: "commercializing",
      thesisImpact: "Expands AI contribution beyond legal into tax and audit workflows.",
    },
  ],
  marketData: {
    ticker: "TRI",
    sourceType: "market_data",
    sourceId: "tri-market-stockanalysis",
    currentPrice: 93.37,
    priceDate: "2026-05-07",
    marketCap: 40_330,
    enterpriseValue: 42_580,
    sharesOutstanding: 436.5,
    peRatio: 27.04,
    forwardPe: 20.3,
    dividendPerShare: 2.53,
    dividendYield: 0.0271,
  },
  scenarioDrivers: triScenarioDrivers,
  notes: [
    "Official actuals are limited to company-reported historical data and are kept separate from market data and forecast assumptions.",
    "AI milestones are management commentary and product evidence; they do not directly enter valuation except through capped explicit assumptions.",
    "Segment EBITDA for FY2025 is approximated from disclosed FY2025 margin framework and Q1 2026 segment economics where exact annual segment margins are not fully reproduced in this module.",
  ],
};
