import type { StockValuationConfig } from "../types";
import type { NowScenarioPresetMap, ValuationAssumptions } from "./model";

export const defaultNowValuationAssumptions: ValuationAssumptions = {
  currentPrice: 95.15,
  dilutedShares: 1_045,
  revenueGrowth: 0.18,
  subscriptionGrowth: 0.20,
  currentRpoGrowth: 0.19,
  agenticAiGrowth: 0.75,
  proPlusAdoptionRate: 0.22,
  netRetentionRate: 1.21,
  operatingMargin: 0.16,
  normalizedFcfMargin: 0.33,
  targetFcfYield: 0.027,
  targetPe: 45,
  targetEvRevenue: 12,
  discountRate: 0.085,
  terminalGrowth: 0.035,
  aiExecutionHaircut: 0.04,
  platformCompetitionHaircut: 0.03,
  sbcDilutionHaircut: 0.02,
  buybackYield: 0.008,
  dividendYield: 0,
};

export const nowScenarioPresets: NowScenarioPresetMap = {
  Bear: {
    ...defaultNowValuationAssumptions,
    revenueGrowth: 0.12,
    subscriptionGrowth: 0.13,
    currentRpoGrowth: 0.12,
    agenticAiGrowth: 0.35,
    proPlusAdoptionRate: 0.16,
    netRetentionRate: 1.16,
    operatingMargin: 0.13,
    normalizedFcfMargin: 0.29,
    targetFcfYield: 0.035,
    targetPe: 32,
    targetEvRevenue: 8,
    discountRate: 0.095,
    aiExecutionHaircut: 0.10,
    platformCompetitionHaircut: 0.08,
    sbcDilutionHaircut: 0.04,
    buybackYield: 0.004,
  },
  Base: defaultNowValuationAssumptions,
  Bull: {
    ...defaultNowValuationAssumptions,
    revenueGrowth: 0.22,
    subscriptionGrowth: 0.23,
    currentRpoGrowth: 0.22,
    agenticAiGrowth: 1.05,
    proPlusAdoptionRate: 0.32,
    netRetentionRate: 1.24,
    operatingMargin: 0.19,
    normalizedFcfMargin: 0.36,
    targetFcfYield: 0.023,
    targetPe: 56,
    targetEvRevenue: 15,
    discountRate: 0.08,
    aiExecutionHaircut: 0.02,
    platformCompetitionHaircut: 0.015,
    sbcDilutionHaircut: 0.015,
    buybackYield: 0.012,
  },
};

export function buildNowValuationConfig(
  calculateValuation: StockValuationConfig["calculateValuation"],
): StockValuationConfig {
  return {
    ticker: "NOW",
    modelType: "saas-agentic-ai-dcf-fcf-ev-revenue-triangulation",
    assumptions: [
      { key: "revenueGrowth", label: "Revenue Growth", value: defaultNowValuationAssumptions.revenueGrowth, min: 0.06, max: 0.30, step: 0.005, format: "percent", source: "assumption", description: "Core revenue growth after subscription, cRPO and AI attach checks.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "subscriptionGrowth", label: "Subscription Growth", value: defaultNowValuationAssumptions.subscriptionGrowth, min: 0.06, max: 0.32, step: 0.005, format: "percent", source: "assumption", description: "Subscription revenue growth durability.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "currentRpoGrowth", label: "cRPO Growth", value: defaultNowValuationAssumptions.currentRpoGrowth, min: 0.04, max: 0.32, step: 0.005, format: "percent", source: "assumption", description: "Forward demand proxy from current remaining performance obligations.", category: "Growth", unit: "percent", periodicity: "forward annual" },
      { key: "agenticAiGrowth", label: "Agent AI Growth", value: defaultNowValuationAssumptions.agenticAiGrowth, min: 0, max: 1.5, step: 0.025, format: "percent", source: "assumption", description: "Agentic AI ARR/customer adoption growth proxy.", category: "AI", unit: "percent", periodicity: "forward annual" },
      { key: "proPlusAdoptionRate", label: "Pro Plus Adoption", value: defaultNowValuationAssumptions.proPlusAdoptionRate, min: 0, max: 0.60, step: 0.01, format: "percent", source: "assumption", description: "AI / Pro Plus attach rate proxy.", category: "AI", unit: "percent" },
      { key: "operatingMargin", label: "Operating Margin", value: defaultNowValuationAssumptions.operatingMargin, min: 0.08, max: 0.25, step: 0.005, format: "percent", source: "assumption", description: "Normalized GAAP operating margin after cloud cost, sales efficiency and SBC pressure.", category: "Margins", unit: "percent", periodicity: "forward annual" },
      { key: "normalizedFcfMargin", label: "FCF Margin", value: defaultNowValuationAssumptions.normalizedFcfMargin, min: 0.22, max: 0.42, step: 0.005, format: "percent", source: "assumption", description: "Normalized FCF conversion after capex and working-capital benefits.", category: "Cash Flow", unit: "percent", periodicity: "forward annual" },
      { key: "targetFcfYield", label: "Target FCF Yield", value: defaultNowValuationAssumptions.targetFcfYield, min: 0.018, max: 0.045, step: 0.001, format: "percent", source: "assumption", description: "FCF yield used in valuation triangulation.", category: "Valuation", unit: "percent" },
      { key: "targetEvRevenue", label: "Target EV/Revenue", value: defaultNowValuationAssumptions.targetEvRevenue, min: 6, max: 18, step: 0.25, format: "multiple", source: "assumption", description: "Enterprise SaaS revenue multiple tied to growth and FCF durability.", category: "Valuation", unit: "multiple" },
      { key: "aiExecutionHaircut", label: "AI Execution Haircut", value: defaultNowValuationAssumptions.aiExecutionHaircut, min: 0, max: 0.15, step: 0.005, format: "percent", source: "assumption", description: "Risk haircut for Agent adoption, monetization and product proof.", category: "Risk", unit: "percent" },
      { key: "platformCompetitionHaircut", label: "Platform Risk", value: defaultNowValuationAssumptions.platformCompetitionHaircut, min: 0, max: 0.12, step: 0.005, format: "percent", source: "assumption", description: "Competition from Salesforce, Microsoft, Atlassian, Workday, BMC and AI workflow tooling.", category: "Risk", unit: "percent" },
      { key: "sbcDilutionHaircut", label: "SBC Dilution", value: defaultNowValuationAssumptions.sbcDilutionHaircut, min: 0, max: 0.08, step: 0.005, format: "percent", source: "assumption", description: "SBC and dilution quality haircut.", category: "Risk", unit: "percent" },
      { key: "buybackYield", label: "Buyback Yield", value: defaultNowValuationAssumptions.buybackYield, min: 0, max: 0.025, step: 0.001, format: "percent", source: "assumption", description: "Gross buyback offset to SBC dilution.", category: "Capital Return", unit: "percent" },
    ],
    scenarios: [
      { name: "Bear", assumptions: nowScenarioPresets.Bear },
      { name: "Base", assumptions: nowScenarioPresets.Base },
      { name: "Bull", assumptions: nowScenarioPresets.Bull },
    ],
    calculateValuation,
  };
}
