import type { LsegRiskRedTeamItem, LsegRiskRedTeamOutput, LsegValuationAssumptions } from "../types";

const baseRisks: LsegRiskRedTeamItem[] = [
  {
    id: "workspace-competition",
    risk: "Workspace fails to close the Bloomberg / FactSet / S&P Capital IQ workflow gap.",
    affectedSegment: "Data & Analytics",
    mechanism: "Lower seat adoption and weaker pricing realization slow D&A organic growth and reduce the platform multiple.",
    leadingIndicator: "ASV growth below 5%, retention commentary weakens, Workspace migrations stall.",
    killCriterion: "D&A organic growth below 4% for two consecutive reporting periods with no offset in data feeds.",
    monitoringTrigger: "Management stops referencing Workspace adoption or discloses elevated cancellations.",
    valuationImpact: -0.08,
    probability: 0.35,
    severity: 0.75,
  },
  {
    id: "refinitiv-synergy-double-count",
    risk: "Refinitiv remains an integration drag or synergy is double counted.",
    affectedSegment: "Data & Analytics",
    mechanism: "Technology rationalization costs absorb margin expansion while revenue synergy is already embedded in growth assumptions.",
    leadingIndicator: "Integration/transformation cash costs stay elevated and margin bridge lacks productivity evidence.",
    killCriterion: "Capex and integration cash costs do not trend down by 2027 while D&A growth stays below group guide.",
    monitoringTrigger: "Guided margin expansion is cut or capex intensity stays above 10%.",
    valuationImpact: -0.06,
    probability: 0.28,
    severity: 0.7,
  },
  {
    id: "data-organic-slowdown",
    risk: "Data & Analytics organic growth slows below premium-compounder threshold.",
    affectedSegment: "Data & Analytics",
    mechanism: "Premium multiple depends on recurring data/workflow growth; slowdown compresses both DCF growth and SOTP multiple.",
    leadingIndicator: "ASV, gross sales and retention trend down.",
    killCriterion: "D&A growth below 3.5% without clear Credit Suisse-type one-off explanation.",
    monitoringTrigger: "Annualized subscription value decelerates below 5%.",
    valuationImpact: -0.07,
    probability: 0.3,
    severity: 0.72,
  },
  {
    id: "ftse-fee-pressure",
    risk: "FTSE Russell passive/index fee pressure offsets high-ROIC IP quality.",
    affectedSegment: "FTSE Russell / Index",
    mechanism: "Asset-based fees and benchmark subscriptions face MSCI/S&P/Nasdaq competition, lowering growth and multiple.",
    leadingIndicator: "Asset-based revenue trails market levels and ETF AUM growth.",
    killCriterion: "FTSE Russell organic growth below 4% while passive markets rise.",
    monitoringTrigger: "Custom/private index wins fail to offset fee compression.",
    valuationImpact: -0.04,
    probability: 0.32,
    severity: 0.55,
  },
  {
    id: "clearing-mcp-regulatory-risk",
    risk: "LCH clearing, MCP and market-infrastructure regulation tighten economics.",
    affectedSegment: "Post Trade / LCH",
    mechanism: "Higher capital, margin model conservatism, default fund requirements or UK/EU/US rules reduce clearing ROIC.",
    leadingIndicator: "Regulator consultations, margin model remediation, default fund calls or client complaints.",
    killCriterion: "Post Trade margin falls materially while volumes remain healthy.",
    monitoringTrigger: "UK/EU/US clearing equivalence or capital rules change.",
    valuationImpact: -0.07,
    probability: 0.22,
    severity: 0.82,
  },
  {
    id: "rates-and-clearing-income-normalization",
    risk: "High-rate clearing/collateral income normalizes.",
    affectedSegment: "Post Trade / LCH",
    mechanism: "Net treasury and collateral income decline as rates fall, exposing lower normalized margins.",
    leadingIndicator: "Net treasury income falls faster than clearing volumes.",
    killCriterion: "Post Trade revenue declines despite stable SwapClear/ForexClear activity.",
    monitoringTrigger: "Central bank rate cuts plus declining non-cash collateral revenue.",
    valuationImpact: -0.04,
    probability: 0.45,
    severity: 0.45,
  },
  {
    id: "tradeweb-cyclicality",
    risk: "Tradeweb / Capital Markets activity proves cyclical.",
    affectedSegment: "Capital Markets",
    mechanism: "Volume, volatility and fixed-income activity normalize, lowering revenue growth and EBITDA.",
    leadingIndicator: "Tradeweb ADV growth fades and fee capture weakens.",
    killCriterion: "Capital Markets growth turns negative in normal market conditions.",
    monitoringTrigger: "Rates/credit/repo ADV declines across multiple months.",
    valuationImpact: -0.035,
    probability: 0.4,
    severity: 0.5,
  },
  {
    id: "ai-distribution-disruption",
    risk: "AI compresses terminal and data distribution pricing faster than LSEG monetizes trusted data.",
    affectedSegment: "Data & Analytics",
    mechanism: "Customers substitute API/AI workflows for high-priced seats, pressuring Workflows revenue.",
    leadingIndicator: "Seat/desktop commentary weakens while data-feed growth fails to accelerate.",
    killCriterion: "Workspace pricing declines and data/API growth does not offset it.",
    monitoringTrigger: "Competitors bundle AI data access or customers renegotiate terminal contracts.",
    valuationImpact: -0.06,
    probability: 0.3,
    severity: 0.68,
  },
  {
    id: "capital-return-balance-sheet",
    risk: "Buyback, dividend, leverage, pension and FX constraints reduce per-share compounding.",
    affectedSegment: "Group",
    mechanism: "FX translation, operating net debt, lease liabilities, pension claims or buybacks above fair value reduce equity value.",
    leadingIndicator: "Operating net debt/leverage rises above target range or buybacks are executed at unattractive prices.",
    killCriterion: "Leverage exceeds 2.5x or FCF coverage of dividend plus buyback falls below 1.0x.",
    monitoringTrigger: "Net debt, lease, pension, FX sensitivity and buyback average price updates.",
    valuationImpact: -0.05,
    probability: 0.25,
    severity: 0.6,
  },
];

export function calculateLsegRiskRedTeamEngine(assumptions: LsegValuationAssumptions): LsegRiskRedTeamOutput {
  const weightedRisk = baseRisks.reduce((sum, risk) => sum + Math.abs(risk.valuationImpact) * risk.probability * risk.severity, 0);
  const cappedRiskAdjustment = -Math.min(weightedRisk, assumptions.riskAdjustmentCap);
  return {
    verdict:
      "The avoid case is not generic macro risk: it is D&A deceleration plus Workspace weakness, unproven Refinitiv platform leverage, FTSE fee pressure and a regulated-clearing haircut arriving while buybacks consume balance-sheet capacity.",
    items: baseRisks,
    topKillCriteria: baseRisks.map((risk) => risk.killCriterion).slice(0, 6),
    cappedRiskAdjustment,
    cap: assumptions.riskAdjustmentCap,
  };
}
