import type { StockValuationConfig, ValuationAssumption, ValuationScenario } from "../types";
import type { AsmlValuationAssumptions } from "./model";

const ASML_SOURCE_NOTE = "Research workflow input; refresh with sourced filings, releases, transcripts, market data, and ADR FX bridge before final IC use.";

export const defaultAsmlValuationAssumptions: AsmlValuationAssumptions = {
  currentPrice: 0,
  normalizedRevenueUsd: 32_000,
  revenueCagr: 0.10,
  ordersGrowth: 0.08,
  backlogConversion: 0.78,
  systemsRevenueMix: 0.78,
  serviceRevenueMix: 0.22,
  euvRevenueMix: 0.48,
  duvRevenueMix: 0.30,
  highNaRevenueMix: 0.08,
  installedBaseServiceGrowth: 0.08,
  grossMargin: 0.51,
  operatingMargin: 0.33,
  fcfMargin: 0.29,
  taxRate: 0.20,
  capexIntensity: 0.08,
  discountRate: 0.09,
  terminalGrowth: 0.035,
  targetFcfYield: 0.028,
  targetPe: 32,
  targetEvEbit: 28,
  systemsRevenueMultiple: 8.5,
  serviceRevenueMultiple: 12,
  highNaRevenueMultiple: 14,
  dilutedAdrShares: 400,
  netCashUsd: 0,
  euvDemandDurability: 0.78,
  highNaAdoption: 0.45,
  backlogCoverage: 1.2,
  chinaRevenueExposure: 0.23,
  customerConcentrationHaircut: 0.04,
  chinaRestrictionHaircut: 0.08,
  aiCapexCycleRisk: 0.10,
  weightDcf: 0.35,
  weightFcfYield: 0.22,
  weightPe: 0.16,
  weightEvEbit: 0.12,
  weightSotp: 0.15,
};

export const asmlScenarioPresets: Record<"Bear" | "Base" | "Bull", Partial<AsmlValuationAssumptions>> = {
  Bear: {
    revenueCagr: 0.04,
    ordersGrowth: -0.04,
    backlogConversion: 0.62,
    systemsRevenueMix: 0.74,
    serviceRevenueMix: 0.26,
    euvRevenueMix: 0.40,
    duvRevenueMix: 0.34,
    highNaRevenueMix: 0.02,
    installedBaseServiceGrowth: 0.04,
    operatingMargin: 0.28,
    fcfMargin: 0.22,
    targetFcfYield: 0.04,
    targetPe: 23,
    targetEvEbit: 20,
    systemsRevenueMultiple: 5.5,
    serviceRevenueMultiple: 8,
    highNaRevenueMultiple: 7,
    euvDemandDurability: 0.58,
    highNaAdoption: 0.20,
    backlogCoverage: 0.85,
    chinaRevenueExposure: 0.25,
    customerConcentrationHaircut: 0.08,
    chinaRestrictionHaircut: 0.16,
    aiCapexCycleRisk: 0.24,
  },
  Base: {},
  Bull: {
    revenueCagr: 0.15,
    ordersGrowth: 0.18,
    backlogConversion: 0.90,
    systemsRevenueMix: 0.80,
    serviceRevenueMix: 0.20,
    euvRevenueMix: 0.55,
    duvRevenueMix: 0.22,
    highNaRevenueMix: 0.16,
    installedBaseServiceGrowth: 0.12,
    operatingMargin: 0.38,
    fcfMargin: 0.34,
    targetFcfYield: 0.022,
    targetPe: 39,
    targetEvEbit: 34,
    systemsRevenueMultiple: 10.5,
    serviceRevenueMultiple: 15,
    highNaRevenueMultiple: 18,
    euvDemandDurability: 0.90,
    highNaAdoption: 0.68,
    backlogCoverage: 1.55,
    chinaRevenueExposure: 0.18,
    customerConcentrationHaircut: 0.025,
    chinaRestrictionHaircut: 0.05,
    aiCapexCycleRisk: 0.05,
  },
};

export const asmlValuationAssumptionDefinitions: ValuationAssumption[] = [
  { key: "currentPrice", label: "Current ADR Price", value: defaultAsmlValuationAssumptions.currentPrice, min: 0, max: 1800, step: 5, format: "currency", source: "placeholder", description: "ASML ADR price anchor. Zero means the local market-price feed is missing.", category: "Market", unit: "USD", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "normalizedRevenueUsd", label: "Revenue Base", value: defaultAsmlValuationAssumptions.normalizedRevenueUsd, min: 0, max: 80_000, step: 250, format: "number", source: "assumption", description: "Normalized annual revenue base in USDm; replace with official EUR reporting and FX bridge.", category: "Revenue", unit: "USD", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "revenueCagr", label: "Revenue CAGR", value: defaultAsmlValuationAssumptions.revenueCagr, min: -0.05, max: 0.25, step: 0.0025, format: "percent", source: "assumption", description: "Through-cycle growth assumption for EUV/DUV/service demand.", category: "Growth", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "ordersGrowth", label: "Orders Growth", value: defaultAsmlValuationAssumptions.ordersGrowth, min: -0.25, max: 0.35, step: 0.005, format: "percent", source: "assumption", description: "Net order intake / booking momentum assumption, separated from revenue recognition.", category: "Demand", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "backlogConversion", label: "Backlog Conversion", value: defaultAsmlValuationAssumptions.backlogConversion, min: 0.35, max: 1.1, step: 0.01, format: "percent", source: "assumption", description: "Share of backlog expected to convert into near-term systems revenue.", category: "Demand", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "systemsRevenueMix", label: "Systems Revenue Mix", value: defaultAsmlValuationAssumptions.systemsRevenueMix, min: 0.55, max: 0.90, step: 0.005, format: "percent", source: "placeholder", description: "Systems share of revenue; source gap until ASML revenue split is loaded.", category: "Revenue Mix", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "serviceRevenueMix", label: "Service Revenue Mix", value: defaultAsmlValuationAssumptions.serviceRevenueMix, min: 0.10, max: 0.45, step: 0.005, format: "percent", source: "placeholder", description: "Installed-base management / service share of revenue.", category: "Revenue Mix", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "euvRevenueMix", label: "EUV Revenue Mix", value: defaultAsmlValuationAssumptions.euvRevenueMix, min: 0.20, max: 0.75, step: 0.005, format: "percent", source: "placeholder", description: "EUV exposure within systems revenue.", category: "Revenue Mix", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "duvRevenueMix", label: "DUV Revenue Mix", value: defaultAsmlValuationAssumptions.duvRevenueMix, min: 0.05, max: 0.55, step: 0.005, format: "percent", source: "placeholder", description: "DUV / immersion exposure within systems revenue.", category: "Revenue Mix", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "highNaRevenueMix", label: "High-NA Mix", value: defaultAsmlValuationAssumptions.highNaRevenueMix, min: 0, max: 0.35, step: 0.005, format: "percent", source: "assumption", description: "Forward High-NA mix ramp assumption.", category: "Revenue Mix", unit: "percent", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "installedBaseServiceGrowth", label: "Service Growth", value: defaultAsmlValuationAssumptions.installedBaseServiceGrowth, min: -0.02, max: 0.20, step: 0.0025, format: "percent", source: "assumption", description: "Installed-base service growth assumption.", category: "Growth", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "grossMargin", label: "Gross Margin", value: defaultAsmlValuationAssumptions.grossMargin, min: 0.35, max: 0.65, step: 0.0025, format: "percent", source: "assumption", description: "Mix/utilization margin assumption; High-NA can help but ramp costs and cycle risk matter.", category: "Margin", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "operatingMargin", label: "Operating Margin", value: defaultAsmlValuationAssumptions.operatingMargin, min: 0.18, max: 0.48, step: 0.0025, format: "percent", source: "assumption", description: "Normalized EBIT margin after R&D, support, and cycle costs.", category: "Margin", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "fcfMargin", label: "FCF Margin", value: defaultAsmlValuationAssumptions.fcfMargin, min: 0.10, max: 0.45, step: 0.0025, format: "percent", source: "assumption", description: "Normalized free cash flow margin after working capital and capex.", category: "Cash Flow", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "taxRate", label: "Tax Rate", value: defaultAsmlValuationAssumptions.taxRate, min: 0.10, max: 0.30, step: 0.0025, format: "percent", source: "assumption", description: "Normalized tax rate for net-income cross-check.", category: "Cash Flow", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "capexIntensity", label: "Capex / Revenue", value: defaultAsmlValuationAssumptions.capexIntensity, min: 0.02, max: 0.16, step: 0.0025, format: "percent", source: "assumption", description: "Capital intensity assumption for capacity, High-NA ramp and supply-chain investment.", category: "Cash Flow", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "discountRate", label: "Discount Rate", value: defaultAsmlValuationAssumptions.discountRate, min: 0.06, max: 0.13, step: 0.001, format: "percent", source: "assumption", description: "DCF discount rate; not a sourced WACC.", category: "DCF", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "terminalGrowth", label: "Terminal Growth", value: defaultAsmlValuationAssumptions.terminalGrowth, min: 0.01, max: 0.055, step: 0.0005, format: "percent", source: "assumption", description: "Long-run nominal growth assumption.", category: "DCF", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "targetFcfYield", label: "Target FCF Yield", value: defaultAsmlValuationAssumptions.targetFcfYield, min: 0.015, max: 0.07, step: 0.0005, format: "percent", source: "assumption", description: "FCF yield cross-check for a platform-critical monopoly supplier.", category: "Multiples", unit: "percent", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "targetPe", label: "Target P/E", value: defaultAsmlValuationAssumptions.targetPe, min: 12, max: 55, step: 0.5, format: "multiple", source: "assumption", description: "Forward P/E cross-check; not a consensus multiple.", category: "Multiples", unit: "multiple", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "targetEvEbit", label: "Target EV / EBIT", value: defaultAsmlValuationAssumptions.targetEvEbit, min: 10, max: 45, step: 0.5, format: "multiple", source: "assumption", description: "EV/EBIT cross-check for operating earnings power.", category: "Multiples", unit: "multiple", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "systemsRevenueMultiple", label: "Systems Revenue Multiple", value: defaultAsmlValuationAssumptions.systemsRevenueMultiple, min: 2, max: 18, step: 0.25, format: "multiple", source: "assumption", description: "SOTP multiple for lithography systems revenue.", category: "SOTP", unit: "multiple", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "serviceRevenueMultiple", label: "Service Revenue Multiple", value: defaultAsmlValuationAssumptions.serviceRevenueMultiple, min: 4, max: 22, step: 0.25, format: "multiple", source: "assumption", description: "SOTP multiple for installed-base service revenue.", category: "SOTP", unit: "multiple", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "highNaRevenueMultiple", label: "High-NA Multiple", value: defaultAsmlValuationAssumptions.highNaRevenueMultiple, min: 0, max: 28, step: 0.25, format: "multiple", source: "assumption", description: "Incremental SOTP multiple for High-NA revenue pool; replaces a separate AI uplift to avoid double counting.", category: "SOTP", unit: "multiple", periodicity: "forward annual", provenance: ASML_SOURCE_NOTE },
  { key: "dilutedAdrShares", label: "ADR Shares", value: defaultAsmlValuationAssumptions.dilutedAdrShares, min: 250, max: 550, step: 1, format: "number", source: "placeholder", description: "Diluted ADR-equivalent shares in millions; replace with sourced share count and ADR treatment.", category: "Equity Bridge", unit: "share", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "netCashUsd", label: "Net Cash", value: defaultAsmlValuationAssumptions.netCashUsd, min: -15_000, max: 30_000, step: 250, format: "number", source: "placeholder", description: "Net cash/debt bridge in USDm; source gap until official balance sheet and FX bridge are loaded.", category: "Equity Bridge", unit: "USD", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "euvDemandDurability", label: "EUV Demand Durability", value: defaultAsmlValuationAssumptions.euvDemandDurability, min: 0, max: 1, step: 0.01, format: "number", source: "assumption", description: "Score for long-run EUV demand durability across logic, memory, and foundry roadmaps.", category: "Moat", unit: "number", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "highNaAdoption", label: "High-NA Adoption", value: defaultAsmlValuationAssumptions.highNaAdoption, min: 0, max: 1, step: 0.01, format: "number", source: "assumption", description: "Score for High-NA lithography adoption and pricing mix-up.", category: "Moat", unit: "number", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "backlogCoverage", label: "Backlog Coverage", value: defaultAsmlValuationAssumptions.backlogCoverage, min: 0, max: 2.5, step: 0.05, format: "multiple", source: "placeholder", description: "Backlog versus forward revenue; source gap until official backlog is loaded.", category: "Demand", unit: "multiple", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "chinaRevenueExposure", label: "China Revenue Exposure", value: defaultAsmlValuationAssumptions.chinaRevenueExposure, min: 0, max: 0.45, step: 0.005, format: "percent", source: "placeholder", description: "China revenue exposure placeholder. This does not imply restricted revenue until sourced.", category: "Risk", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "customerConcentrationHaircut", label: "Customer Concentration Haircut", value: defaultAsmlValuationAssumptions.customerConcentrationHaircut, min: 0, max: 0.18, step: 0.005, format: "percent", source: "assumption", description: "Risk control for foundry/memory customer concentration and capex pushout risk.", category: "Risk", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "chinaRestrictionHaircut", label: "China Restriction Haircut", value: defaultAsmlValuationAssumptions.chinaRestrictionHaircut, min: 0, max: 0.30, step: 0.005, format: "percent", source: "assumption", description: "Valuation haircut for export controls and China shipment/service risk.", category: "Risk", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "aiCapexCycleRisk", label: "AI Capex Cycle Risk", value: defaultAsmlValuationAssumptions.aiCapexCycleRisk, min: 0, max: 0.35, step: 0.005, format: "percent", source: "assumption", description: "Haircut for AI semiconductor capex overbuild or digestion risk.", category: "Risk", unit: "percent", periodicity: "annual", provenance: ASML_SOURCE_NOTE },
  { key: "weightDcf", label: "DCF Weight", value: defaultAsmlValuationAssumptions.weightDcf, min: 0, max: 0.7, step: 0.01, format: "percent", source: "assumption", description: "Weight for DCF in blended fair value.", category: "Blend", unit: "percent", periodicity: "annual" },
  { key: "weightFcfYield", label: "FCF Yield Weight", value: defaultAsmlValuationAssumptions.weightFcfYield, min: 0, max: 0.7, step: 0.01, format: "percent", source: "assumption", description: "Weight for FCF yield cross-check.", category: "Blend", unit: "percent", periodicity: "annual" },
  { key: "weightPe", label: "P/E Weight", value: defaultAsmlValuationAssumptions.weightPe, min: 0, max: 0.7, step: 0.01, format: "percent", source: "assumption", description: "Weight for P/E cross-check.", category: "Blend", unit: "percent", periodicity: "annual" },
  { key: "weightEvEbit", label: "EV / EBIT Weight", value: defaultAsmlValuationAssumptions.weightEvEbit, min: 0, max: 0.7, step: 0.01, format: "percent", source: "assumption", description: "Weight for EV/EBIT cross-check.", category: "Blend", unit: "percent", periodicity: "annual" },
  { key: "weightSotp", label: "SOTP Weight", value: defaultAsmlValuationAssumptions.weightSotp, min: 0, max: 0.7, step: 0.01, format: "percent", source: "assumption", description: "Weight for systems/service/High-NA SOTP.", category: "Blend", unit: "percent", periodicity: "annual" },
];

export const asmlScenarioConfig: ValuationScenario[] = (["Bear", "Base", "Bull"] as const).map((name) => ({
  name,
  assumptions: {
    ...defaultAsmlValuationAssumptions,
    ...asmlScenarioPresets[name],
  },
}));

export function buildAsmlValuationConfig(
  calculateValuation: StockValuationConfig["calculateValuation"],
): Omit<StockValuationConfig, "priceMetadata"> {
  return {
    ticker: "ASML",
    modelType: "ASML AI infrastructure lithography monopoly valuation",
    assumptions: asmlValuationAssumptionDefinitions,
    scenarios: asmlScenarioConfig,
    calculateValuation,
  };
}
