import type { CegDataset } from "./model";

export const cegDataset: CegDataset = {
  ticker: "CEG",
  companyName: "Constellation Energy Corporation",
  currency: "USD",
  latestReportingPeriod: "Q1 2026",
  marketData: {
    currentPrice: 260.8,
    priceDate: "2026-05-18",
    sharesForMarketCap: 354,
    source: "Nasdaq real-time quote snapshot; SEC companyfacts for financials",
    sourceStatus: "market_data",
  },
  periods: [
    { id: "fy2022", label: "FY 2022", fiscalYear: 2022, periodType: "annual", asOfDate: "2023-02-16", sourceStatus: "official_actual", sourceId: "SEC companyfacts CY2022", revenue: 24440, operatingIncome: 495, operatingMargin: 0.020, netIncome: -160, dilutedEps: -0.49, dilutedShares: 329, operatingCashFlow: -2353, capex: 1689, freeCashFlow: -4042, dividendsPaid: 185, buybacks: 0, notes: "First post-spin public-company year; cash flow distorted by working capital and collateral." },
    { id: "fy2023", label: "FY 2023", fiscalYear: 2023, periodType: "annual", asOfDate: "2024-02-27", sourceStatus: "official_actual", sourceId: "SEC companyfacts CY2023", revenue: 24918, operatingIncome: 1610, operatingMargin: 0.065, netIncome: 1623, dilutedEps: 5.01, dilutedShares: 324, operatingCashFlow: -5301, capex: 2422, freeCashFlow: -7723, dividendsPaid: 366, buybacks: 992, notes: "Reported GAAP cash flow not normalized; collateral and power-market working capital dominate." },
    { id: "fy2024", label: "FY 2024", fiscalYear: 2024, periodType: "annual", asOfDate: "2025-02-18", sourceStatus: "official_actual", sourceId: "SEC companyfacts CY2024", revenue: 23568, operatingIncome: 4352, operatingMargin: 0.185, netIncome: 3749, dilutedEps: 11.89, dilutedShares: 315, operatingCashFlow: -2464, capex: 2565, freeCashFlow: -5029, dividendsPaid: 444, buybacks: 999, notes: "Power-price tailwinds and nuclear scarcity narrative strengthened, but reported FCF remained noisy." },
    { id: "fy2025", label: "FY 2025", fiscalYear: 2025, periodType: "annual", asOfDate: "2026-02-17", sourceStatus: "official_actual", sourceId: "SEC companyfacts CY2025", revenue: 25533, operatingIncome: 3086, operatingMargin: 0.121, netIncome: 2319, dilutedEps: 7.4, dilutedShares: 314, operatingCashFlow: 4237, capex: 2949, freeCashFlow: 1288, dividendsPaid: 486, buybacks: 400, notes: "Cleaner positive FCF year, though nuclear capex and growth investments remain central underwriting items." },
    { id: "fy2026-q1", label: "Q1 2026", fiscalYear: 2026, fiscalQuarter: "Q1", periodType: "quarter", asOfDate: "2026-05-08", sourceStatus: "official_actual", sourceId: "SEC companyfacts CY2026Q1", revenue: 11122, operatingIncome: 2332, operatingMargin: 0.210, netIncome: 1590, dilutedEps: 4.49, dilutedShares: 354, operatingCashFlow: 425, capex: 1275, freeCashFlow: -850, dividendsPaid: 155, buybacks: 0, notes: "Includes Calpine step-up in share count/debt; use event-dated data only for historical valuation." },
  ],
  operatingMetrics: [
    { periodId: "fy2022", asOfDate: "2023-02-16", sourceStatus: "research_only", nuclearGenerationTwh: 178, nuclearCapacityFactor: 0.93, zeroCarbonMix: 0.90, grossMarginPerMwh: 23, realizedPowerPrice: 37, commercialLoadGrowth: 0.01, dataCenterPpaCommentary: "Early post-spin baseline before AI data-center power scarcity became a dominant thesis.", nuclearPtcCommentary: "Nuclear PTC optionality known but not yet a mature market underwriting pillar.", hedgingCommentary: "Hedge book and collateral movements create reported FCF noise.", regulatoryCommentary: "Nuclear fleet reliability and market design remain core." },
    { periodId: "fy2023", asOfDate: "2024-02-27", sourceStatus: "research_only", nuclearGenerationTwh: 182, nuclearCapacityFactor: 0.94, zeroCarbonMix: 0.90, grossMarginPerMwh: 26, realizedPowerPrice: 40, commercialLoadGrowth: 0.015, dataCenterPpaCommentary: "Data-center load growth began to enter investor debate, but hyperscaler nuclear PPAs were still early.", nuclearPtcCommentary: "PTC downside support improved margin floor visibility.", hedgingCommentary: "Commodity exposure remains partly hedged; realized prices lag forward curves.", regulatoryCommentary: "State and federal policy support remains helpful but political." },
    { periodId: "fy2024", asOfDate: "2025-02-18", sourceStatus: "research_only", nuclearGenerationTwh: 185, nuclearCapacityFactor: 0.945, zeroCarbonMix: 0.91, grossMarginPerMwh: 31, realizedPowerPrice: 45, commercialLoadGrowth: 0.03, dataCenterPpaCommentary: "AI power scarcity and behind-the-meter / co-located load became a central multiple driver.", nuclearPtcCommentary: "PTC floor plus scarcity premium supports higher through-cycle earnings.", hedgingCommentary: "Hedge roll and power curves now matter more than historical spot revenue.", regulatoryCommentary: "Interconnection, transmission, FERC/state scrutiny are increasingly material." },
    { periodId: "fy2025", asOfDate: "2026-02-17", sourceStatus: "research_only", nuclearGenerationTwh: 188, nuclearCapacityFactor: 0.946, zeroCarbonMix: 0.91, grossMarginPerMwh: 34, realizedPowerPrice: 49, commercialLoadGrowth: 0.04, dataCenterPpaCommentary: "AI data-center demand is priced as a durable scarcity rent; key diligence is contracted price, duration and delivery risk.", nuclearPtcCommentary: "PTC floor reduces downside but should not be double-counted with scarcity premiums.", hedgingCommentary: "Forward curve sensitivity is still the largest non-operating swing factor.", regulatoryCommentary: "Network upgrades, capacity market reform and local reliability politics can cap upside." },
    { periodId: "fy2026-q1", asOfDate: "2026-05-08", sourceStatus: "research_only", nuclearGenerationTwh: 47, nuclearCapacityFactor: 0.94, zeroCarbonMix: 0.90, grossMarginPerMwh: 36, realizedPowerPrice: 51, commercialLoadGrowth: 0.05, dataCenterPpaCommentary: "Calpine integration and AI load growth must translate into contracted cash earnings, not just scarcity narrative.", nuclearPtcCommentary: "PTC remains a downside support mechanism; higher multiple depends on long-duration commercial demand.", hedgingCommentary: "Near-term earnings can diverge from cash because hedge collateral and fuel/power settlements are volatile.", regulatoryCommentary: "Regulatory risk is rising with AI-load politics, consumer power bills and market design debates." },
  ],
  researchQuestions: [
    { key: "nuclear-scarcity", question: "Is CEG a durable nuclear scarcity compounder or a power-price trade?", currentView: "The model separates normalized nuclear earnings, scarcity premium and commodity hedge haircuts so the thesis does not hide power-cycle risk.", evidenceNeeded: "Fleet output, capacity factor, realized gross margin/MWh, hedge roll schedule, PTC floor and contracted data-center load." },
    { key: "ai-power", question: "How much AI data-center demand is already priced in?", currentView: "At the current multiple, investors are paying for durable contracted load growth; the model tests data-center uplift separately from base power price.", evidenceNeeded: "Signed PPA economics, duration, interconnection milestones, counterparty concentration and delivery capex." },
    { key: "regulation", question: "Can regulation cap the nuclear/data-center premium?", currentView: "Regulatory risk is modeled as an explicit haircut, not buried inside growth.", evidenceNeeded: "FERC/state rulings, consumer-bill politics, capacity-market changes, transmission allocation and nuclear license/regulatory updates." },
    { key: "fcf", question: "Does FCF cover dividends, buybacks and growth capex?", currentView: "Reported FCF is volatile; underwriting should focus on normalized FCF after nuclear maintenance, collateral and growth investment.", evidenceNeeded: "Cash conversion bridge, collateral normalization, Calpine integration capex and capital return authorization." },
  ],
  sourceGaps: [
    "CEG standalone public history begins in 2022; older 8-year standalone financials are not available and are not fabricated.",
    "Operating metrics such as nuclear TWh, capacity factor, gross margin/MWh and AI PPA economics are research-only placeholders until parsed from official presentations/calls.",
    "Historical backend valuations use Nasdaq daily close bars as price anchors; adjusted-close dividend treatment is limited by Nasdaq chart payload.",
    "Reported FCF includes collateral and working-capital volatility; model uses normalized FCF margin for valuation rather than blindly capitalizing one noisy year.",
  ],
};
