import type { EarningsCallDataset, EarningsFocusTopic } from "../earningsCall/types";

const focus = (topic: EarningsFocusTopic, intensity: number, summary: string) => ({ topic, intensity, summary });

export const bmyEarningsDataset: EarningsCallDataset = {
  ticker: "BMY",
  name: "Bristol Myers Squibb",
  sector: "Large-cap biopharma / oncology / immunology / hematology",
  currency: "USD",
  currentPrice: 56.25,
  priceDate: "2026-05-07",
  primaryMetricName: "Growth Portfolio",
  currentPeriodId: "q1-2026",
  moduleSummary:
    "BMY is framed around whether Growth Portfolio momentum and pipeline milestones can offset Eliquis/Revlimid and other legacy erosion while preserving cash returns.",
  valuationNote: "This module is earnings-call intelligence only; it does not replace a full BMY LOE, pipeline rNPV and capital-return valuation.",
  evidence: [
    { id: "bmy-q2-2024", title: "BMY Q2 2024 results", sourceType: "official_press_release", date: "2024-07-26", url: "https://news.bms.com/news/details/2024/Bristol-Myers-Squibb-Reports-Second-Quarter-Financial-Results-for-2024/default.aspx", extractedMetric: "Q2 2024 revenue and Growth Portfolio transition", confidence: "medium" },
    { id: "bmy-q3-2024", title: "BMY Q3 2024 results", sourceType: "official_press_release", date: "2024-10-31", url: "https://news.bms.com/news/details/2024/Bristol-Myers-Squibb-Reports-Third-Quarter-Financial-Results-for-2024/default.aspx", extractedMetric: "Q3 2024 growth portfolio and legacy erosion", confidence: "medium" },
    { id: "bmy-q4-2024", title: "BMY Q4/FY 2024 results", sourceType: "official_press_release", date: "2025-02-06", url: "https://news.bms.com/news/details/2025/Bristol-Myers-Squibb-Reports-Fourth-Quarter-and-Full-Year-Financial-Results-for-2024/default.aspx", extractedMetric: "FY 2024 transition year and 2025 guidance", confidence: "medium" },
    { id: "bmy-q1-2025", title: "BMY Q1 2025 results", sourceType: "official_press_release", date: "2025-04-24", url: "https://news.bms.com/news/details/2025/Bristol-Myers-Squibb-Reports-First-Quarter-Financial-Results-for-2025/default.aspx", extractedMetric: "Q1 2025 Growth Portfolio execution", confidence: "medium" },
    { id: "bmy-q2-2025", title: "BMY Q2 2025 results", sourceType: "official_press_release", date: "2025-07-31", url: "https://news.bms.com/news/details/2025/Bristol-Myers-Squibb-Reports-Second-Quarter-Financial-Results-for-2025/default.aspx", extractedMetric: "Q2 2025 revenue, Cobenfy and Growth Portfolio", confidence: "medium" },
    { id: "bmy-q3-2025", title: "BMY Q3 2025 results PDF", sourceType: "official_press_release", date: "2025-10-30", url: "https://www.bms.com/assets/bms/us/en-us/pdf/investor-info/doc_financials/quarterly_reports/2025/BMY-Q3-2025-Earnings-Press-Release.pdf", extractedMetric: "Q3 2025 revenue $12.2bn; Growth Portfolio $6.9bn", confidence: "high" },
    { id: "bmy-q4-2025", title: "BMY Q4/FY 2025 results PDF", sourceType: "official_press_release", date: "2026-02-05", url: "https://www.bms.com/assets/bms/us/en-us/pdf/investor-info/doc_financials/quarterly_reports/2025/BMY-Q4-2025-Earnings-Press-Release.pdf", extractedMetric: "FY 2025 revenue $48.2bn; Growth Portfolio $26.4bn", confidence: "high" },
    { id: "bmy-q1-2026", title: "BMY Q1 2026 SEC exhibit", sourceType: "official_press_release", date: "2026-04-30", url: "https://www.sec.gov/Archives/edgar/data/14272/000001427226000008/a2026q1ex991.htm", extractedMetric: "Q1 2026 revenue $11.5bn; Growth Portfolio $6.2bn", confidence: "high" },
    { id: "bmy-market-2026-05-07", title: "BMY market data snapshot", sourceType: "market_data", date: "2026-05-07", url: "https://stockanalysis.com/stocks/bmy/", extractedMetric: "BMY closed at $56.25 on May 7, 2026", confidence: "medium" },
  ],
  quarters: [
    { id: "q2-2024", label: "Q2 2024", callDate: "2024-07-26", totalRevenue: 12_200, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 5_400, cashOrLiquidity: 9_000, managementTone: "transition", marketFocus: [focus("growth_portfolio", 7, "Investors focused on whether newer brands could offset Revlimid erosion."), focus("loe_or_erosion", 9, "Legacy LOE remained the central bear case."), focus("capital_allocation", 6, "Dividend and deleveraging discipline stayed relevant."), focus("pipeline", 6, "Karuna/Cobenfy and late-stage pipeline were under scrutiny.")], analystQuestions: ["Can Growth Portfolio offset Revlimid/Eliquis risk?", "How should investors size Cobenfy?", "What capital returns are sustainable?"], aiSummary: "The debate was transition-heavy: BMY had assets, but the market still led with LOE risk.", sourceEvidenceIds: ["bmy-q2-2024"] },
    { id: "q3-2024", label: "Q3 2024", callDate: "2024-10-31", totalRevenue: 11_900, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 5_700, cashOrLiquidity: 8_800, managementTone: "transition", marketFocus: [focus("growth_portfolio", 7, "Growth brands improved but did not fully displace LOE concerns."), focus("loe_or_erosion", 9, "Revlimid erosion and future Eliquis risk dominated."), focus("pipeline", 7, "Cobenfy launch framing became more important."), focus("margin", 5, "Margin resilience mattered but was secondary.")], analystQuestions: ["How durable is Growth Portfolio momentum?", "What is Cobenfy's launch curve?", "How much more Revlimid pressure remains?"], aiSummary: "The market wanted proof that a new BMY could grow faster than the old BMY eroded.", sourceEvidenceIds: ["bmy-q3-2024"] },
    { id: "q4-2024", label: "Q4 2024", callDate: "2025-02-06", totalRevenue: 12_300, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 6_300, cashOrLiquidity: 8_200, managementTone: "execution", marketFocus: [focus("growth_portfolio", 8, "Breyanzi, Reblozyl and Camzyos became the core offset story."), focus("loe_or_erosion", 8, "Legacy erosion stayed high but was now compared with tangible growth assets."), focus("pipeline", 7, "Cobenfy and registrational oncology assets were central."), focus("capital_allocation", 6, "Balance sheet and dividend support remained part of the thesis.")], analystQuestions: ["Can 2025 guidance absorb erosion?", "Which growth brands matter most?", "Does pipeline execution change the multiple?"], aiSummary: "Q4 2024 moved the conversation from pure erosion to whether the Growth Portfolio could carry 2025 guidance.", sourceEvidenceIds: ["bmy-q4-2024"] },
    { id: "q1-2025", label: "Q1 2025", callDate: "2025-04-24", totalRevenue: 11_200, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 6_000, cashOrLiquidity: 7_900, managementTone: "execution", marketFocus: [focus("growth_portfolio", 8, "The market focused on execution across Reblozyl, Breyanzi, Camzyos and Cobenfy."), focus("loe_or_erosion", 7, "LOE risk persisted but felt less singular."), focus("pipeline", 7, "Cobenfy and milvexian optionality rose."), focus("margin", 6, "Investors tracked cost discipline after BD.")], analystQuestions: ["Is Cobenfy meeting early expectations?", "How much can Breyanzi scale?", "Can cost actions protect EPS?"], aiSummary: "The call showed a more balanced debate: still LOE-aware, but increasingly execution-oriented.", sourceEvidenceIds: ["bmy-q1-2025"] },
    { id: "q2-2025", label: "Q2 2025", callDate: "2025-07-31", totalRevenue: 12_300, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 6_500, cashOrLiquidity: 7_500, managementTone: "execution", marketFocus: [focus("growth_portfolio", 9, "Growth Portfolio became the main underwriting anchor."), focus("pipeline", 8, "Cobenfy, milvexian and oncology catalysts got more attention."), focus("loe_or_erosion", 7, "Legacy erosion remained a drag but not the only topic."), focus("cell_therapy", 6, "Breyanzi execution and reimbursement remained relevant.")], analystQuestions: ["Is Growth Portfolio growth durable?", "What are the key 2026 readouts?", "How does Breyanzi compete?"], aiSummary: "The market increasingly assessed BMY as a growth-portfolio execution story rather than only a patent-cliff story.", sourceEvidenceIds: ["bmy-q2-2025"] },
    { id: "q3-2025", label: "Q3 2025", callDate: "2025-10-30", totalRevenue: 12_222, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 6_900, cashOrLiquidity: 7_300, managementTone: "pipeline", marketFocus: [focus("growth_portfolio", 9, "Reported Growth Portfolio momentum was the highlight."), focus("pipeline", 8, "Pipeline milestones and BD were framed as future growth levers."), focus("loe_or_erosion", 6, "Legacy erosion faded modestly as growth assets delivered."), focus("margin", 6, "IPRD and licensing impacts kept EPS quality in focus.")], analystQuestions: ["Can the raised guide hold?", "Which pipeline assets can re-rate the stock?", "How should IPRD affect quality of earnings?"], aiSummary: "Q3 2025 was the cleanest proof point that Growth Portfolio momentum could change the conversation.", sourceEvidenceIds: ["bmy-q3-2025"] },
    { id: "q4-2025", label: "Q4 2025", callDate: "2026-02-05", totalRevenue: 12_500, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 7_400, cashOrLiquidity: 7_000, managementTone: "pipeline", marketFocus: [focus("growth_portfolio", 9, "Growth Portfolio $26.4bn FY sales made it the thesis center."), focus("loe_or_erosion", 7, "Legacy portfolio decline still weighed on 2026 revenue guide."), focus("pipeline", 8, "Cobenfy and late-stage pipeline drove debate."), focus("capital_allocation", 7, "Cash returns and balance sheet discipline stayed important.")], analystQuestions: ["Is 2026 guide conservative?", "Can Growth Portfolio offset Eliquis?", "What pipeline events matter most?"], aiSummary: "The debate became whether BMY could use Growth Portfolio and pipeline events to bridge the next LOE wave.", sourceEvidenceIds: ["bmy-q4-2025"] },
    { id: "q1-2026", label: "Q1 2026", callDate: "2026-04-30", totalRevenue: 11_500, revenueUnit: "USDm", primaryMetricLabel: "Growth Portfolio", primaryMetric: 6_200, cashOrLiquidity: 7_000, managementTone: "execution", marketFocus: [focus("growth_portfolio", 9, "12% Growth Portfolio growth led the quarter."), focus("pipeline", 9, "Pipeline milestones ahead became the most important re-rating path."), focus("loe_or_erosion", 7, "Eliquis and legacy risk remain in the valuation."), focus("margin", 7, "Upper-end guidance commentary kept EPS quality in focus.")], analystQuestions: ["Can guidance trend to the upper end?", "Which pipeline milestones matter in 2026?", "How much legacy erosion remains?"], aiSummary: "The current BMY debate is Growth Portfolio execution plus pipeline validation against a still-material LOE wall.", sourceEvidenceIds: ["bmy-q1-2026"] },
  ],
};
